/**
 * chainCatalogData.js
 * Unified, brand-neutral chain procurement catalog.
 * Sources: MAC Chain + Allied-Locke Industries
 * Naming: Allied-Locke "Precision Roller Chains" → "Performance Roller Chains" in our app.
 */

// ── Image bases ──────────────────────────────────────────────────────────────
const ALLIED = "https://chains.alliedlocke.com/";
const MAC = "https://macchain.com/";

// ── Category definitions ─────────────────────────────────────────────────────
export const CHAIN_CATEGORIES = [
  {
    key: "performance_roller",
    label: "Performance Roller Chains",
    icon: "🔗",
    description: "ANSI & metric roller chains for power transmission and conveying. Single, double, and triple strand. Standard, heavy, solid bushing/roller, and super-series variants.",
    color: "#0057A8",
    image: ALLIED + "ImgSmall/PRC%20Ansi%20Drawing.jpg",
    subcategories: [
      { key: "ansi_standard", label: "ANSI Standard Roller Chains" },
      { key: "ansi_heavy", label: "ANSI Heavy Series (H)" },
      { key: "solid_bushing", label: "Solid Bushing / Solid Roller" },
      { key: "super_series", label: "Super Series (Heavy Duty)" },
      { key: "british_standard", label: "British Standard (BS) Chains" },
      { key: "double_pitch", label: "Double Pitch Roller Chains" },
      { key: "double_capacity", label: "Double Capacity Chains" },
      { key: "xdo", label: "XDO Oilfield Series" },
      { key: "stainless", label: "Stainless Steel Chains" },
      { key: "nickel_plated", label: "Nickel Plated Chains" },
      { key: "armor_coat", label: "Armor Coat Chains" },
      { key: "self_lube", label: "Self-Lube Chains" },
    ],
  },
  {
    key: "welded_steel",
    label: "Welded Steel Chains",
    icon: "⛓️",
    description: "Engineered class welded steel chains for heavy-duty conveying. WH, WD, and WF series.",
    color: "#374151",
    image: ALLIED + "ImgSmall/WH124.jpg",
    subcategories: [
      { key: "wh_series", label: "WH Series Welded Steel" },
      { key: "wd_series", label: "WD Series Welded Steel" },
      { key: "wf_series", label: "WF Series Welded Steel" },
    ],
  },
  {
    key: "steel_pintle",
    label: "Steel Pintle Chains",
    icon: "🔩",
    description: "All heat-treated parts, quad-staked pins. Open barrel design for cleaner operation. Common in agricultural and industrial conveying.",
    color: "#92400e",
    image: ALLIED + "ImgSmall/steel-pintle-chains.jpg",
    subcategories: [
      { key: "standard_pintle", label: "Standard Steel Pintle" },
    ],
  },
  {
    key: "engineered_class",
    label: "Engineered Class Chains",
    icon: "⚙️",
    description: "SS Class, MSR Class, MXS Class, Combination, H-Class, Drop Forged Rivetless, and Cast Manganese chains for heavy industrial applications.",
    color: "#1a3a5c",
    image: ALLIED + "ImgSmall/MSR6018.jpg",
    subcategories: [
      { key: "ss_class", label: "SS Class Bushed Steel" },
      { key: "msr_class", label: "MSR Class Bushed Roller Steel" },
      { key: "mxs_class", label: "MXS Class Offset Drive" },
      { key: "combination", label: "Combination Chains" },
      { key: "h_class", label: '"H" Class / Mill / Drag / Transfer' },
      { key: "drop_forged", label: "Rivetless Drop Forged" },
      { key: "cast_manganese", label: "Cast Manganese / Alloy Steel" },
    ],
  },
  {
    key: "agricultural",
    label: "Agricultural Chains",
    icon: "🌾",
    description: "Agricultural roller chains, pintle, detachable, T-Bar, T-Rod, and corn picker gathering chains. Built for combines, forage harvesters, and spreaders.",
    color: "#166534",
    image: ALLIED + "ImgSmall/agricultural-roller-chains.jpg",
    subcategories: [
      { key: "ag_roller", label: "Agricultural Roller Chains" },
      { key: "ag_pintle", label: "Agricultural Steel Pintle" },
      { key: "ag_detachable", label: "Steel Detachable Chains" },
      { key: "ag_tbar", label: "T-Bar Chains" },
      { key: "ag_trod", label: "T-Rod Chains" },
    ],
  },
  {
    key: "transfer",
    label: "Transfer Chains",
    icon: "➡️",
    description: "Transfer and drag chains for mill, elevator, and industrial conveying. H-Class and drag chain families.",
    color: "#7c3aed",
    image: ALLIED + "ImgSmall/H78%20Plain%20Chain.jpg",
    subcategories: [
      { key: "h_transfer", label: "H-Class Transfer Chains" },
    ],
  },
  {
    key: "leaf_chain",
    label: "Leaf Chains",
    icon: "🍃",
    description: "AL and BL series leaf chains for forklift masts, tension linkages, and balance applications.",
    color: "#065f46",
    image: ALLIED + "ImgSmall/a1024.jpg",
    subcategories: [
      { key: "al_series", label: "AL Series Leaf Chains" },
      { key: "bl_series", label: "BL Series Leaf Chains" },
    ],
  },
  {
    key: "silent_chain",
    label: "Silent / Inverted Tooth Chains",
    icon: "🔇",
    description: "High-speed, high-load inverted tooth chains. Low noise, excellent fatigue resistance. Excel and Silent series.",
    color: "#0e7490",
    image: ALLIED + "ImgSmall/Silent%20Chain%20Center%20Guide%20Pic.jpg",
    subcategories: [
      { key: "excel_series", label: "Excel Series" },
      { key: "silent_series", label: "Silent Series" },
    ],
  },
  {
    key: "attachments",
    label: "Chain Attachments",
    icon: "🔧",
    description: "Standard and special attachments for roller, agricultural, pintle, and engineered class chains.",
    color: "#b45309",
    image: ALLIED + "ImgSmall/a1038.jpg",
    subcategories: [
      { key: "roller_attachments", label: "Roller Chain Attachments" },
      { key: "ag_attachments", label: "Agricultural Chain Attachments" },
      { key: "eng_attachments", label: "Engineered Class Attachments" },
    ],
  },
  {
    key: "connecting_links",
    label: "Connecting Links & Master Links",
    icon: "🔑",
    description: "Connecting links, master links, offset links, and cotter pins for all chain families.",
    color: "#6b7280",
    image: ALLIED + "ImgSmall/a1019.jpg",
    subcategories: [
      { key: "connecting_links", label: "Connecting / Master Links" },
      { key: "offset_links", label: "Offset / Half Links" },
    ],
  },
  {
    key: "sprockets",
    label: "Sprockets",
    icon: "⚙️",
    description: "ANSI, BS, and engineered class sprockets for all chain families. Bore-to-size available.",
    color: "#374151",
    image: ALLIED + "ImgSmall/sprokets.jpg",
    subcategories: [
      { key: "ansi_sprockets", label: "ANSI Roller Chain Sprockets" },
      { key: "eng_sprockets", label: "Engineered Class Sprockets" },
      { key: "ag_sprockets", label: "Agricultural Chain Sprockets" },
    ],
  },
];

// ── Helper constants ─────────────────────────────────────────────────────────
const STANDARD_ROLLER_IMAGE = ALLIED + "ImgSmall/PRC%20Ansi%20Drawing.jpg";
const SOLID_BUSHING_IMAGE = ALLIED + "ImgSmall/a1019.jpg";
const DOUBLE_PITCH_IMAGE = ALLIED + "ImgSmall/a1016.jpg";
const WH_IMAGE = ALLIED + "ImgSmall/WH124.jpg";
const PINTLE_IMAGE = ALLIED + "ImgSmall/steel-pintle-chains.jpg";
const AG_IMAGE = ALLIED + "ImgSmall/agricultural-roller-chains.jpg";
const MSR_IMAGE = ALLIED + "ImgSmall/MSR6018.jpg";
const SS_IMAGE = ALLIED + "ImgSmall/SS188%20copy.jpg";
const COMB_IMAGE = ALLIED + "ImgSmall/C188.jpg";
const H_IMAGE = ALLIED + "ImgSmall/H78%20Plain%20Chain.jpg";
const DROP_IMAGE = ALLIED + "ImgSmall/Drop%20Forged%20X%20Pic.jpg";
const CAST_IMAGE = ALLIED + "ImgSmall/cast-manganese-steel-rivetless-chains.jpg";
const LEAF_IMAGE = ALLIED + "ImgSmall/a1024.jpg";
const SILENT_IMAGE = ALLIED + "ImgSmall/Silent%20Chain%20Center%20Guide%20Pic.jpg";
const ATTACH_IMAGE = ALLIED + "ImgSmall/a1038.jpg";
const DETACH_IMAGE = ALLIED + "ImgSmall/steel-detachable-chains.jpg";
const TBAR_IMAGE = ALLIED + "ImgSmall/t-bar-chains.jpg";
const TROD_IMAGE = ALLIED + "ImgSmall/t-rod-chains.jpg";
const MXS_IMAGE = ALLIED + "ImgSmall/MXS881.jpg";

// ── CHAIN PRODUCTS ───────────────────────────────────────────────────────────
export const CHAIN_PRODUCTS = [

  // ────────────────────────────────────────────────────────────────────────────
  // PERFORMANCE ROLLER CHAINS — ANSI STANDARD
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "RC-25", part_number: "25", chain_number: "25",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1/4-inch pitch ANSI roller chain. Single strand, riveted construction. Standard for light-duty power transmission.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Light Machinery", "Agricultural Equipment"],
    features: ["ANSI B29.1 compliant", "Riveted construction", "Carbon steel"],
    specs: { pitch_in: "0.250", roller_width_in: "0.125", roller_dia_in: "0.130", pin_dia_in: "0.0905", plate_height_in: "0.252", plate_thick_in: "0.030", avg_ultimate_lbs: "980", weight_lbs_ft: "0.09" },
    related_pins: [{ code: "25 CL", name: "No. 25 Connecting Link", description: "Standard connecting link for No. 25 chain." }],
    related_sprockets: [{ code: "25B*T", name: "No. 25 Sprockets", description: "ANSI #25 sprockets, various tooth counts.", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered construction (sizes 60+)", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-35", part_number: "35", chain_number: "35",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "3/8-inch pitch ANSI roller chain. Single strand. Common in light machinery, agricultural, and conveyor drives.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Agricultural", "Light Machinery", "Food Processing"],
    features: ["ANSI B29.1 compliant", "Riveted construction", "Carbon steel"],
    specs: { pitch_in: "0.375", roller_width_in: "0.188", roller_dia_in: "0.200", pin_dia_in: "0.141", plate_height_in: "0.355", plate_thick_in: "0.050", avg_ultimate_lbs: "2,100", weight_lbs_ft: "0.21" },
    related_pins: [{ code: "35 CL", name: "No. 35 Connecting Link", description: "Standard connecting link for No. 35 chain." }],
    related_sprockets: [{ code: "35B*T", name: "No. 35 Sprockets", description: "ANSI #35 sprockets.", bore: "To suit" }],
    related_attachments: [],
    options: ["Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-40", part_number: "40", chain_number: "40",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1/2-inch pitch ANSI roller chain. One of the most widely used chain sizes globally. Single, double, and triple strand available.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Agricultural", "Packaging", "Mining", "Oil & Gas"],
    features: ["ANSI B29.1 compliant", "Riveted and cottered construction available", "Carbon steel", "Most widely stocked size"],
    specs: { pitch_in: "0.500", roller_width_in: "0.312", roller_dia_in: "0.312", pin_dia_in: "0.156", plate_height_in: "0.475", plate_thick_in: "0.058", avg_ultimate_lbs: "3,700", weight_lbs_ft: "0.41" },
    related_pins: [
      { code: "40 CL", name: "No. 40 Connecting Link (Slip-Fit)", description: "Standard slip-fit connecting link." },
      { code: "40 CLR", name: "No. 40 Connecting Link (Press-Fit)", description: "Press-fit connecting link for higher loads." },
      { code: "40 OL", name: "No. 40 Offset Link", description: "Half-link for odd-length chains." },
    ],
    related_sprockets: [
      { code: "40B9T", name: "No. 40 Sprocket — 9 Teeth", teeth: 9, bore: "To suit" },
      { code: "40B12T", name: "No. 40 Sprocket — 12 Teeth", teeth: 12, bore: "To suit" },
      { code: "40B15T", name: "No. 40 Sprocket — 15 Teeth", teeth: 15, bore: "To suit" },
      { code: "40B*T", name: "No. 40 Sprockets — All Tooth Counts", description: "Full range available. Contact Uniking.", bore: "To suit" },
    ],
    related_attachments: [
      { code: "40 A1", name: "No. 40 Attachment A1", type: "A1 — One bent tab, one side" },
      { code: "40 A2", name: "No. 40 Attachment A2", type: "A2 — Two bent tabs, both sides" },
      { code: "40 K1", name: "No. 40 Attachment K1", type: "K1 — One extended pin, one side" },
      { code: "40 K2", name: "No. 40 Attachment K2", type: "K2 — Two extended pins, both sides" },
    ],
    options: ["Cottered construction", "Pre-greased rivets", "Hardened pins", "Nickel plated", "Stainless steel"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-50", part_number: "50", chain_number: "50",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "5/8-inch pitch ANSI roller chain. Heavy-duty drives, conveyors, and industrial machinery.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Mining", "Paper & Forest Products"],
    features: ["ANSI B29.1 compliant", "Riveted and cottered construction", "Carbon steel"],
    specs: { pitch_in: "0.625", roller_width_in: "0.375", roller_dia_in: "0.400", pin_dia_in: "0.200", plate_height_in: "0.594", plate_thick_in: "0.079", avg_ultimate_lbs: "6,100", weight_lbs_ft: "0.68" },
    related_pins: [{ code: "50 CL", name: "No. 50 Connecting Link", description: "Standard connecting link." }],
    related_sprockets: [{ code: "50B*T", name: "No. 50 Sprockets", bore: "To suit" }],
    related_attachments: [
      { code: "50 A1", name: "No. 50 Attachment A1", type: "A1" },
      { code: "50 A2", name: "No. 50 Attachment A2", type: "A2" },
      { code: "50 K1", name: "No. 50 Attachment K1", type: "K1" },
    ],
    options: ["Cottered construction", "Pre-greased", "Hardened pins"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-60", part_number: "60", chain_number: "60",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "3/4-inch pitch ANSI roller chain. One of the most common sizes for medium-heavy industrial drives.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Packaging", "Automotive", "Construction Equipment"],
    features: ["ANSI B29.1 compliant", "Riveted and cottered", "Cottered standard at size 60+"],
    specs: { pitch_in: "0.750", roller_width_in: "0.500", roller_dia_in: "0.469", pin_dia_in: "0.235", plate_height_in: "0.712", plate_thick_in: "0.093", avg_ultimate_lbs: "8,500", weight_lbs_ft: "0.96" },
    related_pins: [
      { code: "60 CL", name: "No. 60 Connecting Link", description: "Slip-fit." },
      { code: "60 OL", name: "No. 60 Offset Link", description: "Half-link." },
    ],
    related_sprockets: [{ code: "60B*T", name: "No. 60 Sprockets", bore: "To suit" }],
    related_attachments: [
      { code: "60 A1", name: "No. 60 A1 Attachment", type: "A1" },
      { code: "60 A2", name: "No. 60 A2 Attachment", type: "A2" },
      { code: "60 K1", name: "No. 60 K1 Attachment", type: "K1" },
      { code: "60 K2", name: "No. 60 K2 Attachment", type: "K2" },
    ],
    options: ["Cottered construction (standard at 60)", "Pre-greased", "Hardened pins", "Induction hardened pins"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-80", part_number: "80", chain_number: "80",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1-inch pitch ANSI roller chain. Heavy industrial drives, conveyors, and power transmission.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Steel & Mining", "Paper", "Oil & Gas"],
    features: ["ANSI B29.1 compliant", "Riveted and cottered", "High tensile strength"],
    specs: { pitch_in: "1.000", roller_width_in: "0.625", roller_dia_in: "0.625", pin_dia_in: "0.313", plate_height_in: "0.950", plate_thick_in: "0.125", avg_ultimate_lbs: "14,500", weight_lbs_ft: "1.65" },
    related_pins: [{ code: "80 CL", name: "No. 80 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "80B*T", name: "No. 80 Sprockets", bore: "To suit" }],
    related_attachments: [
      { code: "80 A1", name: "No. 80 A1 Attachment", type: "A1" },
      { code: "80 A2", name: "No. 80 A2 Attachment", type: "A2" },
      { code: "80 K1", name: "No. 80 K1 Attachment", type: "K1" },
    ],
    options: ["Cottered", "Pre-greased", "Hardened pins", "Stainless"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-100", part_number: "100", chain_number: "100",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1-1/4 inch pitch ANSI roller chain. Heavy drives and industrial applications.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Steel", "Mining", "Cement", "Paper"],
    features: ["ANSI B29.1 compliant", "Cottered and riveted"],
    specs: { pitch_in: "1.250", roller_width_in: "0.750", roller_dia_in: "0.750", pin_dia_in: "0.375", plate_height_in: "1.188", plate_thick_in: "0.157", avg_ultimate_lbs: "22,000", weight_lbs_ft: "2.54" },
    related_pins: [{ code: "100 CL", name: "No. 100 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "100B*T", name: "No. 100 Sprockets", bore: "To suit" }],
    related_attachments: [{ code: "100 A1", name: "No. 100 A1 Attachment", type: "A1" }],
    options: ["Cottered", "Pre-greased", "Hardened pins"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-120", part_number: "120", chain_number: "120",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1-1/2 inch pitch ANSI roller chain. Extra heavy industrial power transmission.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Steel", "Mining", "Heavy Industry"],
    features: ["ANSI B29.1 compliant", "Cottered and riveted"],
    specs: { pitch_in: "1.500", roller_width_in: "1.000", roller_dia_in: "0.875", pin_dia_in: "0.437", plate_height_in: "1.425", plate_thick_in: "0.187", avg_ultimate_lbs: "29,000", weight_lbs_ft: "3.87" },
    related_pins: [{ code: "120 CL", name: "No. 120 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "120B*T", name: "No. 120 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered", "Pre-greased", "Hardened pins"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-140", part_number: "140", chain_number: "140",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "1-3/4 inch pitch ANSI roller chain.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Heavy Industry", "Mining"],
    features: ["ANSI B29.1 compliant"],
    specs: { pitch_in: "1.750", roller_width_in: "1.000", roller_dia_in: "1.000", pin_dia_in: "0.500", plate_height_in: "1.663", plate_thick_in: "0.219", avg_ultimate_lbs: "38,000", weight_lbs_ft: "4.96" },
    related_pins: [{ code: "140 CL", name: "No. 140 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "140B*T", name: "No. 140 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-160", part_number: "160", chain_number: "160",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "2-inch pitch ANSI roller chain. Heavy industrial power transmission.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Heavy Industry", "Mining", "Steel"],
    features: ["ANSI B29.1 compliant"],
    specs: { pitch_in: "2.000", roller_width_in: "1.250", roller_dia_in: "1.125", pin_dia_in: "0.563", plate_height_in: "1.901", plate_thick_in: "0.255", avg_ultimate_lbs: "51,000", weight_lbs_ft: "6.39" },
    related_pins: [{ code: "160 CL", name: "No. 160 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "160B*T", name: "No. 160 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-200", part_number: "200", chain_number: "200",
    category: "performance_roller", subcategory: "ansi_standard",
    product_type: "ANSI Standard Roller Chain",
    description: "2-1/2 inch pitch ANSI roller chain. Very heavy industrial applications.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Heavy Industry", "Mining"],
    features: ["ANSI B29.1 compliant"],
    specs: { pitch_in: "2.500", roller_width_in: "1.500", roller_dia_in: "1.563", pin_dia_in: "0.687", plate_height_in: "2.375", plate_thick_in: "0.312", avg_ultimate_lbs: "79,000", weight_lbs_ft: "10.0" },
    related_pins: [{ code: "200 CL", name: "No. 200 Connecting Link", description: "Slip-fit." }],
    related_sprockets: [{ code: "200B*T", name: "No. 200 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "Missing Data – Needs Mapping for full spec confirmation.",
  },

  // ── HEAVY SERIES ─────────────────────────────────────────────────────────
  {
    id: "RC-60H", part_number: "60H", chain_number: "60H",
    category: "performance_roller", subcategory: "ansi_heavy",
    product_type: "ANSI Heavy Series Roller Chain",
    description: "3/4-inch pitch, heavy series (H) ANSI roller chain. Thicker side plates for higher loads.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["General Industrial", "Mining", "Construction"],
    features: ["ANSI B29.1 heavy series", "Thicker side plates", "Higher load capacity than standard"],
    specs: { pitch_in: "0.750", roller_width_in: "0.500", roller_dia_in: "0.469", pin_dia_in: "0.234", plate_height_in: "0.712", plate_thick_in: "0.125", avg_ultimate_lbs: "10,800" },
    related_pins: [{ code: "60H CL", name: "No. 60H Connecting Link", description: "Heavy series connecting link." }],
    related_sprockets: [{ code: "60B*T", name: "No. 60 Sprockets (ANSI)", bore: "To suit", notes: "Standard ANSI #60 sprockets compatible." }],
    related_attachments: [],
    options: ["Cottered", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    notes: "",
  },
  {
    id: "RC-80H", part_number: "80H", chain_number: "80H",
    category: "performance_roller", subcategory: "ansi_heavy",
    product_type: "ANSI Heavy Series Roller Chain",
    description: "1-inch pitch, heavy series (H) ANSI roller chain.",
    image: STANDARD_ROLLER_IMAGE,
    industries: ["Heavy Industrial", "Mining", "Steel"],
    features: ["Thicker side plates", "Higher fatigue strength"],
    specs: { pitch_in: "1.000", roller_width_in: "0.625", roller_dia_in: "0.625", pin_dia_in: "0.312", plate_height_in: "0.950", plate_thick_in: "0.157", avg_ultimate_lbs: "17,200" },
    related_pins: [{ code: "80H CL", name: "No. 80H Connecting Link", description: "Heavy series connecting link." }],
    related_sprockets: [{ code: "80B*T", name: "No. 80 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Cottered", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    notes: "",
  },

  // ── SOLID BUSHING ────────────────────────────────────────────────────────
  {
    id: "RC-40-SOLID", part_number: "40 SOLID", chain_number: "40 SOLID",
    category: "performance_roller", subcategory: "solid_bushing",
    product_type: "Solid Bushing / Solid Roller Chain",
    description: "1/2-inch pitch solid bushing / solid roller chain. One-piece bushings and rollers hold lubrication in, extending wear life by 50%+.",
    image: SOLID_BUSHING_IMAGE,
    industries: ["Food Processing", "General Industrial", "Mining", "Packaging"],
    features: ["Solid one-piece bushings", "Solid one-piece rollers", "50%+ longer wear life", "Better lubrication retention"],
    specs: { pitch_in: "0.500", roller_width_in: "0.312", roller_dia_in: "0.312", riv_end_to_cl_in: "0.321", conn_end_to_cl_in: "0.368", plate_height_in: "0.475", plate_thick_in: "0.058", pin_dia_in: "0.156", avg_ultimate_lbs: "3,970" },
    related_pins: [{ code: "40 CL", name: "No. 40 Connecting Link", description: "Compatible with standard No. 40 connecting link." }],
    related_sprockets: [{ code: "40B*T", name: "No. 40 Sprockets", bore: "To suit", notes: "Standard ANSI #40 sprockets compatible." }],
    related_attachments: [],
    options: ["Pre-greased"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-60-SOLID", part_number: "60 SOLID", chain_number: "60 SOLID",
    category: "performance_roller", subcategory: "solid_bushing",
    product_type: "Solid Bushing / Solid Roller Chain",
    description: "3/4-inch pitch solid bushing/solid roller chain. 50%+ longer wear life.",
    image: SOLID_BUSHING_IMAGE,
    industries: ["General Industrial", "Mining", "Packaging"],
    features: ["Solid one-piece bushings & rollers", "Superior lubrication retention"],
    specs: { pitch_in: "0.750", roller_width_in: "0.500", roller_dia_in: "0.469", riv_end_to_cl_in: "0.497", conn_end_to_cl_in: "0.551", plate_height_in: "0.712", plate_thick_in: "0.093", pin_dia_in: "0.235", avg_ultimate_lbs: "9,270" },
    related_pins: [{ code: "60 CL", name: "No. 60 Connecting Link", description: "Standard connecting link." }],
    related_sprockets: [{ code: "60B*T", name: "No. 60 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Pre-greased"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },
  {
    id: "RC-80-SOLID", part_number: "80 SOLID", chain_number: "80 SOLID",
    category: "performance_roller", subcategory: "solid_bushing",
    product_type: "Solid Bushing / Solid Roller Chain",
    description: "1-inch pitch solid bushing/solid roller chain.",
    image: SOLID_BUSHING_IMAGE,
    industries: ["Heavy Industrial", "Mining"],
    features: ["Solid one-piece bushings & rollers", "Superior lubrication retention"],
    specs: { pitch_in: "1.000", roller_width_in: "0.625", roller_dia_in: "0.625", riv_end_to_cl_in: "0.645", conn_end_to_cl_in: "0.724", plate_height_in: "0.950", plate_thick_in: "0.125", pin_dia_in: "0.313", avg_ultimate_lbs: "16,540" },
    related_pins: [{ code: "80 CL", name: "No. 80 Connecting Link", description: "Standard connecting link." }],
    related_sprockets: [{ code: "80B*T", name: "No. 80 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Pre-greased"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/solid-bushing-solid-roller-chains",
    notes: "",
  },

  // ── DOUBLE PITCH ─────────────────────────────────────────────────────────
  {
    id: "RC-C2040", part_number: "C2040", chain_number: "C2040",
    category: "performance_roller", subcategory: "double_pitch",
    product_type: "Double Pitch Conveyor Chain",
    description: "1-inch (double) pitch conveyor chain. Straight sidebars. C-series for conveyor applications. Standard and over-size rollers available.",
    image: DOUBLE_PITCH_IMAGE,
    industries: ["Conveying", "Packaging", "Assembly Lines"],
    features: ["Double the pitch of ANSI #40", "Straight sidebars (C-series)", "Standard or over-sized rollers", "Economy conveyor chain"],
    specs: { pitch_in: "1.000", roller_width_in: "0.312", roller_dia_in: "0.312", pin_dia_in: "0.156", plate_height_in: "0.475", plate_thick_in: "0.058", avg_ultimate_lbs: "3,700" },
    related_pins: [{ code: "C2040 CL", name: "C2040 Connecting Link", description: "Connecting link for C2040 double pitch chain." }],
    related_sprockets: [{ code: "C2040B*T", name: "C2040 Sprockets", bore: "To suit" }],
    related_attachments: [
      { code: "C2040 A1", name: "C2040 Attachment A1", type: "A1 — Extended tab one side" },
      { code: "C2040 A2", name: "C2040 Attachment A2", type: "A2 — Extended tab both sides" },
      { code: "C2040 K1", name: "C2040 Attachment K1", type: "K1 — Extended pin one side" },
    ],
    options: ["Over-size rollers", "Attachments", "Pre-greased"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/double-pitch-roller-chains",
    notes: "",
  },
  {
    id: "RC-C2050", part_number: "C2050", chain_number: "C2050",
    category: "performance_roller", subcategory: "double_pitch",
    product_type: "Double Pitch Conveyor Chain",
    description: "1-1/4 inch pitch double pitch conveyor chain. C-series straight sidebars.",
    image: DOUBLE_PITCH_IMAGE,
    industries: ["Conveying", "Assembly Lines", "Packaging"],
    features: ["Double pitch conveyor series", "Straight sidebars"],
    specs: { pitch_in: "1.250", roller_width_in: "0.375", roller_dia_in: "0.400", pin_dia_in: "0.200", plate_height_in: "0.594", plate_thick_in: "0.079", avg_ultimate_lbs: "6,100" },
    related_pins: [{ code: "C2050 CL", name: "C2050 Connecting Link", description: "" }],
    related_sprockets: [{ code: "C2050B*T", name: "C2050 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Attachments", "Over-size rollers"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/double-pitch-roller-chains",
    notes: "",
  },
  {
    id: "RC-C2060", part_number: "C2060", chain_number: "C2060",
    category: "performance_roller", subcategory: "double_pitch",
    product_type: "Double Pitch Conveyor Chain",
    description: "1-1/2 inch pitch double pitch conveyor chain. Heavy version (C2060H) also available.",
    image: DOUBLE_PITCH_IMAGE,
    industries: ["Conveying", "Manufacturing", "Packaging"],
    features: ["Double pitch", "H-version available for higher loads"],
    specs: { pitch_in: "1.500", roller_width_in: "0.500", roller_dia_in: "0.469", pin_dia_in: "0.235", plate_height_in: "0.712", plate_thick_in: "0.093", avg_ultimate_lbs: "8,500" },
    related_pins: [{ code: "C2060 CL", name: "C2060 Connecting Link", description: "" }],
    related_sprockets: [{ code: "C2060B*T", name: "C2060 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Heavy version (C2060H)", "Attachments"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/double-pitch-roller-chains",
    notes: "",
  },
  {
    id: "RC-C2080", part_number: "C2080", chain_number: "C2080",
    category: "performance_roller", subcategory: "double_pitch",
    product_type: "Double Pitch Conveyor Chain",
    description: "2-inch pitch double pitch conveyor chain. C2080H heavy version available.",
    image: DOUBLE_PITCH_IMAGE,
    industries: ["Conveying", "Heavy Manufacturing"],
    features: ["Double pitch 2-inch", "H-version available"],
    specs: { pitch_in: "2.000", roller_width_in: "0.625", roller_dia_in: "0.625", pin_dia_in: "0.312", plate_height_in: "0.950", plate_thick_in: "0.125", avg_ultimate_lbs: "14,500" },
    related_pins: [{ code: "C2080 CL", name: "C2080 Connecting Link", description: "" }],
    related_sprockets: [{ code: "C2080B*T", name: "C2080 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Heavy version (C2080H)", "Attachments"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "viewitems/precision-roller-chains/double-pitch-roller-chains",
    notes: "",
  },

  // ── SUPER SERIES ─────────────────────────────────────────────────────────
  {
    id: "RC-60SS", part_number: "60SS", chain_number: "60SS",
    category: "performance_roller", subcategory: "super_series",
    product_type: "Super Series Roller Chain",
    description: "3/4-inch pitch Super Series roller chain. Through-hardened pins, wide waist design, ball-drifted sideplate holes, and solid bushings for maximum fatigue resistance and wear life.",
    image: ALLIED + "ImgSmall/PRC%20Wide%20Waist%20LD.jpg",
    industries: ["Heavy Industrial", "Mining", "Construction Equipment", "Severe-Duty Applications"],
    features: ["Through-hardened pins", "Wide waist design for fatigue resistance", "Ball-drifted sideplate holes (better press fit)", "Solid bushings (enhanced wear)", "Shot peened side plates"],
    specs: { pitch_in: "0.750", notes: "Dimensions match standard ANSI #60. Specs to be confirmed by Uniking." },
    related_pins: [{ code: "60 CL", name: "No. 60 Connecting Link", description: "Standard ANSI #60 connecting link compatible." }],
    related_sprockets: [{ code: "60B*T", name: "No. 60 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Riveted and cottered construction"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/ll-categories-precision-roller-chains-super-series",
    notes: "Full super series spec sheet — contact Uniking or Allied-Locke.",
  },

  // ── STAINLESS STEEL ──────────────────────────────────────────────────────
  {
    id: "RC-40SS", part_number: "40SS", chain_number: "40SS",
    category: "performance_roller", subcategory: "stainless",
    product_type: "Stainless Steel Roller Chain",
    description: "1/2-inch pitch 304 stainless steel roller chain. Corrosion-resistant for food, pharmaceutical, and washdown applications.",
    image: ALLIED + "ImgSmall/a1022.jpg",
    industries: ["Food Processing", "Pharmaceutical", "Chemical", "Marine", "Washdown Applications"],
    features: ["304 Stainless steel construction", "Corrosion resistant", "ANSI-compatible dimensions", "Available in 316 on request"],
    specs: { pitch_in: "0.500", roller_width_in: "0.312", roller_dia_in: "0.312", pin_dia_in: "0.156", avg_ultimate_lbs: "3,300", notes: "Stainless steel avg. strength typically 10% lower than carbon steel equivalent." },
    related_pins: [{ code: "40SS CL", name: "No. 40 SS Connecting Link", description: "Stainless steel connecting link." }],
    related_sprockets: [{ code: "40B*T", name: "No. 40 Sprockets", bore: "To suit", notes: "Stainless sprockets available." }],
    related_attachments: [],
    options: ["304 SS", "316 SS on request", "Passivated"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/stainless-steel-chains",
    notes: "Full stainless range: 25SS through 160SS. Contact Uniking for full list.",
  },

  // ── NICKEL PLATED ────────────────────────────────────────────────────────
  {
    id: "RC-40NP", part_number: "40NP", chain_number: "40NP",
    category: "performance_roller", subcategory: "nickel_plated",
    product_type: "Nickel Plated Roller Chain",
    description: "1/2-inch pitch nickel-plated roller chain. Plated before assembly for corrosion resistance and visual appeal. Near-equivalent strength to standard chain.",
    image: ALLIED + "ImgSmall/a1020.jpg",
    industries: ["Food Processing", "Pharmaceutical", "Clean Room", "Decorative Applications"],
    features: ["Nickel plated before assembly", "Corrosion resistant", "Attractive appearance", "Near-standard strength"],
    specs: { pitch_in: "0.500", notes: "Dimensions identical to standard No. 40. Strength within 5% of standard." },
    related_pins: [{ code: "40 CL NP", name: "No. 40 Nickel Plated Connecting Link", description: "" }],
    related_sprockets: [{ code: "40B*T", name: "No. 40 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Nickel plated full chain", "Can be paired with NP connecting links"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/nickel-plated-chains",
    notes: "Full NP range: 25NP–160NP plus multi-strand. Contact Uniking.",
  },

  // ── SELF-LUBE ────────────────────────────────────────────────────────────
  {
    id: "RC-40SL", part_number: "40SL", chain_number: "40SL",
    category: "performance_roller", subcategory: "self_lube",
    product_type: "Self-Lube Roller Chain",
    description: "1/2-inch pitch self-lubricating roller chain. For applications where normal lubrication is not possible or restricted. Interchangeable with standard ANSI sprockets.",
    image: ALLIED + "ImgSmall/a1012.jpg",
    industries: ["Food Processing", "Pharmaceutical", "Clean Room", "Painting/Coating Lines", "Dry Environments"],
    features: ["Oil-impregnated sintered bushings", "No external lubrication required", "ANSI sprocket compatible", "Seizure-free long life"],
    specs: { pitch_in: "0.500", notes: "Dimensions identical to standard No. 40." },
    related_pins: [{ code: "40 CL", name: "No. 40 Connecting Link", description: "" }],
    related_sprockets: [{ code: "40B*T", name: "No. 40 Sprockets", bore: "To suit" }],
    related_attachments: [],
    options: ["Pre-greased at assembly"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/precision-roller-chains/self-lube-chains",
    notes: "Self-lube range: 40SL–120SL. Contact Uniking for full list.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // WELDED STEEL CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "WS-WH78", part_number: "WH78", chain_number: "WH78",
    category: "welded_steel", subcategory: "wh_series",
    product_type: "WH Series Welded Steel Chain",
    description: "WH78 welded steel chain. For heavy-duty drag, conveyor, and elevator applications. All-welded construction for maximum strength.",
    image: WH_IMAGE,
    industries: ["Mining", "Grain Handling", "Aggregate", "Cement", "Recycling"],
    features: ["All-welded construction", "High tensile strength", "Heat-treated components", "Open barrel design"],
    specs: { pitch_in: "2.609", avg_ultimate_lbs: "22,000", weight_lbs_ft: "3.60", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "WH78 CL", name: "WH78 Connecting Link", description: "WH series connecting link — confirm with Uniking." }],
    related_sprockets: [{ code: "WH78 Sprocket", name: "WH78 Compatible Sprocket", description: "To be confirmed by Uniking.", notes: "Specification to be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments (K1, A1, S1)", "Hardened components"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/welded-steel-chains",
    notes: "Full WH series range: WH78, WH82, WH110, WH111, WH124, WH132, WH150, WH155. Contact Uniking.",
  },
  {
    id: "WS-WH124", part_number: "WH124", chain_number: "WH124",
    category: "welded_steel", subcategory: "wh_series",
    product_type: "WH Series Welded Steel Chain",
    description: "WH124 welded steel chain. Heavy-duty conveying and elevator applications.",
    image: WH_IMAGE,
    industries: ["Mining", "Grain Handling", "Aggregate", "Cement"],
    features: ["All-welded construction", "Heavy-duty rated", "Heat-treated"],
    specs: { pitch_in: "4.000", avg_ultimate_lbs: "47,000", weight_lbs_ft: "7.20", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "WH124 CL", name: "WH124 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "WH124 Sprocket", name: "WH124 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/welded-steel-chains",
    notes: "Missing Data – Needs Mapping for full spec. Contact Uniking.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // STEEL PINTLE CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "SP-667", part_number: "667", chain_number: "667",
    category: "steel_pintle", subcategory: "standard_pintle",
    product_type: "Steel Pintle Chain",
    description: "No. 667 steel pintle chain. All heat-treated parts, quad-staked pins. Open barrel design eliminates material build-up. Common in agricultural conveying.",
    image: PINTLE_IMAGE,
    industries: ["Agricultural", "Grain Handling", "Manure Handling", "General Conveying"],
    features: ["All heat-treated components", "Quad-staked pins", "Open barrel design", "Prevents material build-up at sprocket root"],
    specs: { pitch_in: "1.634", avg_ultimate_lbs: "8,000", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "667 CL", name: "No. 667 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "667 Sprocket", name: "No. 667 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [{ code: "667 A1", name: "667 A1 Attachment", type: "Standard agricultural attachment" }],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/agricultural-chains/steel-pintle-chains",
    notes: "Full pintle range: 662, 667, 677, 698, 699, 700, 708, 720, 730, 740, 750, 762. Contact Uniking.",
  },
  {
    id: "SP-CA550", part_number: "CA550", chain_number: "CA550",
    category: "steel_pintle", subcategory: "standard_pintle",
    product_type: "Steel Pintle Chain",
    description: "No. CA550 agricultural pintle chain. Common standard for farm and conveying equipment.",
    image: PINTLE_IMAGE,
    industries: ["Agricultural", "Farm Equipment", "Grain Handling"],
    features: ["Heat-treated components", "Open barrel design", "Standard agricultural chain"],
    specs: { pitch_in: "1.630", avg_ultimate_lbs: "8,500", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "CA550 CL", name: "CA550 Connecting Link", description: "" }],
    related_sprockets: [{ code: "CA550 Sprocket", name: "CA550 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [{ code: "CA550-A1", name: "CA550 A1 Attachment", type: "A1", image: ALLIED + "ImgSmall/CA550-A1-attachment.jpg" }],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/agricultural-chains/steel-pintle-chains",
    notes: "Missing Data – Needs Mapping for full spec confirmation.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // ENGINEERED CLASS — SS CLASS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "EC-SS188", part_number: "SS188", chain_number: "SS188",
    category: "engineered_class", subcategory: "ss_class",
    product_type: "SS Class Bushed Steel Chain",
    description: "SS188 bushed steel conveying chain. Heavy-duty engineered class for industrial bulk handling and elevating applications.",
    image: SS_IMAGE,
    industries: ["Mining", "Aggregate", "Cement", "Grain", "Industrial Conveying"],
    features: ["Solid bushing design", "Heat-treated components", "High tensile strength", "For heavy drag/conveyor use"],
    specs: { pitch_in: "2.310", avg_ultimate_lbs: "19,000", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "SS188 CL", name: "SS188 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "SS188 Sprocket", name: "SS188 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/ss-class-bushed-steel-chains-2",
    notes: "Full SS class range available. Contact Uniking.",
  },

  // ── MSR CLASS ────────────────────────────────────────────────────────────
  {
    id: "EC-MSR6018", part_number: "MSR6018", chain_number: "MSR6018",
    category: "engineered_class", subcategory: "msr_class",
    product_type: "MSR Class Bushed Roller Steel Chain",
    description: "MSR6018 bushed roller steel chain. Medium-to-heavy industrial conveying with roller for reduced friction.",
    image: MSR_IMAGE,
    industries: ["Industrial Conveying", "Mining", "Aggregate", "Lumber"],
    features: ["Bushed roller design", "Reduced friction vs. plain chains", "Heat-treated components"],
    specs: { pitch_in: "6.000", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "MSR6018 CL", name: "MSR6018 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "MSR6018 Sprocket", name: "MSR6018 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/msr-class-bushed-roller-steel-chains-2",
    notes: "Full MSR class range available. Contact Uniking.",
  },

  // ── MXS CLASS ────────────────────────────────────────────────────────────
  {
    id: "EC-MXS881", part_number: "MXS881", chain_number: "MXS881",
    category: "engineered_class", subcategory: "mxs_class",
    product_type: "MXS Class Offset Steel Drive Chain",
    description: "MXS881 offset steel drive chain for high-load industrial drive applications.",
    image: MXS_IMAGE,
    industries: ["Industrial Drives", "Mining", "Aggregate", "Material Handling"],
    features: ["Offset link design", "High tensile strength", "Heavy-duty drive applications"],
    specs: { pitch_in: "Missing Data – Needs Mapping", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "MXS881 CL", name: "MXS881 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "MXS881 Sprocket", name: "MXS881 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: [],
    source: "Allied-Locke",
    source_url: ALLIED + "category/mxs-class-offset-steel-drive-chains",
    notes: "Missing Data – Needs Mapping. Contact Uniking.",
  },

  // ── COMBINATION ──────────────────────────────────────────────────────────
  {
    id: "EC-C188", part_number: "C188", chain_number: "C188",
    category: "engineered_class", subcategory: "combination",
    product_type: "Combination Chain",
    description: "C188 combination chain. Combines cast iron links with forged steel pins for elevated load capacity and interchangeability.",
    image: COMB_IMAGE,
    industries: ["Aggregate", "Mining", "Grain Handling", "Bulk Material"],
    features: ["Cast/forged combination design", "Interchangeable links", "Heavy-duty rated"],
    specs: { notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "C188 CL", name: "C188 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "C188 Sprocket", name: "C188 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/combination-chains-2",
    notes: "Full combination chain range available. Contact Uniking.",
  },

  // ── H-CLASS / DRAG / TRANSFER ────────────────────────────────────────────
  {
    id: "EC-H78", part_number: "H78", chain_number: "H78",
    category: "engineered_class", subcategory: "h_class",
    product_type: '"H" Class Mill / Drag / Transfer Chain',
    description: 'H78 "H" class mill, drag, and transfer chain. For heavy mill and drag conveyor applications.',
    image: H_IMAGE,
    industries: ["Steel Mills", "Lumber Mills", "Mining", "Aggregate", "Bulk Transfer"],
    features: ["H-class heavy mill construction", "High load capacity", "Drag and transfer applications"],
    specs: { notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "H78 CL", name: "H78 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "H78 Sprocket", name: "H78 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With attachments"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/-h-class-mill-drag-and-transfer-chains",
    notes: "Full H-class range available. Contact Uniking.",
  },

  // ── DROP FORGED RIVETLESS ────────────────────────────────────────────────
  {
    id: "EC-DF458", part_number: "DF458", chain_number: "DF458",
    category: "engineered_class", subcategory: "drop_forged",
    product_type: "Rivetless Drop Forged Chain",
    description: "Drop forged rivetless chain. No rivets to fatigue or fail. Designed for overhead conveying and pusher applications.",
    image: DROP_IMAGE,
    industries: ["Automotive Assembly", "Paint Lines", "Overhead Conveying", "Monorail Systems"],
    features: ["No rivets — rivetless design", "Drop forged steel", "High fatigue resistance", "Easy assembly/disassembly"],
    specs: { notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "DF458 CL", name: "DF458 Connecting Pin", description: "Contact Uniking." }],
    related_sprockets: [{ code: "DF458 Sprocket", name: "DF458 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With pusher attachments", "Overhead trolley attachment"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/rivetless-drop-forged-chains",
    notes: "Full drop forged range available. Contact Uniking.",
  },

  // ── CAST MANGANESE ───────────────────────────────────────────────────────
  {
    id: "EC-CMR", part_number: "CMR Series", chain_number: "CMR",
    category: "engineered_class", subcategory: "cast_manganese",
    product_type: "Cast Manganese / Alloy Steel Rivetless Chain",
    description: "Cast manganese and alloy steel rivetless chains for extreme abrasion and impact resistance. Used in bucket elevators and heavy drag conveyors.",
    image: CAST_IMAGE,
    industries: ["Grain Elevators", "Mining", "Aggregate", "Cement", "Bulk Material"],
    features: ["Cast manganese steel for abrasion resistance", "Alloy steel options", "Rivetless design", "High impact resistance"],
    specs: { notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "CMR CL", name: "CMR Connecting Pin", description: "Contact Uniking." }],
    related_sprockets: [{ code: "CMR Sprocket", name: "CMR Compatible Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["Manganese steel", "Alloy steel"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/cast-manganese-and-alloy-steel-chains",
    notes: "Full cast manganese range available. Contact Uniking.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // AGRICULTURAL CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "AG-CA550R", part_number: "CA550R", chain_number: "CA550R",
    category: "agricultural", subcategory: "ag_roller",
    product_type: "Agricultural Roller Chain",
    description: "CA550R agricultural roller chain. Hardened steel parts, close tolerances. For combines, forage harvesters, and farm equipment.",
    image: AG_IMAGE,
    industries: ["Agriculture", "Combines", "Forage Harvesters", "Farm Equipment"],
    features: ["Hardened steel parts", "Close manufacturing tolerances", "High quality for long service life", "Agricultural standard"],
    specs: { pitch_in: "1.630", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "CA550R CL", name: "CA550R Connecting Link", description: "" }],
    related_sprockets: [{ code: "CA550R Sprocket", name: "CA550R Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [{ code: "CA550R-A1", name: "CA550R Attachment A1", type: "A1 — Agricultural extended tab" }],
    options: ["With slats", "With flights"],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/agricultural-chains/agricultural-roller-chains",
    notes: "Full agricultural roller range: CA550, CA557, CA620, CA2060, etc. Contact Uniking.",
  },
  {
    id: "AG-DETACH55", part_number: "55", chain_number: "No. 55 Detachable",
    category: "agricultural", subcategory: "ag_detachable",
    product_type: "Steel Detachable Chain",
    description: "No. 55 steel detachable chain. Hot-rolled strip steel, heat-treated. For moderate loads and speeds. Easy to install and repair.",
    image: DETACH_IMAGE,
    industries: ["Agriculture", "Grain Handling", "Light Industrial Conveying"],
    features: ["Hot-rolled strip steel", "Heat-treated for strength and wear", "Easy installation and repair", "Moderate loads and speeds"],
    specs: { pitch_in: "Missing Data – Needs Mapping", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "55 CL", name: "No. 55 Connecting Link", description: "" }],
    related_sprockets: [{ code: "55 Sprocket", name: "No. 55 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: [],
    source: "Allied-Locke",
    source_url: ALLIED + "viewitems/agricultural-chains/steel-detachable-chains",
    notes: "Full detachable range: 25, 32, 32W, 41, 51, 52, 55, 57, 62, 67, 67W, 69, 72, 74, 77, 78, 88, 88W, 104. Contact Uniking.",
  },
  {
    id: "AG-TBAR67", part_number: "AL67-T-Bar", chain_number: "67 T-Bar",
    category: "agricultural", subcategory: "ag_tbar",
    product_type: "T-Bar Chain",
    description: "No. 67 T-Bar agricultural chain. Clean design prevents clogging. Easy assembly/disassembly. Longer wear life than detachable or pintle chains.",
    image: TBAR_IMAGE,
    industries: ["Agriculture", "Grain Handling", "Spreader Equipment"],
    features: ["Clean T-bar design — no clogging", "Easy assembly and disassembly", "Longer wear life than detachable/pintle", "Runs on standard #67 sprockets"],
    specs: { pitch_in: "Missing Data – Needs Mapping", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "67 T-Bar CL", name: "No. 67 T-Bar Connecting Link", description: "" }],
    related_sprockets: [{ code: "67 Sprocket", name: "No. 67 Sprocket", description: "Standard #67 sprockets compatible." }],
    related_attachments: [],
    options: [],
    source: "Allied-Locke",
    source_url: ALLIED + "item/agricultural-chains/t-bar-chains/al67-t-bar",
    notes: "",
  },
  {
    id: "AG-TROD67", part_number: "AL67-T-Rod", chain_number: "67 T-Rod",
    category: "agricultural", subcategory: "ag_trod",
    product_type: "T-Rod Chain",
    description: "No. 67 T-Rod chain. Designed for spreaders. Unique design increases fatigue and wear life, reduces stretching. Runs on standard #67 sprockets.",
    image: TROD_IMAGE,
    industries: ["Agriculture", "Spreaders", "Farm Equipment"],
    features: ["Unique T-rod design", "Increased fatigue life", "Reduced stretching", "Smooth and quiet operation", "Standard #67 sprocket compatible"],
    specs: { pitch_in: "Missing Data – Needs Mapping", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "67 T-Rod CL", name: "No. 67 T-Rod Connecting Link", description: "" }],
    related_sprockets: [{ code: "67 Sprocket", name: "No. 67 Sprocket", description: "Standard #67 sprockets compatible." }],
    related_attachments: [],
    options: [],
    source: "Allied-Locke",
    source_url: ALLIED + "item/agricultural-chains/t-rod-chains/al67-t-rod",
    notes: "",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // TRANSFER CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "TR-H78T", part_number: "H78-Transfer", chain_number: "H78 Transfer",
    category: "transfer", subcategory: "h_transfer",
    product_type: "Transfer Chain",
    description: "H-class transfer chain for mill, drag, and heavy product transfer applications. Used in assembly lines, steel mills, and bulk handling facilities.",
    image: H_IMAGE,
    industries: ["Steel Mills", "Assembly Lines", "Lumber", "Mining", "Bulk Transfer"],
    features: ["Heavy mill-class construction", "Transfer and drag rated", "Heat-treated steel"],
    specs: { notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "H78 CL", name: "H78 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [{ code: "H78 Sprocket", name: "H78 Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["With pusher attachments", "With flight attachments"],
    source: "Allied-Locke / MAC Chain",
    source_url: ALLIED + "category/-h-class-mill-drag-and-transfer-chains",
    notes: "Missing Data – Needs Mapping. Contact Uniking.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // LEAF CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "LC-AL422", part_number: "AL422", chain_number: "AL422",
    category: "leaf_chain", subcategory: "al_series",
    product_type: "AL Series Leaf Chain",
    description: "AL422 leaf chain. For forklift masts, tension linkages, and balance applications. No sprockets — runs over sheaves.",
    image: LEAF_IMAGE,
    industries: ["Forklift / Material Handling", "Cranes", "Tension Linkages", "Counterbalance Systems"],
    features: ["AL-series leaf chain (2×2 lacing)", "High tensile strength", "Runs over sheaves (no sprockets)", "ANSI/ASME B29.8 compliant"],
    specs: { pitch_in: "0.500", lacing: "2×2", avg_ultimate_lbs: "5,800", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "AL422 CL", name: "AL422 Anchor Link/Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [],
    related_attachments: [{ code: "AL422 Anchor", name: "Anchor Link — AL422", type: "Anchor / Fork attachment" }],
    options: ["Anchor links", "Various lacing patterns"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/leaf-chains",
    notes: "Full AL and BL series available. Contact Uniking.",
  },
  {
    id: "LC-BL444", part_number: "BL444", chain_number: "BL444",
    category: "leaf_chain", subcategory: "bl_series",
    product_type: "BL Series Leaf Chain",
    description: "BL444 heavy leaf chain. For high-capacity forklift masts and heavy lifting. BL series has more plates per link than AL for higher strength.",
    image: LEAF_IMAGE,
    industries: ["Forklift / Material Handling", "Heavy Cranes", "Lifting Equipment"],
    features: ["BL-series leaf chain (4×4 lacing)", "Very high tensile strength", "Runs over sheaves", "ANSI/ASME B29.8 compliant"],
    specs: { pitch_in: "0.500", lacing: "4×4", avg_ultimate_lbs: "13,100", notes: "Specification to be confirmed by Uniking." },
    related_pins: [{ code: "BL444 CL", name: "BL444 Connecting Link", description: "Contact Uniking." }],
    related_sprockets: [],
    related_attachments: [{ code: "BL444 Anchor", name: "Anchor Link — BL444", type: "Anchor / Fork attachment" }],
    options: ["Anchor links"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/leaf-chains",
    notes: "Full BL series available. Contact Uniking.",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // SILENT / INVERTED TOOTH CHAINS
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "SC-EXCEL", part_number: "Excel Series", chain_number: "Excel IT",
    category: "silent_chain", subcategory: "excel_series",
    product_type: "Silent / Inverted Tooth Chain — Excel Series",
    description: "Excel series inverted tooth chain. Outer sidebars as guides. Type A and Type B link profiles. High speed, high load, low noise. Excellent fatigue resistance and wear life.",
    image: SILENT_IMAGE,
    industries: ["Automotive", "Machinery", "High-Speed Drives", "Timing Applications"],
    features: ["Outer sidebar guide (Excel series)", "Type A (higher load/speed) and Type B options", "High tensile strength", "Excellent fatigue resistance", "Low noise operation", "Long wear life"],
    specs: { notes: "Specification to be confirmed by Uniking. Widths and pitches vary by part number." },
    related_pins: [{ code: "Excel CL", name: "Excel Series Connecting Link", description: "Contact Uniking for specific part." }],
    related_sprockets: [{ code: "Excel Sprocket", name: "Excel Series Inverted Tooth Sprocket", description: "To be confirmed by Uniking." }],
    related_attachments: [],
    options: ["Type A", "Type B", "Custom widths"],
    source: "Allied-Locke",
    source_url: ALLIED + "category/recision-roller-chains-silent-chain-inverted-tooth",
    notes: "Full Excel and Silent series available. Contact Uniking for specific part numbers and dimensions.",
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getProductsByCategory(categoryKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey);
}

export function getProductsBySubcategory(categoryKey, subcategoryKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey && p.subcategory === subcategoryKey);
}

export function searchChainProducts(query) {
  const q = query.toLowerCase();
  return CHAIN_PRODUCTS.filter(p =>
    p.chain_number?.toLowerCase().includes(q) ||
    p.part_number?.toLowerCase().includes(q) ||
    p.product_type?.toLowerCase().includes(q) ||
    p.description?.toLowerCase().includes(q) ||
    p.industries?.some(i => i.toLowerCase().includes(q)) ||
    p.features?.some(f => f.toLowerCase().includes(q))
  );
}

export function getCategoryByKey(key) {
  return CHAIN_CATEGORIES.find(c => c.key === key);
}