/**
 * chainDataEngineered.js
 * Welded Steel (WH/WD), Steel Pintle, Engineered Class,
 * Agricultural, Leaf, Silent/Inverted Tooth, and Attachments.
 * All specs verified from Allied-Locke live catalog.
 */
import { IMG, SRC, cl, spr, att } from "@/lib/chainCatalogImages.js";

export const ENGINEERED_CHAIN_PRODUCTS = [

  // ── WH SERIES WELDED MILL CHAINS ─────────────────────────────────────────
  { id:"WH-WH188", part_number:"WH188", chain_number:"WH188", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH188 welded steel mill chain. 2.609-inch pitch. Soft bend. For conveying, driving, and elevating. Interchangeable with cast chain sprockets.",
    image:IMG.wh_soft, industries:["Mining","Grain Handling","Aggregate","Cement","Recycling"],
    features:["All-welded construction","Soft bend design","Interchangeable with cast chain sprockets","WHX induction-hardened version available"],
    specs:{ pitch_in:"2.609", rivet_dia_in:"0.500", sidebar_width_in:"1.12", barrel_dia_in:"0.88", max_sprocket_face_in:"0.88", bearing_length_in:"1.62", max_working_load_lbs:"2,850" },
    related_pins:[{code:"WH188 CL",name:"WH188 Connecting Link",description:""}], related_sprockets:[{code:"WH188 Sprocket",name:"WH188 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WHX induction-hardened version","With attachments (A1, K1, S1)"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH78", part_number:"WH78", chain_number:"WH78", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH78 welded steel mill chain. 2.609-inch pitch. Most commonly specified welded mill chain.",
    image:IMG.wh_soft, industries:["Mining","Grain Handling","Aggregate","Cement","Industrial Conveying"],
    features:["All-welded construction","Soft bend design","Most common WH size","WHX version available"],
    specs:{ pitch_in:"2.609", rivet_dia_in:"0.500", sidebar_width_in:"1.12", barrel_dia_in:"0.88", max_sprocket_face_in:"1.12", bearing_length_in:"2.00", max_working_load_lbs:"3,500" },
    related_pins:[{code:"WH78 CL",name:"WH78 Connecting Link",description:""}], related_sprockets:[{code:"WH78 Sprocket",name:"WH78 Sprocket",bore:"To suit"}], related_attachments:[{code:"WH78 A1",name:"WH78 A1 Attachment",type:"A1 — One extended tab"}],
    options:["WHX version (induction hardened)","WH78-4 (4-inch pitch)","With attachments"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH78-4", part_number:"WH78-4", chain_number:"WH78-4", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH78-4 welded mill chain. 4.000-inch pitch. Same cross-section as WH78 but longer pitch.",
    image:IMG.wh_soft, industries:["Mining","Grain Handling","Aggregate"],
    features:["4-inch pitch","All-welded construction"],
    specs:{ pitch_in:"4.000", rivet_dia_in:"0.500", sidebar_width_in:"1.12", barrel_dia_in:"0.88", max_sprocket_face_in:"1.12", bearing_length_in:"2.00", max_working_load_lbs:"3,500" },
    related_pins:[{code:"WH78-4 CL",name:"WH78-4 Connecting Link",description:""}], related_sprockets:[{code:"WH78-4 Sprocket",name:"WH78-4 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH82", part_number:"WH82", chain_number:"WH82", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH82 welded steel mill chain. 3.075-inch pitch. Larger cross-section than WH78.",
    image:IMG.wh_soft, industries:["Mining","Grain Handling","Aggregate"],
    features:["3.075-inch pitch","Larger cross-section","All-welded"],
    specs:{ pitch_in:"3.075", rivet_dia_in:"0.560", sidebar_width_in:"1.250", barrel_dia_in:"1.06", max_sprocket_face_in:"1.25", bearing_length_in:"2.25", max_working_load_lbs:"4,400" },
    related_pins:[{code:"WH82 CL",name:"WH82 Connecting Link",description:""}], related_sprockets:[{code:"WH82 Sprocket",name:"WH82 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH124", part_number:"WH124", chain_number:"WH124", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH124 welded steel mill chain. 4.000-inch pitch. 7,200 lb max working load.",
    image:IMG.wh_soft, industries:["Mining","Grain Handling","Aggregate","Cement","Industrial Conveying"],
    features:["4-inch pitch","All-welded construction","Heat-treated components","7,200 lb max working load"],
    specs:{ pitch_in:"4.000", rivet_dia_in:"0.750", sidebar_width_in:"1.50", barrel_dia_in:"1.25", max_sprocket_face_in:"1.50", bearing_length_in:"2.75", max_working_load_lbs:"7,200" },
    related_pins:[{code:"WH124 CL",name:"WH124 Connecting Link",description:""}], related_sprockets:[{code:"WH124 Sprocket",name:"WH124 Sprocket",bore:"To suit"}], related_attachments:[{code:"WH124 A1",name:"WH124 A1 Attachment",type:"A1",image:IMG.wh_attach}],
    options:["WHX version (induction hardened)","WH124HD (10,500 lb)","With attachments"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH124HD", part_number:"WH124HD", chain_number:"WH124HD", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain — Heavy Duty",
    description:"WH124HD heavy-duty welded mill chain. 4.063-inch pitch. 10,500 lb max working load — 46% higher than WH124.",
    image:IMG.wh_soft, industries:["Heavy Mining","Aggregate","Cement"],
    features:["Heavy duty (HD)","10,500 lb max working load","1.00-inch rivet diameter"],
    specs:{ pitch_in:"4.063", rivet_dia_in:"1.00", sidebar_width_in:"2.00", barrel_dia_in:"1.62", max_sprocket_face_in:"1.62", bearing_length_in:"3.00", max_working_load_lbs:"10,500" },
    related_pins:[{code:"WH124HD CL",name:"WH124HD Connecting Link",description:""}], related_sprockets:[{code:"WH124HD Sprocket",name:"WH124HD Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH132", part_number:"WH132", chain_number:"WH132", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH132 welded steel mill chain. 6.050-inch pitch. Hard bend type. 15,300 lb max working load.",
    image:IMG.wh_hard, industries:["Heavy Mining","Aggregate","Bulk Conveying"],
    features:["6.050-inch pitch","Hard bend design","15,300 lb max working load"],
    specs:{ pitch_in:"6.050", rivet_dia_in:"1.00", sidebar_width_in:"2.00", barrel_dia_in:"1.62", max_sprocket_face_in:"2.88", bearing_length_in:"4.38", max_working_load_lbs:"15,300" },
    related_pins:[{code:"WH132 CL",name:"WH132 Connecting Link",description:""}], related_sprockets:[{code:"WH132 Sprocket",name:"WH132 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WH132HD (16,200 lb)","WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH150", part_number:"WH150", chain_number:"WH150", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH150 welded steel mill chain. 6.050-inch pitch. Wider sidebar (2.50 in). Hard bend. 15,300 lb.",
    image:IMG.wh_hard, industries:["Heavy Mining","Industrial Conveying","Bulk Material"],
    features:["6.050-inch pitch","Wide sidebar (2.50 in)","Hard bend design"],
    specs:{ pitch_in:"6.050", rivet_dia_in:"1.00", sidebar_width_in:"2.50", barrel_dia_in:"1.62", max_sprocket_face_in:"2.88", bearing_length_in:"4.38", max_working_load_lbs:"15,300" },
    related_pins:[{code:"WH150 CL",name:"WH150 Connecting Link",description:""}], related_sprockets:[{code:"WH150 Sprocket",name:"WH150 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WH150HD (16,200 lb)","WH150XHD (18,200 lb)","WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH155", part_number:"WH155", chain_number:"WH155", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH155 welded steel mill chain. 6.050-inch pitch. 17,750 lb max working load.",
    image:IMG.wh_hard, industries:["Heavy Mining","Industrial Conveying"],
    features:["6.050-inch pitch","Hard bend","17,750 lb max working load"],
    specs:{ pitch_in:"6.050", rivet_dia_in:"1.12", sidebar_width_in:"2.50", barrel_dia_in:"1.75", max_sprocket_face_in:"3.00", bearing_length_in:"4.50", max_working_load_lbs:"17,750" },
    related_pins:[{code:"WH155 CL",name:"WH155 Connecting Link",description:""}], related_sprockets:[{code:"WH155 Sprocket",name:"WH155 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WHX version available"], source:"Allied-Locke", source_url:SRC.wh },

  { id:"WH-WH159", part_number:"WH159", chain_number:"WH159", category:"welded_steel", subcategory:"wh_series",
    product_type:"WH Series Welded Mill Chain",
    description:"WH159 welded steel mill chain. 6.125-inch pitch. Largest WH size. 20,250 lb max working load. Soft bend.",
    image:IMG.wh_soft, industries:["Very Heavy Mining","Industrial Conveying"],
    features:["6.125-inch pitch","Largest WH size","20,250 lb max working load","Soft bend"],
    specs:{ pitch_in:"6.125", rivet_dia_in:"1.25", sidebar_width_in:"3.00", barrel_dia_in:"2.00", max_sprocket_face_in:"3.00", bearing_length_in:"4.63", max_working_load_lbs:"20,250" },
    related_pins:[{code:"WH159 CL",name:"WH159 Connecting Link",description:""}], related_sprockets:[{code:"WH159 Sprocket",name:"WH159 Sprocket",bore:"To suit"}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.wh },

  // ── WD SERIES WELDED DRAG CHAINS ─────────────────────────────────────────
  { id:"WD-WD104", part_number:"WD104", chain_number:"WD104", category:"welded_steel", subcategory:"wd_series",
    product_type:"WD Series Welded Drag Chain",
    description:"WD104 welded steel drag chain. 6-inch pitch. Large wide pushing area for bulk material. 8,500 lb max working load.",
    image:IMG.wd_drag, industries:["Mining","Bulk Material Handling","Grain Handling","Industrial Conveying"],
    features:["Large wide pushing area","High capacity at moderate speeds","Interchangeable with cast chain sprockets","WDH heavy version available"],
    specs:{ pitch_in:"6.000", rivet_dia_in:"0.750", sidebar_width_in:"1.50", max_sprocket_face_in:"4.12", bearing_length_in:"5.38", overall_width_in:"6.88", max_working_load_lbs:"8,500" },
    related_pins:[{code:"WD104 CL",name:"WD104 Connecting Link",description:""}], related_sprockets:[{code:"WD104 Sprocket",name:"WD104 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WDH104 heavy version (10,000 lb)"], source:"Allied-Locke", source_url:SRC.wd },

  { id:"WD-WD110", part_number:"WD110", chain_number:"WD110", category:"welded_steel", subcategory:"wd_series",
    product_type:"WD Series Welded Drag Chain",
    description:"WD110 welded drag chain. 6-inch pitch. Extra-wide pushing face (9-inch sprocket face). 8,500 lb.",
    image:IMG.wd_drag, industries:["Mining","Bulk Material","Grain Handling"],
    features:["Wide pushing face","9-inch max sprocket face","6-inch pitch"],
    specs:{ pitch_in:"6.000", rivet_dia_in:"0.750", sidebar_width_in:"1.50", max_sprocket_face_in:"9.00", bearing_length_in:"10.38", overall_width_in:"11.88", max_working_load_lbs:"8,500" },
    related_pins:[{code:"WD110 CL",name:"WD110 Connecting Link",description:""}], related_sprockets:[{code:"WD110 Sprocket",name:"WD110 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WDH110 heavy version (10,000 lb)"], source:"Allied-Locke", source_url:SRC.wd },

  { id:"WD-WD120", part_number:"WD120", chain_number:"WD120", category:"welded_steel", subcategory:"wd_series",
    product_type:"WD Series Welded Drag Chain",
    description:"WD120 welded drag chain. 6-inch pitch. 2-inch sidebar width. 11,700 lb max working load.",
    image:IMG.wd_drag, industries:["Mining","Bulk Material Handling","Industrial Conveying"],
    features:["6-inch pitch","2-inch sidebar width","11,700 lb max working load"],
    specs:{ pitch_in:"6.000", rivet_dia_in:"0.88", sidebar_width_in:"2.00", max_sprocket_face_in:"8.62", bearing_length_in:"10.12", overall_width_in:"12.00", max_working_load_lbs:"11,700" },
    related_pins:[{code:"WD120 CL",name:"WD120 Connecting Link",description:""}], related_sprockets:[{code:"WD120 Sprocket",name:"WD120 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WDH120 (15,000 lb)","WDH120RB (round barrel, 15,000 lb)"], source:"Allied-Locke", source_url:SRC.wd },

  { id:"WD-WD122", part_number:"WD122", chain_number:"WD122", category:"welded_steel", subcategory:"wd_series",
    product_type:"WD Series Welded Drag Chain",
    description:"WD122 welded drag chain. 8-inch pitch. 11,700 lb max working load.",
    image:IMG.wd_drag, industries:["Mining","Bulk Material","Industrial Conveying"],
    features:["8-inch pitch","Wide pushing face"],
    specs:{ pitch_in:"8.000", rivet_dia_in:"0.88", sidebar_width_in:"2.00", max_sprocket_face_in:"8.50", bearing_length_in:"10.12", overall_width_in:"12.00", max_working_load_lbs:"11,700" },
    related_pins:[{code:"WD122 CL",name:"WD122 Connecting Link",description:""}], related_sprockets:[{code:"WD122 Sprocket",name:"WD122 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WDH122 (15,000 lb)"], source:"Allied-Locke", source_url:SRC.wd },

  { id:"WD-WD480", part_number:"WD480", chain_number:"WD480", category:"welded_steel", subcategory:"wd_series",
    product_type:"WD Series Welded Drag Chain",
    description:"WD480 welded drag chain. 8-inch pitch. Largest standard WD. 11,700 lb max working load.",
    image:IMG.wd_drag, industries:["Very Heavy Mining","Industrial Conveying"],
    features:["8-inch pitch","Largest standard WD","Wide overall width (13.81 in)"],
    specs:{ pitch_in:"8.000", rivet_dia_in:"0.88", sidebar_width_in:"2.00", max_sprocket_face_in:"11.25", bearing_length_in:"12.75", overall_width_in:"13.81", max_working_load_lbs:"11,700" },
    related_pins:[{code:"WD480 CL",name:"WD480 Connecting Link",description:""}], related_sprockets:[{code:"WD480 Sprocket",name:"WD480 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["WDH480 (15,000 lb)","WDH480RB round barrel (15,000 lb)"], source:"Allied-Locke", source_url:SRC.wd },

  // ── STEEL PINTLE ─────────────────────────────────────────────────────────
  { id:"SP-662", part_number:"662", chain_number:"662", category:"steel_pintle", subcategory:"standard_pintle",
    product_type:"Steel Pintle Chain",
    description:"No. 662 steel pintle chain. All heat-treated parts, quad-staked pins, open barrel design.",
    image:IMG.ag_pintle, industries:["Agricultural","Grain Handling","Manure Handling","General Conveying"],
    features:["All heat-treated components","Quad-staked pins","Open barrel design","Prevents material clogging"],
    specs:{ notes:"Contact Uniking for pitch and load specifications." },
    related_pins:[cl("662")], related_sprockets:[{code:"662 Sprocket",name:"No. 662 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"], source:"Allied-Locke", source_url:SRC.ag_pintle,
    notes:"Full pintle range: 662, 667, 677, 698, 699, 700, 708, 720, 730, 740, 750, 762. Contact Uniking." },

  { id:"SP-667", part_number:"667", chain_number:"667", category:"steel_pintle", subcategory:"standard_pintle",
    product_type:"Steel Pintle Chain",
    description:"No. 667 steel pintle chain. 1.634-inch pitch. All heat-treated parts, quad-staked pins, open barrel. Most common pintle chain size.",
    image:IMG.ag_pintle, industries:["Agricultural","Grain Handling","Manure Handling","General Conveying"],
    features:["All heat-treated components","Quad-staked pins","Open barrel design","Most popular pintle chain size"],
    specs:{ pitch_in:"1.634", notes:"Max working load to be confirmed by Uniking." },
    related_pins:[cl("667")], related_sprockets:[{code:"667 Sprocket",name:"No. 667 Sprocket",bore:"To suit"}], related_attachments:[att("667","A1")],
    options:["With attachments"], source:"Allied-Locke", source_url:SRC.ag_pintle },

  { id:"SP-677", part_number:"677", chain_number:"677", category:"steel_pintle", subcategory:"standard_pintle",
    product_type:"Steel Pintle Chain",
    description:"No. 677 steel pintle chain. Larger capacity than No. 667.",
    image:IMG.ag_pintle, industries:["Agricultural","Industrial Conveying","Grain Handling"],
    features:["All heat-treated components","Quad-staked pins","Open barrel design"],
    specs:{ notes:"Contact Uniking for pitch and load specs." },
    related_pins:[cl("677")], related_sprockets:[{code:"677 Sprocket",name:"No. 677 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"], source:"Allied-Locke", source_url:SRC.ag_pintle },

  { id:"SP-698", part_number:"698", chain_number:"698", category:"steel_pintle", subcategory:"standard_pintle",
    product_type:"Steel Pintle Chain",
    description:"No. 698 steel pintle chain.",
    image:IMG.ag_pintle, industries:["Agricultural","Industrial Conveying"],
    features:["All heat-treated components","Quad-staked pins","Open barrel"],
    specs:{ notes:"Contact Uniking for pitch and load specs." },
    related_pins:[cl("698")], related_sprockets:[{code:"698 Sprocket",name:"No. 698 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"], source:"Allied-Locke", source_url:SRC.ag_pintle },

  // ── ENGINEERED CLASS — SS ────────────────────────────────────────────────
  { id:"EC-SS188", part_number:"SS188", chain_number:"SS188", category:"engineered_class", subcategory:"ss_class",
    product_type:"SS Class Bushed Steel Chain",
    description:"SS188 bushed steel conveying chain. Heavy-duty engineered class for industrial bulk handling and elevating.",
    image:IMG.ss_class, industries:["Mining","Aggregate","Cement","Grain","Industrial Conveying"],
    features:["Solid bushing design","Heat-treated components","High tensile strength","Heavy drag/conveyor use"],
    specs:{ pitch_in:"2.310", notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"SS188 CL",name:"SS188 Connecting Link",description:""}], related_sprockets:[{code:"SS188 Sprocket",name:"SS188 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"],
    source:"Allied-Locke", source_url:SRC.ss_ec,
    notes:"Full SS class range available. Contact Uniking." },

  // ── MSR CLASS ────────────────────────────────────────────────────────────
  { id:"EC-MSR6018", part_number:"MSR6018", chain_number:"MSR6018", category:"engineered_class", subcategory:"msr_class",
    product_type:"MSR Class Bushed Roller Steel Chain",
    description:"MSR6018 bushed roller steel chain. 6-inch pitch. Medium-to-heavy industrial conveying with roller to reduce friction.",
    image:IMG.msr_class, industries:["Industrial Conveying","Mining","Aggregate","Lumber"],
    features:["Bushed roller design","Reduced friction vs. plain chains","Heat-treated components"],
    specs:{ pitch_in:"6.000", notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"MSR6018 CL",name:"MSR6018 Connecting Link",description:""}], related_sprockets:[{code:"MSR6018 Sprocket",name:"MSR6018 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"],
    source:"Allied-Locke", source_url:SRC.msr,
    notes:"Full MSR class range available. Contact Uniking." },

  // ── MXS CLASS ────────────────────────────────────────────────────────────
  { id:"EC-MXS881", part_number:"MXS881", chain_number:"MXS881", category:"engineered_class", subcategory:"mxs_class",
    product_type:"MXS Class Offset Steel Drive Chain",
    description:"MXS881 offset steel drive chain for high-load industrial drive applications. Unique offset link design.",
    image:IMG.mxs_class, industries:["Industrial Drives","Mining","Aggregate","Material Handling"],
    features:["Offset link design","High tensile strength","Heavy-duty drive applications"],
    specs:{ notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"MXS881 CL",name:"MXS881 Connecting Link",description:""}], related_sprockets:[{code:"MXS881 Sprocket",name:"MXS881 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["Full MXS class range available"],
    source:"Allied-Locke", source_url:SRC.mxs,
    notes:"Full MXS class range available. Contact Uniking." },

  // ── COMBINATION ──────────────────────────────────────────────────────────
  { id:"EC-C188", part_number:"C188", chain_number:"C188", category:"engineered_class", subcategory:"combination",
    product_type:"Combination Chain",
    description:"C188 combination chain. Combines cast iron links with forged steel pins. Interchangeable with cast or welded chain sprockets.",
    image:IMG.combination, industries:["Aggregate","Mining","Grain Handling","Bulk Material"],
    features:["Cast/forged combination design","Interchangeable with cast chain sprockets","Heavy-duty rated"],
    specs:{ notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"C188 CL",name:"C188 Connecting Link",description:""}], related_sprockets:[{code:"C188 Sprocket",name:"C188 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"],
    source:"Allied-Locke", source_url:SRC.comb,
    notes:"Full combination chain range available. Contact Uniking." },

  // ── H-CLASS ──────────────────────────────────────────────────────────────
  { id:"EC-H78", part_number:"H78", chain_number:"H78", category:"engineered_class", subcategory:"h_class",
    product_type:'"H" Class Mill / Drag / Transfer Chain',
    description:'H78 "H" class chain. For heavy mill, drag, and transfer conveyor applications.',
    image:IMG.h_class, industries:["Steel Mills","Lumber Mills","Mining","Aggregate","Bulk Transfer"],
    features:["H-class heavy mill construction","High load capacity","Drag and transfer applications","Smooth plain chain"],
    specs:{ notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"H78 CL",name:"H78 Connecting Link",description:""}], related_sprockets:[{code:"H78 Sprocket",name:"H78 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With attachments"],
    source:"Allied-Locke", source_url:SRC.h_class,
    notes:"Full H-class range available. Contact Uniking." },

  // ── DROP FORGED ──────────────────────────────────────────────────────────
  { id:"EC-DF458", part_number:"DF458", chain_number:"DF458", category:"engineered_class", subcategory:"drop_forged",
    product_type:"Rivetless Drop Forged Chain",
    description:"Drop forged rivetless chain. No rivets to fatigue or fail. For overhead conveying, pusher conveyors, and monorail systems.",
    image:IMG.drop_forged, industries:["Automotive Assembly","Paint Lines","Overhead Conveying","Monorail Systems"],
    features:["No rivets — rivetless design","Drop forged steel","High fatigue resistance","Easy assembly and disassembly"],
    specs:{ notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"DF458 CL",name:"DF458 Connecting Pin",description:""}], related_sprockets:[{code:"DF458 Sprocket",name:"DF458 Sprocket",bore:"To suit"}], related_attachments:[],
    options:["With pusher attachments","Overhead trolley attachment"],
    source:"Allied-Locke", source_url:SRC.drop,
    notes:"Full drop forged range available. Contact Uniking." },

  // ── CAST MANGANESE ───────────────────────────────────────────────────────
  { id:"EC-CMR", part_number:"CMR Series", chain_number:"CMR", category:"engineered_class", subcategory:"cast_manganese",
    product_type:"Cast Manganese / Alloy Steel Rivetless Chain",
    description:"Cast manganese and alloy steel rivetless chains for extreme abrasion and impact resistance. Bucket elevators and heavy drag conveyors.",
    image:IMG.cast_mang, industries:["Grain Elevators","Mining","Aggregate","Cement","Bulk Material"],
    features:["Cast manganese steel for abrasion resistance","Alloy steel options","Rivetless design","High impact resistance"],
    specs:{ notes:"Contact Uniking for full spec sheet." },
    related_pins:[{code:"CMR CL",name:"CMR Connecting Pin",description:""}], related_sprockets:[{code:"CMR Sprocket",name:"CMR Compatible Sprocket",bore:"To suit"}], related_attachments:[],
    options:["Manganese steel","Alloy steel"],
    source:"Allied-Locke", source_url:SRC.cast,
    notes:"Full cast manganese range available. Contact Uniking." },

  // ── AGRICULTURAL ROLLER ──────────────────────────────────────────────────
  { id:"AG-CA550", part_number:"CA550", chain_number:"CA550", category:"agricultural", subcategory:"ag_roller",
    product_type:"Agricultural Roller Chain",
    description:"CA550 agricultural roller chain. Hardened steel parts, tight tolerances. Standard for farm and conveying equipment.",
    image:IMG.ag_roller, industries:["Agriculture","Combines","Forage Harvesters","Farm Equipment"],
    features:["Hardened steel parts","Close manufacturing tolerances","Long service life","Standard agricultural chain"],
    specs:{ pitch_in:"1.630", notes:"Contact Uniking for full spec." },
    related_pins:[cl("CA550")], related_sprockets:[{code:"CA550 Sprocket",name:"CA550 Sprocket",bore:"To suit"}], related_attachments:[att("CA550","A1")],
    options:["With slats","With flights"], source:"Allied-Locke", source_url:SRC.ag_roller },

  { id:"AG-CA550R", part_number:"CA550R", chain_number:"CA550R", category:"agricultural", subcategory:"ag_roller",
    product_type:"Agricultural Roller Chain",
    description:"CA550R agricultural roller chain with roller. Hardened steel parts, close tolerances. For combines, forage harvesters, and farm equipment.",
    image:IMG.ag_roller, industries:["Agriculture","Combines","Forage Harvesters"],
    features:["With roller","Hardened steel parts","Close tolerances"],
    specs:{ pitch_in:"1.630", notes:"Roller version of CA550." },
    related_pins:[cl("CA550R")], related_sprockets:[{code:"CA550R Sprocket",name:"CA550R Sprocket",bore:"To suit"}], related_attachments:[att("CA550R","A1")],
    options:["With slats","With flights"],
    source:"Allied-Locke", source_url:SRC.ag_roller,
    notes:"Full agricultural roller range: CA550, CA550R, CA557, CA620, CA2060, etc. Contact Uniking." },

  // ── AG DETACHABLE ────────────────────────────────────────────────────────
  { id:"AG-DETACH55", part_number:"55", chain_number:"No. 55 Detachable", category:"agricultural", subcategory:"ag_detachable",
    product_type:"Steel Detachable Chain",
    description:"No. 55 steel detachable chain. Hot-rolled strip steel, heat-treated. Easy to install and repair — detaches without tools.",
    image:IMG.ag_detach, industries:["Agriculture","Grain Handling","Light Industrial Conveying"],
    features:["Hot-rolled strip steel","Heat-treated for strength and wear","Tool-free installation and repair","Moderate loads and speeds"],
    specs:{ notes:"Contact Uniking for pitch and load specs." },
    related_pins:[cl("55")], related_sprockets:[{code:"55 Sprocket",name:"No. 55 Sprocket",bore:"To suit"}], related_attachments:[],
    options:[],
    source:"Allied-Locke", source_url:SRC.ag_det,
    notes:"Full detachable range: 25, 32, 32W, 41, 51, 52, 55, 57, 62, 67, 67W, 69, 72, 74, 77, 78, 88, 88W, 104. Contact Uniking." },

  // ── T-BAR & T-ROD ────────────────────────────────────────────────────────
  { id:"AG-TBAR67", part_number:"AL67-T-Bar", chain_number:"67 T-Bar", category:"agricultural", subcategory:"ag_tbar",
    product_type:"T-Bar Chain",
    description:"No. 67 T-Bar chain. Clean design prevents clogging. Easy assembly/disassembly. Longer wear life than detachable or pintle chains. Runs on standard #67 sprockets.",
    image:IMG.tbar, industries:["Agriculture","Grain Handling","Spreader Equipment"],
    features:["T-bar design — no material clogging","Easy assembly / disassembly","Longer wear life than detachable/pintle","Standard #67 sprocket compatible"],
    specs:{ notes:"Contact Uniking for pitch and load specs." },
    related_pins:[{code:"67 T-Bar CL",name:"No. 67 T-Bar Connecting Link",description:""}], related_sprockets:[{code:"67 Sprocket",name:"No. 67 Sprocket",bore:"Standard #67 sprockets compatible."}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.tbar },

  { id:"AG-TROD67", part_number:"AL67-T-Rod", chain_number:"67 T-Rod", category:"agricultural", subcategory:"ag_trod",
    product_type:"T-Rod Chain",
    description:"No. 67 T-Rod chain. Designed for spreaders. Unique design increases fatigue and wear life, reduces stretching. Smooth and quiet.",
    image:IMG.trod, industries:["Agriculture","Spreaders","Farm Equipment"],
    features:["T-rod unique design","Increased fatigue life","Reduced stretching","Smooth and quiet operation","Standard #67 sprocket compatible"],
    specs:{ notes:"Contact Uniking for pitch and load specs." },
    related_pins:[{code:"67 T-Rod CL",name:"No. 67 T-Rod Connecting Link",description:""}], related_sprockets:[{code:"67 Sprocket",name:"No. 67 Sprocket",bore:"Standard #67 sprockets compatible."}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.trod },

  // ── LEAF CHAINS ──────────────────────────────────────────────────────────
  { id:"LC-AL322", part_number:"AL322", chain_number:"AL322", category:"leaf_chain", subcategory:"al_series",
    product_type:"AL Series Leaf Chain",
    description:"AL322 leaf chain. 3/8-inch pitch, 2×2 lacing. For forklift masts, tension linkages, and balance applications. Runs over sheaves.",
    image:IMG.leaf, industries:["Forklift / Material Handling","Cranes","Tension Linkages"],
    features:["2×2 lacing","3/8-inch pitch","ANSI/ASME B29.8","Runs over sheaves"],
    specs:{ pitch_in:"0.375", lacing:"2×2", notes:"Contact Uniking for ultimate strength." },
    related_pins:[{code:"AL322 AL",name:"AL322 Anchor Link",description:""}], related_sprockets:[], related_attachments:[{code:"AL322 Anchor",name:"Anchor Link",type:"Fork / anchor attachment"}],
    options:["Anchor links"], source:"Allied-Locke", source_url:SRC.leaf },

  { id:"LC-AL422", part_number:"AL422", chain_number:"AL422", category:"leaf_chain", subcategory:"al_series",
    product_type:"AL Series Leaf Chain",
    description:"AL422 leaf chain. 1/2-inch pitch, 2×2 lacing. The most common AL leaf chain for forklifts.",
    image:IMG.leaf, industries:["Forklift / Material Handling","Cranes","Tension Linkages"],
    features:["2×2 lacing","1/2-inch pitch","ANSI/ASME B29.8","Runs over sheaves"],
    specs:{ pitch_in:"0.500", lacing:"2×2", avg_ultimate_lbs:"5,800" },
    related_pins:[{code:"AL422 AL",name:"AL422 Anchor Link",description:""}], related_sprockets:[], related_attachments:[{code:"AL422 Anchor",name:"Anchor Link — AL422",type:"Anchor / Fork attachment"}],
    options:["Anchor links"],
    source:"Allied-Locke", source_url:SRC.leaf,
    notes:"Full AL series available: AL322–AL1022. Contact Uniking." },

  { id:"LC-AL622", part_number:"AL622", chain_number:"AL622", category:"leaf_chain", subcategory:"al_series",
    product_type:"AL Series Leaf Chain",
    description:"AL622 leaf chain. 3/4-inch pitch, 2×2 lacing.",
    image:IMG.leaf, industries:["Forklift / Material Handling","Heavy Cranes"],
    features:["2×2 lacing","3/4-inch pitch","ANSI/ASME B29.8"],
    specs:{ pitch_in:"0.750", lacing:"2×2", notes:"Contact Uniking for ultimate strength." },
    related_pins:[{code:"AL622 AL",name:"AL622 Anchor Link",description:""}], related_sprockets:[], related_attachments:[{code:"AL622 Anchor",name:"Anchor Link — AL622",type:"Fork / anchor"}],
    options:["Anchor links"], source:"Allied-Locke", source_url:SRC.leaf },

  { id:"LC-BL422", part_number:"BL422", chain_number:"BL422", category:"leaf_chain", subcategory:"bl_series",
    product_type:"BL Series Leaf Chain",
    description:"BL422 leaf chain. 1/2-inch pitch, 4×2 lacing. BL series has more plate rows than AL for higher strength.",
    image:IMG.leaf, industries:["Forklift / Material Handling","Cranes","Heavy Lifting"],
    features:["4×2 lacing — higher strength than AL422","1/2-inch pitch","ANSI/ASME B29.8","Runs over sheaves"],
    specs:{ pitch_in:"0.500", lacing:"4×2", notes:"Contact Uniking for ultimate strength." },
    related_pins:[{code:"BL422 CL",name:"BL422 Connecting Link",description:""}], related_sprockets:[], related_attachments:[{code:"BL422 Anchor",name:"Anchor Link — BL422",type:"Fork / anchor"}],
    options:["Anchor links"], source:"Allied-Locke", source_url:SRC.leaf },

  { id:"LC-BL444", part_number:"BL444", chain_number:"BL444", category:"leaf_chain", subcategory:"bl_series",
    product_type:"BL Series Leaf Chain",
    description:"BL444 heavy leaf chain. 1/2-inch pitch, 4×4 lacing. For high-capacity forklift masts and heavy lifting.",
    image:IMG.leaf, industries:["Forklift / Material Handling","Heavy Cranes","Lifting Equipment"],
    features:["4×4 lacing — very high tensile strength","1/2-inch pitch","ANSI/ASME B29.8","Runs over sheaves"],
    specs:{ pitch_in:"0.500", lacing:"4×4", avg_ultimate_lbs:"13,100" },
    related_pins:[{code:"BL444 CL",name:"BL444 Connecting Link",description:""}], related_sprockets:[], related_attachments:[{code:"BL444 Anchor",name:"Anchor Link — BL444",type:"Anchor / Fork attachment"}],
    options:["Anchor links"],
    source:"Allied-Locke", source_url:SRC.leaf,
    notes:"Full BL series available: BL422–BL1244. Contact Uniking." },

  { id:"LC-BL634", part_number:"BL634", chain_number:"BL634", category:"leaf_chain", subcategory:"bl_series",
    product_type:"BL Series Leaf Chain",
    description:"BL634 leaf chain. 3/4-inch pitch, 6×3 lacing. High-capacity forklift and heavy lifting.",
    image:IMG.leaf, industries:["Heavy Forklift","Cranes"],
    features:["6×3 lacing","3/4-inch pitch","High load capacity"],
    specs:{ pitch_in:"0.750", lacing:"6×3", notes:"Contact Uniking for ultimate strength." },
    related_pins:[{code:"BL634 CL",name:"BL634 Connecting Link",description:""}], related_sprockets:[], related_attachments:[],
    options:["Anchor links"], source:"Allied-Locke", source_url:SRC.leaf },

  // ── SILENT / INVERTED TOOTH ──────────────────────────────────────────────
  { id:"SC-EXCEL", part_number:"SC40A-1", chain_number:"Excel Series", category:"silent_chain", subcategory:"excel_series",
    product_type:"Silent Chain — Excel Series (Outer Guide)",
    description:"Excel series inverted tooth chain. Outer sidebars as guides. Type A (higher load/speed). High tensile strength, excellent fatigue resistance, low noise, long wear life.",
    image:IMG.silent, industries:["Automotive","Machinery","High-Speed Drives","Timing Applications"],
    features:["Outer sidebar guide — Excel series","Type A link profile — higher load and speed","High tensile strength","Excellent fatigue resistance","Low noise operation","Long wear life"],
    specs:{ notes:"Width and part numbers vary. Contact Uniking for specific Excel part numbers and dimensions." },
    related_pins:[{code:"Excel CL",name:"Excel Series Connecting Link",description:""}], related_sprockets:[{code:"Excel Sprocket",name:"Excel Series Inverted Tooth Sprocket",bore:"To suit"}], related_attachments:[],
    options:["Type A","Type B","Custom widths","All pitches and widths available"],
    source:"Allied-Locke", source_url:SRC.silent,
    notes:"Contact Uniking for specific Excel part numbers, pitches, and widths." },

  { id:"SC-SILENT", part_number:"SC Series", chain_number:"Silent SC", category:"silent_chain", subcategory:"silent_series",
    product_type:"Silent Chain — Silent Series (Center Guide)",
    description:"Silent series inverted tooth chain. Center-most sidebar as guide. High-speed, high-load, low-noise power transmission.",
    image:IMG.silent, industries:["Automotive","Machinery","Precision Drives","Timing Drives"],
    features:["Center guide sidebar (most sizes)","High tensile strength","Excellent fatigue resistance","Low noise","Long wear life"],
    specs:{ notes:"Contact Uniking for specific Silent series part numbers." },
    related_pins:[{code:"SC Series CL",name:"SC Series Connecting Link",description:""}], related_sprockets:[{code:"SC Sprocket",name:"Silent Series Inverted Tooth Sprocket",bore:"To suit"}], related_attachments:[],
    options:["Multiple widths","Various pitches"],
    source:"Allied-Locke", source_url:SRC.silent,
    notes:"Contact Uniking for specific Silent series part numbers and dimensions." },

  // ── ATTACHMENTS ──────────────────────────────────────────────────────────
  { id:"ATT-A1", part_number:"A1 Attachment", chain_number:"A1", category:"attachments", subcategory:"roller_attachments",
    product_type:"Roller Chain Attachment — A1",
    description:"A1 standard attachment. One bent extended tab on one side. For conveying, pushing, pulling, and carrying loads. All standard ANSI sizes available.",
    image:IMG.attachments, industries:["Conveying","Packaging","Assembly Lines","Agriculture"],
    features:["One bent tab — one side","Standard ANSI compatible","All pitch sizes available"],
    specs:{ notes:"Available for sizes 25 through 240 and double-pitch chains." },
    related_pins:[], related_sprockets:[], related_attachments:[],
    options:["Available for all ANSI pitch sizes (25–240)","Double-pitch versions available"],
    source:"Allied-Locke", source_url:SRC.attach },

  { id:"ATT-A2", part_number:"A2 Attachment", chain_number:"A2", category:"attachments", subcategory:"roller_attachments",
    product_type:"Roller Chain Attachment — A2",
    description:"A2 standard attachment. Two bent extended tabs, one on each side. Symmetrical design for balanced load carrying.",
    image:IMG.attachments, industries:["Conveying","Packaging","Assembly Lines"],
    features:["Two bent tabs — both sides","Symmetrical design","Standard ANSI compatible"],
    specs:{ notes:"Available for all standard ANSI pitch sizes." },
    related_pins:[], related_sprockets:[], related_attachments:[],
    options:["All ANSI pitch sizes available"], source:"Allied-Locke", source_url:SRC.attach },

  { id:"ATT-K1", part_number:"K1 Attachment", chain_number:"K1", category:"attachments", subcategory:"roller_attachments",
    product_type:"Roller Chain Attachment — K1",
    description:"K1 extended pin attachment. One extended pin protruding from one side. Used for connecting flights, guides, and special components.",
    image:IMG.attachments, industries:["Conveying","Special Applications","Flight Chains"],
    features:["One extended pin — one side","For flight and guide attachment","Standard ANSI compatible"],
    specs:{ notes:"Available for all standard ANSI sizes." },
    related_pins:[], related_sprockets:[], related_attachments:[],
    options:["K2 available (both sides)"], source:"Allied-Locke", source_url:SRC.attach },

  { id:"ATT-K2", part_number:"K2 Attachment", chain_number:"K2", category:"attachments", subcategory:"roller_attachments",
    product_type:"Roller Chain Attachment — K2",
    description:"K2 extended pin attachment. Extended pins on both sides. For cross-rod and flight-bar conveyor systems.",
    image:IMG.attachments, industries:["Cross-Rod Conveyors","Flight Chains","Special Applications"],
    features:["Extended pins both sides","Cross-rod conveyor compatible"],
    specs:{ notes:"Available for all standard ANSI sizes." },
    related_pins:[], related_sprockets:[], related_attachments:[],
    options:["K1 (one side) also available"], source:"Allied-Locke", source_url:SRC.attach },

  { id:"ATT-WH-A1", part_number:"WH A1 Attachment", chain_number:"WH-A1", category:"attachments", subcategory:"weld_attachments",
    product_type:"Welded Steel Chain Attachment — A1",
    description:"A1 attachment for WH series welded steel mill chains. Welded extended tabs for conveying bulk material.",
    image:IMG.wh_attach, industries:["Mining","Grain Handling","Bulk Material"],
    features:["Welded construction","Compatible with WH series","Bulk material handling"],
    specs:{ notes:"Available for WH78, WH124, WH132, WH150, WH155 and other WH sizes." },
    related_pins:[], related_sprockets:[], related_attachments:[],
    options:["Various WH sizes"], source:"Allied-Locke", source_url:SRC.wh_attach },
];