/**
 * chainDataRoller.js
 * ANSI Standard, Multi-Strand, Heavy Series, Solid Bushing, Super Series,
 * British Standard, Double Pitch, Double Capacity, XDO, Stainless,
 * Nickel Plated, Armor Coat, Self-Lube, SLB chains.
 * All specs verified from Allied-Locke live catalog.
 */
import { IMG, SRC, cl, ol, spr, att } from "@/lib/chainCatalogImages.js";

export const ROLLER_CHAIN_PRODUCTS = [

  // ── ANSI STANDARD SINGLE STRAND ──────────────────────────────────────────
  { id:"RC-25", part_number:"25", chain_number:"25", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1/4-inch pitch ANSI single-strand roller chain. Lightest standard size for light-duty drives and instrumentation.",
    image:IMG.ansi_single, industries:["Light Machinery","Instrumentation","Agricultural","Small Drives"],
    features:["ANSI B29.1 compliant","Riveted construction","Carbon steel","Smallest standard ANSI pitch"],
    specs:{ pitch_in:"0.250", roller_width_in:"0.125", roller_dia_in:"0.130", riv_end_to_cl_in:"0.153", conn_end_to_cl_in:"0.189", plate_height_in:"0.228", plate_thick_in:"0.029", pin_dia_in:"0.091", avg_ultimate_lbs:"930" },
    related_pins:[cl("25")], related_sprockets:[spr("25")], related_attachments:[],
    options:["Pre-greased"], source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-35", part_number:"35", chain_number:"35", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"3/8-inch pitch ANSI roller chain. Common in light machinery, agricultural, and small conveyor drives.",
    image:IMG.ansi_single, industries:["Agricultural","Light Machinery","Food Processing","Small Conveyors"],
    features:["ANSI B29.1 compliant","Riveted construction","Carbon steel"],
    specs:{ pitch_in:"0.375", roller_width_in:"0.188", roller_dia_in:"0.200", riv_end_to_cl_in:"0.228", conn_end_to_cl_in:"0.276", plate_height_in:"0.356", plate_thick_in:"0.050", pin_dia_in:"0.141", avg_ultimate_lbs:"2,320" },
    related_pins:[cl("35")], related_sprockets:[spr("35")], related_attachments:[],
    options:["Pre-greased","Multi-strand (35-2, 35-3)"], source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-40", part_number:"40", chain_number:"40", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1/2-inch pitch ANSI roller chain — the world's most widely used chain size. Single, double, triple, and quad strand available.",
    image:IMG.ansi_single, industries:["General Industrial","Agricultural","Packaging","Food Processing","Mining","Oil & Gas"],
    features:["ANSI B29.1 compliant","Riveted construction (all sizes)","Cottered (size 60+)","Most widely stocked size globally"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.368", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"3,970" },
    related_pins:[cl("40"),ol("40")], related_sprockets:[spr("40")],
    related_attachments:[att("40","A1"),att("40","A2"),att("40","K1"),att("40","K2")],
    options:["Pre-greased","Nickel plated (40NP)","Stainless (40SS)","Self-lube (40SL)","Super series (40S)","Multi-strand (40-2, 40-3, 40-4)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-41", part_number:"41", chain_number:"41", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1/2-inch pitch narrow-series ANSI roller chain. Narrower roller width (0.250 in) than No. 40. Lightweight alternative.",
    image:IMG.ansi_single, industries:["Light Machinery","Office Equipment","Small Drives"],
    features:["ANSI B29.1 compliant","Narrow roller (0.250 in)","Lighter than No. 40"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.250", roller_dia_in:"0.306", riv_end_to_cl_in:"0.261", conn_end_to_cl_in:"0.314", plate_height_in:"0.390", plate_thick_in:"0.050", pin_dia_in:"0.141", avg_ultimate_lbs:"2,760" },
    related_pins:[cl("41")], related_sprockets:[spr("41")], related_attachments:[],
    options:["Pre-greased"], source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-50", part_number:"50", chain_number:"50", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"5/8-inch pitch ANSI roller chain. Heavy-duty drives, conveyors, and industrial machinery.",
    image:IMG.ansi_single, industries:["General Industrial","Mining","Paper & Forest Products","Conveyors"],
    features:["ANSI B29.1 compliant","Riveted and cottered construction","Carbon steel"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.397", conn_end_to_cl_in:"0.455", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"6,620" },
    related_pins:[cl("50"),ol("50")], related_sprockets:[spr("50")],
    related_attachments:[att("50","A1"),att("50","A2"),att("50","K1")],
    options:["Pre-greased","Cottered","Multi-strand (50-2, 50-3, 50-4)","Super series (50S, 50SHD)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-60", part_number:"60", chain_number:"60", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"3/4-inch pitch ANSI roller chain. One of the most common sizes for medium-heavy industrial drives. Cottered construction standard at size 60+.",
    image:IMG.ansi_single, industries:["General Industrial","Packaging","Automotive","Construction Equipment","Agriculture"],
    features:["ANSI B29.1 compliant","Riveted and cottered","Wide range of attachments"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.497", conn_end_to_cl_in:"0.551", plate_height_in:"0.712", plate_thick_in:"0.093", pin_dia_in:"0.234", avg_ultimate_lbs:"9,270" },
    related_pins:[cl("60"),ol("60")], related_sprockets:[spr("60")],
    related_attachments:[att("60","A1"),att("60","A2"),att("60","K1"),att("60","K2")],
    options:["Cottered","Pre-greased","Multi-strand (60-2, 60-3, 60-4)","Super series (60S, 60SHD)","Solid bushing (60 SOLID)","Stainless (60SS)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-80", part_number:"80", chain_number:"80", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1-inch pitch ANSI roller chain. Standard heavy-duty industrial drive chain.",
    image:IMG.ansi_single, industries:["General Industrial","Steel & Mining","Paper Mills","Oil & Gas"],
    features:["ANSI B29.1 compliant","Riveted and cottered","High tensile strength"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"0.645", conn_end_to_cl_in:"0.724", plate_height_in:"0.950", plate_thick_in:"0.125", pin_dia_in:"0.312", avg_ultimate_lbs:"16,540" },
    related_pins:[cl("80"),ol("80")], related_sprockets:[spr("80")],
    related_attachments:[att("80","A1"),att("80","A2"),att("80","K1"),att("80","K2")],
    options:["Cottered","Pre-greased","Multi-strand (80-2, 80-3, 80-4)","Super series (80S, 80SHD)","Solid bushing (80 SOLID)","Stainless (80SS)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-100", part_number:"100", chain_number:"100", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1-1/4 inch pitch ANSI roller chain. Heavy drives and industrial applications.",
    image:IMG.ansi_single, industries:["Steel","Mining","Cement","Paper"],
    features:["ANSI B29.1 compliant","Cottered and riveted"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.750", roller_dia_in:"0.750", riv_end_to_cl_in:"0.789", conn_end_to_cl_in:"0.941", plate_height_in:"1.188", plate_thick_in:"0.157", pin_dia_in:"0.375", avg_ultimate_lbs:"25,360" },
    related_pins:[cl("100"),ol("100")], related_sprockets:[spr("100")],
    related_attachments:[att("100","A1"),att("100","A2"),att("100","K1")],
    options:["Cottered","Pre-greased","Multi-strand (100-2, 100-3, 100-4)","Super series (100S, 100SHD)","Solid bushing (100 SOLID)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-120", part_number:"120", chain_number:"120", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1-1/2 inch pitch ANSI roller chain. Extra heavy industrial power transmission.",
    image:IMG.ansi_single, industries:["Steel","Mining","Heavy Industry"],
    features:["ANSI B29.1 compliant","Cottered and riveted"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"0.875", riv_end_to_cl_in:"0.983", conn_end_to_cl_in:"1.219", plate_height_in:"1.425", plate_thick_in:"0.189", pin_dia_in:"0.437", avg_ultimate_lbs:"32,640" },
    related_pins:[cl("120"),ol("120")], related_sprockets:[spr("120")], related_attachments:[],
    options:["Cottered","Pre-greased","Multi-strand (120-2, 120-3, 120-4)","Super series (120S, 120SHD)","Solid bushing (120 SOLID)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-140", part_number:"140", chain_number:"140", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"1-3/4 inch pitch ANSI roller chain. Heavy industrial applications.",
    image:IMG.ansi_single, industries:["Heavy Industry","Mining","Steel Mills"],
    features:["ANSI B29.1 compliant","Cottered construction"],
    specs:{ pitch_in:"1.750", roller_width_in:"1.000", roller_dia_in:"1.000", riv_end_to_cl_in:"1.066", conn_end_to_cl_in:"1.259", plate_height_in:"1.663", plate_thick_in:"0.219", pin_dia_in:"0.500", avg_ultimate_lbs:"45,210" },
    related_pins:[cl("140"),ol("140")], related_sprockets:[spr("140")], related_attachments:[],
    options:["Cottered","Pre-greased","Multi-strand (140-2, 140-3)","Super series (140S, 140SHD)","Solid bushing (140 SOLID)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-160", part_number:"160", chain_number:"160", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"2-inch pitch ANSI roller chain. Very heavy industrial power transmission.",
    image:IMG.ansi_single, industries:["Heavy Industry","Mining","Steel Mills"],
    features:["ANSI B29.1 compliant","High load capacity"],
    specs:{ pitch_in:"2.000", roller_width_in:"1.250", roller_dia_in:"1.125", riv_end_to_cl_in:"1.282", conn_end_to_cl_in:"1.469", plate_height_in:"1.901", plate_thick_in:"0.255", pin_dia_in:"0.563", avg_ultimate_lbs:"57,780" },
    related_pins:[cl("160"),ol("160")], related_sprockets:[spr("160")], related_attachments:[],
    options:["Cottered","Pre-greased","Multi-strand (160-2, 160-3)","Super series (160S, 160SHD)","Solid bushing (160 SOLID)"],
    source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-180", part_number:"180", chain_number:"180", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"2-1/4 inch pitch ANSI roller chain. Large pitch for very heavy industrial applications.",
    image:IMG.ansi_single, industries:["Heavy Industry","Mining"],
    features:["ANSI B29.1 compliant"],
    specs:{ pitch_in:"2.250", roller_width_in:"1.406", roller_dia_in:"1.406", riv_end_to_cl_in:"1.404", conn_end_to_cl_in:"1.675", plate_height_in:"2.130", plate_thick_in:"0.283", pin_dia_in:"0.687", avg_ultimate_lbs:"80,480" },
    related_pins:[cl("180"),ol("180")], related_sprockets:[spr("180")], related_attachments:[],
    options:["Cottered","Super series (180S, 180SHD)"], source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-200", part_number:"200", chain_number:"200", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"2-1/2 inch pitch ANSI roller chain. Extreme heavy industrial applications.",
    image:IMG.ansi_single, industries:["Heavy Industry","Mining","Steel"],
    features:["ANSI B29.1 compliant"],
    specs:{ pitch_in:"2.500", roller_width_in:"1.500", roller_dia_in:"1.562", riv_end_to_cl_in:"1.580", conn_end_to_cl_in:"1.764", plate_height_in:"2.376", plate_thick_in:"0.312", pin_dia_in:"0.782", avg_ultimate_lbs:"109,150" },
    related_pins:[cl("200"),ol("200")], related_sprockets:[spr("200")], related_attachments:[],
    options:["Cottered","Super series (200S, 200SHD)"], source:"Allied-Locke", source_url:SRC.ansi },

  { id:"RC-240", part_number:"240", chain_number:"240", category:"performance_roller", subcategory:"ansi_standard",
    product_type:"ANSI Standard Roller Chain",
    description:"3-inch pitch ANSI roller chain. The largest standard ANSI pitch. Maximum load, slow-speed applications.",
    image:IMG.ansi_single, industries:["Very Heavy Industry","Mining"],
    features:["ANSI B29.1 compliant","Largest standard ANSI pitch"],
    specs:{ pitch_in:"3.000", roller_width_in:"1.875", roller_dia_in:"1.875", riv_end_to_cl_in:"1.886", conn_end_to_cl_in:"2.184", plate_height_in:"2.850", plate_thick_in:"0.375", pin_dia_in:"0.937", avg_ultimate_lbs:"152,140" },
    related_pins:[cl("240"),ol("240")], related_sprockets:[spr("240")], related_attachments:[],
    options:["Cottered","Super series (240S)"], source:"Allied-Locke", source_url:SRC.ansi },

  // ── ANSI MULTIPLE STRAND ─────────────────────────────────────────────────
  { id:"RC-35-2", part_number:"35-2", chain_number:"35-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"3/8-inch pitch double-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Agricultural","Light Conveyors"],
    features:["Double strand","ANSI B29.1 compliant","Riveted construction"],
    specs:{ pitch_in:"0.375", roller_width_in:"0.188", roller_dia_in:"0.200", riv_end_to_cl_in:"0.438", conn_end_to_cl_in:"0.468", plate_height_in:"0.356", plate_thick_in:"0.050", pin_dia_in:"0.141", avg_ultimate_lbs:"4,640" },
    related_pins:[{code:"35-2 CL",name:"No. 35-2 Connecting Link",description:""}], related_sprockets:[spr("35")], related_attachments:[],
    options:["Triple strand (35-3)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-35-3", part_number:"35-3", chain_number:"35-3", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Triple Strand Roller Chain",
    description:"3/8-inch pitch triple-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Agricultural"],
    features:["Triple strand","ANSI B29.1 compliant"],
    specs:{ pitch_in:"0.375", roller_width_in:"0.188", roller_dia_in:"0.200", riv_end_to_cl_in:"0.631", conn_end_to_cl_in:"0.675", plate_height_in:"0.356", plate_thick_in:"0.050", pin_dia_in:"0.141", avg_ultimate_lbs:"6,950" },
    related_pins:[{code:"35-3 CL",name:"No. 35-3 Connecting Link",description:""}], related_sprockets:[spr("35")], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-40-2", part_number:"40-2", chain_number:"40-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"1/2-inch pitch double-strand ANSI roller chain. Doubles the load capacity of single-strand No. 40.",
    image:IMG.ansi_multi, industries:["General Industrial","Packaging","Agricultural","Mining"],
    features:["Double strand — 2× load capacity","ANSI B29.1 compliant","Riveted construction"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.606", conn_end_to_cl_in:"0.661", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"7,500" },
    related_pins:[{code:"40-2 CL",name:"No. 40-2 Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["Triple strand (40-3)","Quad strand (40-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-40-3", part_number:"40-3", chain_number:"40-3", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Triple Strand Roller Chain",
    description:"1/2-inch pitch triple-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Heavy Packaging"],
    features:["Triple strand","ANSI B29.1 compliant"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.888", conn_end_to_cl_in:"0.947", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"11,250" },
    related_pins:[{code:"40-3 CL",name:"No. 40-3 Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["Quad strand (40-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-40-4", part_number:"40-4", chain_number:"40-4", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Quad Strand Roller Chain",
    description:"1/2-inch pitch quad-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["Heavy Industrial"],
    features:["Quad strand","ANSI B29.1 compliant"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"1.171", conn_end_to_cl_in:"1.242", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"15,000" },
    related_pins:[{code:"40-4 CL",name:"No. 40-4 Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-50-2", part_number:"50-2", chain_number:"50-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"5/8-inch pitch double-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Mining","Conveyors"],
    features:["Double strand","5/8-inch pitch"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.752", conn_end_to_cl_in:"0.807", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"13,230" },
    related_pins:[{code:"50-2 CL",name:"No. 50-2 Connecting Link",description:""}], related_sprockets:[spr("50")], related_attachments:[],
    options:["Triple strand (50-3)","Quad strand (50-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-50-3", part_number:"50-3", chain_number:"50-3", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Triple Strand Roller Chain",
    description:"5/8-inch pitch triple-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Mining"],
    features:["Triple strand","5/8-inch pitch"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"1.111", conn_end_to_cl_in:"1.178", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"19,850" },
    related_pins:[{code:"50-3 CL",name:"No. 50-3 Connecting Link",description:""}], related_sprockets:[spr("50")], related_attachments:[],
    options:["Quad strand (50-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-60-2", part_number:"60-2", chain_number:"60-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"3/4-inch pitch double-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Conveying","Mining"],
    features:["Double strand","3/4-inch pitch","ANSI B29.1 compliant"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.945", conn_end_to_cl_in:"1.000", plate_height_in:"0.712", plate_thick_in:"0.093", pin_dia_in:"0.234", avg_ultimate_lbs:"18,530" },
    related_pins:[{code:"60-2 CL",name:"No. 60-2 Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["Triple strand (60-3)","Quad strand (60-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-60-3", part_number:"60-3", chain_number:"60-3", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Triple Strand Roller Chain",
    description:"3/4-inch pitch triple-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["General Industrial","Heavy Industrial"],
    features:["Triple strand","3/4-inch pitch"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"1.397", conn_end_to_cl_in:"1.452", plate_height_in:"0.712", plate_thick_in:"0.093", pin_dia_in:"0.234", avg_ultimate_lbs:"27,790" },
    related_pins:[{code:"60-3 CL",name:"No. 60-3 Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["Quad strand (60-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-80-2", part_number:"80-2", chain_number:"80-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"1-inch pitch double-strand ANSI roller chain. For heavy industrial parallel drives.",
    image:IMG.ansi_multi, industries:["Heavy Industrial","Mining","Steel","Paper"],
    features:["Double strand","1-inch pitch","High tensile strength"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"1.220", conn_end_to_cl_in:"1.303", plate_height_in:"0.950", plate_thick_in:"0.125", pin_dia_in:"0.312", avg_ultimate_lbs:"33,080" },
    related_pins:[{code:"80-2 CL",name:"No. 80-2 Connecting Link",description:""}], related_sprockets:[spr("80")], related_attachments:[],
    options:["Triple strand (80-3)","Quad strand (80-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-80-3", part_number:"80-3", chain_number:"80-3", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Triple Strand Roller Chain",
    description:"1-inch pitch triple-strand ANSI roller chain.",
    image:IMG.ansi_multi, industries:["Heavy Industrial","Mining","Steel"],
    features:["Triple strand","1-inch pitch"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"1.791", conn_end_to_cl_in:"1.882", plate_height_in:"0.950", plate_thick_in:"0.125", pin_dia_in:"0.312", avg_ultimate_lbs:"49,620" },
    related_pins:[{code:"80-3 CL",name:"No. 80-3 Connecting Link",description:""}], related_sprockets:[spr("80")], related_attachments:[],
    options:["Quad strand (80-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-100-2", part_number:"100-2", chain_number:"100-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"1-1/4 inch pitch double-strand roller chain.",
    image:IMG.ansi_multi, industries:["Steel","Mining","Cement","Paper"],
    features:["Double strand","High load capacity"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.750", roller_dia_in:"0.750", riv_end_to_cl_in:"1.493", conn_end_to_cl_in:"1.662", plate_height_in:"1.188", plate_thick_in:"0.157", pin_dia_in:"0.375", avg_ultimate_lbs:"50,720" },
    related_pins:[{code:"100-2 CL",name:"No. 100-2 Connecting Link",description:""}], related_sprockets:[spr("100")], related_attachments:[],
    options:["Triple strand (100-3)","Quad strand (100-4)"], source:"Allied-Locke", source_url:SRC.multi },

  { id:"RC-120-2", part_number:"120-2", chain_number:"120-2", category:"performance_roller", subcategory:"ansi_multi",
    product_type:"ANSI Double Strand Roller Chain",
    description:"1-1/2 inch pitch double-strand roller chain.",
    image:IMG.ansi_multi, industries:["Heavy Industrial","Mining"],
    features:["Double strand","1-1/2 inch pitch"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"0.875", riv_end_to_cl_in:"1.888", conn_end_to_cl_in:"2.060", plate_height_in:"1.425", plate_thick_in:"0.189", pin_dia_in:"0.437", avg_ultimate_lbs:"65,270" },
    related_pins:[{code:"120-2 CL",name:"No. 120-2 Connecting Link",description:""}], related_sprockets:[spr("120")], related_attachments:[],
    options:["Triple strand (120-3)","Quad strand (120-4)"], source:"Allied-Locke", source_url:SRC.multi },

  // ── ANSI HEAVY SERIES ────────────────────────────────────────────────────
  { id:"RC-50H", part_number:"50H", chain_number:"50H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"5/8-inch pitch heavy-series (H) ANSI roller chain. Thicker side plates for higher loads vs. standard No. 50.",
    image:IMG.ansi_heavy, industries:["General Industrial","Mining","Construction"],
    features:["ANSI B29.1 heavy series","Thicker side plates","Higher fatigue strength"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.432", conn_end_to_cl_in:"0.487", plate_height_in:"0.594", plate_thick_in:"0.093", pin_dia_in:"0.200", avg_ultimate_lbs:"7,940" },
    related_pins:[{code:"50H CL",name:"No. 50H Connecting Link",description:""}], related_sprockets:[spr("50")], related_attachments:[],
    options:["Cottered","Double strand (50H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-60H", part_number:"60H", chain_number:"60H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"3/4-inch pitch heavy-series (H) ANSI roller chain. Thicker side plates for higher loads.",
    image:IMG.ansi_heavy, industries:["General Industrial","Mining","Construction Equipment"],
    features:["Thicker side plates","Higher load capacity than standard","ANSI heavy series"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.570", conn_end_to_cl_in:"0.625", plate_height_in:"0.712", plate_thick_in:"0.125", pin_dia_in:"0.234", avg_ultimate_lbs:"12,130" },
    related_pins:[{code:"60H CL",name:"No. 60H Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["Cottered","Double strand (60H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-80H", part_number:"80H", chain_number:"80H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"1-inch pitch heavy-series (H) ANSI roller chain.",
    image:IMG.ansi_heavy, industries:["Heavy Industrial","Mining","Steel"],
    features:["Thicker side plates","Higher fatigue strength"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"0.720", conn_end_to_cl_in:"0.783", plate_height_in:"0.950", plate_thick_in:"0.157", pin_dia_in:"0.312", avg_ultimate_lbs:"19,850" },
    related_pins:[{code:"80H CL",name:"No. 80H Connecting Link",description:""}], related_sprockets:[spr("80")], related_attachments:[],
    options:["Cottered","Double strand (80H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-100H", part_number:"100H", chain_number:"100H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"1-1/4 inch pitch heavy-series ANSI roller chain.",
    image:IMG.ansi_heavy, industries:["Heavy Industrial","Mining","Steel","Cement"],
    features:["Thicker side plates","Higher load than standard 100"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.750", roller_dia_in:"0.750", riv_end_to_cl_in:"0.845", conn_end_to_cl_in:"1.002", plate_height_in:"1.188", plate_thick_in:"0.189", pin_dia_in:"0.375", avg_ultimate_lbs:"30,870" },
    related_pins:[{code:"100H CL",name:"No. 100H Connecting Link",description:""}], related_sprockets:[spr("100")], related_attachments:[],
    options:["Cottered","Double strand (100H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-120H", part_number:"120H", chain_number:"120H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"1-1/2 inch pitch heavy-series ANSI roller chain.",
    image:IMG.ansi_heavy, industries:["Heavy Industrial","Mining","Steel"],
    features:["Thicker side plates","Enhanced wear resistance"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"0.875", riv_end_to_cl_in:"1.070", conn_end_to_cl_in:"1.259", plate_height_in:"1.425", plate_thick_in:"0.219", pin_dia_in:"0.437", avg_ultimate_lbs:"36,390" },
    related_pins:[{code:"120H CL",name:"No. 120H Connecting Link",description:""}], related_sprockets:[spr("120")], related_attachments:[],
    options:["Cottered","Double strand (120H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-140H", part_number:"140H", chain_number:"140H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"1-3/4 inch pitch heavy-series ANSI roller chain.",
    image:IMG.ansi_heavy, industries:["Heavy Industrial","Mining"],
    features:["Thicker side plates"],
    specs:{ pitch_in:"1.750", roller_width_in:"1.000", roller_dia_in:"1.000", riv_end_to_cl_in:"1.138", conn_end_to_cl_in:"1.303", plate_height_in:"1.663", plate_thick_in:"0.250", pin_dia_in:"0.500", avg_ultimate_lbs:"48,510" },
    related_pins:[{code:"140H CL",name:"No. 140H Connecting Link",description:""}], related_sprockets:[spr("140")], related_attachments:[],
    options:["Cottered","Double strand (140H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-160H", part_number:"160H", chain_number:"160H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"2-inch pitch heavy-series ANSI roller chain.",
    image:IMG.ansi_heavy, industries:["Heavy Industrial","Mining","Steel"],
    features:["Thicker side plates"],
    specs:{ pitch_in:"2.000", roller_width_in:"1.250", roller_dia_in:"1.125", riv_end_to_cl_in:"1.337", conn_end_to_cl_in:"1.514", plate_height_in:"1.901", plate_thick_in:"0.281", pin_dia_in:"0.563", avg_ultimate_lbs:"60,630" },
    related_pins:[{code:"160H CL",name:"No. 160H Connecting Link",description:""}], related_sprockets:[spr("160")], related_attachments:[],
    options:["Cottered","Double strand (160H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  { id:"RC-200H", part_number:"200H", chain_number:"200H", category:"performance_roller", subcategory:"ansi_heavy",
    product_type:"ANSI Heavy Series Roller Chain",
    description:"2-1/2 inch pitch heavy-series ANSI roller chain. Maximum load capacity.",
    image:IMG.ansi_heavy, industries:["Very Heavy Industry","Mining"],
    features:["Thicker side plates","Maximum load capacity"],
    specs:{ pitch_in:"2.500", roller_width_in:"1.500", roller_dia_in:"1.562", riv_end_to_cl_in:"1.689", conn_end_to_cl_in:"1.894", plate_height_in:"2.376", plate_thick_in:"0.375", pin_dia_in:"0.782", avg_ultimate_lbs:"103,630" },
    related_pins:[{code:"200H CL",name:"No. 200H Connecting Link",description:""}], related_sprockets:[spr("200")], related_attachments:[],
    options:["Cottered","Double strand (200H-2)"], source:"Allied-Locke", source_url:SRC.heavy },

  // ── SOLID BUSHING / SOLID ROLLER ─────────────────────────────────────────
  { id:"SB-40", part_number:"40 SOLID", chain_number:"40 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"1/2-inch pitch solid bushing/solid roller chain. One-piece bushings and rollers retain lubrication for 50%+ longer wear life vs. standard chain.",
    image:IMG.solid_bushing, industries:["Food Processing","General Industrial","Mining","Packaging"],
    features:["Solid one-piece bushings","Solid one-piece rollers","50%+ longer wear life","Better lubrication retention"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.368", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"3,970" },
    related_pins:[cl("40")], related_sprockets:[spr("40")], related_attachments:[],
    options:["Pre-greased","Double strand (40-2 SOLID)"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-50", part_number:"50 SOLID", chain_number:"50 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"5/8-inch pitch solid bushing/solid roller chain.",
    image:IMG.solid_bushing, industries:["General Industrial","Mining","Packaging"],
    features:["Solid one-piece bushings & rollers","50%+ wear life increase"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.399", conn_end_to_cl_in:"0.455", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"6,620" },
    related_pins:[cl("50")], related_sprockets:[spr("50")], related_attachments:[],
    options:["Pre-greased","Double strand (50-2 SOLID)"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-60", part_number:"60 SOLID", chain_number:"60 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"3/4-inch pitch solid bushing/solid roller chain.",
    image:IMG.solid_bushing, industries:["General Industrial","Mining","Packaging"],
    features:["Solid one-piece bushings & rollers","Superior lubrication retention"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.497", conn_end_to_cl_in:"0.551", plate_height_in:"0.712", plate_thick_in:"0.093", pin_dia_in:"0.235", avg_ultimate_lbs:"9,270" },
    related_pins:[cl("60")], related_sprockets:[spr("60")], related_attachments:[],
    options:["Pre-greased","Heavy (60H SOLID)","Double strand (60-2 SOLID)"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-80", part_number:"80 SOLID", chain_number:"80 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"1-inch pitch solid bushing/solid roller chain.",
    image:IMG.solid_bushing, industries:["Heavy Industrial","Mining"],
    features:["Solid one-piece bushings & rollers"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"0.645", conn_end_to_cl_in:"0.724", plate_height_in:"0.950", plate_thick_in:"0.125", pin_dia_in:"0.313", avg_ultimate_lbs:"16,540" },
    related_pins:[cl("80")], related_sprockets:[spr("80")], related_attachments:[],
    options:["Pre-greased","Heavy (80H SOLID)","Double strand (80-2 SOLID)"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-100", part_number:"100 SOLID", chain_number:"100 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"1-1/4 inch pitch solid bushing/solid roller chain.",
    image:IMG.solid_bushing, industries:["Heavy Industrial","Mining"],
    features:["Solid one-piece bushings & rollers"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.750", roller_dia_in:"0.750", riv_end_to_cl_in:"0.789", conn_end_to_cl_in:"0.941", plate_height_in:"1.188", plate_thick_in:"0.157", pin_dia_in:"0.375", avg_ultimate_lbs:"25,360" },
    related_pins:[cl("100")], related_sprockets:[spr("100")], related_attachments:[],
    options:["Pre-greased","Heavy (100H SOLID)"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-120", part_number:"120 SOLID", chain_number:"120 SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing / Solid Roller Chain",
    description:"1-1/2 inch pitch solid bushing/solid roller chain.",
    image:IMG.solid_bushing, industries:["Heavy Industrial","Mining"],
    features:["Solid one-piece bushings & rollers"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"0.875", riv_end_to_cl_in:"0.983", conn_end_to_cl_in:"1.219", plate_height_in:"1.425", plate_thick_in:"0.187", pin_dia_in:"0.437", avg_ultimate_lbs:"32,640" },
    related_pins:[cl("120")], related_sprockets:[spr("120")], related_attachments:[],
    options:["Pre-greased"], source:"Allied-Locke", source_url:SRC.solid },

  { id:"SB-C2060H", part_number:"C2060H SOLID", chain_number:"C2060H SOLID", category:"performance_roller", subcategory:"solid_bushing",
    product_type:"Solid Bushing Double Pitch Conveyor Chain",
    description:"1-1/2 inch double pitch heavy conveyor chain with solid bushings. Combines economy of double pitch with solid bushing wear life.",
    image:IMG.solid_bushing, industries:["Conveying","Manufacturing","Packaging"],
    features:["Solid bushings","Double pitch heavy (C2060H)","Conveyor application"],
    specs:{ pitch_in:"1.500", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.570", conn_end_to_cl_in:"0.625", plate_height_in:"0.712", plate_thick_in:"0.125", pin_dia_in:"0.234", avg_ultimate_lbs:"12,130" },
    related_pins:[{code:"C2060H CL",name:"C2060H Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["C2080H SOLID also available"], source:"Allied-Locke", source_url:SRC.solid },

  // ── SUPER SERIES ─────────────────────────────────────────────────────────
  { id:"SS-60S", part_number:"60S", chain_number:"60S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"3/4-inch pitch Super Series. Through-hardened pins, wide waist sideplates, ball-drifted holes, solid bushings. 9,700 lb avg. ultimate.",
    image:IMG.super_series, industries:["Heavy Industrial","Mining","Construction Equipment","Severe-Duty"],
    features:["Through-hardened pins","Wide waist sideplates — better fatigue resistance","Ball-drifted sideplate holes — extended life","Solid bushings — enhanced wear","Shot peened sideplates"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.501", conn_end_to_cl_in:"0.601", plate_height_in:"0.712", plate_thick_in:"0.094", pin_dia_in:"0.235", avg_ultimate_lbs:"9,700" },
    related_pins:[cl("60")], related_sprockets:[spr("60")], related_attachments:[],
    options:["SHD version: 60SHD (12,100 lb)"], source:"Allied-Locke", source_url:SRC.super_s },

  { id:"SS-80S", part_number:"80S", chain_number:"80S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"1-inch pitch Super Series. 18,500 lb avg. ultimate vs. 16,540 lb standard.",
    image:IMG.super_series, industries:["Heavy Industrial","Mining","Oil & Gas"],
    features:["Through-hardened pins","Wide waist","Ball-drifted holes","Solid bushings"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.613", roller_dia_in:"0.625", riv_end_to_cl_in:"0.650", conn_end_to_cl_in:"0.803", plate_height_in:"0.950", plate_thick_in:"0.125", pin_dia_in:"0.313", avg_ultimate_lbs:"18,500" },
    related_pins:[cl("80")], related_sprockets:[spr("80")], related_attachments:[],
    options:["SHD version: 80SHD (21,800 lb)"], source:"Allied-Locke", source_url:SRC.super_s },

  { id:"SS-100S", part_number:"100S", chain_number:"100S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"1-1/4 inch pitch Super Series. 29,300 lb avg. ultimate.",
    image:IMG.super_series, industries:["Heavy Industrial","Mining","Steel"],
    features:["Through-hardened pins","Wide waist","Ball-drifted holes","Solid bushings"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.752", roller_dia_in:"0.750", riv_end_to_cl_in:"0.781", conn_end_to_cl_in:"0.950", plate_height_in:"1.187", plate_thick_in:"0.156", pin_dia_in:"0.376", avg_ultimate_lbs:"29,300" },
    related_pins:[cl("100")], related_sprockets:[spr("100")], related_attachments:[],
    options:["SHD version: 100SHD (30,800 lb)"], source:"Allied-Locke", source_url:SRC.super_s },

  { id:"SS-120S", part_number:"120S", chain_number:"120S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"1-1/2 inch pitch Super Series. 40,500 lb avg. ultimate.",
    image:IMG.super_series, industries:["Heavy Industrial","Mining"],
    features:["Through-hardened pins","Wide waist","Ball-drifted holes","Solid bushings"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"0.875", riv_end_to_cl_in:"1.005", conn_end_to_cl_in:"1.174", plate_height_in:"1.425", plate_thick_in:"0.187", pin_dia_in:"0.437", avg_ultimate_lbs:"40,500" },
    related_pins:[cl("120")], related_sprockets:[spr("120")], related_attachments:[],
    options:["SHD version: 120SHD (42,100 lb)"], source:"Allied-Locke", source_url:SRC.super_s },

  { id:"SS-160S", part_number:"160S", chain_number:"160S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"2-inch pitch Super Series. 69,400 lb avg. ultimate.",
    image:IMG.super_series, industries:["Heavy Industrial","Mining","Steel"],
    features:["Through-hardened pins","Wide waist","Ball-drifted holes","Solid bushings"],
    specs:{ pitch_in:"2.000", roller_width_in:"1.250", roller_dia_in:"1.125", riv_end_to_cl_in:"1.290", conn_end_to_cl_in:"1.459", plate_height_in:"1.900", plate_thick_in:"0.250", pin_dia_in:"0.563", avg_ultimate_lbs:"69,400" },
    related_pins:[cl("160")], related_sprockets:[spr("160")], related_attachments:[],
    options:["SHD version: 160SHD (71,600 lb)"], source:"Allied-Locke", source_url:SRC.super_s },

  { id:"SS-200S", part_number:"200S", chain_number:"200S", category:"performance_roller", subcategory:"super_series",
    product_type:"Super Series Roller Chain",
    description:"2-1/2 inch pitch Super Series. 110,200 lb avg. ultimate.",
    image:IMG.super_series, industries:["Very Heavy Industrial","Mining"],
    features:["Through-hardened pins","Wide waist","Ball-drifted holes","Solid bushings"],
    specs:{ pitch_in:"2.500", roller_width_in:"1.500", roller_dia_in:"1.562", riv_end_to_cl_in:"1.589", conn_end_to_cl_in:"1.825", plate_height_in:"2.375", plate_thick_in:"0.312", pin_dia_in:"0.781", avg_ultimate_lbs:"110,200" },
    related_pins:[cl("200")], related_sprockets:[spr("200")], related_attachments:[],
    options:["SHD version also available"], source:"Allied-Locke", source_url:SRC.super_s },

  // ── BRITISH STANDARD ─────────────────────────────────────────────────────
  { id:"BS-04B1", part_number:"04B-1", chain_number:"04B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"0.236-inch pitch British Standard single-strand roller chain.",
    image:IMG.british, industries:["European OEM","Light Machinery"],
    features:["British Standard (BS/ISO)","Smallest BS pitch"],
    specs:{ pitch_in:"0.236", roller_width_in:"0.110", roller_dia_in:"0.157", riv_end_to_cl_in:"0.124", conn_end_to_cl_in:"0.179", plate_height_in:"0.198", plate_thick_in:"0.024", pin_dia_in:"0.072", avg_ultimate_lbs:"730" },
    related_pins:[{code:"04B-1 CL",name:"04B-1 Connecting Link",description:""}], related_sprockets:[{code:"04B Sprocket",name:"04B Sprockets",bore:"To suit"}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-06B1", part_number:"06B-1", chain_number:"06B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"3/8-inch pitch British Standard single-strand roller chain. Common in European and Asian equipment.",
    image:IMG.british, industries:["European OEM","Automotive","General Industrial"],
    features:["British Standard (BS/ISO)","3/8-inch pitch","Different dimensions from ANSI chains of same pitch"],
    specs:{ pitch_in:"0.375", roller_width_in:"0.225", roller_dia_in:"0.250", riv_end_to_cl_in:"0.253", conn_end_to_cl_in:"0.291", plate_height_in:"0.325", plate_thick_in:"0.050", pin_dia_in:"0.129", avg_ultimate_lbs:"2,250" },
    related_pins:[{code:"06B-1 CL",name:"06B-1 Connecting Link",description:""}], related_sprockets:[{code:"06B Sprocket",name:"06B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (06B-2)","Triple strand (06B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-08B1", part_number:"08B-1", chain_number:"08B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"1/2-inch pitch British Standard single-strand chain. NOT interchangeable with ANSI #40.",
    image:IMG.british, industries:["European OEM","Agricultural","General Industrial"],
    features:["British Standard (BS/ISO)","1/2-inch pitch","NOT interchangeable with ANSI #40"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.305", roller_dia_in:"0.335", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.361", plate_height_in:"0.465", plate_thick_in:"0.058", pin_dia_in:"0.175", avg_ultimate_lbs:"4,080" },
    related_pins:[{code:"08B-1 CL",name:"08B-1 Connecting Link",description:""}], related_sprockets:[{code:"08B Sprocket",name:"08B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (08B-2)","Triple strand (08B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-10B1", part_number:"10B-1", chain_number:"10B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"5/8-inch pitch British Standard single-strand chain.",
    image:IMG.british, industries:["European OEM","General Industrial"],
    features:["British Standard (BS/ISO)","5/8-inch pitch"],
    specs:{ pitch_in:"0.625", roller_width_in:"0.380", roller_dia_in:"0.400", riv_end_to_cl_in:"0.385", conn_end_to_cl_in:"0.440", plate_height_in:"0.580", plate_thick_in:"0.067", pin_dia_in:"0.200", avg_ultimate_lbs:"5,850" },
    related_pins:[{code:"10B-1 CL",name:"10B-1 Connecting Link",description:""}], related_sprockets:[{code:"10B Sprocket",name:"10B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (10B-2)","Triple strand (10B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-12B1", part_number:"12B-1", chain_number:"12B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"3/4-inch pitch British Standard single-strand chain. NOT interchangeable with ANSI #60.",
    image:IMG.british, industries:["European OEM","General Industrial"],
    features:["British Standard","3/4-inch pitch","Different from ANSI #60"],
    specs:{ pitch_in:"0.750", roller_width_in:"0.460", roller_dia_in:"0.475", riv_end_to_cl_in:"0.440", conn_end_to_cl_in:"0.483", plate_height_in:"0.635", plate_thick_in:"0.073", pin_dia_in:"0.225", avg_ultimate_lbs:"7,060" },
    related_pins:[{code:"12B-1 CL",name:"12B-1 Connecting Link",description:""}], related_sprockets:[{code:"12B Sprocket",name:"12B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (12B-2)","Triple strand (12B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-16B1", part_number:"16B-1", chain_number:"16B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"1-inch pitch British Standard single-strand chain.",
    image:IMG.british, industries:["European OEM","General Industrial","Mining"],
    features:["British Standard","1-inch pitch"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.670", roller_dia_in:"0.625", riv_end_to_cl_in:"0.702", conn_end_to_cl_in:"0.819", plate_height_in:"0.830", plate_thick_in:"0.157", pin_dia_in:"0.326", avg_ultimate_lbs:"15,880" },
    related_pins:[{code:"16B-1 CL",name:"16B-1 Connecting Link",description:""}], related_sprockets:[{code:"16B Sprocket",name:"16B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (16B-2)","Triple strand (16B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-20B1", part_number:"20B-1", chain_number:"20B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"1-1/4 inch pitch British Standard single-strand chain. 22,050 lb avg. ultimate.",
    image:IMG.british, industries:["European OEM","Heavy Industrial"],
    features:["British Standard","1-1/4 inch pitch","High tensile strength"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.770", roller_dia_in:"0.750", riv_end_to_cl_in:"0.786", conn_end_to_cl_in:"0.955", plate_height_in:"1.040", plate_thick_in:"0.175", pin_dia_in:"0.401", avg_ultimate_lbs:"22,050" },
    related_pins:[{code:"20B-1 CL",name:"20B-1 Connecting Link",description:""}], related_sprockets:[{code:"20B Sprocket",name:"20B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (20B-2)","Triple strand (20B-3)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-24B1", part_number:"24B-1", chain_number:"24B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"1-1/2 inch pitch British Standard single-strand chain. 36,830 lb avg. ultimate.",
    image:IMG.british, industries:["European OEM","Heavy Industrial"],
    features:["British Standard","1-1/2 inch pitch"],
    specs:{ pitch_in:"1.500", roller_width_in:"1.000", roller_dia_in:"1.000", riv_end_to_cl_in:"1.059", conn_end_to_cl_in:"1.256", plate_height_in:"1.315", plate_thick_in:"0.219", pin_dia_in:"0.576", avg_ultimate_lbs:"36,830" },
    related_pins:[{code:"24B-1 CL",name:"24B-1 Connecting Link",description:""}], related_sprockets:[{code:"24B Sprocket",name:"24B Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Double strand (24B-2)"], source:"Allied-Locke", source_url:SRC.british },

  { id:"BS-32B1", part_number:"32B-1", chain_number:"32B-1", category:"performance_roller", subcategory:"british_standard",
    product_type:"British Standard Roller Chain",
    description:"2-inch pitch British Standard single-strand chain. 57,330 lb avg. ultimate.",
    image:IMG.british, industries:["European OEM","Very Heavy Industrial"],
    features:["British Standard","2-inch pitch","High load capacity"],
    specs:{ pitch_in:"2.000", roller_width_in:"1.220", roller_dia_in:"1.150", riv_end_to_cl_in:"1.327", conn_end_to_cl_in:"1.556", plate_height_in:"1.662", plate_thick_in:"0.275", pin_dia_in:"0.703", avg_ultimate_lbs:"57,330" },
    related_pins:[{code:"32B-1 CL",name:"32B-1 Connecting Link",description:""}], related_sprockets:[{code:"32B Sprocket",name:"32B Sprockets",bore:"To suit"}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.british },

  // ── DOUBLE PITCH ─────────────────────────────────────────────────────────
  { id:"DP-A2040", part_number:"A2040", chain_number:"A2040", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Drive Chain",
    description:"1-inch (double) pitch drive chain. Figure-8 sidebars. Drive applications where lighter weight is acceptable.",
    image:IMG.double_pitch_a, industries:["Light Drives","Conveying","Assembly Lines"],
    features:["Double pitch for lighter weight","Figure-8 sidebars (A-series)","Drive applications","Compatible with No. 40 sprockets"],
    specs:{ type:"Drive Series", pitch_in:"1.000", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.368", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"3,970" },
    related_pins:[{code:"A2040 CL",name:"A2040 Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["A2050 (1.250\"), A2060 (1.50\"), A2080 (2.00\") also available"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-A2050", part_number:"A2050", chain_number:"A2050", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Drive Chain",
    description:"1-1/4 inch pitch drive chain with figure-8 sidebars.",
    image:IMG.double_pitch_a, industries:["Light Drives","Conveying"],
    features:["Figure-8 sidebars","Drive series","Double pitch"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.399", conn_end_to_cl_in:"0.455", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"6,620" },
    related_pins:[{code:"A2050 CL",name:"A2050 Connecting Link",description:""}], related_sprockets:[spr("50")], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2040", part_number:"C2040", chain_number:"C2040", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Standard Roller",
    description:"1-inch (double) pitch conveyor chain. Straight sidebars. Standard roller. Economy conveyor chain for low-speed applications.",
    image:IMG.double_pitch_c, industries:["Conveying","Packaging","Assembly Lines","Parts Washing"],
    features:["Double pitch — fewer links per foot = economy","Straight sidebars (C-series)","Standard rollers","Low-speed conveying"],
    specs:{ type:"Conveyor Series Standard Roller", pitch_in:"1.000", roller_width_in:"0.312", roller_dia_in:"0.312", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.368", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"3,970" },
    related_pins:[{code:"C2040 CL",name:"C2040 Connecting Link",description:""}], related_sprockets:[{code:"C2040 Sprocket",name:"C2040 Sprockets",bore:"To suit"}], related_attachments:[att("C2040","A1"),att("C2040","A2"),att("C2040","K1")],
    options:["Over-size rollers (C2042)","Attachments"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2050", part_number:"C2050", chain_number:"C2050", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Standard Roller",
    description:"1-1/4 inch pitch double pitch conveyor chain with standard rollers.",
    image:IMG.double_pitch_c, industries:["Conveying","Assembly Lines","Packaging"],
    features:["Double pitch","Straight sidebars","Standard rollers"],
    specs:{ pitch_in:"1.250", roller_width_in:"0.375", roller_dia_in:"0.400", riv_end_to_cl_in:"0.399", conn_end_to_cl_in:"0.455", plate_height_in:"0.594", plate_thick_in:"0.079", pin_dia_in:"0.200", avg_ultimate_lbs:"6,620" },
    related_pins:[{code:"C2050 CL",name:"C2050 Connecting Link",description:""}], related_sprockets:[{code:"C2050 Sprocket",name:"C2050 Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Over-size rollers (C2052)","Attachments"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2060H", part_number:"C2060H", chain_number:"C2060H", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Heavy",
    description:"1-1/2 inch pitch heavy double pitch conveyor chain. Standard and over-size roller (C2062H) available.",
    image:IMG.double_pitch_c, industries:["Conveying","Manufacturing","Packaging"],
    features:["Heavy (H) version — thicker plates","Double pitch","Over-size roller variant available"],
    specs:{ pitch_in:"1.500", roller_width_in:"0.500", roller_dia_in:"0.469", riv_end_to_cl_in:"0.570", conn_end_to_cl_in:"0.625", plate_height_in:"0.712", plate_thick_in:"0.125", pin_dia_in:"0.234", avg_ultimate_lbs:"12,130" },
    related_pins:[{code:"C2060H CL",name:"C2060H Connecting Link",description:""}], related_sprockets:[{code:"C2060 Sprocket",name:"C2060 Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Over-size roller (C2062H)","Attachments","Solid bushing (C2060H SOLID)"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2080H", part_number:"C2080H", chain_number:"C2080H", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Heavy",
    description:"2-inch pitch heavy double pitch conveyor chain.",
    image:IMG.double_pitch_c, industries:["Conveying","Heavy Manufacturing"],
    features:["Heavy double pitch","2-inch pitch"],
    specs:{ pitch_in:"2.000", roller_width_in:"0.625", roller_dia_in:"0.625", riv_end_to_cl_in:"0.720", conn_end_to_cl_in:"0.873", plate_height_in:"0.950", plate_thick_in:"0.157", pin_dia_in:"0.312", avg_ultimate_lbs:"19,850" },
    related_pins:[{code:"C2080H CL",name:"C2080H Connecting Link",description:""}], related_sprockets:[{code:"C2080 Sprocket",name:"C2080 Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Over-size roller (C2082H)","Solid bushing (C2080H SOLID)","Attachments"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2100H", part_number:"C2100H", chain_number:"C2100H", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Heavy",
    description:"2-1/2 inch pitch heavy double pitch conveyor chain. 30,870 lb avg. ultimate.",
    image:IMG.double_pitch_c, industries:["Conveying","Heavy Manufacturing"],
    features:["Heavy double pitch","2-1/2 inch pitch"],
    specs:{ pitch_in:"2.500", roller_width_in:"0.750", roller_dia_in:"0.750", riv_end_to_cl_in:"0.845", conn_end_to_cl_in:"1.002", plate_height_in:"1.188", plate_thick_in:"0.189", pin_dia_in:"0.375", avg_ultimate_lbs:"30,870" },
    related_pins:[{code:"C2100H CL",name:"C2100H Connecting Link",description:""}], related_sprockets:[{code:"C2100 Sprocket",name:"C2100 Sprockets",bore:"To suit"}], related_attachments:[],
    options:["Over-size roller (C2102H)"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2042", part_number:"C2042", chain_number:"C2042", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Oversize Roller",
    description:"1-inch pitch double pitch conveyor chain with oversize rollers (0.625 in dia). For walk-on-rail conveyor systems.",
    image:IMG.double_pitch_co, industries:["Walk-on-Rail Conveyors","Parts Washers","Industrial Conveying"],
    features:["Oversize rollers — walks on structural rail","Double pitch economy","Smooth product support"],
    specs:{ pitch_in:"1.000", roller_width_in:"0.312", roller_dia_in:"0.625", riv_end_to_cl_in:"0.321", conn_end_to_cl_in:"0.368", plate_height_in:"0.475", plate_thick_in:"0.058", pin_dia_in:"0.156", avg_ultimate_lbs:"3,970" },
    related_pins:[{code:"C2042 CL",name:"C2042 Connecting Link",description:""}], related_sprockets:[{code:"C2042 Sprocket",name:"C2042 Sprockets",bore:"To suit"}], related_attachments:[],
    options:["C2052, C2062H, C2082H oversize roller chains also available"], source:"Allied-Locke", source_url:SRC.double_p },

  { id:"DP-C2062H", part_number:"C2062H", chain_number:"C2062H", category:"performance_roller", subcategory:"double_pitch",
    product_type:"Double Pitch Conveyor Chain — Heavy Oversize Roller",
    description:"1-1/2 inch pitch heavy double pitch chain with oversize rollers (0.875 in dia).",
    image:IMG.double_pitch_co, industries:["Walk-on-Rail Conveyors","Industrial Conveying"],
    features:["Oversize rollers (0.875 in)","Heavy double pitch","Walk-on-rail"],
    specs:{ pitch_in:"1.500", roller_width_in:"0.500", roller_dia_in:"0.875", riv_end_to_cl_in:"0.570", conn_end_to_cl_in:"0.625", plate_height_in:"0.712", plate_thick_in:"0.125", pin_dia_in:"0.234", avg_ultimate_lbs:"12,130" },
    related_pins:[{code:"C2062H CL",name:"C2062H Connecting Link",description:""}], related_sprockets:[{code:"C2062 Sprocket",name:"C2062 Sprockets",bore:"To suit"}], related_attachments:[],
    options:[], source:"Allied-Locke", source_url:SRC.double_p },

  // ── DOUBLE CAPACITY ──────────────────────────────────────────────────────
  { id:"DC-40DC", part_number:"40DC", chain_number:"40DC", category:"performance_roller", subcategory:"double_capacity",
    product_type:"Double Capacity Chain",
    description:"1/2-inch pitch double capacity roller chain. Extended pins with twice the number of link plates — doubles tensile strength. Primarily for lifting applications.",
    image:IMG.double_pitch_a, industries:["Hoisting","Lifting Equipment","Elevators","Heavy Lifting"],
    features:["2× number of link plates","Extended pins","Twice the tensile strength of standard","Primarily for lifting"],
    specs:{ pitch_in:"0.500", notes:"Tensile strength = 2× standard No. 40. Contact Uniking for full spec." },
    related_pins:[{code:"40DC CL",name:"40DC Connecting Link",description:"Double capacity connecting link."}], related_sprockets:[spr("40")], related_attachments:[],
    options:["Available in sizes 40DC through 120DC"],
    source:"Allied-Locke", source_url:SRC.double_cap,
    notes:"Full double capacity range: 40–120 sizes. Contact Uniking." },

  // ── XDO OILFIELD ─────────────────────────────────────────────────────────
  { id:"XDO-80XDO", part_number:"80XDO", chain_number:"80XDO", category:"performance_roller", subcategory:"xdo",
    product_type:"XDO Oilfield Series Roller Chain",
    description:"1-inch pitch XDO oilfield roller chain. Shot peened for fatigue, wider waist plates, ball-drifted holes, hot dip lubrication. Optimized for oilfield pumping units.",
    image:IMG.xdo, industries:["Oil & Gas","Oilfield Pumping Units","Heavy Industrial"],
    features:["Shot peened — improved fatigue strength","Wider waist sideplates — shock resistance","Ball-drifted sideplate holes — extended life","Hot dip lubrication — maximum penetration","ANSI-compatible dimensions"],
    specs:{ pitch_in:"1.000", notes:"XDO dimensions match standard ANSI. 102 part numbers available in XDO series." },
    related_pins:[{code:"80XDO CL",name:"80XDO Connecting Link",description:""}], related_sprockets:[spr("80")], related_attachments:[],
    options:["All ANSI sizes from 40XDO to 200XDO","Multi-strand XDO available"],
    source:"Allied-Locke", source_url:SRC.xdo,
    notes:"102 XDO part numbers available. Contact Uniking for full range." },

  // ── STAINLESS STEEL ──────────────────────────────────────────────────────
  { id:"SS-40SS", part_number:"40SS", chain_number:"40SS", category:"performance_roller", subcategory:"stainless",
    product_type:"Stainless Steel Roller Chain",
    description:"1/2-inch pitch 304 stainless steel roller chain. Most common stainless roller chain size.",
    image:IMG.stainless, industries:["Food Processing","Pharmaceutical","Chemical Processing","Marine","Washdown"],
    features:["304 Stainless steel","Corrosion resistant","ANSI #40 compatible sprockets","316 SS available on request"],
    specs:{ pitch_in:"0.500", roller_width_in:"0.312", roller_dia_in:"0.312", pin_dia_in:"0.156", notes:"~10% lower avg. strength than carbon steel equivalent." },
    related_pins:[{code:"40SS CL",name:"No. 40 SS Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["304 SS","316 SS on request","Passivated"],
    source:"Allied-Locke", source_url:SRC.ss,
    notes:"Full stainless range: 25SS–160SS. Contact Uniking for complete list." },

  { id:"SS-60SS", part_number:"60SS", chain_number:"60SS", category:"performance_roller", subcategory:"stainless",
    product_type:"Stainless Steel Roller Chain",
    description:"3/4-inch pitch 304 stainless steel roller chain.",
    image:IMG.stainless, industries:["Food Processing","Pharmaceutical","Chemical","Marine"],
    features:["304 Stainless steel","Corrosion resistant"],
    specs:{ pitch_in:"0.750", notes:"~10% lower avg. strength than carbon steel equivalent." },
    related_pins:[{code:"60SS CL",name:"No. 60 SS Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["304 SS","316 SS on request"], source:"Allied-Locke", source_url:SRC.ss },

  { id:"SS-80SS", part_number:"80SS", chain_number:"80SS", category:"performance_roller", subcategory:"stainless",
    product_type:"Stainless Steel Roller Chain",
    description:"1-inch pitch 304 stainless steel roller chain.",
    image:IMG.stainless, industries:["Food Processing","Pharmaceutical","Chemical","Heavy Industrial"],
    features:["304 Stainless steel","Corrosion resistant"],
    specs:{ pitch_in:"1.000", notes:"~10% lower avg. strength than carbon steel equivalent." },
    related_pins:[{code:"80SS CL",name:"No. 80 SS Connecting Link",description:""}], related_sprockets:[spr("80")], related_attachments:[],
    options:["304 SS","316 SS on request"], source:"Allied-Locke", source_url:SRC.ss },

  // ── NICKEL PLATED ────────────────────────────────────────────────────────
  { id:"NP-40NP", part_number:"40NP", chain_number:"40NP", category:"performance_roller", subcategory:"nickel_plated",
    product_type:"Nickel Plated Roller Chain",
    description:"1/2-inch pitch nickel-plated roller chain. Plated before assembly. Corrosion resistance exceeds standard chain.",
    image:IMG.nickel_plated, industries:["Food Processing","Pharmaceutical","Clean Room","Light Corrosive"],
    features:["Nickel plated before assembly — all surfaces protected","Corrosion resistant","Within 5% of standard strength","ANSI sprocket compatible"],
    specs:{ pitch_in:"0.500", notes:"Dimensions identical to standard No. 40. Plated before assembly." },
    related_pins:[{code:"40NP CL",name:"No. 40 Nickel Plated Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["Full range: 25NP–160NP","Multi-strand NP available"],
    source:"Allied-Locke", source_url:SRC.np,
    notes:"Full NP range: 25NP–160NP plus multi-strand. Contact Uniking." },

  { id:"NP-60NP", part_number:"60NP", chain_number:"60NP", category:"performance_roller", subcategory:"nickel_plated",
    product_type:"Nickel Plated Roller Chain",
    description:"3/4-inch pitch nickel-plated roller chain.",
    image:IMG.nickel_plated, industries:["Food Processing","Pharmaceutical","Clean Room"],
    features:["Nickel plated before assembly","Corrosion resistant"],
    specs:{ pitch_in:"0.750", notes:"Dimensions identical to standard No. 60." },
    related_pins:[{code:"60NP CL",name:"No. 60 Nickel Plated Connecting Link",description:""}], related_sprockets:[spr("60")], related_attachments:[],
    options:["Full range: 25NP–160NP"], source:"Allied-Locke", source_url:SRC.np },

  // ── ARMOR COAT ───────────────────────────────────────────────────────────
  { id:"AC-40AC", part_number:"40AC", chain_number:"40AC", category:"performance_roller", subcategory:"armor_coat",
    product_type:"Armor Coat Chain",
    description:"1/2-inch pitch Armor Coat roller chain. Baked-on coating applied before AND after assembly — corrosion resistance exceeds nickel-plated chain.",
    image:IMG.armor_coat, industries:["Food Processing","Pharmaceutical","Marine","Outdoor","Corrosive Environments"],
    features:["Armor Coat applied before AND after assembly","Corrosion resistance exceeds nickel plated","Carbon steel strength retained","ANSI sprocket compatible","Available in 13 sizes"],
    specs:{ pitch_in:"0.500", notes:"Dimensions identical to standard No. 40. Full coating inside and outside." },
    related_pins:[{code:"40AC CL",name:"No. 40 Armor Coat Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["Available sizes: 25–120 (13 sizes total)"],
    source:"Allied-Locke", source_url:SRC.armor,
    notes:"13 Armor Coat sizes available. Contact Uniking for full range." },

  // ── SELF-LUBE ────────────────────────────────────────────────────────────
  { id:"SL-40SL", part_number:"40SL", chain_number:"40SL", category:"performance_roller", subcategory:"self_lube",
    product_type:"Self-Lube Roller Chain",
    description:"1/2-inch pitch self-lubricating roller chain with oil-impregnated sintered bushings. No external lubrication required.",
    image:IMG.self_lube, industries:["Food Processing","Pharmaceutical","Clean Room","Painting/Coating Lines","Dry Environments"],
    features:["Oil-impregnated sintered bushings","No external lubrication required","ANSI sprocket compatible","Seizure-free long service life"],
    specs:{ pitch_in:"0.500", notes:"Dimensions identical to standard No. 40." },
    related_pins:[cl("40")], related_sprockets:[spr("40")], related_attachments:[],
    options:["Available: 40SL, 50SL, 60SL, 80SL, 100SL, 120SL"],
    source:"Allied-Locke", source_url:SRC.self_lube,
    notes:"Self-lube range: 40SL–120SL. Contact Uniking for full list." },

  { id:"SL-60SL", part_number:"60SL", chain_number:"60SL", category:"performance_roller", subcategory:"self_lube",
    product_type:"Self-Lube Roller Chain",
    description:"3/4-inch pitch self-lubricating roller chain.",
    image:IMG.self_lube, industries:["Food Processing","Clean Room","Dry Environments"],
    features:["Oil-impregnated sintered bushings","No external lubrication required"],
    specs:{ pitch_in:"0.750", notes:"Dimensions identical to standard No. 60." },
    related_pins:[cl("60")], related_sprockets:[spr("60")], related_attachments:[],
    options:["Full SL range: 40SL–120SL"], source:"Allied-Locke", source_url:SRC.self_lube },

  { id:"SLB-40SLB", part_number:"40SLB", chain_number:"40SLB", category:"performance_roller", subcategory:"slb",
    product_type:"Self-Lube Bushing (SLB) Chain",
    description:"1/2-inch pitch SLB chain. Nickel plated pins, specially treated sideplates, sintered oil-impregnated bushings. Maximum corrosion resistance + self-lube.",
    image:IMG.slb, industries:["Food Processing","Pharmaceutical","Wet/Corrosive Environments","Clean Room"],
    features:["Nickel plated pins — corrosion resistance","Treated sideplates — max corrosion resistance","Sintered oil-impregnated bushings","ANSI sprocket interchangeable","SLH heavy version available"],
    specs:{ pitch_in:"0.500", notes:"Dimensions interchangeable with ANSI No. 40. Furnished with rollers." },
    related_pins:[{code:"40SLB CL",name:"No. 40 SLB Connecting Link",description:""}], related_sprockets:[spr("40")], related_attachments:[],
    options:["SLH (heavy version) available","Available: 40SLB–120SLB"],
    source:"Allied-Locke", source_url:SRC.slb,
    notes:"Full SLB range: 40SLB–120SLB. SLH (heavy) available. Contact Uniking." },
];