// ─── Static data for Elevator Belts, Hardware, Splices ───────────────────────

export const BELTS = [
  {
    id: "belt-ml-rubber-grade2",
    supplier: "Maxi-Lift",
    type: "Rubber",
    grade: "Grade 2",
    description: "Standard duty rubber elevator belt — general grain and agricultural conveying",
    widths: ['4"', '5"', '6"', '7"', '8"', '9"', '10"', '12"', '14"', '16"', '18"', '20"', '24"'],
    spliceCompatibility: ["Mechanical Fasteners", "Hot Vulcanized", "Maxi-Splice"],
    temp: "-40°F to +200°F",
    notes: "Available in custom lengths. Specify width and length on RFQ.",
    image: null,
    url: "https://maxilift.com/elevator-belting",
  },
  {
    id: "belt-ml-rubber-epdm",
    supplier: "Maxi-Lift",
    type: "Rubber",
    grade: "EPDM",
    description: "EPDM rubber belt for high-temperature and chemical-resistant applications",
    widths: ['4"', '6"', '8"', '10"', '12"', '16"', '18"', '24"'],
    spliceCompatibility: ["Mechanical Fasteners", "Hot Vulcanized", "Maxi-Splice"],
    temp: "-60°F to +300°F",
    notes: "Oil-resistant, FDA-compliant grade available on request.",
    image: null,
    url: "https://maxilift.com/elevator-belting",
  },
  {
    id: "belt-ml-pvc",
    supplier: "Maxi-Lift",
    type: "PVC",
    grade: "Standard",
    description: "PVC elevator belt for light-duty grain and food processing",
    widths: ['4"', '6"', '8"', '10"', '12"'],
    spliceCompatibility: ["Mechanical Fasteners", "Maxi-Splice"],
    temp: "-20°F to +150°F",
    notes: "Lighter weight than rubber. Not recommended for heavy or abrasive materials.",
    image: null,
    url: "https://maxilift.com/elevator-belting",
  },
  {
    id: "belt-tapco-dura",
    supplier: "Tapco",
    type: "Rubber",
    grade: "Scandura Dura-Splice Compatible",
    description: "Heavy-duty rubber belt engineered for use with Scandura Dura-Splice mechanical fasteners",
    widths: ['4"', '5"', '6"', '7"', '8"', '9"', '10"', '12"', '14"', '16"', '18"', '20"', '24"'],
    spliceCompatibility: ["Scandura Dura-Splice", "Jackson Plate", "Mechanical Fasteners"],
    temp: "-40°F to +200°F",
    notes: "Designed for easy field splicing with Dura-Splice fasteners. Order belt and splices together.",
    image: null,
    url: "https://tapcoinc.com/belting",
  },
  {
    id: "belt-4b-standard",
    supplier: "4B",
    type: "Rubber",
    grade: "Standard Duty",
    description: "4B Braime™ standard rubber elevator belt for agricultural and industrial bucket elevators",
    widths: ['4"', '5"', '6"', '7"', '8"', '10"', '12"', '14"', '16"', '18"', '20"', '24"'],
    spliceCompatibility: ["Mechanical Fasteners", "Hot Vulcanized"],
    temp: "-40°F to +200°F",
    notes: "Supplied per metre or per foot. Custom widths available.",
    image: null,
    url: "https://www.go4b.com/usa/bucket-elevator-components/belting-and-fasteners/",
  },
  {
    id: "belt-4b-heavy",
    supplier: "4B",
    type: "Rubber",
    grade: "Heavy Duty",
    description: "4B Braime™ heavy-duty rubber elevator belt for high-capacity industrial applications",
    widths: ['6"', '8"', '10"', '12"', '14"', '16"', '18"', '20"', '24"', '30"', '36"'],
    spliceCompatibility: ["Mechanical Fasteners", "Hot Vulcanized"],
    temp: "-40°F to +200°F",
    notes: "Higher tensile strength construction. Contact Uniking for specific belt ratings.",
    image: null,
    url: "https://www.go4b.com/usa/bucket-elevator-components/belting-and-fasteners/",
  },
];

export const HARDWARE = [
  {
    id: "hw-ml-bolt-1",
    supplier: "Maxi-Lift",
    name: "Standard #1 Elevator Bolt",
    description: "Round head, square neck elevator bolt — standard profile for most plastic buckets",
    sizes: ['5/16" x 3/4"', '5/16" x 1"', '3/8" x 3/4"', '3/8" x 1"', '1/2" x 1"', '1/2" x 1-1/4"'],
    materials: ["Zinc Plated", "Stainless Steel 304", "Stainless Steel 316"],
    grade: "Grade 5",
    notes: "Use with standard #1 elevator nut. Square neck prevents rotation during installation.",
    image: null,
    url: "https://maxilift.com/hardware",
  },
  {
    id: "hw-ml-bolt-sabretooth",
    supplier: "Maxi-Lift",
    name: "Sabre-Tooth Elevator Bolt",
    description: "Maxi-Lift exclusive Sabre-Tooth bolt with aggressive underhead serrations to prevent loosening under vibration",
    sizes: ['5/16" x 3/4"', '5/16" x 1"', '3/8" x 3/4"', '3/8" x 1"'],
    materials: ["Zinc Plated", "Stainless Steel 304"],
    grade: "Grade 5",
    notes: "Self-locking serrations eliminate the need for lock washers. Recommended for high-vibration applications.",
    image: null,
    url: "https://maxilift.com/hardware",
  },
  {
    id: "hw-tapco-norway",
    supplier: "Tapco",
    name: "Norway Flat Head Elevator Bolt",
    description: "Flat head elevator bolt for installations where a flush surface is required",
    sizes: ['5/16" x 3/4"', '5/16" x 1"', '3/8" x 3/4"', '3/8" x 1"', '1/2" x 1"'],
    materials: ["Zinc Plated", "Stainless Steel 304", "Carbon Steel"],
    grade: "Grade 5",
    notes: "Flat head sits flush with bucket surface. Popular for steel bucket installations.",
    image: null,
    url: "https://tapcoinc.com/hardware",
  },
  {
    id: "hw-tapco-countersunk",
    supplier: "Tapco",
    name: "Countersunk Elevator Bolt",
    description: "Countersunk head elevator bolt for smooth back face on belt — reduces wear",
    sizes: ['5/16" x 3/4"', '5/16" x 1"', '3/8" x 1"', '1/2" x 1"'],
    materials: ["Zinc Plated", "Stainless Steel"],
    grade: "Grade 5",
    notes: "Countersunk head provides smooth belt contact surface. Common on urethane bucket installations.",
    image: null,
    url: "https://tapcoinc.com/hardware",
  },
  {
    id: "hw-4b-elevator-bolt",
    supplier: "4B",
    name: "4B Elevator Bolt & Nut Set",
    description: "4B Braime™ precision elevator bolt and nut set for bucket attachment to belt or chain",
    sizes: ['5/16" x 3/4"', '5/16" x 1"', '3/8" x 3/4"', '3/8" x 1"', '1/2" x 1"'],
    materials: ["Zinc Plated", "Stainless Steel 304", "Stainless Steel 316"],
    grade: "Grade 5 / Grade 8",
    notes: "Matching nuts supplied with bolts. Available in bulk packs. Specify quantity on RFQ.",
    image: null,
    url: "https://www.go4b.com/usa/bucket-elevator-components/belting-and-fasteners/",
  },
  {
    id: "hw-nuts-standard",
    supplier: "Maxi-Lift",
    name: "Elevator Nut (Standard)",
    description: "Heavy hex nut for use with #1 and Sabre-Tooth elevator bolts",
    sizes: ['5/16"', '3/8"', '1/2"'],
    materials: ["Zinc Plated", "Stainless Steel 304"],
    grade: "Grade 5",
    notes: "Weld-on and flange nut styles available. Contact for specialty nut requirements.",
    image: null,
    url: "https://maxilift.com/hardware",
  },
];

export const SPLICES = [
  {
    id: "splice-tapco-dura",
    supplier: "Tapco",
    name: "Scandura Dura-Splice",
    description: "Industry-standard mechanical belt fastener for elevator belts — easy field installation without belt removal",
    beltWidths: ['4"', '5"', '6"', '7"', '8"', '9"', '10"', '12"', '14"', '16"', '18"', '20"', '24"'],
    beltThickness: ['3/16"', '1/4"', '5/16"', '3/8"', '7/16"', '1/2"'],
    materials: ["Carbon Steel (Zinc Plated)", "Stainless Steel 316"],
    notes: "No tools required for installation. Reusable. Rated for high-speed applications. Specify belt width and thickness.",
    image: null,
    url: "https://tapcoinc.com/splices",
  },
  {
    id: "splice-tapco-jackson",
    supplier: "Tapco",
    name: "Jackson Plate Belt Fastener",
    description: "Traditional hinged plate belt fastener for heavy-duty elevator belt applications",
    beltWidths: ['4"', '6"', '8"', '10"', '12"', '16"', '18"', '20"', '24"'],
    beltThickness: ['1/4"', '5/16"', '3/8"', '1/2"'],
    materials: ["Carbon Steel (Zinc Plated)", "Stainless Steel"],
    notes: "Heavy-duty plate-and-hinge construction. Suitable for high-tension belt applications.",
    image: null,
    url: "https://tapcoinc.com/splices",
  },
  {
    id: "splice-ml-maxi",
    supplier: "Maxi-Lift",
    name: "Maxi-Splice",
    description: "Maxi-Lift patented one-piece mechanical belt fastener — installs in minutes without special tools",
    beltWidths: ['4"', '5"', '6"', '7"', '8"', '9"', '10"', '12"', '14"', '16"', '18"', '20"', '24"'],
    beltThickness: ['3/16"', '1/4"', '5/16"', '3/8"'],
    materials: ["Zinc Plated Steel", "Stainless Steel"],
    notes: "Patented one-piece design — no loose parts. Rated up to 700 FPM belt speed. FDA-compliant SS version available.",
    image: null,
    url: "https://maxilift.com/maxi-splice",
  },
  {
    id: "splice-4b-fasteners",
    supplier: "4B",
    name: "4B Belt Fasteners",
    description: "4B Braime™ mechanical belt fasteners for bucket elevator belt splicing",
    beltWidths: ['4"', '6"', '8"', '10"', '12"', '16"', '18"', '20"', '24"'],
    beltThickness: ['3/16"', '1/4"', '5/16"', '3/8"', '1/2"'],
    materials: ["Zinc Plated", "Stainless Steel 304", "Stainless Steel 316"],
    notes: "Multiple fastener styles available. Contact Uniking for correct fastener selection based on belt specifications.",
    image: null,
    url: "https://www.go4b.com/usa/bucket-elevator-components/belting-and-fasteners/",
  },
];

export const SUPPLIER_INFO = {
  "Maxi-Lift": {
    color: "#b45309",
    bg: "#fffbeb",
    border: "#fde68a",
    dot: "#f59e0b",
    logo: null,
    url: "https://maxilift.com",
    tagline: "Agricultural & Industrial Buckets",
  },
  "Tapco": {
    color: "#1d4ed8",
    bg: "#eff6ff",
    border: "#bfdbfe",
    dot: "#3b82f6",
    logo: null,
    url: "https://tapcoinc.com",
    tagline: "CC, AA & Steel Bucket Styles",
  },
  "4B": {
    color: "#b91c1c",
    bg: "#fef2f2",
    border: "#fecaca",
    dot: "#ef4444",
    logo: null,
    url: "https://www.go4b.com",
    tagline: "Starco, AC & Steel Buckets",
  },
};