/**
 * fourBData.js
 * 4B Braime™ Electronics & Monitoring product catalog data.
 * All data sourced from go4b.com — verified 2026-05-05.
 * Images and downloads link directly to 4B official resources.
 */

const B = "https://www.go4b.com/usa/";
const IMG = B + "images/";

// ── Approval badge definitions ────────────────────────────────────────────────
export const APPROVALS = {
  CSA:   { label: "CSA",   fullLabel: "CSA — USA & Canada",         logo: IMG + "misc/csa-logo.gif",   color: "#c00",   bg: "#fff5f5" },
  ATEX:  { label: "ATEX",  fullLabel: "ATEX — Europe (Dust/Gas)",   logo: IMG + "misc/atex-logo.gif",  color: "#e07b00",bg: "#fff8f0" },
  CE:    { label: "CE",    fullLabel: "CE — Europe",                 logo: IMG + "misc/ce-logo.gif",    color: "#003399",bg: "#f0f4ff" },
  IECEx: { label: "IECEx", fullLabel: "IECEx — International",      logo: IMG + "misc/iecex-logo.gif", color: "#006600",bg: "#f0fff4" },
  MET:   { label: "MET",   fullLabel: "MET — USA & Canada",         logo: IMG + "misc/MET.gif",        color: "#660099",bg: "#faf0ff" },
};

// ── Subcategories ─────────────────────────────────────────────────────────────
export const SUBCATEGORIES = [
  {
    key: "hazard",
    label: "Hazard Monitoring Systems",
    description: "CSA / ATEX / CE approved hazard monitoring systems for bucket elevators and conveyors in dust hazard environments.",
    icon: "🛡️",
    url: B + "products/hazard-monitoring-systems/default.asp",
    heroImage: IMG + "hazard-monitors/Watchdog-Super-Elite-WDC4.jpg",
  },
  {
    key: "alignment",
    label: "Alignment Sensors",
    description: "Belt, pulley and chain alignment monitoring — force-activated, rub block, and magnetic proximity sensors.",
    icon: "📐",
    url: B + "products/alignment-sensors/default.asp",
    heroImage: IMG + "hazard-monitors/touchswitch_red.jpg",
  },
  {
    key: "speed",
    label: "Speed Switches",
    description: "Proximity, inductive, zero speed, stop motion and encoder sensors for dangerous belt slip or underspeed detection.",
    icon: "⚡",
    url: B + "products/speed-switches/default.asp",
    heroImage: IMG + "speed-switches/M800-Elite-Speed-Switch.jpg",
  },
  {
    key: "temperature",
    label: "Temperature Sensors",
    description: "Bearing and surface temperature sensors for predictive maintenance and explosion prevention in dust environments.",
    icon: "🌡️",
    url: B + "products/temperature-sensors/default.asp",
    heroImage: IMG + "temperature-sensors/adb_bearing_temperature_sensor.jpg",
  },
  {
    key: "level",
    label: "Level Indicators",
    description: "RF, rotary paddle and capacitance level indicators for tanks, bins, silos, chutes, conveyors and elevator legs.",
    icon: "📊",
    url: B + "products/level-indicators/default.asp",
    heroImage: IMG + "level-indicators/auto-set-level-indicator.jpg",
  },
  {
    key: "inductive",
    label: "Inductive Sensors",
    description: "Inductive proximity sensors for shaft speed, shaft position, gate position or object presence detection.",
    icon: "🔍",
    url: B + "products/inductive-sensors/default.asp",
    heroImage: IMG + "inductive/p100_sensor.jpg",
  },
  {
    key: "safety",
    label: "Safety Switches",
    description: "Failsafe taut wire emergency pull cord safety stop switches for open conveyors.",
    icon: "🔴",
    url: B + "products/conveyor-safety-switches/default.asp",
    heroImage: IMG + "pullswitch/pullswitch.jpg",
  },
  {
    key: "alarms",
    label: "Alarms & Displays",
    description: "Alarm monitoring panels, digital tachometers, speed relays and display units for conveyor safety systems.",
    icon: "🔔",
    url: B + "products/alarms-and-displays/default.asp",
    heroImage: IMG + "hazard-monitors/X400_alarmswitch.jpg",
  },
];

// ── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS = [

  // ── HAZARD MONITORING SYSTEMS ─────────────────────────────────────────────
  {
    id: "ie-node",
    subcategory: "hazard",
    name: "IE-Node",
    trademark: null,
    image: IMG + "hazard-monitors/IE-Node-IT.jpg",
    description: "Sensor interfaces for PLCs and automation systems. Supports PROFINET, EtherNet/IP and Modbus TCP/IP. Up to 16 total sensor inputs with available expansion boards.",
    keyFunction: "Hazard Monitoring — Network Interface",
    features: [
      "Sensor Interfaces for PLC's and Automation Systems",
      "Supports PROFINET, EtherNet/IP and Modbus TCP/IP",
      "Up to 16 Total Sensor Inputs with Available Expansion Boards",
      "Configurator Software for Easy Network Set Up and Visual Overview of All Devices",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Belt Conveyors", "PLC-Integrated Systems", "Grain Handling", "Milling"],
    source_url: B + "products/hazard-monitoring-systems/ie-node.asp",
    downloads: [
      { name: "IE-Node Datasheet", type: "PDF", url: B + "datasheets/ie-node-datasheet.pdf" },
    ],
    accessories: [],
    partNumbers: ["IE-NODE"],
  },
  {
    id: "watchdog-super-elite",
    subcategory: "hazard",
    name: "Watchdog™ Super Elite",
    trademark: "Watchdog™",
    image: IMG + "hazard-monitors/Watchdog-Super-Elite-WDC4.jpg",
    description: "Designed for one elevator leg or one conveyor. Monitors belt speed, belt alignment, bearing temperature, pulley alignment and plug conditions. Includes PLC communications (Modbus TCP/IP), event & alarm logging, and HazardMon.com cloud based monitoring.",
    keyFunction: "All-In-One Hazard Monitor — Single Elevator or Conveyor",
    features: [
      "Designed for One Elevator Leg or One Conveyor",
      "Monitors: Belt Speed, Belt Alignment, Bearing Temperature, Pulley Alignment & Plug Conditions",
      "PLC Communications (Modbus TCP/IP)",
      "Event & Alarm Logging",
      "HazardMon.com Cloud Based Monitoring",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Grain Handling", "Feed Mills", "Flour Mills"],
    source_url: B + "products/hazard-monitoring-systems/watchdog-super-elite-hazard-monitor.asp",
    downloads: [
      { name: "Watchdog Super Elite Datasheet", type: "PDF", url: B + "datasheets/watchdog-super-elite-hazard-monitor.pdf" },
      { name: "Watchdog Super Elite Manual", type: "PDF", url: B + "technical-support/product-manuals/hazard-monitors/watchdog-super-elite-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["WDC4"],
  },
  {
    id: "hazardmon",
    subcategory: "hazard",
    name: "HazardMon.com®",
    trademark: "HazardMon.com®",
    image: IMG + "hazard-monitors/HazardMon.com.gif",
    description: "Secure cloud based hazard monitoring platform. Integrates with IE-Node, Watchdog™ Super Elite & T500 Elite Hotbus™. Provides real time system status, alert email notifications, automatic data logging and automated maintenance reporting. View on any web-enabled device.",
    keyFunction: "Cloud-Based Remote Hazard Monitoring Platform",
    features: [
      "Secure Cloud Based Hazard Monitoring",
      "Integrates with IE-Node, Watchdog™ Super Elite & T500 Elite Hotbus™",
      "Real Time System Status & Alert Email Notifications",
      "Data Logged Automatically",
      "Automated Maintenance",
      "View on Any Web-Enabled Device",
    ],
    approvals: [],
    applications: ["Remote Monitoring", "Multi-Site Facilities", "Grain Terminals", "Ports & Export Elevators"],
    source_url: B + "products/hazard-monitoring-systems/hazardmon.com.asp",
    downloads: [],
    accessories: [],
    partNumbers: [],
  },
  {
    id: "t500-elite-hotbus",
    subcategory: "hazard",
    name: "T500 Elite Hotbus™",
    trademark: "Hotbus™",
    image: IMG + "hazard-monitors/t500_hotbus.jpg",
    description: "Designed for multiple elevator legs or conveyors. Monitors belt speed, belt alignment, bearing temperature, pulley alignment, bin/silo level indication and plug conditions. Serial network system accepts inputs from 256 sensors. LCD displays system status. HazardMon.com cloud monitoring.",
    keyFunction: "Multi-Elevator/Multi-Conveyor Hazard Monitor — 256 Sensor Inputs",
    features: [
      "Designed for Multiple Elevator Legs or Conveyors",
      "Monitors: Belt Speed, Belt Alignment, Bearing Temperature, Pulley Alignment, Bin/Silo Level & Plug Conditions",
      "Serial Network System, Accepts Inputs from 256 Sensors",
      "LCD Displays System Status",
      "HazardMon.com Cloud Based Monitoring",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Grain Terminals", "Large Elevator Complexes", "Feed Mills", "Multi-Leg Installations"],
    source_url: B + "products/hazard-monitoring-systems/t500-elite-hotbus-hazard-monitor.asp",
    downloads: [
      { name: "T500 Elite Hotbus Datasheet", type: "PDF", url: B + "datasheets/t500-elite-hotbus-hazard-monitor.pdf" },
      { name: "T500 Elite Hotbus Manual", type: "PDF", url: B + "technical-support/product-manuals/hazard-monitors/t500-elite-hotbus-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["T500"],
  },
  {
    id: "t400n-hotswitch",
    subcategory: "hazard",
    name: "T400N Elite Hotswitch",
    trademark: "Hotswitch",
    image: IMG + "hazard-monitors/t400_hotswitch.jpg",
    description: "Bearing and surface temperature monitor. Monitors up to 8 NTC type temperature sensors. Features 2 separate alarm and 2 separate stop relays with status LEDs.",
    keyFunction: "Bearing & Surface Temperature Monitor — Up to 8 Sensors",
    features: [
      "Bearing & Surface Temperature Monitor",
      "Monitors up to 8 NTC Type Temperature Sensors",
      "2 Separate Alarm & 2 Separate Stop Relays",
      "Status LEDs",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Conveyors", "Bearing Monitoring", "Grain Handling"],
    source_url: B + "products/hazard-monitoring-systems/t400n-elite-hotswitch-temperature-monitor.asp",
    downloads: [
      { name: "T400N Elite Hotswitch Datasheet", type: "PDF", url: B + "datasheets/t400n-elite-hotswitch-temperature-monitor.pdf" },
    ],
    accessories: [],
    partNumbers: ["T400N"],
  },

  // ── ALIGNMENT SENSORS ─────────────────────────────────────────────────────
  {
    id: "touchswitch",
    subcategory: "alignment",
    name: "Touchswitch™",
    trademark: "Touchswitch™",
    image: IMG + "hazard-monitors/touchswitch_red.jpg",
    description: "Force-activated belt and pulley misalignment sensor. Not a rub block — instantaneous misalignment indication when belt or pulley contacts the hardened stainless steel face. Built-in solid-state electronic circuitry activates a voltage-free relay contact for immediate alarm and shutdown.",
    keyFunction: "Force-Activated Belt & Pulley Misalignment Detection",
    features: [
      "Force Activated Belt and Pulley Misalignment Sensor",
      "Instantaneous Misalignment Indication",
      "Hardened Stainless Steel Contact Face",
      "External Test Feature",
      "Output LED Indication",
      "Not a Rub Block",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Grain Handling", "Milling", "Mining"],
    source_url: B + "products/alignment-sensors/touchswitch-belt-alignment-sensor.asp",
    downloads: [
      { name: "Touchswitch Datasheet", type: "PDF", url: B + "datasheets/touchswitch-belt-alignment-sensor.pdf" },
      { name: "Touchswitch Manual", type: "PDF", url: B + "technical-support/product-manuals/alignment-sensors/touchswitch-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["TS100", "TS200"],
  },
  {
    id: "brass-rub-blocks",
    subcategory: "alignment",
    name: "Brass Rub Blocks",
    trademark: null,
    image: IMG + "alignment-sensors/brass-rub-blocks.jpg",
    description: "Belt misalignment monitoring via heat generated by belt friction. A temperature sensor within the solid brass block detects friction heat and triggers alarm and shutdown at set trip points. No moving parts.",
    keyFunction: "Friction-Heat Belt Misalignment Monitoring",
    features: [
      "Belt Misalignment Monitoring",
      "Easy Installation",
      "No Moving Parts (Solid Brass Block)",
      "Temperature Activated (Friction)",
      "External Sensor Testing (ADB Tester)",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Grain Handling"],
    source_url: B + "products/alignment-sensors/brass-rub-block-belt-misalignment-sensor.asp",
    downloads: [
      { name: "Brass Rub Blocks Datasheet", type: "PDF", url: B + "datasheets/brass-rub-block-belt-misalignment-sensor.pdf" },
    ],
    accessories: [],
    partNumbers: ["BRB100"],
  },
  {
    id: "wda-motion-sensor",
    subcategory: "alignment",
    name: "WDA Motion Alignment Sensor",
    trademark: null,
    image: IMG + "hazard-monitors/wda_sensor.jpg",
    description: "Magnetic proximity sensor for belt speed and belt misalignment. Detects moving steel ferrous targets including elevator buckets, ferrous bolts on plastic buckets, or as a broken/slack chain detector on drag chain conveyors. Adjustable sensing range 1–3 inches. Stainless steel construction.",
    keyFunction: "Magnetic Proximity Speed & Alignment — Detects Ferrous Targets",
    features: [
      "Magnetic Proximity Belt Speed and Belt Misalignment Sensor",
      "Detects Moving Steel Ferrous Targets",
      "Adjustable Sensing Range of 1 to 3 Inches",
      "Not Affected by Material Build Up",
      "Stainless Steel Construction",
      "High Temperature Version Available",
    ],
    approvals: ["CSA", "ATEX", "CE", "IECEx"],
    applications: ["Bucket Elevators", "Drag Chain Conveyors", "Screw Conveyors", "Grain Handling"],
    source_url: B + "products/alignment-sensors/wda-motion-alignment-sensor.asp",
    downloads: [
      { name: "WDA Sensor Datasheet", type: "PDF", url: B + "datasheets/wda-motion-alignment-sensor.pdf" },
      { name: "WDA Sensor Manual", type: "PDF", url: B + "technical-support/product-manuals/alignment-sensors/wda-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["WDA100", "WDA200-HT"],
  },
  {
    id: "bulldog",
    subcategory: "alignment",
    name: "Bulldog",
    trademark: null,
    image: IMG + "alignment-sensors/bulldog.jpg",
    description: "Belt misalignment sensor with ATEX and IECEx Zone 21 approval. No calibration required. Robust design with 20° belt misalignment alarm and 35° belt misalignment shutdown.",
    keyFunction: "ATEX Zone 21 Belt Misalignment — 20° Alarm / 35° Shutdown",
    features: [
      "ATEX and IECEx Zone 21 Approved",
      "Easy Installation",
      "No Calibration Required",
      "Robust Design",
      "20° Belt Misalignment Alarm",
      "35° Belt Misalignment Shutdown",
    ],
    approvals: ["CSA", "ATEX", "CE", "IECEx"],
    applications: ["Bucket Elevators", "Belt Conveyors", "High-Dust Environments", "Zone 21 Areas"],
    source_url: B + "products/alignment-sensors/Bulldog.asp",
    downloads: [
      { name: "Bulldog Datasheet", type: "PDF", url: B + "datasheets/bulldog-alignment-sensor.pdf" },
    ],
    accessories: [],
    partNumbers: ["BULLDOG"],
  },

  // ── SPEED SWITCHES ────────────────────────────────────────────────────────
  {
    id: "encoder-flex-1024",
    subcategory: "speed",
    name: "Encoder-Flex 1024",
    trademark: null,
    image: IMG + "speed-switches/Encoder-Flex%201024_thumbnail.jpg",
    description: "Programmable encoder with 4-20 mA, Quadrature Pulse and RS485 Modbus RTU outputs. Programmable resolution from 1 to 1024 pulses per revolution. Memorizes shaft position in case of power loss. Sealed stainless steel enclosure.",
    keyFunction: "Programmable Encoder — 4-20 mA / RS485 / Quadrature Output",
    features: [
      "Outputs: 4-20 mA, Quadrature Pulse (Speed/Relative Rotation), and RS485 Modbus RTU",
      "Programmable Resolution from 1 to 1024 Pulses per Revolution",
      "Memorizes Shaft Position in Case of a Power Loss",
      "Sealed Stainless Steel Enclosure",
    ],
    approvals: ["MET", "ATEX", "CE", "IECEx"],
    applications: ["Conveyors", "Elevators", "PLC Systems", "Automation Integration"],
    source_url: B + "products/speed-switches/encoder-flex-1024.asp",
    downloads: [
      { name: "Encoder-Flex 1024 Datasheet", type: "PDF", url: B + "datasheets/encoder-flex-1024.pdf" },
    ],
    accessories: [],
    partNumbers: ["EF1024"],
  },
  {
    id: "whirligig",
    subcategory: "speed",
    name: "Whirligig®",
    trademark: "Whirligig®",
    image: IMG + "speed-switches/Whirligig.jpg",
    description: "Fully guarded target for easy mounting of motion sensors. Universal application — suits all DIN style and industry standard cylindrical sensors. Only requires 1/2\" UNC tapped hole in the machine shaft, or use a Mag-Con™ for magnetic connection. Available with 1, 2, 4 or 8 targets.",
    keyFunction: "Universal Sensor Mounting Target — 1/2\" UNC or Magnetic Connection",
    features: [
      "Fully Guarded Target for Easy Mounting of Motion Sensors",
      "Universal Application — Suits All DIN Style and Industry Standard Cylindrical Sensors",
      "Easy Installation — Only Requires 1/2\" UNC Tapped Hole or Mag-Con™ Magnetic Connection",
      "Available with 1, 2, 4 or 8 Targets",
    ],
    approvals: ["ATEX", "CE"],
    applications: ["All Shaft-Mounted Speed Sensor Applications", "Bucket Elevators", "Conveyors"],
    source_url: B + "products/speed-switches/whirligig.asp",
    downloads: [
      { name: "Whirligig Datasheet", type: "PDF", url: B + "datasheets/whirligig.pdf" },
    ],
    accessories: [],
    partNumbers: ["WG-1", "WG-2", "WG-4", "WG-8", "MAG-CON"],
  },
  {
    id: "milli-speed",
    subcategory: "speed",
    name: "Milli-Speed Switch",
    trademark: "Milli-Speed™",
    image: IMG + "speed-switches/Milli-Speed-Switch.jpg",
    description: "4-20 mA output speed sensor with simple magnetic calibration. Loop powered (2-wire). Totally sealed construction (submersible). Easy installation with Whirligig® sensor mount. SpeedMaster™ compatible for accurate testing.",
    keyFunction: "4-20 mA Loop-Powered Speed Sensor — Submersible",
    features: [
      "4 - 20 mA Output",
      "Simple Magnetic Calibration",
      "Loop Powered (2 Wire)",
      "Totally Sealed Construction (Submersible)",
      "Easy Installation with Whirligig® Sensor Mount",
      "SpeedMaster™ Compatible for Accurate Testing",
    ],
    approvals: ["CSA"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Screw Conveyors", "Grain Handling"],
    source_url: B + "products/speed-switches/milli-speed-switch.asp",
    downloads: [
      { name: "Milli-Speed Datasheet", type: "PDF", url: B + "datasheets/milli-speed-switch.pdf" },
      { name: "Milli-Speed Manual", type: "PDF", url: B + "technical-support/product-manuals/speed-switches/milli-speed-manual.pdf" },
    ],
    accessories: ["whirligig", "speedmaster"],
    partNumbers: ["MS100"],
  },
  {
    id: "m800-elite",
    subcategory: "speed",
    name: "M800 Elite Speed Switch",
    trademark: null,
    image: IMG + "speed-switches/M800-Elite-Speed-Switch.jpg",
    description: "Microprocessor controlled speed switch with LED indication. Non-contacting and fail-safe design. Totally sealed construction (submersible). Dual set points for alarm and shutdown. Universal voltage (24–240 VAC/VDC).",
    keyFunction: "Microprocessor Speed Switch — Dual Alarm/Shutdown Setpoints",
    features: [
      "Microprocessor Controlled Speed Switch",
      "LED Indication",
      "Non-Contacting and Fail-Safe",
      "Totally Sealed Construction (Submersible)",
      "Dual Set Points for Alarm and Shutdown",
      "Universal Voltage (24 - 240 VAC/VDC)",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Grain Handling", "Milling", "Mining"],
    source_url: B + "products/speed-switches/m800-elite-speed-switch.asp",
    downloads: [
      { name: "M800 Elite Datasheet", type: "PDF", url: B + "datasheets/m800-elite-speed-switch.pdf" },
      { name: "M800 Elite Manual", type: "PDF", url: B + "technical-support/product-manuals/speed-switches/M800-manual.pdf" },
    ],
    accessories: ["whirligig", "speedmaster", "p100-proxswitch"],
    partNumbers: ["M800"],
  },
  {
    id: "m300-slipswitch",
    subcategory: "speed",
    name: "M300 Slipswitch",
    trademark: "Slipswitch",
    image: IMG + "speed-switches/M300-Slipswitch.jpg",
    description: "Microprocessor controlled underspeed monitor with inductive proximity sensor (30 mm diameter housing). Single set point — 20% underspeed. Available in 2 wire and 5 wire versions. Totally sealed construction (submersible). Non-contacting and fail-safe.",
    keyFunction: "Microprocessor Underspeed Monitor — 20% Trip Point",
    features: [
      "Microprocessor Controlled Underspeed Monitor",
      "Inductive Proximity Sensor (30 mm Diameter Housing)",
      "Single Set Point — 20% Underspeed",
      "2 Wire & 5 Wire Versions",
      "Totally Sealed Construction (Submersible)",
      "Non-Contacting and Fail-Safe",
    ],
    approvals: ["CSA", "ATEX", "CE", "IECEx"],
    applications: ["Bucket Elevators", "Belt Conveyors", "Grain Handling", "All Rotating Machinery"],
    source_url: B + "products/speed-switches/m300-slipswitch.asp",
    downloads: [
      { name: "M300 Slipswitch Datasheet", type: "PDF", url: B + "datasheets/m300-slipswitch.pdf" },
      { name: "M300 Slipswitch Manual", type: "PDF", url: B + "technical-support/product-manuals/speed-switches/M300-manual.pdf" },
    ],
    accessories: ["whirligig"],
    partNumbers: ["M300-2W", "M300-5W"],
  },
  {
    id: "speedmaster",
    subcategory: "speed",
    name: "SpeedMaster™",
    trademark: "SpeedMaster™",
    image: IMG + "speed-switches/speedmaster.jpg",
    description: "Speed switch calibration testing tool. Provides exact alarm and shutdown point testing without modifying the sensor assembly.",
    keyFunction: "Speed Switch Calibration & Testing Tool",
    features: [
      "Speed Switch Calibration Testing",
      "Exact Alarm & Shutdown Point Testing",
      "No Need To Modify Sensor Assembly For Testing",
    ],
    approvals: [],
    applications: ["Testing & Maintenance", "M800 Elite", "M300 Slipswitch", "Milli-Speed"],
    source_url: B + "products/speed-switches/speedmaster.asp",
    downloads: [
      { name: "SpeedMaster Datasheet", type: "PDF", url: B + "datasheets/speedmaster.pdf" },
    ],
    accessories: [],
    partNumbers: ["SPEEDMASTER"],
  },

  // ── TEMPERATURE SENSORS ───────────────────────────────────────────────────
  {
    id: "milli-vib",
    subcategory: "temperature",
    name: "Milli-Vib Vibration Sensor",
    trademark: null,
    image: IMG + "temperature-sensors/Milli-Vib_Web_Thumbnail_Red_Background.jpg",
    description: "Analog vibration sensor with 4-20 mA output. RMS Velocity 0-25 mm/s standard (0-50 mm/s available). 304 stainless steel body with 3/4\" male conduit threads. 1/4\"-28 UNF female mounting threads with thread adaptor.",
    keyFunction: "4-20 mA Vibration Monitoring — RMS Velocity",
    features: [
      "Analog with 4-20 mA Output",
      "RMS Velocity 0-25 mm/s Standard (0-50 mm/s Available)",
      "304 Stainless Steel Body (3/4\" Male Conduit Threads)",
      "1/4\"-28 UNF Female Mounting Threads with Thread Adaptor",
    ],
    approvals: ["MET", "ATEX", "CE"],
    applications: ["Bearing Monitoring", "Predictive Maintenance", "Conveyor Drives", "Fans & Blowers"],
    source_url: B + "products/temperature-sensors/Milli-Vib.asp",
    downloads: [
      { name: "Milli-Vib Datasheet", type: "PDF", url: B + "datasheets/Milli-Vib-datasheet.pdf" },
    ],
    accessories: [],
    partNumbers: ["MILLI-VIB"],
  },
  {
    id: "adb-bearing-sensor",
    subcategory: "temperature",
    name: "ADB Series Bearing Temperature Sensor",
    trademark: null,
    image: IMG + "temperature-sensors/adb_bearing_temperature_sensor.jpg",
    description: "Digital NTC and PT100 RTD bearing temperature sensor. Adjustable depth temperature probe screws into existing grease zerk location with integrated zerk for continued bearing lubrication. 304 stainless steel body with 1/2\" NPT conduit entry.",
    keyFunction: "Bearing Temperature — NTC / PT100 RTD — Grease Zerk Mount",
    features: [
      "Digital NTC and PT100 RTD Versions",
      "Adjustable Depth Temperature Probe",
      "Screws Into Existing Grease Zerk Location",
      "Integrated Zerk For Bearing Lubrication",
      "304 Stainless Steel Body (1/2\" NPT Conduit Entry)",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevator Bearings", "Conveyor Bearings", "Grain Handling", "Milling"],
    source_url: B + "products/temperature-sensors/adb-bearing-sensor.asp",
    downloads: [
      { name: "ADB Series Datasheet", type: "PDF", url: B + "datasheets/adb-bearing-temperature-sensor.pdf" },
      { name: "ADB Series Manual", type: "PDF", url: B + "technical-support/product-manuals/temperature-sensors/adb-manual.pdf" },
    ],
    accessories: ["adb-tester"],
    partNumbers: ["ADB-NTC", "ADB-PT100"],
  },
  {
    id: "milli-temp",
    subcategory: "temperature",
    name: "Milli-Temp Series Bearing Temperature Sensor",
    trademark: "Milli-Temp™",
    image: IMG + "temperature-sensors/milli-temp-sensor.jpg",
    description: "Analog 4-20 mA bearing temperature sensor. Adjustable depth probe screws into existing grease zerk location with integrated zerk for continued lubrication. 304 stainless steel body with 1/2\" NPT conduit entry.",
    keyFunction: "4-20 mA Bearing Temperature — Grease Zerk Mount",
    features: [
      "Analog with 4-20 mA Output",
      "Adjustable Depth Temperature Probe",
      "Screws Into Existing Grease Zerk Location",
      "Integrated Zerk For Bearing Lubrication",
      "304 Stainless Steel Body (1/2\" NPT Conduit Entry)",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevator Bearings", "Conveyor Bearings", "Grain Handling"],
    source_url: B + "products/temperature-sensors/milli-temp-bearing-sensor.asp",
    downloads: [
      { name: "Milli-Temp Datasheet", type: "PDF", url: B + "datasheets/milli-temp-bearing-sensor.pdf" },
    ],
    accessories: ["adb-tester"],
    partNumbers: ["MT-4-20"],
  },
  {
    id: "adb-tester",
    subcategory: "temperature",
    name: "ADB & Milli-Temp Bearing Sensor Tester",
    trademark: null,
    image: IMG + "temperature-sensors/adb-tester.jpg",
    description: "Portable diagnostic tool for ADB and Milli-Temp bearing temperature sensors. Provides exact alarm and shutdown point testing. Hand held unit with easy-to-read OLED display.",
    keyFunction: "Portable Diagnostic Tester for ADB & Milli-Temp Sensors",
    features: [
      "Diagnostic Tool for ADB and Milli-Temp Bearing Sensors",
      "Hand Held Portable Unit",
      "Exact Alarm Point Testing",
      "Exact Shutdown Point Testing",
      "Easy To Read OLED Display",
    ],
    approvals: [],
    applications: ["Testing & Maintenance", "ADB Series Sensors", "Milli-Temp Series Sensors"],
    source_url: B + "products/temperature-sensors/adb-tester.asp",
    downloads: [],
    accessories: [],
    partNumbers: ["ADB-TESTER"],
  },
  {
    id: "adb-lug",
    subcategory: "temperature",
    name: "ADB Lug Series Surface Temperature Sensor",
    trademark: null,
    image: IMG + "hazard-monitors/ADB_LUG_SENSOR_web_image_red.jpg",
    description: "Surface mount installation temperature sensor for continuous temperature monitoring. Available in NTC, PT100 RTD, or 4-20 mA versions. CSA approved. 3/8\" to 1/2\" bolt entry with 1/2\" NPT conduit entry.",
    keyFunction: "Surface Mount Temperature Monitoring — Bolted Installation",
    features: [
      "Surface Mount Installation",
      "NTC, PT100 RTD, or 4-20 mA Versions",
      "Continuous Temperature Monitoring",
      "3/8\" to 1/2\" Bolt Entry",
      "1/2\" NPT Conduit Entry",
    ],
    approvals: ["CSA"],
    applications: ["Drive Shafts", "Belt Surfaces", "Housing Surfaces", "Conveyor Equipment"],
    source_url: B + "products/temperature-sensors/adb-lug.asp",
    downloads: [
      { name: "ADB Lug Datasheet", type: "PDF", url: B + "datasheets/adb-lug-surface-temperature-sensor.pdf" },
    ],
    accessories: [],
    partNumbers: ["ADB-LUG-NTC", "ADB-LUG-PT100", "ADB-LUG-420"],
  },
  {
    id: "wdb1-wdb2",
    subcategory: "temperature",
    name: "WDB1 & WDB2 Series Bearing Temperature Sensors",
    trademark: null,
    image: IMG + "hazard-monitors/wdb1_2_series_sensors.jpg",
    description: "NTC, PTC and RTD PT100 bearing temperature sensors. Screw into existing grease zerk location with integrated zerk for continued lubrication. WDB1 — Brass body (no conduit entry). WDB2 — 304 Stainless steel body with 1/2\" NPT conduit entry.",
    keyFunction: "Bearing Temperature — NTC/PTC/PT100 — Brass or Stainless Body",
    features: [
      "NTC, PTC and RTD PT100 Versions",
      "Screws Into Existing Grease Zerk Location",
      "Integrated Zerk For Bearing Lubrication",
      "WDB1 — Brass Body (No Conduit Entry)",
      "WDB2 — 304 Stainless Steel Body (1/2\" NPT Conduit Entry)",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Bucket Elevator Bearings", "Conveyor Bearings", "Industrial Bearings"],
    source_url: B + "products/temperature-sensors/wdb1-wdb2-bearing-sensors.asp",
    downloads: [
      { name: "WDB1 & WDB2 Datasheet", type: "PDF", url: B + "datasheets/wdb1-wdb2-bearing-sensors.pdf" },
    ],
    accessories: [],
    partNumbers: ["WDB1-NTC", "WDB1-PTC", "WDB1-PT100", "WDB2-NTC", "WDB2-PTC", "WDB2-PT100"],
  },

  // ── LEVEL INDICATORS ──────────────────────────────────────────────────────
  {
    id: "auto-set",
    subcategory: "level",
    name: "Auto-Set™",
    trademark: "Auto-Set™",
    image: IMG + "level-indicators/auto-set-level-indicator.jpg",
    description: "Radio Frequency (RF) level indicator with fail-safe operation. Push button calibration with digital display and internal timer. Power Shield compensates for material build up. Probe lengths from 3 inches to 33 feet.",
    keyFunction: "RF Level Indicator — Push Button Calibration — 3\" to 33' Probes",
    features: [
      "Radio Frequency (RF) Level Indicator",
      "Fail-Safe",
      "Push Button Calibration",
      "Digital Display and Internal Timer",
      "Power Shield Compensates for Material Build Up",
      "3 Inch to 33 Foot Probe Lengths",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Grain Bins", "Silos", "Tanks", "Chutes", "Conveyors", "Elevator Legs"],
    source_url: B + "products/level-indicators/auto-set-level-indicator.asp",
    downloads: [
      { name: "Auto-Set Datasheet", type: "PDF", url: B + "datasheets/auto-set-rf-level-indicator.pdf" },
      { name: "Auto-Set Manual", type: "PDF", url: B + "technical-support/product-manuals/level-indicators/auto-set-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["AS100"],
  },
  {
    id: "auto-set-remote",
    subcategory: "level",
    name: "Auto-Set™ Remote",
    trademark: "Auto-Set™",
    image: IMG + "level-indicators/auto-set-remote-level-indicator.jpg",
    description: "RF level indicator ideal for high temperature and vibration applications. Remote electronics separate from the probe. Fail-safe with push button calibration, digital display and internal timer. Power Shield compensates for material build up. Probe lengths from 3 inches to 33 feet.",
    keyFunction: "RF Level Indicator — Remote Electronics — High Temp/Vibration",
    features: [
      "Radio Frequency (RF) Level Indicator",
      "Ideal for High Temperature and Vibration Applications",
      "Fail-Safe and Push Button Calibration",
      "Digital Display and Internal Timer",
      "Power Shield Compensates for Material Build Up",
      "3 Inch to 33 Foot Probe Lengths",
    ],
    approvals: ["ATEX", "CE"],
    applications: ["High Temperature Bins", "Vibrating Conveyors", "Silos", "Dryers"],
    source_url: B + "products/level-indicators/auto-set-remote-level-indicator.asp",
    downloads: [
      { name: "Auto-Set Remote Datasheet", type: "PDF", url: B + "datasheets/auto-set-remote-rf-level-indicator.pdf" },
    ],
    accessories: [],
    partNumbers: ["AS-REMOTE"],
  },
  {
    id: "auto-set-flush",
    subcategory: "level",
    name: "Auto-Set™ Flush Probe",
    trademark: "Auto-Set™",
    image: IMG + "level-indicators/auto-set-flush-probe-level-indicator.jpg",
    description: "RF level indicator ideal for low profile applications where standard probes cannot be used. Fail-safe with push button calibration, digital display and internal timer. Power Shield compensates for material build up.",
    keyFunction: "RF Level Indicator — Flush Probe — Low Profile Applications",
    features: [
      "Radio Frequency (RF) Level Indicator",
      "Ideal for Low Profile Applications",
      "Fail-Safe and Push Button Calibration",
      "Digital Display and Internal Timer",
      "Power Shield Compensates for Material Build Up",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Low Profile Bins", "Hoppers", "Chutes", "Tight Space Applications"],
    source_url: B + "products/level-indicators/auto-set-flush-probe.asp",
    downloads: [
      { name: "Auto-Set Flush Probe Datasheet", type: "PDF", url: B + "datasheets/auto-set-flush-probe-level-indicator.pdf" },
    ],
    accessories: [],
    partNumbers: ["AS-FLUSH"],
  },
  {
    id: "rli-shaker",
    subcategory: "level",
    name: "RLI \"SHAKER\"",
    trademark: null,
    image: IMG + "level-indicators/rli-shaker-rotary-level-indicator.jpg",
    description: "Rotary paddle level indicator with unique shaking action for shedding material build-up. User adjustable torque control. Direct stepper motor drive (no clutch or gearbox). Fail-safe rotation detection. Vertical extensions up to 14 feet.",
    keyFunction: "Rotary Paddle Level — Anti-Build-Up Shaking Action",
    features: [
      "Rotary Paddle Level Indicator",
      "Unique Shaking Action for Shedding Material Build Up",
      "User Adjustable Torque Control",
      "Direct Stepper Motor Drive (No Clutch or Gearbox)",
      "Fail-Safe Rotation Detection",
      "14 Foot Vertical Extensions (Maximum)",
    ],
    approvals: ["ATEX"],
    applications: ["Powders", "Free-Flowing Granular Solids", "Sticky Materials", "Silos", "Bins"],
    source_url: B + "products/level-indicators/rli-shaker-rotary-paddle-level-indicator.asp",
    downloads: [
      { name: "RLI Shaker Datasheet", type: "PDF", url: B + "datasheets/rli-shaker-rotary-level-indicator.pdf" },
    ],
    accessories: [],
    partNumbers: ["RLI-SHAKER"],
  },
  {
    id: "roto-safe",
    subcategory: "level",
    name: "Roto-Safe™",
    trademark: "Roto-Safe™",
    image: IMG + "level-indicators/roto-safe-rotary-level-indicator.jpg",
    description: "Rotary paddle level indicator with CSA and ATEX dust hazard approval. Designed for detecting high, intermediate, or low levels of liquids, powders and free flowing granular solids.",
    keyFunction: "CSA/ATEX Rotary Paddle Level Indicator",
    features: [
      "Rotary Paddle Level Indicator",
      "Dust Hazard Approved (CSA)",
      "Fail-Safe Design",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Grain Bins", "Feed Mills", "Flour Mills", "Silos", "Hoppers"],
    source_url: B + "products/level-indicators/roto-safe-rotary-paddle-level-indicator.asp",
    downloads: [
      { name: "Roto-Safe Datasheet", type: "PDF", url: B + "datasheets/roto-safe-level-indicator.pdf" },
    ],
    accessories: [],
    partNumbers: ["ROTO-SAFE"],
  },

  // ── INDUCTIVE SENSORS ─────────────────────────────────────────────────────
  {
    id: "p100-proxswitch",
    subcategory: "inductive",
    name: "P100 Proxswitch — 18 mm",
    trademark: null,
    image: IMG + "inductive/p100_sensor.jpg",
    description: "18 mm inductive proximity sensor for no-contact detection of shaft speed, shaft/gate position or object presence. Totally sealed (submersible). 5/16\" (8 mm) detection range for ferrous targets. Easy installation with Whirligig® sensor mount.",
    keyFunction: "18 mm Inductive Proximity — Shaft Speed & Position Detection",
    features: [
      "Detects Shaft Speed, Shaft/Gate Position or Object Presence",
      "No Contact Monitoring",
      "Totally Sealed Construction (Submersible)",
      "5/16\" (8 mm) Detection Range — Ferrous Target",
      "Easy Installation with Whirligig® Sensor Mount",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Shaft Speed Monitoring", "Gate Position", "Object Presence", "All Rotating Machinery"],
    source_url: B + "products/inductive-sensors/p100-proxswitch.asp",
    downloads: [
      { name: "P100 Proxswitch Datasheet", type: "PDF", url: B + "datasheets/p100-proxswitch.pdf" },
    ],
    accessories: ["whirligig"],
    partNumbers: ["P100"],
  },
  {
    id: "p300-proxswitch",
    subcategory: "inductive",
    name: "P300 Proxswitch — 30 mm",
    trademark: null,
    image: IMG + "inductive/p300_sensor.jpg",
    description: "30 mm inductive proximity sensor for no-contact detection of shaft speed, shaft/gate position or object presence. Totally sealed (submersible). 11/32\" (9 mm) detection range for ferrous targets. LED status indication for target detection.",
    keyFunction: "30 mm Inductive Proximity — LED Status Indication",
    features: [
      "Detects Shaft Speed, Shaft/Gate Position or Object Presence",
      "No Contact Monitoring",
      "Totally Sealed Construction (Submersible)",
      "11/32\" (9 mm) Detection Range — Ferrous Target",
      "LED Status Indication for Target Detection",
      "Easy Installation with Whirligig® Sensor Mount",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Shaft Speed Monitoring", "Gate Position", "Object Presence"],
    source_url: B + "products/inductive-sensors/p300-proxswitch.asp",
    downloads: [
      { name: "P300 Proxswitch Datasheet", type: "PDF", url: B + "datasheets/p300-proxswitch.pdf" },
    ],
    accessories: ["whirligig"],
    partNumbers: ["P300"],
  },
  {
    id: "p800-proxswitch",
    subcategory: "inductive",
    name: "P800 Proxswitch — DIN Style",
    trademark: null,
    image: IMG + "inductive/P800-Proxswitch-1-2.jpg",
    description: "DIN style inductive proximity sensor. Totally sealed (submersible). 1/2\" (12 mm) detection range for ferrous targets. LED status indication. Integrated 1/2\" NPT conduit entry. Easy installation with Whirligig® sensor mount.",
    keyFunction: "DIN Style Inductive Proximity — 12 mm Range — Integrated Conduit",
    features: [
      "Detects Shaft Speed, Shaft/Gate Position or Object Presence",
      "Totally Sealed Construction (Submersible)",
      "1/2\" (12 mm) Detection Range — Ferrous Target",
      "LED Status Indication for Target Detection",
      "Integrated 1/2\" NPT Conduit Entry",
      "Easy Installation with Whirligig® Sensor Mount",
    ],
    approvals: ["CSA"],
    applications: ["Shaft Speed Monitoring", "Gate Position", "Industrial Applications"],
    source_url: B + "products/inductive-sensors/p800-proxswitch.asp",
    downloads: [
      { name: "P800 Proxswitch Datasheet", type: "PDF", url: B + "datasheets/p800-proxswitch.pdf" },
    ],
    accessories: ["whirligig"],
    partNumbers: ["P800"],
  },

  // ── SAFETY SWITCHES ───────────────────────────────────────────────────────
  {
    id: "pullswitch",
    subcategory: "safety",
    name: "Pullswitch",
    trademark: null,
    image: IMG + "pullswitch/pullswitch.jpg",
    description: "Failsafe taut wire emergency pull cord safety stop switch for open conveyors. PVC coated steel pull wire and pigtails connect between switches. IP65 / NEMA 4, 4X, 9 rated polycarbonate enclosure with stainless steel plates. Can be installed at 200 ft. intervals. Six independent changeover contacts.",
    keyFunction: "Taut Wire Emergency Pull Cord Safety Stop — Conveyor E-Stop",
    features: [
      "Designed For Open Conveyors",
      "Corrosion Resistant Weather Tight Housing (IP65 / NEMA 4, 4X, 9)",
      "Unique Taut Wire Failsafe System",
      "Reflector and/or Flag Tripped Indication",
      "Exclusive Double Ended Snap Action Mechanism",
      "CSA Class II Division 1 Groups E, F & G Approved",
      "Installable at 200 ft. Intervals",
    ],
    approvals: ["CSA", "ATEX", "CE"],
    applications: ["Open Conveyors", "Emergency Stop", "Grain Handling", "Mining", "Industrial Conveying"],
    source_url: B + "products/conveyor-safety-switches/default.asp",
    specs: {
      "Enclosure": "UV Protected Polycarbonate and 304 Stainless Steel Plated",
      "Mechanism": "Double Ended Taut Wire",
      "Activation Pull Force": "15.5 lbs. / 69 Newtons (Calculated Average)",
      "Pull Wire Deflection": "9.8 in / 250 mm (Calculated Average)",
      "Contacts": "5 Amps (240 VAC)",
      "Conduit Entries": "Two 1/2\" NPT",
      "Operating Temperature": "-4°F to 131°F (-20°C to 55°C)",
      "Weight": "4 lb. (1.8 kg)",
      "Protection": "IP65 / NEMA 4, 4X, 9",
    },
    downloads: [
      { name: "Pullswitch Datasheet", type: "PDF", url: B + "datasheets/pullswitch-conveyor-safety-stop-switch.pdf" },
      { name: "Pullswitch Manual", type: "PDF", url: B + "technical-support/product-manuals/safety-switches/pullswitch-manual.pdf" },
      { name: "Product Drawing — Single Unit", type: "PDF", url: B + "technical-support/autocad/PST1000C.pdf" },
      { name: "Product Drawing — Single Unit", type: "DWG", url: B + "technical-support/autocad/PST1000C.zip" },
      { name: "Installation — Single Unit (up to 200 ft.)", type: "PDF", url: B + "technical-support/autocad/SINGLE%20PULLSWITCH%20INSTALLATION.pdf" },
      { name: "Installation — Multiple Units (over 200 ft.)", type: "PDF", url: B + "technical-support/autocad/MULTIPLE%20PULLSWITCH%20INSTALLATION.pdf" },
    ],
    accessories: [],
    partNumbers: ["PST1000C", "PTA100 (Tensioner)", "PAS100 (Anchor Spring)", "PWPVCR (PVC Pull Wire)", "PTPVC4 (Pigtail)", "PFK100 (Flag Indicator)"],
  },

  // ── ALARMS & DISPLAYS ─────────────────────────────────────────────────────
  {
    id: "universal-speed-relay",
    subcategory: "alarms",
    name: "Universal Speed Relay",
    trademark: null,
    image: IMG + "Alarms%20and%20Displays/Universal%20Speed%20Relay_Product%20Thumbnail.jpg",
    description: "Sensor input speed relay with 0.1 to 1,000 Hz range (6 to 60,000 ppm). Dual outputs: mechanical (30 VDC / 250 VAC, 2.5A) and solid-state relay (230 V AC/DC, 100 mA). Full color 160x80 LCD display with 2 LED indicators. Multi voltage power supply (18–28 VDC or 85–264 VAC). Start delay programmable up to 100 seconds.",
    keyFunction: "Universal Speed Relay — Dual Output — Full Color LCD",
    features: [
      "Sensor Input Speed Range from 0.1 to 1,000 Hz (6 to 60,000 ppm)",
      "Dual Outputs: Mechanical 30 VDC / 250 VAC, 2.5 A Max and Solid-State Relay 230 V AC/DC, 100 mA",
      "Full Color 160x80 LCD Display and 2 LED Indicators",
      "Multi Voltage Power Supply: +18 to +28 VDC or 85 to 264 VAC",
      "Start Delay Programmable Up To 100 Seconds",
      "24 VDC Available When Powered by AC Voltage",
      "Interlock Input 18 to 28 VDC / 85 to 264 VAC",
    ],
    approvals: [],
    applications: ["Speed Monitoring", "Conveyor Control", "PLC Integration", "All Rotating Machinery"],
    source_url: B + "products/alarms-and-displays/Universal%20Speed%20Relay.asp",
    downloads: [
      { name: "Universal Speed Relay Datasheet", type: "PDF", url: B + "datasheets/Universal%20Speed%20Relay_Datasheet_121324.pdf" },
      { name: "Universal Speed Relay Manual", type: "PDF", url: B + "technical-support/product-manuals/Alarms%20and%20Displays/Speed%20Relay_Manual_071025.pdf" },
    ],
    accessories: [],
    partNumbers: ["USR"],
  },
  {
    id: "tacho-display",
    subcategory: "alarms",
    name: "Tacho — Digital Tachometer",
    trademark: null,
    image: IMG + "hazard-monitors/tacho_red.jpg",
    description: "Panel-mounting DIN style meter capable of use as a tachometer or timer. High visibility 6-digit vacuum fluorescent display. Accepts wide range of sensor inputs including M800, Whirligig + proximity switch. User/factory programmable. Output displayed in real engineering units.",
    keyFunction: "DIN Panel Tachometer — 6-Digit VF Display",
    features: [
      "Panel-Mounting DIN Style Meter (Tachometer or Timer)",
      "High Visibility 6-Digit Vacuum Fluorescent Display",
      "Accepts M800, Whirligig + Proximity Switch Inputs",
      "User/Factory Programmable",
      "Output Displayed in Real Engineering Units",
    ],
    approvals: [],
    applications: ["Speed Display", "Panel Mounting", "Conveyor Monitoring", "Tachometer Applications"],
    source_url: B + "products/alarms-and-displays/default.asp",
    downloads: [
      { name: "Tacho Datasheet", type: "PDF", url: B + "datasheets/tacho-display.pdf" },
      { name: "Tacho Manual (TACH3V5)", type: "PDF", url: B + "technical-support/product-manuals/speed-switches/TACH3V5%20Manual%20V2.pdf" },
    ],
    accessories: ["m800-elite", "whirligig"],
    partNumbers: ["TACH3V5"],
  },
  {
    id: "x400-alarm",
    subcategory: "alarms",
    name: "X400 Elite — Alarm Monitoring System",
    trademark: null,
    image: IMG + "hazard-monitors/X400_alarmswitch.jpg",
    description: "Alarm monitoring system with alarm indication panel and external alarm horn. For use with level indicators, hazard controls and limit switch devices. Microprocessor controlled — monitors up to 8 alarm zones. Dust hazard approved.",
    keyFunction: "8-Zone Alarm Monitoring — Dust Hazard Approved",
    features: [
      "Alarm Monitoring System",
      "Alarm Indication Panel with External Alarm Horn",
      "For Use with Level Indicators, Hazard Controls and Limit Switch Devices",
      "Microprocessor Unit Monitors Up to 8 Alarm Zones",
      "Dust Hazard Approved",
    ],
    approvals: ["CSA"],
    applications: ["Level Monitoring", "Hazard Control", "Limit Switch Monitoring", "Grain Handling", "Milling"],
    source_url: B + "products/alarms-and-displays/default.asp",
    downloads: [
      { name: "X400 Datasheet", type: "PDF", url: B + "datasheets/x400-alarmswitch.pdf" },
      { name: "X400 Elite Manual", type: "PDF", url: B + "technical-support/product-manuals/x400-alarmswitch/x400-manual.pdf" },
    ],
    accessories: [],
    partNumbers: ["X400"],
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────
export function getProductsBySubcategory(key) {
  return PRODUCTS.filter(p => p.subcategory === key);
}

export function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

export function getSubcategoryByKey(key) {
  return SUBCATEGORIES.find(s => s.key === key) || null;
}

export function getAccessoryProducts(product) {
  if (!product.accessories || !product.accessories.length) return [];
  return product.accessories.map(id => getProductById(id)).filter(Boolean);
}