// ─────────────────────────────────────────────────────────────────────────────
// Intralox Modular Plastic Belting — 2026 Catalog Data
// Source: 2026 Intralox MPB Engineering Manual + Belt Finder
// All specs sourced from official Intralox publications. No data invented.
// ─────────────────────────────────────────────────────────────────────────────

export const INTRALOX_LOGO_ICON = "https://www.intralox.com/assets/img/intralox-logo.png";
export const MPB_MANUAL_URL = "https://assets-us-01.kc-usercontent.com/19eb64b5-1815-003a-d268-e7109927ccad/b2679b1e-559b-4919-b559-6992adc8b1f3/5012156.4%202026%20MPB%20Engineering%20Manual.pdf";
const INTRALOX_RED = "#E31837";

// ── Belt Material Reference ───────────────────────────────────────────────────
export const BELT_MATERIALS = {
  PP:  { label: "Polypropylene",              abbr: "PP",  tempF: "34 to 220",   tempC: "1 to 104",    notes: "General purpose, FDA-compliant" },
  PE:  { label: "Polyethylene",               abbr: "PE",  tempF: "-50 to 150",  tempC: "-46 to 66",   notes: "Low-temp, chemical resistant" },
  AC:  { label: "Acetal",                     abbr: "AC",  tempF: "-50 to 200",  tempC: "-46 to 93",   notes: "High-strength, low friction" },
  NY:  { label: "Nylon",                      abbr: "NY",  tempF: "-50 to 240",  tempC: "-46 to 116",  notes: "High temp, high strength" },
  HHR: { label: "HHR Nylon",                  abbr: "HHR", tempF: "-50 to 310",  tempC: "-46 to 154",  notes: "Highest heat resistance" },
  PK:  { label: "PK",                         abbr: "PK",  tempF: "-40 to 176",  tempC: "-40 to 80",   notes: "Chemical resistant" },
  DPP: { label: "Detectable Polypropylene A22",abbr: "DPP", tempF: "0 to 150",   tempC: "-18 to 66",   notes: "Metal/X-ray detectable" },
  XAC: { label: "X-ray Detectable Acetal",    abbr: "XAC", tempF: "-50 to 200",  tempC: "-46 to 93",   notes: "X-ray and metal detectable" },
};

// ── Image helpers — official Intralox Kentico CDN ────────────────────────────
const CDN = "https://assets-us-01.kc-usercontent.com/19eb64b5-1815-003a-d268-e7109927ccad/";

// Correct Belt Finder surface images per series (from official Intralox Belt Finder)
const IMG = {
  S100:  CDN + "bed9dd72-5ea8-41ab-9208-ca6e50f7a23a/5014239_DTA27732_S100-Flush-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S200:  CDN + "e2b82e52-3ebb-4478-a849-383da180a232/5014239_DTA28936_S200-Open-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S400:  CDN + "b3a9b599-f6fe-4f13-9bc4-4660f1ada7e1/5014239_DSCF1506_S400-Flush-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S560:  CDN + "a1838535-8d2c-4677-8b8a-528c2de70eb9/5009284_DSCF4450_S560-Flat-Top-surface-no-annotation.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S570:  CDN + "c79ee694-7862-4ac4-b9f0-0f71d5ebd811/5014109_DSCF1624_S570-Flat-Top_surface-top_cropped_no_annotation.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S800:  CDN + "20a32c1d-5b99-4e99-a557-8390dbcab9d1/5014239_DSCF2195_S800-Flat-Top_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S850:  CDN + "f77767f9-2c60-47dd-a40c-7a9aee558eed/202292_850surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S888:  CDN + "db0e58e6-a240-41ba-a8ba-c7dc9c1c7278/53479_Surface_IMG_6577.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S900:  CDN + "837cac22-0a98-48c7-8163-a606b20909ab/5014239_DTA29161_S900-Open-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1000: CDN + "881a2be5-0d02-48a1-b3b8-7a28fd010870/202388_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1100: CDN + "2f810594-c293-4f51-8d91-232a81c06b9d/5014239_DTA28209_S1100-Flush-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1200: CDN + "3deb47ca-f531-4689-98c0-812f2d086bb5/5014239_12DTA28337_S1200-Flush-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1400: CDN + "11234f48-bef8-40a6-8e02-559739e85ed5/201052_color-LPedit_S1400-Flat-Top_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1500: CDN + "713b1718-17c3-4fd9-b99f-8743f6fd351f/5014239_DSCF3823_S1500-Blue-PK_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1600: CDN + "d827166f-f3fd-4b75-9df3-a3899f5141ef/5014239_DTA28805_S1600-Open-Hinge-Flat-Top_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1650: CDN + "5605cf88-b97b-4b8c-a532-500fc65fa0f3/202383_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1700: CDN + "e52082ab-e275-447e-9700-9081080a7c46/202074-ts_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1750: CDN + "d2f2f044-6e30-44d3-9572-e501cffaafbe/5002546_IMG_3770_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1800: CDN + "20a32c1d-5b99-4e99-a557-8390dbcab9d1/5014239_DSCF2195_S800-Flat-Top_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S1900: CDN + "d0dea248-1e70-42d8-991f-0fdfe1b7cb5f/202303surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2100: CDN + "61313927-cc44-468c-a800-2b1053654a7e/5000180_P1470067.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2200: CDN + "41ff3bce-91cd-4867-8017-dab5c73c7d59/5014239_DTA29940_S2200-Radius-Flush-Grid_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2300: CDN + "102f5bdc-8c68-477e-83fe-2d743dd5622a/5001046_IMG_9855_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2400: CDN + "51f69ab6-7066-4a57-821d-b41a04ef68ee/5014239_DTA29740_S2400-Tight-Turning-Radius_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2600: CDN + "93ab759a-7e0e-4205-9486-66a743decde8/5014239_DSCF3280_S2600-Spiral-3.2_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2700: CDN + "79a9409f-5e55-4c50-8448-b026b488654d/202212surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2800: CDN + "93ab759a-7e0e-4205-9486-66a743decde8/5014239_DSCF3280_S2600-Spiral-3.2_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2900: CDN + "93ab759a-7e0e-4205-9486-66a743decde8/5014239_DSCF3280_S2600-Spiral-3.2_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  S2950: CDN + "93ab759a-7e0e-4205-9486-66a743decde8/5014239_DSCF3280_S2600-Spiral-3.2_Surface_cropped.jpg?w=568&h=298&fit=crop&q=85&auto=format",
  // Style counts from Belt Finder (accurate)
  STYLE_COUNTS: { S100:2,S200:3,S400:13,S560:2,S570:1,S800:21,S850:2,S888:4,S900:23,S1000:13,S1100:10,S1200:5,S1400:18,S1500:2,S1600:8,S1650:1,S1700:3,S1750:1,S1800:4,S1900:1,S2100:1,S2200:6,S2300:5,S2400:17,S2600:6,S2700:7,S2800:5,S2900:4,S2950:3,S3000:4,S4000:3,S4400:2,S4500:2,S9000:2,S10000:2 },
};

// ── STRAIGHT-RUNNING SERIES ───────────────────────────────────────────────────
export const STRAIGHT_SERIES = [
  {
    id: "S100",
    name: "Series 100",
    beltType: "Straight-Running",
    pitch_in: 0.333,
    pitch_mm: 8.47,
    catalogPage: 33,
    image: IMG.S100,
    description: "Ultra-small 1/3-inch pitch belt for tight transfers and precision conveying of small parts. Very fine pitch reduces chordal action for smooth, quiet operation.",
    applications: ["Small parts conveying", "Can & bottle handling", "Tight transfers", "Packaging lines", "Electronics assembly"],
    advantages: ["1/3-in pitch — smallest in Intralox line", "Smooth quiet operation", "Tight transfer over very small nosebars", "Wide material selection"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 33. Contact Uniking for sprocket selection.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-100" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "33",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: CDN + "d5243989-0dde-4c19-99cf-ed3f8774b8d4/5004310_P1070334_16-9_darken15.jpeg?w=568&h=298.2&rect=0,0,2400,1350&fit=&q=85&auto=format", description: "Smooth closed-surface ultra-small pitch belt.", applications: ["Small parts", "Packaging", "Electronics"], beltData: "To be confirmed by Uniking", notes: ["1/3-in (8.47 mm) pitch."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~30%", surface: "Open Grid", image: null, description: "Open flush grid for drainage and airflow at very small pitch.", applications: ["Drainage", "Airflow", "Visibility"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S200",
    name: "Series 200",
    beltType: "Straight-Running",
    pitch_in: 0.50,
    pitch_mm: 12.7,
    catalogPage: 41,
    image: IMG.S200,
    description: "1/2-inch pitch versatile belt with many surface styles for food processing, packaging, and general conveying applications.",
    applications: ["Food processing", "Packaging", "General conveying", "Accumulation", "Sorting"],
    advantages: ["1/2-in pitch for tight transfers", "Wide surface variety", "FDA-compliant materials available", "Multiple material options"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 41. Contact Uniking.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-200" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "41",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth 1/2-inch pitch flat top belt.", applications: ["General conveying", "Packaging"], beltData: "To be confirmed by Uniking", notes: ["0.50 in (12.7 mm) pitch."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~38%", surface: "Open Grid", image: null, description: "Open grid for drainage and airflow.", applications: ["Drainage", "Cooling"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S400",
    name: "Series 400",
    beltType: "Straight-Running",
    pitch_in: 0.50,
    pitch_mm: 12.7,
    catalogPage: 49,
    image: IMG.S400,
    description: "1/2-inch pitch heavy-duty belt for sorting, accumulation and incline applications. Available in many surface styles including ribbed, side-flexing, and grip variants.",
    applications: ["Sorting & Accumulation", "Small parts conveying", "Inclines", "Tight transfers", "Can conveying"],
    advantages: ["1/2-in pitch for tight transfers", "Many surface styles", "Multiple material options", "Suitable for inclines"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 49+. Contact Uniking.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-400" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "49",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth closed 1/2-inch pitch belt.", applications: ["Small parts", "Sorting", "Accumulation"], beltData: "To be confirmed by Uniking", notes: ["0.50 in (12.7 mm) pitch."] },
      { key: "ribbed_top", label: "Ribbed Top", openArea: "0%", surface: "Ribbed", image: null, description: "Ribbed surface for improved grip on inclines.", applications: ["Inclines", "Declines", "Grip conveying"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S560",
    name: "Series 560",
    beltType: "Straight-Running",
    pitch_in: 0.60,
    pitch_mm: 15.2,
    catalogPage: 77,
    image: IMG.S560,
    description: "0.60-inch pitch high-friction, high-grip belt for reliable product handling on inclines and declines. Ideal for accumulation and tight-transfer applications.",
    applications: ["Inclines & declines", "Accumulation conveying", "Tight transfers", "Slip-resistant conveying"],
    advantages: ["High-friction surface options", "0.60-in pitch", "FDA-compliant materials", "Multiple grip-style variants"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 77. Contact Uniking.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-560" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "77",
    styles: [
      { key: "friction_top", label: "Friction Top", openArea: "0%", surface: "Friction / Grip", image: null, description: "High-friction top surface for incline and decline applications.", applications: ["Inclines", "Declines"], beltData: "To be confirmed by Uniking", notes: ["Rubber friction inserts available."] },
    ],
  },
  {
    id: "S570",
    name: "Series 570",
    beltType: "Straight-Running",
    pitch_in: 0.60,
    pitch_mm: 15.2,
    catalogPage: 83,
    image: IMG.S570,
    description: "0.60-inch pitch low-backpressure and accumulation belt with excellent release properties. Designed for gentle product handling at tight transfers.",
    applications: ["Accumulation conveying", "Gentle product handling", "Low-backpressure lines", "Packaging"],
    advantages: ["Low-friction surface variants", "0.60-in pitch tight transfers", "Gentle on products", "Multiple surface styles"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 83. Contact Uniking.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-570" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "83",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth 0.60-inch pitch belt for gentle accumulation.", applications: ["Accumulation", "Packaging"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S800",
    name: "Series 800",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 87,
    min_width_in: 2,
    min_width_mm: 51,
    width_increment_in: 0.66,
    width_increment_mm: 16.8,
    rod_dia_in: 0.24,
    rod_dia_mm: 6.1,
    rod_retention: "Snap-lock; headed",
    hinge: "Open",
    image: IMG.S800,
    description: "Intralox's time-tested, industry-leading belt for meat and poultry processing. 2-inch pitch snap-lock design handles the toughest food-processing environments.",
    applications: ["Meat & Poultry Processing", "Food Processing", "Dairy", "Direct Food Contact", "Abrasive Products"],
    advantages: ["Snap-lock rod retention for easy replacement", "Closed surface prevents product loss", "Drive bar guides water/debris away", "Abrasion-resistant link design", "Flights and sideguards available"],
    sprockets: [
      { name: "CleanLock™ Sprockets", material: "Acetal / Polypropylene", notes: "2026 Hygienic Design Award winner. Improved sanitation in food processing.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-800/cleanlocktm-sprockets" },
      { name: "EZ Clean™ Sprocket", material: "Acetal", notes: "Open-spoke design for easy cleaning and inspection.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-800/ez-cleantm-sprocket" },
      { name: "Molded Acetal Sprocket", material: "Acetal", notes: "Standard molded acetal sprocket for Series 800.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-800/molded-sprocket" },
      { name: "Molded Polypropylene Sprocket", material: "Polypropylene", notes: "Standard molded polypropylene sprocket.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-800/molded-polypropylene-sprocket" },
      { name: "Abrasion Resistant Split Metal Sprockets", material: "Metal", notes: "High-wear environments. Split design.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-800/abrasion-resistant-split-metal-sprockets" },
    ],
    accessories: [
      { name: "Flights", type: "flight", notes: "Available for Series 800. Contact Uniking for details." },
      { name: "Sideguards", type: "sideguard", notes: "Available for Series 800. Contact Uniking for details." },
    ],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "87",
    styles: [
      {
        key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth",
        image: CDN + "2533dfe1-7249-4133-a3db-628335811ba6/5014239_DSCF1947_S800%20Molded%20Sprocket.jpg?w=568&h=298.2&rect=0,442,6240,3276&fit=&q=85&auto=format",
        description: "Impact-resistant flat top belt for direct food-contact applications. Smooth, closed upper surface with fully flush edges.",
        applications: ["Meat & poultry processing", "Slaughter lines", "Direct food contact", "Abrasive applications"],
        beltData: [
          { material: "Polypropylene", rodMaterial: "Polypropylene", strengthLbfFt: 1000, strengthNm: 14600, tempF: "34 to 220", tempC: "1 to 104", massLbFt2: 1.77, massKgM2: 8.66 },
          { material: "Polyethylene", rodMaterial: "Polyethylene", strengthLbfFt: 500, strengthNm: 7300, tempF: "-50 to 150", tempC: "-46 to 66", massLbFt2: 1.87, massKgM2: 9.13 },
          { material: "Acetal", rodMaterial: "Polyethylene", strengthLbfFt: 900, strengthNm: 13100, tempF: "-50 to 150", tempC: "-46 to 66", massLbFt2: 2.75, massKgM2: 13.43 },
          { material: "Nylon", rodMaterial: "Nylon", strengthLbfFt: 1200, strengthNm: 17500, tempF: "-50 to 225", tempC: "-46 to 107", massLbFt2: 2.43, massKgM2: 11.86 },
          { material: "Detectable Polypropylene A22", rodMaterial: "Polyethylene", strengthLbfFt: 650, strengthNm: 9490, tempF: "0 to 150", tempC: "-18 to 66", massLbFt2: 2.21, massKgM2: 10.79 },
        ],
        notes: ["Smooth, closed upper surface with fully flush edges.", "Impact-resistant belt for meat-industry applications.", "Flights and sideguards available."],
      },
      { key: "flush_grid", label: "Flush Grid", openArea: "~45%", surface: "Open Grid", image: CDN + "5caec7b8-a7d6-4445-acb4-ba1cad5e1a6c/5014995_DSCF7337.jpg?w=568&h=298.2&rect=0,442,6240,3276&fit=&q=85&auto=format", description: "High open area grid for maximum drainage and airflow.", applications: ["Blanching", "Cooling", "Baking", "Drainage applications"], beltData: "To be confirmed by Uniking", notes: ["High open area."] },
      { key: "perforated_flat_top", label: "Perforated Flat Top", openArea: "~13%", surface: "Perforated", image: null, description: "Perforated top for drainage while maintaining product support.", applications: ["Drainage", "Washing", "Cooling", "Marinating"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S850",
    name: "Series 850",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 121,
    image: IMG.S850,
    description: "Series 850 is designed specifically for fish and seafood processing with enhanced drainage and cleanability features over Series 800.",
    applications: ["Seafood & fish processing", "Wet food processing", "High-hygiene environments", "Direct food contact"],
    advantages: ["Enhanced drainage vs Series 800", "Snap-lock rod retention", "Easy strip-down cleaning", "Open-hinge design available"],
    sprockets: [
      { name: "EZ Clean™ Angled Sprocket", material: "Acetal", notes: "Angled EZ Clean design for enhanced cleanability.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-850" },
    ],
    accessories: [{ name: "Flights & Sideguards", type: "flight", notes: "Available for Series 850. Contact Uniking." }],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "121",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top for seafood and fish conveying.", applications: ["Seafood processing", "Direct food contact"], beltData: "To be confirmed by Uniking", notes: ["2.00 in (50.8 mm) pitch."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~45%", surface: "Open Grid", image: null, description: "High open area grid for drainage in seafood processing.", applications: ["Drainage", "Seafood processing"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S888",
    name: "Series 888",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 127,
    image: IMG.S888,
    description: "Series 888 offers enhanced strength and wear resistance over Series 800, with a 2-inch pitch design for heavy-duty food processing.",
    applications: ["Heavy food processing", "Meat processing", "High-load applications", "Abrasive environments"],
    advantages: ["Higher strength than S800", "2-in pitch", "Snap-lock retention", "Heavy-duty construction"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 127.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-888" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "127",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "High-strength flat top for heavy food processing.", applications: ["Meat processing", "Heavy food processing"], beltData: "To be confirmed by Uniking", notes: ["2.00 in (50.8 mm) pitch."] },
    ],
  },
  {
    id: "S900",
    name: "Series 900",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 135,
    image: IMG.S900,
    description: "Series 900 offers a 1-inch pitch design for food-processing applications requiring smooth product transfer and easy cleaning in sanitary environments.",
    applications: ["Food processing", "Baking", "Snack food", "Sanitary conveying", "Dairy"],
    advantages: ["1-in pitch", "Sanitary design", "Multiple surface styles", "FDA materials available"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 135.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-900" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "135",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth 1-inch pitch flat top for sanitary food conveying.", applications: ["Food processing", "Dairy", "Baking"], beltData: "To be confirmed by Uniking", notes: ["1.00 in (25.4 mm) pitch."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~40%", surface: "Open Grid", image: null, description: "Open flush grid for drainage and cooling.", applications: ["Drainage", "Cooling", "Baking"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1000",
    name: "Series 1000",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 171,
    min_width_in: 3,
    min_width_mm: 76,
    width_increment_in: 1.00,
    width_increment_mm: 25.4,
    image: IMG.S1000,
    description: "1-inch pitch versatile straight-running belt for general conveying and food processing. Balanced strength and cleanability for medium-duty applications.",
    applications: ["Food Processing", "Beverage", "General Conveying", "Bakery", "Packaging"],
    advantages: ["1-in pitch for balanced strength and flexibility", "Available in wide material range", "Flights and sideguards available"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 171.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1000" }],
    accessories: [{ name: "Flights & Sideguards", type: "flight", notes: "Available. Contact Uniking." }],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "171",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth closed 1-inch pitch belt for food and industrial conveying.", applications: ["Food processing", "Packaging", "General conveying"], beltData: "To be confirmed by Uniking", notes: ["1.00 in (25.4 mm) pitch."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~45%", surface: "Open Grid", image: CDN + "5caec7b8-a7d6-4445-acb4-ba1cad5e1a6c/5014995_DSCF7337.jpg?w=568&h=298.2&rect=0,442,6240,3276&fit=&q=85&auto=format", description: "Open grid for drainage and airflow.", applications: ["Drainage", "Baking", "Cooling", "Blanching"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1100",
    name: "Series 1100",
    beltType: "Straight-Running",
    pitch_in: 0.60,
    pitch_mm: 15.2,
    catalogPage: 191,
    min_width_in: 3,
    min_width_mm: 76,
    width_increment_in: 1.00,
    width_increment_mm: 25.4,
    rod_dia_in: 0.18,
    rod_dia_mm: 4.6,
    rod_retention: "Occluded edge; unheaded",
    hinge: "Open",
    nosebar_in: 0.875,
    nosebar_mm: 22.2,
    image: IMG.S1100,
    description: "Versatile small-pitch belt for tight transfers and general conveying across canmaking, food processing, and packaging. Lightweight with smooth closed surface.",
    applications: ["Canmaking", "Food Processing", "Packaging", "General Conveying", "Tight Transfers"],
    advantages: ["0.60-in pitch reduces chordal action", "Tight transfers over 0.875-in nosebars", "Lightweight smooth surface", "Wide material selection including PK and HHR nylon"],
    sprockets: [
      { name: "EZ Track™ Glass-Filled Nylon Split Sprockets", material: "Glass-Filled Nylon", notes: "Split sprocket for installation without shaft removal.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1100" },
      { name: "EZ Track™ and EZ Clean™ Sprockets", material: "Acetal", notes: "Combines belt tracking and open-spoke cleanability.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1100" },
      { name: "Abrasion Resistant Metal Sprockets", material: "Metal", notes: "For abrasive applications.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1100" },
    ],
    accessories: [
      { name: "Sideguards", type: "sideguard", notes: "Molded sideguards for Series 1100.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1100/sideguards" },
      { name: "Flat Top Base Flights (Streamline)", type: "flight", notes: "Streamline base flights for incline conveying.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1100/flat-top-base-flights-streamline" },
    ],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "191",
    styles: [
      {
        key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth",
        image: CDN + "6faaa1c7-2418-464f-a174-dec87c8a7e46/202190B.jpg?w=568&h=298.2&rect=&fit=crop&q=85&auto=format",
        description: "Lightweight, smooth, closed-surface belt. Tight transfer capability over 0.875-in nosebars.",
        applications: ["Canmaking", "Food processing", "Packaging"],
        beltData: [
          { material: "Polypropylene", rodMaterial: "Polypropylene", strengthLbfFt: 500, strengthNm: 4903, tempF: "34 to 220", tempC: "1 to 104", massLbFt2: 0.90, massKgM2: 4.40 },
          { material: "Polyethylene", rodMaterial: "Polyethylene", strengthLbfFt: 300, strengthNm: 2942, tempF: "-50 to 150", tempC: "-46 to 66", massLbFt2: 0.96, massKgM2: 4.69 },
          { material: "Acetal", rodMaterial: "Polypropylene", strengthLbfFt: 1000, strengthNm: 14600, tempF: "34 to 200", tempC: "1 to 93", massLbFt2: 1.30, massKgM2: 6.35 },
          { material: "HHR Nylon", rodMaterial: "HHR Nylon", strengthLbfFt: 800, strengthNm: 7845, tempF: "-50 to 310", tempC: "-46 to 154", massLbFt2: 1.175, massKgM2: 5.74 },
          { material: "PK", rodMaterial: "PK", strengthLbfFt: 1000, strengthNm: 14600, tempF: "-40 to 176", tempC: "-40 to 80", massLbFt2: 1.14, massKgM2: 5.57 },
        ],
        notes: ["Small pitch reduces chordal action and gap at transfer dead plate.", "Can be used over 0.875 in (22.2 mm) nosebar for tight transfers."],
      },
      { key: "flush_grid", label: "Flush Grid", openArea: "~35%", surface: "Open Grid", image: CDN + "2466a77a-96d1-46b2-b3aa-3a42cd664acf/5014239_28DTA28188_S1100%20Flush%20Grid%20Streamline%20Base%20Flight.jpg?w=568&h=298.2&rect=&fit=crop&q=85&auto=format", description: "Open grid for drainage and airflow with 0.60-in pitch.", applications: ["Drainage", "Cooling", "Airflow"], beltData: "To be confirmed by Uniking", notes: [] },
      { key: "perforated_flat_top", label: "Perforated Flat Top", openArea: "~15%", surface: "Perforated", image: null, description: "Perforated closed surface for partial drainage.", applications: ["Drainage", "Washing", "Drying"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1200",
    name: "Series 1200",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 209,
    image: IMG.S1200,
    description: "1-inch pitch high-strength belt with excellent chemical resistance. Designed for demanding food processing and chemical environments.",
    applications: ["Chemical environments", "Food processing", "Beverage", "Demanding wash-down"],
    advantages: ["Chemical-resistant materials", "1-in pitch", "High strength", "FDA-compliant options"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 209.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1200" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "209",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Chemical-resistant 1-inch pitch flat top.", applications: ["Chemical environments", "Food processing"], beltData: "To be confirmed by Uniking", notes: ["1.00 in (25.4 mm) pitch."] },
    ],
  },
  {
    id: "S1400",
    name: "Series 1400",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 223,
    min_width_in: 3,
    min_width_mm: 76,
    width_increment_in: 1.00,
    width_increment_mm: 25.4,
    image: IMG.S1400,
    description: "Series 1400 offers lightweight belting with multiple surface styles for food and packaging applications. 1-inch pitch with broad material options.",
    applications: ["Packaging", "Food Processing", "Bakery", "Snack Food", "Light Manufacturing"],
    advantages: ["Lightweight construction", "Multiple surface styles", "1-in pitch", "Wide material availability"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 223.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1400" }],
    accessories: [{ name: "Accessories & Components", type: "accessory", notes: "Contact Uniking for Series 1400 accessories." }],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "223",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Lightweight flat top 1-inch pitch belt.", applications: ["Packaging", "Food processing"], beltData: "To be confirmed by Uniking", notes: ["1.00 in (25.4 mm) pitch."] },
    ],
  },
  {
    id: "S1500",
    name: "Series 1500",
    beltType: "Straight-Running",
    pitch_in: 1.50,
    pitch_mm: 38.1,
    catalogPage: 249,
    image: IMG.S1500,
    description: "1.5-inch pitch heavy-duty belt with high-strength construction for industrial and food processing applications requiring substantial load capacity.",
    applications: ["Heavy industrial conveying", "Food processing", "Automotive parts", "High-load applications"],
    advantages: ["1.5-in pitch for heavy loads", "High-strength construction", "Multiple material options", "Flights available"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 249.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1500" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "249",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "1.5-inch pitch heavy-duty flat top belt.", applications: ["Heavy industrial", "Food processing"], beltData: "To be confirmed by Uniking", notes: ["1.50 in (38.1 mm) pitch."] },
    ],
  },
  {
    id: "S1600",
    name: "Series 1600",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 255,
    image: IMG.S1600,
    description: "Series 1600 is designed for poultry processing and wet food environments with open grid construction optimized for drainage and easy cleaning.",
    applications: ["Poultry processing", "Wet food processing", "Sanitary environments", "Drainage-critical applications"],
    advantages: ["Optimized drainage design", "1-in pitch", "Sanitary open-grid construction", "Easy strip-down"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 255.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1600" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "255",
    styles: [
      { key: "flush_grid", label: "Flush Grid", openArea: "~50%", surface: "Open Grid", image: null, description: "High-drainage open grid for poultry and wet food processing.", applications: ["Poultry processing", "Wet food processing"], beltData: "To be confirmed by Uniking", notes: [] },
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top for sanitary direct-food-contact applications.", applications: ["Poultry processing", "Sanitary conveying"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1650",
    name: "Series 1650",
    beltType: "Straight-Running",
    pitch_in: 1.00,
    pitch_mm: 25.4,
    catalogPage: 269,
    image: IMG.S1650,
    description: "Series 1650 offers enhanced Series 1600 capabilities with additional belt styles for meat, poultry, and seafood processing.",
    applications: ["Meat & poultry processing", "Seafood processing", "Sanitary direct-food contact", "Hygienic environments"],
    advantages: ["Enhanced drainage over S1600", "1-in pitch", "Additional belt style options", "Snap-lock rod retention"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 269.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1650" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "269",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top for meat and seafood processing.", applications: ["Meat & poultry", "Seafood"], beltData: "To be confirmed by Uniking", notes: [] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~50%", surface: "Open Grid", image: null, description: "High open area drainage grid.", applications: ["Drainage", "Seafood processing"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1700",
    name: "Series 1700",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 273,
    image: IMG.S1700,
    description: "2-inch pitch heavy-duty belt for bulk material handling, aggregates, and high-load industrial conveying applications.",
    applications: ["Bulk material handling", "Aggregates", "Industrial conveying", "Heavy loads", "Mining"],
    advantages: ["Heavy-duty 2-in pitch construction", "High load capacity", "Robust belt modules", "Wide material options"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 273.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1700" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "273",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Heavy-duty flat top for bulk material conveying.", applications: ["Bulk materials", "Aggregates"], beltData: "To be confirmed by Uniking", notes: ["2.00 in (50.8 mm) pitch."] },
    ],
  },
  {
    id: "S1750",
    name: "Series 1750",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 281,
    image: IMG.S1750,
    description: "2-inch pitch belt with specialized side-guard capabilities for bulk handling and containment applications.",
    applications: ["Bulk material containment", "Industrial conveying", "Incline bulk handling"],
    advantages: ["Side-guard containment options", "2-in pitch heavy duty", "Robust construction"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 281.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1750" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "281",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "2-inch pitch flat top with side-guard options.", applications: ["Bulk handling", "Containment"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1800",
    name: "Series 1800",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 287,
    image: IMG.S1800,
    description: "Series 1800 HDE (Hygienic Design Equipment) — the newest addition to the Intralox food-safe line, featuring enhanced open-grid design optimized for hygiene and cleanability.",
    applications: ["Food processing", "Hygienic environments", "Meat & poultry", "Dairy", "Seafood"],
    advantages: ["HDE hygienic design principles", "Enhanced cleanability", "Open-grid construction", "2-in pitch FDA materials"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 287.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1800" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "287",
    styles: [
      { key: "flush_grid", label: "Flush Grid (HDE)", openArea: "~55%", surface: "Open Grid", image: CDN + "036c4722-8bdd-45b7-8ab7-e6a45600d79d/5016395_FoodSafe%20New%20Products_s1800%20HDE_-36.jpg?w=568&h=298.2&rect=0,0,6720,3528&fit=&q=85&auto=format", description: "HDE optimized flush grid for maximum cleanability and drainage.", applications: ["Food processing", "Hygienic environments"], beltData: "To be confirmed by Uniking", notes: ["HDE = Hygienic Design Equipment."] },
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top for direct food contact.", applications: ["Direct food contact", "Meat & poultry"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S1900",
    name: "Series 1900",
    beltType: "Straight-Running",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 295,
    image: IMG.S1900,
    description: "Series 1900 is designed for large-format and heavy-duty conveying at 2-inch pitch with a wider module width option.",
    applications: ["Heavy food processing", "Industrial conveying", "Large-format products", "High-load applications"],
    advantages: ["Wide module width", "High strength", "2-in pitch", "Multiple surface styles"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 295.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-1900" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "295",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Heavy-duty 2-inch pitch flat top for large-format conveying.", applications: ["Heavy food processing", "Industrial"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S4400",
    name: "Series 4400",
    beltType: "Side-Flexing",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 301,
    image: IMG.S800,
    description: "Series 4400 is a side-flexing modular belt that can navigate horizontal curves as well as straight runs, reducing the need for transfer plates.",
    applications: ["Horizontal curves", "Straight & curved conveying", "Packaging lines", "Accumulation"],
    advantages: ["Side-flexing capability", "Eliminates curve conveyor transfers", "2-in pitch", "Multiple surface styles"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 301.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-4400" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "301",
    styles: [
      { key: "flat_top", label: "Flat Top (Side-Flexing)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Side-flexing flat top for curved conveyor paths.", applications: ["Horizontal curves", "Straight runs"], beltData: "To be confirmed by Uniking", notes: ["Side-flexing belt."] },
    ],
  },
  {
    id: "S4500",
    name: "Series 4500",
    beltType: "Side-Flexing",
    pitch_in: 2.00,
    pitch_mm: 50.8,
    catalogPage: 307,
    image: IMG.S800,
    description: "Series 4500 enhanced side-flexing belt for tighter curve radii than Series 4400. Suitable for complex conveyor layouts.",
    applications: ["Tight horizontal curves", "Complex layouts", "Packaging lines"],
    advantages: ["Tighter curve radius than S4400", "Smooth product surface", "Side-flexing modular design"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 307.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-4500" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "307",
    styles: [
      { key: "flat_top", label: "Flat Top (Side-Flexing)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Tight-radius side-flexing flat top.", applications: ["Tight curves", "Complex layouts"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S9000",
    name: "Series 9000",
    beltType: "Straight-Running",
    pitch_in: "To be confirmed by Uniking",
    pitch_mm: "To be confirmed by Uniking",
    catalogPage: 317,
    image: IMG.S900,
    description: "Series 9000 is a specialty belt series for specific industrial or food processing applications. Pitch and full specifications to be confirmed by Uniking.",
    applications: ["Specialty industrial applications", "To be confirmed by Uniking"],
    advantages: ["Specialty design for demanding applications", "Contact Uniking for full specifications"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 317.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-9000" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "317",
    styles: [
      { key: "belt_style", label: "Belt Style", openArea: "To be confirmed by Uniking", surface: "To be confirmed by Uniking", image: null, description: "Full belt style data to be confirmed by Uniking.", applications: ["To be confirmed by Uniking"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S10000",
    name: "Series 10000",
    beltType: "Straight-Running",
    pitch_in: "To be confirmed by Uniking",
    pitch_mm: "To be confirmed by Uniking",
    catalogPage: 323,
    image: IMG.S1000,
    description: "Series 10000 is a specialty belt series for specific industrial applications. Full specifications to be confirmed by Uniking.",
    applications: ["Specialty industrial applications", "To be confirmed by Uniking"],
    advantages: ["Specialty design", "Contact Uniking for full specifications"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 323.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-10000" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "323",
    styles: [
      { key: "belt_style", label: "Belt Style", openArea: "To be confirmed by Uniking", surface: "To be confirmed by Uniking", image: null, description: "Full belt style data to be confirmed by Uniking.", applications: ["To be confirmed by Uniking"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
];

// ── RADIUS SERIES ─────────────────────────────────────────────────────────────
export const RADIUS_SERIES = [
  {
    id: "S2100",
    name: "Series 2100",
    beltType: "Radius",
    catalogPage: 333,
    image: IMG.S2100,
    description: "Series 2100 radius belt for 90° and multi-directional curves. Designed for horizontal curve conveying in food processing and packaging applications.",
    applications: ["90° horizontal curves", "Multi-directional conveying", "Food processing", "Packaging lines"],
    advantages: ["Designed for tight curve radii", "Smooth product surface", "Multiple surface styles", "FDA materials available"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 333.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2100" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "333",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top radius belt for horizontal curves.", applications: ["90° curves", "Food processing"], beltData: "To be confirmed by Uniking", notes: ["Radius belt — requires matching drive shaft and sprocket configuration."] },
    ],
  },
  {
    id: "S2200",
    name: "Series 2200",
    beltType: "Radius",
    catalogPage: 337,
    image: IMG.S2200,
    description: "Series 2200 radius belt with enhanced load capacity for heavier product conveying on horizontal curves. Wider pitch than S2100.",
    applications: ["Horizontal curves — heavier loads", "Food processing", "Industrial conveying"],
    advantages: ["Higher load capacity than S2100", "Radius conveying capability", "Multiple surface styles"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 337.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2200" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "337",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Flat top radius belt for heavy product curves.", applications: ["Horizontal curves", "Heavy conveying"], beltData: "To be confirmed by Uniking", notes: ["Radius belt."] },
      { key: "flush_grid", label: "Flush Grid", openArea: "~40%", surface: "Open Grid", image: null, description: "Open grid radius belt for drainage and airflow on curves.", applications: ["Drainage curves", "Cooling curves"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S2300",
    name: "Series 2300",
    beltType: "Radius",
    catalogPage: 349,
    image: IMG.S2300,
    description: "Series 2300 radius belt designed specifically for food processing curves, featuring enhanced hygiene and drainage in wet processing environments.",
    applications: ["Food processing curves", "Wet environments", "Sanitary horizontal curves", "Poultry & meat processing"],
    advantages: ["Hygienic open design", "Enhanced drainage on curves", "FDA-compliant materials", "Sanitary construction"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 349.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2300" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "349",
    styles: [
      { key: "flush_grid", label: "Flush Grid", openArea: "~50%", surface: "Open Grid", image: null, description: "High-drainage flush grid for food processing curves.", applications: ["Food processing", "Wet environments"], beltData: "To be confirmed by Uniking", notes: [] },
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Smooth flat top for sanitary curve conveying.", applications: ["Sanitary processing", "Direct food contact"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S2400",
    name: "Series 2400",
    beltType: "Radius",
    catalogPage: 359,
    image: IMG.S2400,
    description: "Series 2400 heavy-duty radius belt for industrial curve conveying at higher loads and larger belt widths.",
    applications: ["Heavy industrial curves", "Large-format products", "Wide belt curve conveying", "General industrial"],
    advantages: ["Heavy-duty radius construction", "Wide belt options", "Multiple surface styles", "High load capacity"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 359.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2400" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "359",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Heavy-duty flat top radius belt for wide belt and high loads.", applications: ["Heavy industrial", "Wide belt curves"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S3000",
    name: "Series 3000",
    beltType: "Radius",
    catalogPage: 385,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 3000 radius belt for 180° turns and complex multi-directional layouts. Suitable for compact conveyor systems that require tight turns.",
    applications: ["180° turns", "Compact conveyor layouts", "Multi-directional systems", "Packaging & food processing"],
    advantages: ["180° turning capability", "Compact layout design", "Multiple surface options"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 385.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-3000" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "385",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Flat top radius belt for 180° turns.", applications: ["180° turns", "Compact layouts"], beltData: "To be confirmed by Uniking", notes: ["Radius belt for 180° turns."] },
    ],
  },
  {
    id: "S4000",
    name: "Series 4000",
    beltType: "Radius",
    catalogPage: 391,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 4000 high-performance radius belt with enhanced module design for reliability in food and industrial horizontal curve applications.",
    applications: ["High-performance horizontal curves", "Food processing", "Industrial curve conveying"],
    advantages: ["High-performance radius design", "Reliable module construction", "FDA materials available"],
    sprockets: [{ name: "Compatible Sprockets", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 391.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-4000" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "391",
    styles: [
      { key: "flat_top", label: "Flat Top", openArea: "0%", surface: "Closed / Smooth", image: null, description: "High-performance flat top radius belt.", applications: ["High-performance curves", "Food processing"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
];

// ── SPIRAL SERIES ─────────────────────────────────────────────────────────────
export const SPIRAL_SERIES = [
  {
    id: "S2600",
    name: "Series 2600",
    beltType: "Spiral",
    catalogPage: 409,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 2600 spiral belt for spiral freezer and cooler systems. Designed to withstand the demanding conditions of spiral conveyor towers.",
    applications: ["Spiral freezers", "Spiral coolers", "Proofing towers", "Vertical conveying systems"],
    advantages: ["Designed for spiral systems", "High tension strength", "Self-stacking for compact footprint", "FDA materials available"],
    sprockets: [{ name: "Compatible Drum Drive", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 409.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2600" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "409",
    styles: [
      { key: "flat_top", label: "Flat Top (Spiral)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Flat top spiral belt for freezer and cooler towers.", applications: ["Spiral freezers", "Spiral coolers"], beltData: "To be confirmed by Uniking", notes: ["Spiral belt — requires spiral conveyor system."] },
      { key: "flush_grid", label: "Flush Grid (Spiral)", openArea: "~40%", surface: "Open Grid", image: null, description: "Open grid spiral belt for maximum airflow in spiral systems.", applications: ["Spiral coolers", "Proofing towers"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S2700",
    name: "Series 2700",
    beltType: "Spiral",
    catalogPage: 421,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 2700 enhanced spiral belt with improved module design for higher-tension spiral applications and wider belt widths.",
    applications: ["High-tension spiral systems", "Wide spiral freezers", "Commercial spiral coolers", "Proofing towers"],
    advantages: ["Higher tension than S2600", "Wider belt options", "Improved module design", "FDA materials available"],
    sprockets: [{ name: "Compatible Drum Drive", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 421.", url: "https://www.intralox.com/belt-finder/modular-plastic-belting/series-2700" }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "421",
    styles: [
      { key: "flat_top", label: "Flat Top (Spiral)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Higher-strength spiral flat top belt.", applications: ["High-tension spiral systems", "Commercial spiral coolers"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S2800",
    name: "Series 2800",
    beltType: "Spiral",
    catalogPage: 433,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 2800 spiral belt for high-capacity spiral freezers and coolers. Features reinforced module design for increased tension loads in large commercial spiral systems.",
    applications: ["High-capacity spiral freezers", "Commercial spiral coolers", "Large-format spiral systems", "Proofing towers"],
    advantages: ["Higher capacity than S2700", "Reinforced module design", "Increased tension load capability", "FDA materials available"],
    sprockets: [{ name: "Compatible Drum Drive", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 433.", url: MPB_MANUAL_URL }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "433",
    styles: [
      { key: "flat_top", label: "Flat Top (Spiral)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "High-capacity spiral flat top belt for large commercial freezer/cooler towers.", applications: ["High-capacity spiral freezers", "Commercial coolers"], beltData: "To be confirmed by Uniking", notes: ["Spiral belt — requires spiral conveyor system.", "Refer to 2026 catalog page 433."] },
      { key: "flush_grid", label: "Flush Grid (Spiral)", openArea: "~40%", surface: "Open Grid", image: null, description: "Open grid spiral belt for maximum airflow in large spiral systems.", applications: ["Spiral coolers", "Proofing towers"], beltData: "To be confirmed by Uniking", notes: [] },
    ],
  },
  {
    id: "S2900",
    name: "Series 2900",
    beltType: "Spiral",
    catalogPage: 441,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 2900 spiral belt engineered for demanding spiral freezer/cooler applications requiring maximum strength and reliability in continuous operation environments.",
    applications: ["Demanding spiral freezer applications", "High-throughput coolers", "Continuous operation spiral systems"],
    advantages: ["Maximum strength for spiral systems", "Reliable continuous operation design", "Durable module construction", "FDA materials available"],
    sprockets: [{ name: "Compatible Drum Drive", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 441.", url: MPB_MANUAL_URL }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "441",
    styles: [
      { key: "flat_top", label: "Flat Top (Spiral)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Maximum-strength spiral flat top belt for demanding continuous operation.", applications: ["Demanding spiral freezers", "High-throughput coolers"], beltData: "To be confirmed by Uniking", notes: ["Spiral belt — requires spiral conveyor system.", "Refer to 2026 catalog page 441."] },
    ],
  },
  {
    id: "S2950",
    name: "Series 2950",
    beltType: "Spiral",
    catalogPage: 453,
    image: CDN + "f045209f-e054-4c2f-a058-7cc4476e062b/modular-plastic-belting-40_21.jpg?w=568&h=298.2&rect=0,0,2400,1260&fit=&q=85&auto=format",
    description: "Series 2950 premium spiral belt for the most demanding spiral conveyor applications. Highest tension ratings in the Intralox spiral belt range.",
    applications: ["Premium spiral freezer systems", "Highest-demand coolers", "High-load spiral proofing towers"],
    advantages: ["Highest tension ratings in spiral range", "Premium spiral module design", "Maximum reliability for critical applications", "FDA materials available"],
    sprockets: [{ name: "Compatible Drum Drive", material: "To be confirmed by Uniking", notes: "Refer to 2026 catalog page 453.", url: MPB_MANUAL_URL }],
    accessories: [],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "453",
    styles: [
      { key: "flat_top", label: "Flat Top (Spiral)", openArea: "0%", surface: "Closed / Smooth", image: null, description: "Premium spiral flat top belt — highest tension rating in the Intralox spiral range.", applications: ["Premium spiral freezers", "High-demand coolers"], beltData: "To be confirmed by Uniking", notes: ["Spiral belt — requires spiral conveyor system.", "Refer to 2026 catalog page 453."] },
    ],
  },
];

// ── BELT SUPPORT TOOLS ────────────────────────────────────────────────────────
// Source: 2026 MPB Engineering Manual pp. 457–481
export const BELT_SUPPORT_TOOLS = [
  {
    id: "BST_SQUARE_SHAFTS",
    name: "Square Shafts",
    beltType: "Belt Support Tool",
    catalogPage: 458,
    image: null,
    description: "Square shafts for driving Intralox modular plastic belt sprockets. Available in multiple sizes to match sprocket bore requirements.",
    applications: ["All belt series", "Drive shaft installation", "Sprocket mounting"],
    advantages: ["Positive drive engagement", "Multiple sizes available", "Compatible with all Intralox sprockets"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 458."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "458",
  },
  {
    id: "BST_RETAINER_RINGS",
    name: "Retainer Rings & Center Sprocket Offset",
    beltType: "Belt Support Tool",
    catalogPage: 460,
    image: null,
    description: "Retainer rings to secure sprockets on drive shafts and center sprocket offset components for proper belt tracking and alignment.",
    applications: ["Sprocket retention", "Belt tracking", "Drive shaft assembly"],
    advantages: ["Prevents axial sprocket movement", "Ensures proper belt tracking", "Easy installation"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 460."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "460",
  },
  {
    id: "BST_RETURNWAY_RINGS",
    name: "Returnway Rings",
    beltType: "Belt Support Tool",
    catalogPage: 466,
    image: null,
    description: "Returnway rings to support the belt on the return side of the conveyor, maintaining belt tracking and preventing sag.",
    applications: ["Belt return support", "Belt tracking on returnway", "All belt series"],
    advantages: ["Supports belt on return", "Reduces belt sag", "Improves belt life"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 466."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "466",
  },
  {
    id: "BST_ONETRACK_ROLLERS",
    name: "OneTrack™ Rollers",
    beltType: "Belt Support Tool",
    catalogPage: 467,
    image: null,
    description: "OneTrack™ rollers provide smooth, low-friction belt support on the returnway. Reduces belt wear and drive power requirements.",
    applications: ["Belt returnway support", "Low-friction return", "Long conveyors"],
    advantages: ["Low-friction return support", "Reduces drive power", "Extends belt life"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 467."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "467",
  },
  {
    id: "BST_SPROCKET_SPACERS",
    name: "Sprocket Spacers",
    beltType: "Belt Support Tool",
    catalogPage: 467,
    image: null,
    description: "Spacers used between sprockets on a drive shaft to maintain correct spacing and belt tracking.",
    applications: ["Sprocket spacing", "Belt tracking", "Drive shaft assembly"],
    advantages: ["Maintains correct sprocket spacing", "Simple installation", "Compatible with all series"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 467."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "467",
  },
  {
    id: "BST_ROUND_BORE_ADAPTERS",
    name: "Round Bore Adapters",
    beltType: "Belt Support Tool",
    catalogPage: 468,
    image: null,
    description: "Adapters to mount Intralox sprockets with square bore onto round shafts.",
    applications: ["Square-bore sprockets on round shafts", "Retrofit installations"],
    advantages: ["Enables use of square-bore sprockets on round shafts", "Retrofit-friendly"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 468."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "468",
  },
  {
    id: "BST_SCROLL_IDLERS",
    name: "Scroll Idlers",
    beltType: "Belt Support Tool",
    catalogPage: 469,
    image: null,
    description: "Scroll idlers help track and train the belt on the carryway or returnway, preventing belt drift on wide or long conveyors.",
    applications: ["Belt tracking", "Wide belt conveyors", "Long conveyors", "Belt drift prevention"],
    advantages: ["Prevents belt drift", "Improves belt tracking", "Available for multiple series"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 469."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "469",
  },
  {
    id: "BST_WEARSTRIPS",
    name: "Wearstrips",
    beltType: "Belt Support Tool",
    catalogPage: 470,
    image: null,
    description: "Wearstrips support the belt on the carryway and reduce friction and wear between belt modules and the conveyor frame. Available in multiple materials and profiles.",
    applications: ["Carryway belt support", "Belt wear reduction", "All belt series", "Conveyor frame protection"],
    advantages: ["Reduces belt and frame wear", "Multiple material options (UHMW-PE, stainless steel, etc.)", "Custom profiles available"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 470."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "470",
  },
  {
    id: "BST_CUSTOM_WEARSTRIPS",
    name: "Custom Wearstrips",
    beltType: "Belt Support Tool",
    catalogPage: 473,
    image: null,
    description: "Custom-profile wearstrips for non-standard conveyor frames or special application requirements.",
    applications: ["Non-standard conveyor frames", "Special carryway profiles", "Custom conveyor designs"],
    advantages: ["Tailored to specific conveyor geometry", "Multiple materials available"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 473."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "473",
  },
  {
    id: "BST_PUSHER_BARS",
    name: "Pusher Bars",
    beltType: "Belt Support Tool",
    catalogPage: 475,
    image: null,
    description: "Pusher bars assist in product handling, diverting, or accumulation by providing a lateral push force on the conveyor surface.",
    applications: ["Product diverting", "Accumulation", "Product alignment", "Sorting systems"],
    advantages: ["Facilitates product diverting and accumulation", "Compatible with modular belt systems"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 475."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "475",
  },
  {
    id: "BST_TRANSFER_PLATES",
    name: "Transfer Plates",
    beltType: "Belt Support Tool",
    catalogPage: 477,
    image: null,
    description: "Transfer plates bridge the gap between belt sections or from belt to processing equipment for smooth, low-impact product transfers.",
    applications: ["Belt-to-belt transfers", "Belt-to-equipment transfers", "Tight product transfers", "Dead plate transfers"],
    advantages: ["Reduces product impact at transfers", "Smooth transfer geometry", "Stainless steel options"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 477."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "477",
  },
  {
    id: "BST_EZ_CLEAN_CIP",
    name: "EZ Clean In Place (CIP) System",
    beltType: "Belt Support Tool",
    catalogPage: 477,
    image: null,
    description: "EZ Clean In Place (CIP) system enables cleaning of the belt and conveyor without full disassembly, reducing downtime in food processing environments.",
    applications: ["Food processing sanitation", "CIP cleaning systems", "High-hygiene environments"],
    advantages: ["Reduces cleaning downtime", "Enables in-place belt sanitation", "Compatible with food-safe cleaning chemicals"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 477."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "477",
  },
  {
    id: "BST_HOLD_DOWN_ROLLERS",
    name: "Hold Down Rollers",
    beltType: "Belt Support Tool",
    catalogPage: 478,
    image: null,
    description: "Hold down rollers prevent belt lifting on the carryway, especially on inclines, declines, and high-speed conveyors.",
    applications: ["Incline conveyors", "Decline conveyors", "High-speed conveying", "Belt lift prevention"],
    advantages: ["Prevents belt lifting", "Ensures consistent belt-to-carryway contact", "Reduces belt noise"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 478."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "478",
  },
  {
    id: "BST_ABRASION_RESISTANCE",
    name: "Abrasion Resistance System",
    beltType: "Belt Support Tool",
    catalogPage: 479,
    image: null,
    description: "Abrasion resistance system provides enhanced carryway protection for belts operating with highly abrasive products or environments.",
    applications: ["Abrasive products", "Mining", "Aggregates", "Heavy industrial conveying"],
    advantages: ["Significantly extends belt life in abrasive conditions", "Protects conveyor frame from abrasive wear"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 479."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "479",
  },
  {
    id: "BST_ABRASION_HINGE_RODS",
    name: "Abrasion Resistance Hinge Rods",
    beltType: "Belt Support Tool",
    catalogPage: 480,
    image: null,
    description: "Hardened hinge rods for use in highly abrasive applications where standard rods would wear prematurely.",
    applications: ["Abrasive material handling", "Mining", "Aggregates", "Industrial bulk conveying"],
    advantages: ["Extended rod life in abrasive environments", "Drop-in replacement for standard rods"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 480."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "480",
  },
  {
    id: "BST_EZ_MOUNT_SCRAPER",
    name: "EZ Mount Flex Tip Scraper",
    beltType: "Belt Support Tool",
    catalogPage: 481,
    image: null,
    description: "EZ Mount Flex Tip Scraper removes product buildup from belt surfaces with a flexible tip design that conforms to belt surface irregularities.",
    applications: ["Belt cleaning", "Product buildup removal", "Food processing", "Sticky product conveying"],
    advantages: ["Flexible tip conforms to belt surface", "Easy mounting and removal", "Reduces product carryback"],
    notes: ["Refer to 2026 MPB Engineering Manual p. 481."],
    techChartUrl: MPB_MANUAL_URL,
    engineeringManualPage: "481",
  },
];

// ── Combined exports for legacy compatibility ─────────────────────────────────
export const INTRALOX_SERIES = [...STRAIGHT_SERIES, ...RADIUS_SERIES, ...SPIRAL_SERIES];

export const INTRALOX_INDUSTRIES = [
  "Meat & Poultry Processing", "Food & Beverage", "Bakery & Snack",
  "Seafood Processing", "Dairy", "Can & Bottle Handling",
  "Packaging", "Automotive", "General Industrial", "Pharmaceutical", "Other",
];

export const INTRALOX_EQUIPMENT_TYPES = [
  "Straight conveyor", "Incline / decline conveyor", "Accumulation conveyor",
  "Washdown conveyor", "Freezer / cold storage conveyor", "Oven / heat tunnel",
  "Tight-transfer conveyor", "Radius / curve conveyor", "Spiral freezer / cooler", "Other — please specify",
];