/**
 * sharpTopData.js
 * Normalized SharpTop Chain catalog — brand-neutral procurement reference.
 * Sources: Connexus Industries (Viking/Summit), Renold Jeffrey, Peer Chain, PTI
 * All specs verified from manufacturer technical documents.
 */

// ── Tooth Configuration Definitions ─────────────────────────────────────────
export const TOOTH_CONFIGS = {
  STD:    { code: "STD",    label: "STD — Summit Tip Design",          shortLabel: "STD",    desc: "Standard 3-point Summit tip. Most common configuration for log handling and general sawmill conveying.",            points: 3, frequency: "Every Pitch" },
  "5PEP": { code: "5PEP",  label: "5PEP — 5 Points Every Pitch",       shortLabel: "5PEP",   desc: "5-point tip on every pitch link. Maximum grip for high-speed infeed and controlled log positioning.",              points: 5, frequency: "Every Pitch" },
  "4STA": { code: "4STA",  label: "4STA — 4 Points Every Pitch",        shortLabel: "4STA",   desc: "4-point alternating tip every pitch. Balanced grip for dimensional lumber and cant sorting applications.",         points: 4, frequency: "Every Pitch" },
  "4ST":  { code: "4ST",   label: "4ST — 4 Points Every 2nd Pitch",     shortLabel: "4ST",    desc: "4-point tip on every 2nd pitch link. Reduced weight alternative to 4STA with excellent grip performance.",        points: 4, frequency: "Every 2nd Pitch" },
  "3PT":  { code: "3PT",   label: "3PT — 3 Points Every 2nd Pitch",     shortLabel: "3PT",    desc: "Standard 3-point tip on every 2nd pitch link. Classic configuration for general log and lumber conveying.",       points: 3, frequency: "Every 2nd Pitch" },
  "SL-LP":{ code: "SL-LP", label: "SL-LP — Slasher Low Profile",        shortLabel: "SL-LP",  desc: "Low-profile slasher tip for slasher saws and cut-to-length applications. Reduced height prevents binding.",       points: 2, frequency: "Every 2nd Pitch" },
  P2PAD:  { code: "P2PAD", label: "P2PAD — Every 2nd Pitch Alternating", shortLabel: "P2PAD",  desc: "Points every 2nd pitch in alternating directions. Centering action for precise log alignment before saws.",        points: 3, frequency: "Alternating / Every 2nd Pitch" },
  P4PAD:  { code: "P4PAD", label: "P4PAD — Every 4th Pitch Alternating", shortLabel: "P4PAD",  desc: "Points every 4th pitch alternating direction. Used in sorting lines and variable-speed positioning systems.",     points: 3, frequency: "Alternating / Every 4th Pitch" },
  P8PAD:  { code: "P8PAD", label: "P8PAD — Every 8th Pitch Alternating", shortLabel: "P8PAD",  desc: "Points every 8th pitch alternating direction. Light grip for gentle handling of finished lumber products.",       points: 3, frequency: "Alternating / Every 8th Pitch" },
  SP:     { code: "SP",    label: "SP — Single Point",                  shortLabel: "SP",     desc: "Single point per link. Minimal grip profile for slow-speed or light-duty lumber handling.",                       points: 1, frequency: "Every Pitch" },
  W2P:    { code: "W2P",   label: "W2P — Waferizer Every 2nd Pitch",     shortLabel: "W2P",    desc: "Wide waferizer profile every 2nd pitch. Designed specifically for waferizer (flaker) infeed conveyors.",         points: 4, frequency: "Every 2nd Pitch" },
  W4P:    { code: "W4P",   label: "W4P — Waferizer Every 4th Pitch",     shortLabel: "W4P",    desc: "Wide waferizer profile every 4th pitch. Slower feed control for thicker wafer/flaker applications.",             points: 4, frequency: "Every 4th Pitch" },
  DP:     { code: "DP",    label: "DP — Double Point",                  shortLabel: "DP",     desc: "Double deep-point profile. Used on BS/special pitch chains for maximum penetration in dense materials.",          points: 2, frequency: "Every 2nd Pitch" },
  "08B-6P":{ code: "08B-6P", label: "08B-6P — 6 Points Every Pitch",   shortLabel: "6P",     desc: "6-point configuration on 1/2\" pitch chain. High-density grip for small-diameter material handling.",            points: 6, frequency: "Every Pitch" },
  "50-STD":{ code: "50-STD", label: "50 STD — Summit Tip (50 Series)",  shortLabel: "50 STD", desc: "Summit tip design for 5/8\" pitch chains. Standard config for medium-duty forestry conveying.",                   points: 3, frequency: "Every Pitch" },
  IH:     { code: "IH",    label: "IH — Induction Hardened Upgrade",    shortLabel: "IH",     desc: "Induction hardened sharp tops for maximum wear life. Add-on upgrade to any configuration. Extends tip life 3–5×.", points: null, frequency: "Upgrade" },
};

// ── Subcategory Definitions ──────────────────────────────────────────────────
export const SHARPTOP_SUBCATEGORIES = [
  {
    key: "standard_pitch",
    label: "Standard Pitch SharpTop",
    icon: "⛓",
    description: "ANSI 60 & 80 series SharpTop chains — the most common sizes for sawmill infeed, log decks, and sorting lines. Available in single through 6-strand.",
    pitches: ["3/4\" (60 Series)", "1\" (80 Series)"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "heavy_duty",
    label: "Heavy Duty SharpTop",
    icon: "🔩",
    description: "100, 120, 80H and Super series SharpTop chains for high-load applications. Heavier plate and pin for aggressive material handling.",
    pitches: ["1-1/4\" (100 Series)", "1-1/2\" (120 Series)", "1\" Heavy (80H)"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "slasher_lp",
    label: "Slasher / Low Profile",
    icon: "✂️",
    description: "SL-LP configurations across all pitch sizes. Designed for slasher saws, cut-to-length lines, and applications where reduced tip height prevents binding.",
    pitches: ["60, 80, 100 Series with SL-LP profile"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "waferizer",
    label: "Waferizer Chains",
    icon: "📐",
    description: "W2P and W4P profiles on 80-3 base chain. Specifically designed for waferizer (flaker) infeed applications in oriented strand board (OSB) and particleboard plants.",
    pitches: ["1\" 3-strand (80-3 W2P / W4P)"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "multi_point",
    label: "Multi-Point / PAD Chains",
    icon: "🎯",
    description: "P2PAD, P4PAD, P8PAD alternating-direction configurations for precise log centering and alignment. Used before gang saws and profilers.",
    pitches: ["60, 80, 100 Series with alternating tip patterns"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "large_pitch",
    label: "Large Pitch Sharp Chains",
    icon: "🔗",
    description: "3\", 4\", and 6\" pitch sharp chains for heavy timber, large-diameter log handling, and high-load industrial conveying applications.",
    pitches: ["3\" (76.2mm)", "4\" (101.6mm)", "6\" (152.4mm)"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    key: "specialty",
    label: "Specialty / BS / Metric",
    icon: "⚙️",
    description: "British Standard (08B, 32B), metric series, and special application SharpTop chains. Includes 50 series, 08B-6P high-density, and DP double-point configurations.",
    pitches: ["1/2\" BS (08B)", "2\" BS (32B)", "5/8\" (50 Series)", "Custom Pitch"],
    image: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
];

// ── Product Catalog ───────────────────────────────────────────────────────────
// Specs: pitch in inches, ANSI base designation, all verified from Connexus/Renold/Peer catalogs
export const SHARPTOP_PRODUCTS = [

  // ── STANDARD PITCH — 60 SERIES ────────────────────────────────────────────
  {
    id: "st-60-1",
    subcategory: "standard_pitch",
    chain_number: "60-1",
    display_name: "60-1 SharpTop Chain",
    pitch_in: 0.75,
    pitch_mm: 19.05,
    strands: 1,
    base_ansi: "60",
    weight_lbs_ft: 1.2,
    roller_dia_in: 0.469,
    roller_dia_mm: 11.91,
    width_inner_in: 0.500,
    width_inner_mm: 12.70,
    pin_dia_in: 0.234,
    pin_dia_mm: 5.94,
    plate_thickness_in: 0.094,
    plate_thickness_mm: 2.39,
    min_tensile_lbf: 8500,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Log infeed", "Lumber sorting", "Small-diameter material handling", "General sawmill conveying"],
    description: "Single-strand 3/4\" pitch SharpTop chain. The most common size for light-duty sawmill infeed conveyors, small-log handling, and lumber sorting lines. Solid roller and bushing construction with quad-staked pins.",
    available_configs: ["STD", "3PT", "5PEP", "SL-LP", "P2PAD", "SP"],
    standard_config: "STD",
    weight_by_config: { "STD": 1.2, "P2PAD": 1.2 },
    notes: "Base #60 ANSI roller chain. Compatible with standard #60 sprockets.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-60-2",
    subcategory: "standard_pitch",
    chain_number: "60-2",
    display_name: "60-2 SharpTop Chain",
    pitch_in: 0.75,
    pitch_mm: 19.05,
    strands: 2,
    base_ansi: "60",
    weight_lbs_ft: 2.4,
    roller_dia_in: 0.469,
    roller_dia_mm: 11.91,
    width_inner_in: 0.500,
    width_inner_mm: 12.70,
    pin_dia_in: 0.234,
    pin_dia_mm: 5.94,
    plate_thickness_in: 0.094,
    plate_thickness_mm: 2.39,
    min_tensile_lbf: 17000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Log deck conveying", "Twin-strand log handling", "Small sawmill infeed"],
    description: "Double-strand 3/4\" pitch SharpTop chain. Used in twin-track log deck applications where parallel strands are required for stable log transport.",
    available_configs: ["STD", "3PT", "SL-LP"],
    standard_config: "STD",
    weight_by_config: { "STD": 2.4 },
    notes: "2-strand #60 base. Transverse pitch per ANSI standard.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-60-3",
    subcategory: "standard_pitch",
    chain_number: "60-3",
    display_name: "60-3 SharpTop Chain",
    pitch_in: 0.75,
    pitch_mm: 19.05,
    strands: 3,
    base_ansi: "60",
    weight_lbs_ft: 3.6,
    roller_dia_in: 0.469,
    roller_dia_mm: 11.91,
    width_inner_in: 0.500,
    width_inner_mm: 12.70,
    pin_dia_in: 0.234,
    pin_dia_mm: 5.94,
    plate_thickness_in: 0.094,
    plate_thickness_mm: 2.39,
    min_tensile_lbf: 25500,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["3-strand log deck", "High-volume sawmill infeed", "Wide-deck log handling"],
    description: "Triple-strand 3/4\" pitch SharpTop chain for high-volume sawmill operations. Provides wide stable log support across 3 parallel strands.",
    available_configs: ["STD", "SL-LP"],
    standard_config: "STD",
    weight_by_config: { "STD": 3.6 },
    notes: "3-strand #60 base chain.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── STANDARD PITCH — 80 SERIES ────────────────────────────────────────────
  {
    id: "st-80-1",
    subcategory: "standard_pitch",
    chain_number: "80-1",
    display_name: "80-1 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 1,
    base_ansi: "80",
    weight_lbs_ft: 2.1,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 14500,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Log infeed", "Cant conveying", "Lumber sorting", "General sawmill"],
    description: "Single-strand 1\" pitch SharpTop chain. The most widely-used SharpTop size across the sawmill industry. Available in the widest range of tooth configurations.",
    available_configs: ["STD", "3PT", "5PEP", "4STA", "4ST", "SL-LP", "P2PAD", "P4PAD", "SP"],
    standard_config: "STD",
    weight_by_config: { "STD": 2.1, "SL-LP": 2.4 },
    notes: "Base #80 ANSI. Compatible with all standard #80 sprockets.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-2",
    subcategory: "standard_pitch",
    chain_number: "80-2",
    display_name: "80-2 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80",
    weight_lbs_ft: 4.2,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 29000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Primary log infeed", "Double-strand log decks", "Quadrant saws", "High-production sawmill infeed"],
    description: "Double-strand 1\" pitch SharpTop — the industry standard for primary log infeed on band saws, circular saws, and quad saws. Renold part 10065130 (3PT E2P), 10065155 (5PEP).",
    available_configs: ["STD", "3PT", "5PEP", "4STA", "4ST", "SL-LP", "P2PAD", "P4PAD", "P8PAD"],
    standard_config: "STD",
    weight_by_config: { "STD": 4.2, "5PEP": 4.4, "4STA": 4.4, "SL-LP": 4.4, "P8PAD": 4.0 },
    notes: "Most common SharpTop size in North American sawmills.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
    featured: true,
  },
  {
    id: "st-80-3",
    subcategory: "standard_pitch",
    chain_number: "80-3",
    display_name: "80-3 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 3,
    base_ansi: "80",
    weight_lbs_ft: 6.3,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 43500,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["3-strand log infeed", "Waferizer infeed (W2P/W4P)", "High-production conveying", "Planer mill infeed"],
    description: "Triple-strand 1\" pitch SharpTop for heavy-production sawmills. The standard base for W2P and W4P waferizer configurations. Also available in 5PEP for high-grip applications.",
    available_configs: ["STD", "3PT", "5PEP", "SL-LP", "W2P", "W4P"],
    standard_config: "STD",
    weight_by_config: { "STD": 6.3, "5PEP": 6.6, "SL-LP": 6.3, "W2P": 5.7, "W4P": 5.7 },
    notes: "Only chain base compatible with W2P / W4P waferizer profiles.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-4",
    subcategory: "standard_pitch",
    chain_number: "80-4",
    display_name: "80-4 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 4,
    base_ansi: "80",
    weight_lbs_ft: 8.1,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 58000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["4-strand high-production infeed", "Wide-deck conveying", "Large log handling"],
    description: "4-strand 1\" SharpTop for wide-deck, high-production log handling. Used on large-diameter log infeed systems where maximum grip and load distribution is required.",
    available_configs: ["STD", "3PT", "5PEP", "SL-LP"],
    standard_config: "STD",
    weight_by_config: { "STD": 8.1, "SL-LP": 8.3, "5PEP": 8.6 },
    notes: "Connexus stock item. Also available as 80-4-P (with attachments).",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-6",
    subcategory: "standard_pitch",
    chain_number: "80-6",
    display_name: "80-6 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 6,
    base_ansi: "80",
    weight_lbs_ft: 12.0,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 87000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["6-strand wide-deck conveying", "Very large log handling", "High-tonnage production"],
    description: "6-strand 1\" SharpTop for the largest production sawmill applications. Maximum load capacity and grip in a single-pitch configuration.",
    available_configs: ["STD", "SL-LP", "5PEP"],
    standard_config: "STD",
    weight_by_config: { "STD": 12.0, "SL-LP": 12.0, "5PEP": 12.0 },
    notes: "Heavy-duty application. Confirm sprocket and drive system before ordering.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-8",
    subcategory: "standard_pitch",
    chain_number: "80-8",
    display_name: "80-8 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 8,
    base_ansi: "80",
    weight_lbs_ft: 16.0,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 116000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Ultra-wide deck conveying", "Maximum load applications"],
    description: "8-strand 1\" SharpTop for the most demanding wide-deck log handling. Connexus stock item for large-scale sawmill operations.",
    available_configs: ["STD"],
    standard_config: "STD",
    weight_by_config: { "STD": 16.0 },
    notes: "Confirm drive and take-up system capacity before ordering.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── HEAVY DUTY — 80H SERIES ───────────────────────────────────────────────
  {
    id: "st-80h-2",
    subcategory: "heavy_duty",
    chain_number: "80H-2",
    display_name: "80H-2 SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80H",
    weight_lbs_ft: 4.6,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 38000,
    materials: "Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened — Heavy Series",
    applications: ["Heavy-duty log infeed", "High-impact sawmill applications", "Large log handling"],
    description: "Double-strand heavy-series 1\" SharpTop. Heavier plate and pin for high-shock applications. STD and 5PEP/4STA configurations available. P8PAD also available for alignment applications.",
    available_configs: ["STD", "5PEP", "4STA", "P8PAD"],
    standard_config: "STD",
    weight_by_config: { "STD": 4.6, "5PEP": 4.6, "P8PAD": 4.6 },
    notes: "Heavy series — heavier plate (H suffix). Recommended for high-shock or abrasive environments.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80sh-2",
    subcategory: "heavy_duty",
    chain_number: "80SH-2",
    display_name: "80SH-2 Super SharpTop Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80SH",
    weight_lbs_ft: 4.6,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 42000,
    materials: "Alloy Steel",
    heat_treatment: "Super Heavy — Full Heat Treatment",
    applications: ["Extreme-duty sawmill", "High-speed infeed", "Abrasive environments"],
    description: "Super series 2-strand SharpTop. Connexus highest grade for 1\" pitch applications. Maximum fatigue and wear resistance.",
    available_configs: ["STD"],
    standard_config: "STD",
    weight_by_config: { "STD": 4.6 },
    notes: "Super series — highest grade available. Confirm with Uniking for availability.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── HEAVY DUTY — 100 SERIES ───────────────────────────────────────────────
  {
    id: "st-100-1",
    subcategory: "heavy_duty",
    chain_number: "100-1",
    display_name: "100-1 SharpTop Chain",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 1,
    base_ansi: "100",
    weight_lbs_ft: 3.1,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 24000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Heavy log conveying", "Large-diameter log decks", "High-load sorting lines"],
    description: "Single-strand 1-1/4\" pitch SharpTop for heavy-duty log handling. Renold part 10065138 (3PT E2P). Available in STD, SL-LP, and high-grip configurations.",
    available_configs: ["STD", "3PT", "SL-LP"],
    standard_config: "STD",
    weight_by_config: { "STD": 3.1, "SL-LP": 3.4 },
    notes: "Base #100 ANSI chain.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-100-2",
    subcategory: "heavy_duty",
    chain_number: "100-2",
    display_name: "100-2 SharpTop Chain",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 2,
    base_ansi: "100",
    weight_lbs_ft: 6.1,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 48000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Large log infeed", "High-capacity band saws", "Heavy-production sawmill", "Large diameter cant handling"],
    description: "Double-strand 1-1/4\" pitch SharpTop — the heavy-duty workhorse for large-log sawmills. Available with 3PT (Renold 10065138), 5PEP (Renold 10065160), SL-LP (Renold 10065164), and P4PAD configurations.",
    available_configs: ["STD", "3PT", "5PEP", "SL-LP", "P4PAD"],
    standard_config: "STD",
    weight_by_config: { "STD": 6.1, "5PEP": 6.5, "SL-LP": 6.3, "P4PAD": 6.0 },
    notes: "One of the two most common heavy-duty sizes alongside 80-2.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
    featured: true,
  },
  {
    id: "st-100-3",
    subcategory: "heavy_duty",
    chain_number: "100-3",
    display_name: "100-3 SharpTop Chain",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 3,
    base_ansi: "100",
    weight_lbs_ft: 9.2,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 72000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Wide-deck heavy log handling", "High-tonnage production"],
    description: "Triple-strand 1-1/4\" pitch SharpTop for very large log and high-production applications. STD and SL-LP available.",
    available_configs: ["STD", "SL-LP"],
    standard_config: "STD",
    weight_by_config: { "STD": 9.2, "SL-LP": 9.2 },
    notes: "Connexus stock item.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-100-6",
    subcategory: "heavy_duty",
    chain_number: "100-6",
    display_name: "100-6 SharpTop Chain",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 6,
    base_ansi: "100",
    weight_lbs_ft: null,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: null,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Ultra-heavy wide-deck log handling"],
    description: "6-strand 1-1/4\" SharpTop for maximum-width heavy-log applications. Connexus catalog item — confirm availability with Uniking.",
    available_configs: ["STD", "SL-LP"],
    standard_config: "STD",
    weight_by_config: {},
    notes: "Weight to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── HEAVY DUTY — 120 SERIES ───────────────────────────────────────────────
  {
    id: "st-120-1",
    subcategory: "heavy_duty",
    chain_number: "120-1",
    display_name: "120-1 SharpTop Chain",
    pitch_in: 1.50,
    pitch_mm: 38.10,
    strands: 1,
    base_ansi: "120",
    weight_lbs_ft: 4.5,
    roller_dia_in: 0.875,
    roller_dia_mm: 22.23,
    width_inner_in: 1.000,
    width_inner_mm: 25.40,
    pin_dia_in: 0.437,
    pin_dia_mm: 11.10,
    plate_thickness_in: 0.187,
    plate_thickness_mm: 4.75,
    min_tensile_lbf: 34000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Large-log high-load infeed", "Timber framing production", "Heavy industrial conveying"],
    description: "Single-strand 1-1/2\" pitch SharpTop for very heavy log and timber applications. STD and PEP configurations available.",
    available_configs: ["STD", "5PEP"],
    standard_config: "STD",
    weight_by_config: { "STD": 4.5 },
    notes: "Base #120 ANSI chain.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-120-2",
    subcategory: "heavy_duty",
    chain_number: "120-2",
    display_name: "120-2 SharpTop Chain",
    pitch_in: 1.50,
    pitch_mm: 38.10,
    strands: 2,
    base_ansi: "120",
    weight_lbs_ft: null,
    roller_dia_in: 0.875,
    roller_dia_mm: 22.23,
    width_inner_in: 1.000,
    width_inner_mm: 25.40,
    pin_dia_in: 0.437,
    pin_dia_mm: 11.10,
    plate_thickness_in: 0.187,
    plate_thickness_mm: 4.75,
    min_tensile_lbf: 68000,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Large-diameter log infeed", "Heavy timber production"],
    description: "Double-strand 1-1/2\" pitch SharpTop. Connexus catalog item — STD and PEP available.",
    available_configs: ["STD", "5PEP"],
    standard_config: "STD",
    weight_by_config: {},
    notes: "Weight to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── SLASHER / LOW PROFILE ─────────────────────────────────────────────────
  {
    id: "st-80-1-sl",
    subcategory: "slasher_lp",
    chain_number: "80-1 SL-LP",
    display_name: "80-1 Slasher Low Profile",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 1,
    base_ansi: "80",
    weight_lbs_ft: 2.4,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 14500,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Slasher saws", "Cut-to-length (CTL) lines", "Bucking conveyors"],
    description: "Single-strand SL-LP SharpTop for slasher applications. Low-profile tip prevents binding in saw slots and reduces chain noise in high-speed CTL systems.",
    available_configs: ["SL-LP"],
    standard_config: "SL-LP",
    weight_by_config: { "SL-LP": 2.4 },
    notes: "SL-LP profile only for this application-specific chain.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-2-sl",
    subcategory: "slasher_lp",
    chain_number: "80-2 SL-LP",
    display_name: "80-2 Slasher Low Profile",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80",
    weight_lbs_ft: 4.4,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 29000,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Double-strand slasher", "High-speed CTL", "Bucking line infeed"],
    description: "Double-strand SL-LP for twin-track slasher and CTL infeed systems. The most common slasher configuration for modern cut-to-length processors.",
    available_configs: ["SL-LP"],
    standard_config: "SL-LP",
    weight_by_config: { "SL-LP": 4.4 },
    notes: "Renold part 10065167 (80-1 SL-LP, E2P). Confirm Renold 10065164 for 100-2 SL-LP.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-100-2-sl",
    subcategory: "slasher_lp",
    chain_number: "100-2 SL-LP",
    display_name: "100-2 Slasher Low Profile",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 2,
    base_ansi: "100",
    weight_lbs_ft: 6.3,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 48000,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Heavy-duty slasher", "Large log CTL", "High-capacity bucking"],
    description: "Double-strand 1-1/4\" SL-LP slasher chain for large-log cut-to-length applications. Renold part 10065164. Commonly used on Komatsu and John Deere CTL processors.",
    available_configs: ["SL-LP"],
    standard_config: "SL-LP",
    weight_by_config: { "SL-LP": 6.3 },
    notes: "Renold 10065164.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── WAFERIZER CHAINS ─────────────────────────────────────────────────────
  {
    id: "st-80-3-w2p",
    subcategory: "waferizer",
    chain_number: "80-3 W2P",
    display_name: "80-3 Waferizer Chain — W2P",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 3,
    base_ansi: "80",
    weight_lbs_ft: 5.7,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 43500,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Waferizer infeed", "Flaker infeed (OSB)", "Chip-n-saw infeed", "Particleboard plant"],
    description: "Triple-strand W2P waferizer chain — wide-profile tooth every 2nd pitch for positive log control feeding into waferizers (flakers). The Connexus standard for OSB and particleboard plant infeed.",
    available_configs: ["W2P"],
    standard_config: "W2P",
    weight_by_config: { "W2P": 5.7 },
    notes: "W2P = Waferizer Every 2nd Pitch. 80-3 base only. Not available on other strand counts.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
    featured: true,
  },
  {
    id: "st-80-3-w4p",
    subcategory: "waferizer",
    chain_number: "80-3 W4P",
    display_name: "80-3 Waferizer Chain — W4P",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 3,
    base_ansi: "80",
    weight_lbs_ft: 5.7,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 43500,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Waferizer infeed", "Slower feed waferizer", "Thick-wafer applications"],
    description: "Triple-strand W4P waferizer chain — wide-profile tooth every 4th pitch for slower, more controlled feeding into waferizers processing thicker flakes or denser species.",
    available_configs: ["W4P"],
    standard_config: "W4P",
    weight_by_config: { "W4P": 5.7 },
    notes: "W4P = Waferizer Every 4th Pitch. 80-3 base only.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── MULTI-POINT / PAD ─────────────────────────────────────────────────────
  {
    id: "st-80-2-p2pad",
    subcategory: "multi_point",
    chain_number: "80-2 P2PAD",
    display_name: "80-2 P2PAD Centering Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80",
    weight_lbs_ft: 4.4,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 29000,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Log centering before gang saws", "Alignment conveyors", "Profiler infeed"],
    description: "Double-strand P2PAD centering chain. Alternating-direction points every 2nd pitch push logs toward center line for precise gang saw or profiler alignment.",
    available_configs: ["P2PAD"],
    standard_config: "P2PAD",
    weight_by_config: { "P2PAD": 4.4 },
    notes: "P2PAD = Points Every 2nd Pitch Alternating Direction. Essential for accurate cant centering.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-80-2-p4pad",
    subcategory: "multi_point",
    chain_number: "80-2 P4PAD",
    display_name: "80-2 P4PAD Alignment Chain",
    pitch_in: 1.00,
    pitch_mm: 25.40,
    strands: 2,
    base_ansi: "80",
    weight_lbs_ft: null,
    roller_dia_in: 0.625,
    roller_dia_mm: 15.88,
    width_inner_in: 0.625,
    width_inner_mm: 15.88,
    pin_dia_in: 0.312,
    pin_dia_mm: 7.92,
    plate_thickness_in: 0.125,
    plate_thickness_mm: 3.18,
    min_tensile_lbf: 29000,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Sorting line alignment", "Variable-speed log positioning", "Profile control conveying"],
    description: "Double-strand P4PAD alignment chain. Points every 4th pitch with alternating direction — used in sorting lines where lighter grip and log repositioning is needed.",
    available_configs: ["P4PAD"],
    standard_config: "P4PAD",
    weight_by_config: {},
    notes: "Weight to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-100-2-p4pad",
    subcategory: "multi_point",
    chain_number: "100-2 P4PAD",
    display_name: "100-2 P4PAD Alignment Chain",
    pitch_in: 1.25,
    pitch_mm: 31.75,
    strands: 2,
    base_ansi: "100",
    weight_lbs_ft: 6.0,
    roller_dia_in: 0.750,
    roller_dia_mm: 19.05,
    width_inner_in: 0.750,
    width_inner_mm: 19.05,
    pin_dia_in: 0.375,
    pin_dia_mm: 9.53,
    plate_thickness_in: 0.156,
    plate_thickness_mm: 3.96,
    min_tensile_lbf: 48000,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated & Shot Peened",
    applications: ["Heavy log centering", "Large-log gang saw alignment", "Profiler infeed control"],
    description: "Heavy-duty P4PAD centering chain on 1-1/4\" pitch for large-log alignment applications. Points every 4th pitch in alternating direction.",
    available_configs: ["P4PAD"],
    standard_config: "P4PAD",
    weight_by_config: { "P4PAD": 6.0 },
    notes: "Connexus catalog item.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── LARGE PITCH SHARP CHAINS ──────────────────────────────────────────────
  {
    id: "st-3in",
    subcategory: "large_pitch",
    chain_number: '3" Sharp Chain',
    display_name: '3" Pitch Sharp Chain',
    pitch_in: 3.00,
    pitch_mm: 76.20,
    strands: 1,
    base_ansi: "Custom",
    weight_lbs_ft: 8.2,
    roller_dia_in: null,
    roller_dia_mm: null,
    width_inner_in: null,
    width_inner_mm: null,
    pin_dia_in: null,
    pin_dia_mm: null,
    plate_thickness_in: null,
    plate_thickness_mm: null,
    min_tensile_lbf: null,
    materials: "Alloy Steel",
    heat_treatment: "Heat Treated",
    applications: ["Heavy timber infeed", "Large-diameter log handling", "High-load industrial conveying", "Pulpwood handling"],
    description: "3\" pitch large sharp chain for heavy timber and large-diameter log infeed applications. Used where standard ANSI pitch sizes are insufficient for the load or speed requirements.",
    available_configs: ["STD"],
    standard_config: "STD",
    weight_by_config: { "STD": 8.2 },
    notes: "Connexus catalog item. Detailed specs to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-4in",
    subcategory: "large_pitch",
    chain_number: '4" Sharp Chain',
    display_name: '4" Pitch Sharp Chain',
    pitch_in: 4.00,
    pitch_mm: 101.60,
    strands: 1,
    base_ansi: "Custom",
    weight_lbs_ft: 5.0,
    roller_dia_in: null,
    roller_dia_mm: null,
    width_inner_in: null,
    width_inner_mm: null,
    pin_dia_in: null,
    pin_dia_mm: null,
    plate_thickness_in: null,
    plate_thickness_mm: null,
    min_tensile_lbf: null,
    materials: "Alloy Steel",
    heat_treatment: "Heat Treated",
    applications: ["Extra-heavy timber", "Pulpwood deck conveying", "Industrial heavy log handling"],
    description: "4\" pitch large sharp chain for extreme heavy-duty applications. Low weight-per-foot reflects wider pitch with fewer teeth per foot.",
    available_configs: ["STD"],
    standard_config: "STD",
    weight_by_config: { "STD": 5.0 },
    notes: "Connexus catalog item. Detailed specs to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-6in",
    subcategory: "large_pitch",
    chain_number: '6" Sharp Chain',
    display_name: '6" Pitch Sharp Chain',
    pitch_in: 6.00,
    pitch_mm: 152.40,
    strands: 1,
    base_ansi: "Custom",
    weight_lbs_ft: 18.5,
    roller_dia_in: null,
    roller_dia_mm: null,
    width_inner_in: null,
    width_inner_mm: null,
    pin_dia_in: null,
    pin_dia_mm: null,
    plate_thickness_in: null,
    plate_thickness_mm: null,
    min_tensile_lbf: null,
    materials: "Alloy Steel",
    heat_treatment: "Heat Treated",
    applications: ["Extreme load heavy timber", "Large industrial conveying", "Pulpwood yard handling"],
    description: "6\" pitch large sharp chain — the heaviest standard sharp chain in the Connexus catalog at 18.5 lbs/ft. For extreme-load heavy timber infeed and industrial conveying.",
    available_configs: ["STD"],
    standard_config: "STD",
    weight_by_config: { "STD": 18.5 },
    notes: "Connexus catalog item. Full specs to be confirmed by Uniking.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },

  // ── SPECIALTY / BS / METRIC ───────────────────────────────────────────────
  {
    id: "st-50-1",
    subcategory: "specialty",
    chain_number: "50-1",
    display_name: "50-1 SharpTop Chain",
    pitch_in: 0.625,
    pitch_mm: 15.875,
    strands: 1,
    base_ansi: "50",
    weight_lbs_ft: 2.3,
    roller_dia_in: 0.375,
    roller_dia_mm: 9.53,
    width_inner_in: 0.375,
    width_inner_mm: 9.53,
    pin_dia_in: 0.200,
    pin_dia_mm: 5.08,
    plate_thickness_in: 0.078,
    plate_thickness_mm: 1.98,
    min_tensile_lbf: 6100,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated",
    applications: ["Light-duty lumber handling", "Small-diameter material", "Planer mill"],
    description: "Single-strand 5/8\" pitch SharpTop with Summit Tip Design. Lighter-duty chain for small-dimension lumber and planer mill applications.",
    available_configs: ["50-STD"],
    standard_config: "50-STD",
    weight_by_config: { "50-STD": 2.3 },
    notes: "50 series Summit Tip only.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-50-2",
    subcategory: "specialty",
    chain_number: "50-2",
    display_name: "50-2 SharpTop Chain",
    pitch_in: 0.625,
    pitch_mm: 15.875,
    strands: 2,
    base_ansi: "50",
    weight_lbs_ft: 2.6,
    roller_dia_in: 0.375,
    roller_dia_mm: 9.53,
    width_inner_in: 0.375,
    width_inner_mm: 9.53,
    pin_dia_in: 0.200,
    pin_dia_mm: 5.08,
    plate_thickness_in: 0.078,
    plate_thickness_mm: 1.98,
    min_tensile_lbf: 12200,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated",
    applications: ["Double-strand light conveying", "Small-dimension lumber"],
    description: "Double-strand 5/8\" pitch SharpTop with Summit Tip. Used in twin-track light conveying for small-dimension lumber products.",
    available_configs: ["50-STD"],
    standard_config: "50-STD",
    weight_by_config: { "50-STD": 2.6 },
    notes: "50 series Summit Tip only.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-08b-3",
    subcategory: "specialty",
    chain_number: "08B-3",
    display_name: "08B-3 SharpTop Chain (BS 1/2\")",
    pitch_in: 0.50,
    pitch_mm: 12.70,
    strands: 3,
    base_ansi: "08B (BS)",
    weight_lbs_ft: 1.5,
    roller_dia_in: 0.312,
    roller_dia_mm: 7.92,
    width_inner_in: 0.312,
    width_inner_mm: 7.92,
    pin_dia_in: null,
    pin_dia_mm: null,
    plate_thickness_in: null,
    plate_thickness_mm: null,
    min_tensile_lbf: null,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated",
    applications: ["High-density material handling", "Small-section lumber", "Narrow conveyor applications"],
    description: "British Standard 1/2\" pitch triple-strand SharpTop with 6-point-per-pitch configuration. High tooth density for maximum grip on small-section material.",
    available_configs: ["08B-6P"],
    standard_config: "08B-6P",
    weight_by_config: { "08B-6P": 1.5 },
    notes: "BS 08B base. 6 points every pitch only.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-08b-6",
    subcategory: "specialty",
    chain_number: "08B-6",
    display_name: "08B-6 SharpTop Chain (BS 1/2\")",
    pitch_in: 0.50,
    pitch_mm: 12.70,
    strands: 6,
    base_ansi: "08B (BS)",
    weight_lbs_ft: 3.0,
    roller_dia_in: 0.312,
    roller_dia_mm: 7.92,
    width_inner_in: 0.312,
    width_inner_mm: 7.92,
    pin_dia_in: null,
    pin_dia_mm: null,
    plate_thickness_in: null,
    plate_thickness_mm: null,
    min_tensile_lbf: null,
    materials: "Carbon Steel",
    heat_treatment: "Heat Treated",
    applications: ["Wide-deck small-section", "High-density grip", "Specialty narrow conveying"],
    description: "British Standard 1/2\" pitch 6-strand SharpTop with 6-point-per-pitch configuration. Maximum grip density for specialty narrow conveying applications.",
    available_configs: ["08B-6P"],
    standard_config: "08B-6P",
    weight_by_config: { "08B-6P": 3.0 },
    notes: "BS 08B 6-strand base.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
  {
    id: "st-32b-1",
    subcategory: "specialty",
    chain_number: "32B-1",
    display_name: "32B-1 SharpTop Chain (BS 2\")",
    pitch_in: 2.00,
    pitch_mm: 50.80,
    strands: 1,
    base_ansi: "32B (BS)",
    weight_lbs_ft: 8.2,
    roller_dia_in: 1.378,
    roller_dia_mm: 35.00,
    width_inner_in: 1.181,
    width_inner_mm: 30.00,
    pin_dia_in: 0.551,
    pin_dia_mm: 14.00,
    plate_thickness_in: 0.217,
    plate_thickness_mm: 5.50,
    min_tensile_lbf: null,
    materials: "Carbon Steel, Alloy Steel",
    heat_treatment: "Heat Treated",
    applications: ["Heavy timber", "Large log handling", "Industrial heavy conveying"],
    description: "British Standard 2\" pitch SharpTop with DP (double point) configuration. Part 5269. Also available as 5202, 5167 variants. Used in heavy timber and large log infeed for European-market equipment.",
    available_configs: ["DP"],
    standard_config: "DP",
    weight_by_config: { "DP": 8.2 },
    notes: "32B BS base. DP profile (5269/5202/5167). Connexus catalog stock.",
    image_url: "https://www.cnxsind.com/wp-content/uploads/2021/08/hp-featurepic-chain.png",
  },
];

// ── Upgrade Options ───────────────────────────────────────────────────────────
export const SHARPTOP_UPGRADES = [
  {
    code: "IH",
    label: "Induction Hardened Tips",
    description: "Induction hardened sharp top plates for 3–5× longer tip life in abrasive or high-speed applications. Hardened inner links available.",
    available_on: "All chains",
    lead_time: "Custom — confirm with Uniking",
  },
  {
    code: "CHROME-PIN",
    label: "Chrome Pins",
    description: "Chrome-plated or chrome-alloy pins for enhanced corrosion resistance and reduced friction in wet environments.",
    available_on: "Most standard chains",
    lead_time: "Custom — confirm with Uniking",
  },
  {
    code: "ANTI-CORR",
    label: "Anti-Corrosion Coating",
    description: "Zinc or proprietary coating for marine, wet, or chemical-exposure environments. Extends chain life in high-humidity sawmill applications.",
    available_on: "Most standard chains",
    lead_time: "Custom — confirm with Uniking",
  },
  {
    code: "GROUND-BOTTOM",
    label: "Ground Bottom Surfaces",
    description: "Machined bottom guide rail surfaces for precise tracking on guide rail systems. Reduces wear on guide rails and improves chain alignment.",
    available_on: "Most standard chains",
    lead_time: "Custom — confirm with Uniking",
  },
  {
    code: "SOLID-CENTER",
    label: "Solid One-Piece Center Plates",
    description: "Solid forged center plates replace standard hollow-pin construction for maximum strength in high-shock applications.",
    available_on: "Selected chains",
    lead_time: "Custom — confirm with Uniking",
  },
  {
    code: "SS-PINS",
    label: "Stainless Steel Pins",
    description: "Stainless steel pins for food-grade or extreme corrosion environments. Maintains strength in wet and chemical washdown conditions.",
    available_on: "Most standard chains",
    lead_time: "Custom — confirm with Uniking",
  },
];

// ── Compatible Sprockets ───────────────────────────────────────────────────────
export const COMPATIBLE_SPROCKETS = {
  "60": [
    { teeth: [7,8,9,10,11,12,13,14,15,17,19,21], material: "Carbon Steel / Stainless", bore_options: "Stock bore or taper lock", note: "#60 standard ANSI sprockets" },
  ],
  "80": [
    { teeth: [7,8,9,10,11,12,13,14,15,17,19,21,23,25], material: "Carbon Steel / Alloy / Stainless", bore_options: "Stock bore, taper lock, QD bushing", note: "#80 standard ANSI sprockets" },
  ],
  "100": [
    { teeth: [7,8,9,10,11,12,13,14,15,17,19,21], material: "Carbon Steel / Alloy", bore_options: "Stock bore, taper lock, QD bushing", note: "#100 standard ANSI sprockets" },
  ],
  "120": [
    { teeth: [7,8,9,10,11,12,13,14,15,17,19], material: "Carbon Steel / Alloy", bore_options: "Stock bore, taper lock, QD bushing", note: "#120 standard ANSI sprockets" },
  ],
};

// ── Helper functions ──────────────────────────────────────────────────────────
export function getProductsBySubcategory(subKey) {
  return SHARPTOP_PRODUCTS.filter(p => p.subcategory === subKey);
}

export function getSubcategoryByKey(key) {
  return SHARPTOP_SUBCATEGORIES.find(s => s.key === key);
}

export function buildRFQLabel(product, configCode) {
  const cfg = TOOTH_CONFIGS[configCode];
  return `${product.chain_number} SharpTop Chain${cfg ? ` — ${cfg.shortLabel}` : ""}`;
}