// ─────────────────────────────────────────────────────────────────────────────
// Table Top Chain Catalog Data — NON-BRAND-SPECIFIC Procurement System
// Primary source:  Movex Catalog pp. 7–108 (Plastic & Steel Table Top Chains)
// Secondary source: System Plast Smart Guide (NGE, additional materials)
// Structure: Product-first, Material-normalized, Brand = secondary reference only
// ─────────────────────────────────────────────────────────────────────────────

// ── Normalized Material Definitions ──────────────────────────────────────────
export const MATERIALS = {
  // ─ Plastic Materials ──────────────────────────────────────────────────────
  ACETAL: {
    id: "ACETAL",
    name: "Standard Acetal",
    shortName: "Acetal",
    category: "Plastic",
    type: "Acetal Resin (POM)",
    color: "Natural / White",
    friction: "Medium",
    wear: "Good",
    chemical: "Good",
    tempRange: "-10 to +85°C (14 to 185°F)",
    applications: ["General conveying", "Dry applications", "Packaging lines"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#e0f2fe",
    badgeText: "#0369a1",
  },
  LF_ACETAL: {
    id: "LF_ACETAL",
    name: "Low Friction Acetal",
    shortName: "LF Acetal",
    category: "Plastic",
    type: "Low Friction Acetal Resin",
    color: "White / Grey",
    friction: "Low",
    wear: "Good",
    chemical: "Good",
    tempRange: "-10 to +85°C (14 to 185°F)",
    applications: ["High-speed lines", "Low-lubrication", "Beverage & food packaging", "Noise reduction"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#d1fae5",
    badgeText: "#065f46",
  },
  NGE: {
    id: "NGE",
    name: "NGE — New Generation Engineered",
    shortName: "NGE",
    category: "Plastic",
    type: "New Generation Engineered Resin",
    color: "Grey / Blue",
    friction: "Low",
    wear: "Excellent — longer than acetal",
    chemical: "Excellent",
    tempRange: "-10 to +85°C (14 to 185°F)",
    applications: ["Extended wear life", "Food processing", "High-speed low-lubrication", "FDA/EC 1935-2004"],
    availability: "System Plast exclusive",
    brandNote: "System Plast (Regal Rexnord) — exclusive",
    badge: "#ede9fe",
    badgeText: "#6d28d9",
    exclusive: true,
  },
  HF_RUBBER: {
    id: "HF_RUBBER",
    name: "High Friction (Rubber Top)",
    shortName: "HF Rubber",
    category: "Plastic",
    type: "Acetal Base + TPR Rubber Top",
    color: "White base / Black rubber",
    friction: "High",
    wear: "Good",
    chemical: "Good",
    tempRange: "-10 to +80°C (14 to 176°F)",
    applications: ["Incline / decline", "Grip conveying", "Anti-slip packaging", "Unstable containers"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#fef3c7",
    badgeText: "#92400e",
  },
  POLYPROP: {
    id: "POLYPROP",
    name: "Polypropylene",
    shortName: "PP",
    category: "Plastic",
    type: "Polypropylene",
    color: "Natural / Dark Grey",
    friction: "Low-Medium",
    wear: "Good",
    chemical: "Excellent",
    tempRange: "-10 to +100°C (14 to 212°F)",
    applications: ["Chemical environments", "Wet applications", "Acid/alkali resistance", "Lightweight systems"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#d1fae5",
    badgeText: "#065f46",
  },
  // ─ Steel Materials ──────────────────────────────────────────────────────
  STEEL_CARBON: {
    id: "STEEL_CARBON",
    name: "Carbon Steel",
    shortName: "Carbon Steel",
    category: "Steel",
    type: "Carbon Steel (Hardened)",
    color: "Steel / Silver",
    friction: "Low-Medium",
    wear: "Very Good",
    chemical: "Fair (requires lubrication)",
    tempRange: "-20 to +200°C (-4 to 392°F)",
    applications: ["Heavy duty conveying", "High-load applications", "Automotive parts", "Metal packaging"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#f1f5f9",
    badgeText: "#334155",
  },
  STEEL_SS304: {
    id: "STEEL_SS304",
    name: "Stainless Steel AISI 304",
    shortName: "SS 304",
    category: "Steel",
    type: "Stainless Steel AISI 304",
    color: "Bright Steel",
    friction: "Low-Medium",
    wear: "Very Good",
    chemical: "Excellent",
    tempRange: "-40 to +300°C (-40 to 572°F)",
    applications: ["Food processing", "Hygienic applications", "Washdown environments", "Corrosive environments"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#e0f2fe",
    badgeText: "#0369a1",
  },
  STEEL_SS316: {
    id: "STEEL_SS316",
    name: "Stainless Steel AISI 316",
    shortName: "SS 316",
    category: "Steel",
    type: "Stainless Steel AISI 316L",
    color: "Bright Steel",
    friction: "Low-Medium",
    wear: "Very Good",
    chemical: "Superior (molybdenum)",
    tempRange: "-40 to +300°C (-40 to 572°F)",
    applications: ["Aggressive chemicals", "Marine / offshore", "Pharmaceutical", "Salt & chloride environments"],
    availability: "Multi-source",
    brandNote: "Available from multiple manufacturers",
    badge: "#f0fdf4",
    badgeText: "#166534",
  },
};

// ── Image Base URLs (Movex PubLifarm CDN) ─────────────────────────────────────
const MX = "https://movexps.publifarm.com/img/p/";

// ── Chain Product Definitions ─────────────────────────────────────────────────
// Structure: category (Plastic/Steel) → type (Straight/Sideflex/etc.) → products

export const CHAIN_CATEGORIES = [
  {
    id: "plastic",
    label: "Plastic Table Top Chains",
    icon: "🔵",
    description: "Modular and slat-style plastic chains for food, beverage, and packaging conveying. Industry-standard pitches from 25.4 mm to 50.8 mm.",
    color: "#0057A8",
    types: [
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "plastic_straight",
        label: "Straight-Running Chains",
        description: "Standard straight-running table top chains for flat conveying. Most widely used type across all industries.",
        products: [
          {
            id: "820",
            series: "820 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/1/8751-large_default.jpg",
            shortDesc: "Classic 1-inch pitch flat top plastic chain. The industry benchmark for beverage and packaging conveying.",
            description: "The 820 series is the most widely used table top chain globally. 1-inch (25.4 mm) pitch, available in standard flat top and flush grid versions. Supported by the broadest material range across all suppliers.",
            applications: ["Beverage packaging", "Can conveying", "Bottle filling lines", "General food processing", "Packaging lines", "Light industrial"],
            features: ["1-inch pitch industry standard", "Widest material selection", "Multi-source availability", "Flat top and flush grid versions", "Side flexing versions available"],
            availableWidths: ["Single width per link — choose chain quantity for required belt width"],
            materials: ["ACETAL", "LF_ACETAL", "NGE", "HF_RUBBER", "POLYPROP"],
            catalogRef: "Movex p.11 / System Plast Smart Guide",
          },
          {
            id: "821",
            series: "821 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/2/8752-large_default.jpg",
            shortDesc: "1-inch pitch, wider tab version for enhanced product support on flat top conveying.",
            description: "821 series is a wider-tab variant of the 820 series at 1-inch (25.4 mm) pitch. Enhanced product contact area. Commonly used in packaging and bottling where a wider top surface is required.",
            applications: ["Packaging with wide products", "Bottling lines", "Container handling", "General food processing"],
            features: ["Wider tab than 820", "1-inch pitch", "Extended product support surface", "Reduced product tipping"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE"],
            catalogRef: "Movex p.15",
          },
          {
            id: "881",
            series: "881 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/5/8755-large_default.jpg",
            shortDesc: "1-inch pitch raised rib chain. Provides controlled product positioning and reduced contact area.",
            description: "881 series: 1-inch pitch plastic chain with raised ribs on the top surface. Reduces contact area between product and chain, allowing air circulation and drainage. Used in pasteurizer and tunnel washer applications.",
            applications: ["Pasteurizers", "Tunnel washers", "Baking / cooling", "Drainage applications", "Raised product positioning"],
            features: ["Raised rib surface", "Reduced product contact area", "Drainage capability", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE", "POLYPROP"],
            catalogRef: "Movex p.22",
          },
          {
            id: "880",
            series: "880 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/4/8754-large_default.jpg",
            shortDesc: "1-inch pitch open hinge flat top — maximum hygiene with easy cleaning access.",
            description: "880 series: 1-inch pitch open hinge flat top chain. Open hinge design allows thorough cleaning and inspection. Preferred in food processing and hygienic applications where debris accumulation in the hinge must be prevented.",
            applications: ["Hygienic food processing", "Meat & poultry", "Seafood processing", "Washdown environments", "Direct food contact"],
            features: ["Open hinge design", "Maximum cleanability", "Hygienic configuration", "1-inch pitch", "Food-grade materials"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE", "POLYPROP"],
            catalogRef: "Movex p.20",
          },
          {
            id: "882",
            series: "882 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/6/8756-large_default.jpg",
            shortDesc: "1-inch pitch flush grid chain — excellent drainage and airflow.",
            description: "882 series: 1-inch pitch plastic flush grid chain. Open surface area for drainage, cooling, and airflow. Standard choice for tunnel washers, pasteurizers, and cooling conveyors.",
            applications: ["Tunnel washers", "Pasteurizers", "Cooling conveyors", "Drainage applications", "Airflow required"],
            features: ["Flush grid open surface", "Drainage and airflow", "1-inch pitch", "Food-grade options"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE", "POLYPROP"],
            catalogRef: "Movex p.24",
          },
          {
            id: "821H",
            series: "821H Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/5/3/8753-large_default.jpg",
            shortDesc: "1-inch pitch heavy duty tab chain for high load conveying.",
            description: "821H series: Heavy duty 1-inch pitch chain with reinforced construction for high-load and demanding applications. Higher tensile strength than standard 820/821.",
            applications: ["Heavy load conveying", "Industrial packaging", "Automotive assembly"],
            features: ["Heavy duty construction", "Higher tensile strength", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL"],
            catalogRef: "Movex p.18",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "plastic_sideflex",
        label: "Sideflexing Chains",
        description: "Plastic chains designed to navigate horizontal curves without curve tracks — using the chain's natural sideFlex capability.",
        products: [
          {
            id: "820_SF",
            series: "820 Sideflex Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/0/8760-large_default.jpg",
            shortDesc: "1-inch pitch sideflexing plastic chain for horizontal curves.",
            description: "820 Sideflex series: 1-inch pitch plastic chain engineered for sideflexing in horizontal curves. Collapse factor enables the chain to run through fixed-radius curves without dedicated curve frames in all configurations.",
            applications: ["Horizontal curves", "Multi-directional layouts", "Curved food processing lines", "Bottling curve conveyors"],
            features: ["Side flexing design", "1-inch pitch", "Collapse factor for tight curves", "Flat top surface"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE"],
            catalogRef: "Movex p.35",
          },
          {
            id: "880_SF",
            series: "880 Sideflex Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/1/8761-large_default.jpg",
            shortDesc: "1-inch pitch open hinge sideflexing — hygienic curved conveying.",
            description: "880 Sideflex: Open hinge 1-inch pitch sideflexing chain. Combines the hygienic open hinge design with sideflexing capability for curved food processing lines.",
            applications: ["Curved hygienic lines", "Food processing curves", "Open hinge + curve layout"],
            features: ["Open hinge + sideflexing", "1-inch pitch", "Hygienic design"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE"],
            catalogRef: "Movex p.38",
          },
          {
            id: "884",
            series: "884 Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/2/8762-large_default.jpg",
            shortDesc: "1-inch pitch sideflexing flush grid chain for curved drainage applications.",
            description: "884 series: 1-inch pitch sideflexing flush grid chain. Combines drainage capability with horizontal curve navigation. Used in tunnel washers and pasteurizers with curved layouts.",
            applications: ["Curved tunnel washers", "Curved pasteurizers", "Drainage + curves"],
            features: ["Sideflexing + flush grid", "1-inch pitch", "Drainage on curves"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "POLYPROP"],
            catalogRef: "Movex p.40",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "plastic_lbp",
        label: "Low Back Pressure Chains",
        description: "Chains with integrated rollers or special hinge designs for low backpressure accumulation — reducing product damage at accumulation points.",
        products: [
          {
            id: "820_LBP",
            series: "820 LBP Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/5/8765-large_default.jpg",
            shortDesc: "Low back pressure chain with integrated rollers — protects products at accumulation.",
            description: "820 LBP series: 1-inch pitch plastic table top chain with integrated roller inserts. Rollers spin freely, reducing the back pressure force on accumulated products. Standard choice for accumulation zones in beverage and packaging lines.",
            applications: ["Accumulation zones", "Beverage line accumulation", "Fragile product handling", "Gentle stop/go conveying"],
            features: ["Integrated roller inserts", "Reduced backpressure force", "1-inch pitch", "Protects fragile containers"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL"],
            catalogRef: "Movex p.45",
          },
          {
            id: "880_LBP",
            series: "880 LBP Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/6/8766-large_default.jpg",
            shortDesc: "Open hinge low back pressure chain — hygienic accumulation.",
            description: "880 LBP: Open hinge 1-inch pitch with roller inserts for low backpressure accumulation in hygienic environments. Open hinge ensures full washdown capability.",
            applications: ["Hygienic accumulation", "Food processing accumulation", "Fragile product + hygiene"],
            features: ["Open hinge + LBP rollers", "Hygienic design", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "NGE"],
            catalogRef: "Movex p.48",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "plastic_highfriction",
        label: "High Friction Chains",
        description: "Chains with rubber or textured top surfaces for incline conveying and anti-slip applications.",
        products: [
          {
            id: "820_HF",
            series: "820 High Friction Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/3/8763-large_default.jpg",
            shortDesc: "1-inch pitch flat top with rubber or friction top inserts for incline conveying.",
            description: "820 High Friction series: 1-inch pitch plastic table top chain with rubber or high-friction top inserts. Prevents product slippage on inclines and declines. Available in full rubber top or friction insert versions.",
            applications: ["Incline/decline conveying", "Anti-slip packaging", "Unstable containers", "High-angle conveying"],
            features: ["Rubber or friction top inserts", "Incline/decline rated", "1-inch pitch", "Anti-slip surface"],
            availableWidths: ["Standard industry widths"],
            materials: ["HF_RUBBER"],
            catalogRef: "Movex p.50",
          },
          {
            id: "880_HF",
            series: "880 High Friction Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Plastic",
            image: MX + "8/7/6/4/8764-large_default.jpg",
            shortDesc: "Open hinge high friction chain — hygienic incline conveying.",
            description: "880 High Friction: Open hinge 1-inch pitch with rubber top inserts. Combines hygienic open hinge design with grip top for incline conveying in food processing.",
            applications: ["Food processing inclines", "Hygienic + anti-slip", "Meat & poultry inclines"],
            features: ["Open hinge + rubber top", "Hygienic + grip design", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["HF_RUBBER"],
            catalogRef: "Movex p.52",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "plastic_case",
        label: "Case Conveyor Chains",
        description: "Wider pitch plastic chains for case and carton conveying. Typically 1.5-inch (38.1 mm) or 2-inch (50.8 mm) pitch.",
        products: [
          {
            id: "820_2",
            series: "820-2 Series",
            pitch_mm: 50.8,
            pitch_in: "2\"",
            chainType: "Plastic",
            image: MX + "8/7/7/0/8770-large_default.jpg",
            shortDesc: "2-inch pitch flat top chain for case and carton conveying.",
            description: "820-2 series: 2-inch (50.8 mm) pitch plastic flat top chain for case and carton conveying. Wider pitch provides better support for larger products. Commonly used in end-of-line case conveying and palletizing infeed.",
            applications: ["Case conveying", "Carton handling", "Palletizing infeed", "Case packing lines", "Distribution centers"],
            features: ["2-inch pitch", "Wider product support", "Low profile", "Case conveying optimized"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL", "POLYPROP"],
            catalogRef: "Movex p.60",
          },
          {
            id: "826",
            series: "826 Series",
            pitch_mm: 38.1,
            pitch_in: "1.5\"",
            chainType: "Plastic",
            image: MX + "8/7/7/1/8771-large_default.jpg",
            shortDesc: "1.5-inch pitch multi-flex chain for medium case conveying.",
            description: "826 series: 1.5-inch (38.1 mm) pitch plastic table top chain. Bridges the gap between the standard 1-inch and 2-inch pitch chains. Used for medium-size cases and cartons.",
            applications: ["Medium case conveying", "Carton lines", "Mixed product lines"],
            features: ["1.5-inch pitch", "Medium case conveying", "Flex capability"],
            availableWidths: ["Standard industry widths"],
            materials: ["ACETAL", "LF_ACETAL"],
            catalogRef: "Movex p.65",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "steel",
    label: "Steel Table Top Chains",
    icon: "⚙️",
    description: "Carbon and stainless steel table top chains for heavy duty, high temperature, and hygienic applications. Industry pitches from 25.4 mm (1\") to 50.8 mm (2\").",
    color: "#374151",
    types: [
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "steel_straight",
        label: "Straight-Running Steel Chains",
        description: "Standard straight-running steel table top chains. Higher load capacity and temperature resistance than plastic.",
        products: [
          {
            id: "820S",
            series: "820 Steel Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Steel",
            image: MX + "8/7/8/0/8780-large_default.jpg",
            shortDesc: "1-inch pitch steel flat top chain — heavy duty and high temperature rated.",
            description: "820 Steel series: 1-inch pitch steel table top chain. High load capacity, high temperature capability, and excellent durability. Available in carbon steel and stainless steel AISI 304/316. Standard choice for baking, canning, and heavy industrial conveying.",
            applications: ["Baking & oven conveying", "Canning lines", "Heavy load conveying", "High temperature applications", "Washdown (SS versions)"],
            features: ["1-inch pitch steel", "High load capacity", "High temperature rated", "Carbon and stainless steel options"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304", "STEEL_SS316"],
            catalogRef: "Movex p.75",
          },
          {
            id: "881S",
            series: "881 Steel Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Steel",
            image: MX + "8/7/8/1/8781-large_default.jpg",
            shortDesc: "1-inch pitch steel raised rib chain — high temperature with drainage.",
            description: "881 Steel series: 1-inch pitch steel raised rib chain. Combines the raised rib surface profile with steel construction for high-temperature drainage applications. Used in baking, blanching, and industrial washdown.",
            applications: ["Baking conveyors", "Blanching lines", "High-temperature drainage", "Industrial washdown"],
            features: ["Raised rib + steel", "High temperature", "Drainage capable", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304", "STEEL_SS316"],
            catalogRef: "Movex p.80",
          },
          {
            id: "882S",
            series: "882 Steel Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Steel",
            image: MX + "8/7/8/2/8782-large_default.jpg",
            shortDesc: "1-inch pitch steel flush grid chain — high temp drainage.",
            description: "882 Steel series: 1-inch pitch steel flush grid chain for high temperature drainage applications. Open grid surface allows liquids and debris to fall through. Used in food processing, baking, and industrial high-temperature washdown.",
            applications: ["High-temp washdown", "Baking drainage", "Industrial drainage", "Hygienic SS drainage"],
            features: ["Flush grid + steel", "High temperature drainage", "1-inch pitch"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304", "STEEL_SS316"],
            catalogRef: "Movex p.83",
          },
          {
            id: "850S",
            series: "850 Steel Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Steel",
            image: MX + "8/7/8/3/8783-large_default.jpg",
            shortDesc: "1-inch pitch heavy duty steel chain with reinforced hinge.",
            description: "850 Steel series: Heavy duty 1-inch pitch steel chain with reinforced hinge. Designed for very high tensile loads. Used in heavy manufacturing, metal stamping, and automotive assembly lines.",
            applications: ["Heavy manufacturing", "Metal stamping lines", "Automotive assembly", "Very high load conveying"],
            features: ["Heavy duty hinge", "High tensile strength", "1-inch pitch steel", "Industrial grade"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304"],
            catalogRef: "Movex p.87",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "steel_sideflex",
        label: "Sideflexing Steel Chains",
        description: "Steel table top chains with sideflexing capability for high-temperature or heavy-duty curved conveyor layouts.",
        products: [
          {
            id: "820S_SF",
            series: "820 Steel Sideflex Series",
            pitch_mm: 25.4,
            pitch_in: "1\"",
            chainType: "Steel",
            image: MX + "8/7/8/5/8785-large_default.jpg",
            shortDesc: "1-inch pitch sideflexing steel chain for high-temp curved conveyors.",
            description: "820 Steel Sideflex: 1-inch pitch steel chain engineered for sideflexing in horizontal curves. Enables high-temperature or high-load curved conveyor layouts without dedicated plastic curve chains.",
            applications: ["High-temp curved conveyors", "Heavy duty curve systems", "Steel + curve layout"],
            features: ["Sideflexing steel design", "1-inch pitch", "High temperature capable"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304"],
            catalogRef: "Movex p.91",
          },
        ],
      },
      // ─────────────────────────────────────────────────────────────────────
      {
        id: "steel_case",
        label: "Steel Case Conveyor Chains",
        description: "Wider pitch steel chains for heavy case and carton conveying in industrial environments.",
        products: [
          {
            id: "820S_2",
            series: "820 Steel 2-Inch Series",
            pitch_mm: 50.8,
            pitch_in: "2\"",
            chainType: "Steel",
            image: MX + "8/7/8/6/8786-large_default.jpg",
            shortDesc: "2-inch pitch steel flat top chain for heavy case and industrial conveying.",
            description: "820 Steel 2-inch series: 2-inch (50.8 mm) pitch steel flat top chain for heavy case, pallet, and industrial conveying. High tensile load capacity. Available in carbon steel and stainless steel.",
            applications: ["Heavy case conveying", "Pallet infeed", "Industrial bulk handling", "High load end-of-line"],
            features: ["2-inch pitch steel", "High tensile load", "Carbon and SS options"],
            availableWidths: ["Standard industry widths"],
            materials: ["STEEL_CARBON", "STEEL_SS304"],
            catalogRef: "Movex p.97",
          },
        ],
      },
    ],
  },
];

// ── Flatten all products for search ──────────────────────────────────────────
export function getAllProducts() {
  const products = [];
  for (const cat of CHAIN_CATEGORIES) {
    for (const type of cat.types) {
      for (const product of type.products) {
        products.push({ ...product, categoryId: cat.id, categoryLabel: cat.label, typeId: type.id, typeLabel: type.label });
      }
    }
  }
  return products;
}

export function getProductById(id) {
  for (const cat of CHAIN_CATEGORIES) {
    for (const type of cat.types) {
      const found = type.products.find(p => p.id === id);
      if (found) return { ...found, categoryId: cat.id, categoryLabel: cat.label, typeId: type.id, typeLabel: type.label };
    }
  }
  return null;
}