/**
 * Table Top Chain unified product data
 * Source: Movex Imperial Catalog pages 7–108 (primary) + System Plast Smart Guide (materials)
 * Product-first, brand-neutral. Brand only shown for exclusive materials.
 */

// ─── Normalized Material Library ─────────────────────────────────────────────
export const MATERIALS = {
  LF: {
    id: "LF",
    name: "Low Friction Acetal",
    category: "Plastic",
    type: "LF Acetal",
    friction: "Low (µ ≈ 0.10–0.15)",
    wearResistance: "High",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "General conveying, beverage, food packaging, dry & wet environments",
    availability: "Standard",
    brand: null, // multi-source
    color: "#e0f2fe",
    badge: "Most Common",
  },
  MX: {
    id: "MX",
    name: "Performance PBT",
    category: "Plastic",
    type: "PBT (Polybutylene Terephthalate)",
    friction: "Low–Medium (µ ≈ 0.12–0.18)",
    wearResistance: "Very High",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "High-speed lines, chemical environments, elevated temperatures",
    availability: "Standard",
    brand: null,
    color: "#f0fdf4",
    badge: "High Performance",
  },
  PFX: {
    id: "PFX",
    name: "PFX Dry-Run PBT",
    category: "Plastic",
    type: "Extra Performance PBT",
    friction: "Very Low (µ ≈ 0.08–0.12)",
    wearResistance: "Excellent",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "Dry-run applications, PET bottle lines, limited lubrication environments",
    availability: "Standard",
    brand: "Movex (exclusive formulation)",
    color: "#fefce8",
    badge: "Dry-Run Optimized",
  },
  MPX: {
    id: "MPX",
    name: "Lubricated Acetal",
    category: "Plastic",
    type: "MPX Acetal",
    friction: "Very Low (µ ≈ 0.08–0.12)",
    wearResistance: "High",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "Lube-free or minimal-lube lines, accumulation conveyors",
    availability: "Standard",
    brand: null,
    color: "#fef9c3",
    badge: null,
  },
  DKM: {
    id: "DKM",
    name: "Aramid-Reinforced Acetal",
    category: "Plastic",
    type: "DKM Acetal Composite",
    friction: "Medium (µ ≈ 0.15–0.20)",
    wearResistance: "Exceptional",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "Heavy-load lines, abrasive products, long conveyors requiring high tensile strength",
    availability: "On request",
    brand: null,
    color: "#fdf4ff",
    badge: "Heavy Duty",
  },
  MWX: {
    id: "MWX",
    name: "Polyamide Composite",
    category: "Plastic",
    type: "MWX PA Composite",
    friction: "Medium (µ ≈ 0.18–0.25)",
    wearResistance: "Very High",
    chemicalResistance: "Moderate",
    tempRange: "-40°F to +212°F (-40°C to +100°C)",
    applications: "Wet/hot environments, food processing with frequent washdowns",
    availability: "On request",
    brand: null,
    color: "#f0f9ff",
    badge: null,
  },
  GT: {
    id: "GT",
    name: "Grip Top (TPE Rubber Insert)",
    category: "Plastic",
    type: "Acetal + TPE Rubber (50 ShA)",
    friction: "Very High (rubber grip)",
    wearResistance: "Moderate",
    chemicalResistance: "Good",
    tempRange: "-20°F to +140°F (-30°C to +60°C)",
    applications: "Incline/decline conveying, unstable containers, grip-critical applications",
    availability: "Standard",
    brand: null,
    color: "#fff7ed",
    badge: "High Friction",
  },
  NGE: {
    id: "NGE",
    name: "NGE (Next Generation Engineering)",
    category: "Plastic",
    type: "NGE Composite (Regal Rexnord)",
    friction: "Very Low (µ ≈ 0.07–0.10)",
    wearResistance: "Outstanding — 3–5× standard acetal",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "Extended service life, high-speed lines, reduced maintenance, dry-lube environments",
    availability: "On request",
    brand: "System Plast (exclusive)",
    color: "#ecfdf5",
    badge: "Extended Life",
  },
  SS: {
    id: "SS",
    name: "Stainless Steel",
    category: "Steel",
    type: "AISI 304 / 316 Stainless Steel",
    friction: "Low–Medium",
    wearResistance: "High",
    chemicalResistance: "Excellent",
    tempRange: "-100°F to +500°F (-73°C to +260°C)",
    applications: "Food & beverage, washdown environments, high temperatures, corrosive conditions",
    availability: "Standard",
    brand: null,
    color: "#f8fafc",
    badge: "Food Grade",
  },
  CS: {
    id: "CS",
    name: "Carbon Steel",
    category: "Steel",
    type: "Carbon Steel",
    friction: "Medium",
    wearResistance: "High",
    chemicalResistance: "Low (requires lubrication)",
    tempRange: "-40°F to +400°F (-40°C to +200°C)",
    applications: "General industrial, non-corrosive dry environments, heavy loads",
    availability: "Standard",
    brand: null,
    color: "#f1f5f9",
    badge: null,
  },
};

// ─── Product Catalog ──────────────────────────────────────────────────────────

export const CHAIN_CATEGORIES = {
  PLASTIC: "Plastic Table Top Chains",
  STEEL: "Steel Table Top Chains",
};

export const CHAIN_TYPES = {
  STRAIGHT: "Straight Running",
  SIDEFLEX: "Sideflexing",
  HEAVY: "Heavy Duty",
  LBP: "Low Back Pressure",
  HIGH_FRICTION: "High Friction",
  CASE: "Case Conveyor",
  MICRO: "Micro Pitch",
  FLUSH_GRID: "Flush Grid / Open",
};

// Image base URLs from movexii.com CDN
const IMG = "https://movexps.publifarm.com/img/p";

export const CHAIN_PRODUCTS = [

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — STRAIGHT RUNNING
  // ═══════════════════════════════════════════════════════════
  {
    id: "820",
    name: "820 Series",
    series: "820",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "The industry-standard flat top chain for general conveying. Improved design with 45% less open gap and 15% more contact surface for superior product stability.",
    features: [
      "Improved design — 45% smaller open gap",
      "15% increased contact surface",
      "Fully interchangeable with previous design",
      "Stainless steel connecting pins (standard)",
      "Plastic pin variant available",
    ],
    applications: ["Beverage", "Food packaging", "General manufacturing", "Light assembly"],
    widths: ['3.25"', '3.30"', '3.50"', '4.00"', '4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "365 lbs", MX: "284 lbs", PFX: "284 lbs", MPX: "365 lbs", DKM: "365 lbs", MWX: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX", "DKM", "MWX"],
    image: `${IMG}/1/0/6/9/2/10692-large_default.jpg`,
    catalogPage: "9–11",
  },
  {
    id: "820V",
    name: "820 V Series",
    series: "820 V",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Vacuum-belt variant of the 820 with perforated top for vacuum conveying applications.",
    features: [
      "Perforated top plate for vacuum holding",
      "Same improved design as standard 820",
      "Stainless steel pins",
    ],
    applications: ["Vacuum conveying", "Packaging", "Label application stations"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/6/9/3/10693-large_default.jpg`,
    catalogPage: "11",
  },
  {
    id: "828",
    name: "828 Series",
    series: "828",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Heavy-bodied straight-running flat top chain with higher load capacity than the 820. Wide flat top surface for stable product transport.",
    features: [
      "Higher load capacity than 820 series",
      "Wide flat plate top",
      "Stainless steel connecting pins",
    ],
    applications: ["Beverage cans", "Heavier containers", "Food processing", "General packaging"],
    widths: ['3.25"', '3.30"'],
    maxLoad: { LF: "522 lbs", MX: "418 lbs", PFX: "418 lbs", MPX: "522 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX"],
    image: `${IMG}/1/0/6/9/8/10698-large_default.jpg`,
    catalogPage: "12",
  },
  {
    id: "831",
    name: "831 Series",
    series: "831",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Straight-running chain with slightly raised rib profile for improved product stability. Ideal for containers with unstable bases.",
    features: [
      "Raised rib top surface",
      "Improved container stability",
      "Stainless steel pins",
    ],
    applications: ["Unstable containers", "Cans & bottles", "Light manufacturing"],
    widths: ['3.25"', '4.50"', '7.50"'],
    maxLoad: { LF: "365 lbs", MX: "284 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/9/10699-large_default.jpg`,
    catalogPage: "13",
  },
  {
    id: "821",
    name: "821 Series",
    series: "821",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch flat top chain designed for large containers and heavy loads. The go-to choice for case conveying on wide conveyors.",
    features: [
      '1.5" pitch for higher load capacity',
      "Wide flat top plate",
      "Suitable for cases and heavy products",
      "Stainless steel connecting pins",
    ],
    applications: ["Case conveying", "Boxes & cartons", "Heavy packaging", "Distribution centers"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "623 lbs", MX: "495 lbs", MPX: "623 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "MPX"],
    image: `${IMG}/1/0/6/9/5/10695-large_default.jpg`,
    catalogPage: "14",
  },
  {
    id: "821GT",
    name: "821 GT Series",
    series: "821 GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "821 series with integrated TPE rubber grip top insert. Provides exceptional friction for inclines and unstable products.",
    features: [
      "Integrated TPE rubber grip insert (50 ShA)",
      '1.5" pitch wide plate',
      "Excellent grip for inclines up to 30°",
      "Stainless steel pins",
    ],
    applications: ["Incline/decline conveyors", "Cases & unstable products", "Packaging lines"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "623 lbs", MX: "495 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/6/10696-large_default.jpg`,
    catalogPage: "15",
  },
  {
    id: "821LBP",
    name: "821 LBP Series",
    series: "821 LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Low back pressure variant of the 821 for accumulation lines where gentle product handling is critical.",
    features: [
      "Low back pressure design",
      "Roller bottom for accumulation",
      "Reduced product-to-chain contact pressure",
      "Ideal for sensitive containers",
    ],
    applications: ["Accumulation lines", "Dead-plate transfers", "Glass bottles", "Fragile containers"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/7/10697-large_default.jpg`,
    catalogPage: "16",
  },

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — SIDEFLEXING
  // ═══════════════════════════════════════════════════════════
  {
    id: "8257",
    name: "8257 Series",
    series: "8257",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Sideflexing flat top chain for curved conveyor sections. Achieves tight curve radii without additional curved sections.",
    features: [
      "True sideflexing capability",
      "Smooth transition through curves",
      "Flat top surface for stable transport",
      "Stainless steel pins",
    ],
    applications: ["Curved conveyors", "Beverage lines", "Space-saving layouts", "Food & beverage"],
    widths: ['3.25"', '3.30"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/5/10725-large_default.jpg`,
    catalogPage: "17",
  },
  {
    id: "8257GT",
    name: "8257 GT Series",
    series: "8257 GT",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Sideflexing chain with TPE rubber grip top for curved sections requiring additional friction.",
    features: [
      "Sideflexing with grip top",
      "TPE rubber insert (50 ShA)",
      "Curved layout with high friction",
    ],
    applications: ["Curved incline sections", "Grip conveying through curves", "Packaging"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/6/10726-large_default.jpg`,
    catalogPage: "18",
  },
  {
    id: "8257LBP",
    name: "8257 LBP Series",
    series: "8257 LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Low back pressure sideflexing chain for curved accumulation lines with fragile products.",
    features: [
      "Sideflexing + low back pressure",
      "Roller underside for accumulation in curves",
      "Gentle on fragile containers",
    ],
    applications: ["Curved accumulation", "Glass & PET bottles through curves", "Fragile products"],
    widths: ['3.25"', '3.50"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/7/10727-large_default.jpg`,
    catalogPage: "19",
  },
  {
    id: "878TAB",
    name: "878 TAB Series",
    series: "878 TAB",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "TAB (Tab-design) sideflexing chain providing curve retention in tight-radius applications.",
    features: [
      "TAB side retention design",
      "Sideflexing through curves",
      "Secure product containment",
      "Stainless steel pins",
    ],
    applications: ["Tight-radius curves", "Beverage lines", "Can conveying", "Curved sections"],
    widths: ['3.25"', '3.50"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/0/10700-large_default.jpg`,
    catalogPage: "20",
  },

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — HEAVY DUTY (879 / 880 / 882 family)
  // ═══════════════════════════════════════════════════════════
  {
    id: "879M",
    name: "879 M Series",
    series: "879 M",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing flat top chain. Large format body with high tensile strength for demanding curved applications.",
    features: [
      '1.5" pitch for maximum load',
      "Sideflexing capability",
      "Heavy-duty construction",
      "Stainless steel pins",
    ],
    applications: ["Heavy load curves", "Automotive", "Industrial", "Large container conveying"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/4/10704-large_default.jpg`,
    catalogPage: "21",
  },
  {
    id: "879TAB",
    name: "879 TAB Series",
    series: "879 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "TAB-design heavy-duty sideflexing chain with curve retention tabs. Prevents derailment on tight, high-load curves.",
    features: [
      "TAB retention design prevents derailment",
      '1.5" pitch heavy-duty body',
      "Curve-stable under high loads",
      "Stainless steel pins",
    ],
    applications: ["High-load curved conveyors", "Automotive", "Heavy packaging", "Logistics"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/5/10705-large_default.jpg`,
    catalogPage: "22",
  },
  {
    id: "888TAB",
    name: "888 TAB Series",
    series: "888 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch TAB flat top chain providing maximum load capacity and stable sideflexing. Premium heavy-duty chain for demanding applications.",
    features: [
      "Maximum flat-top coverage",
      "TAB design for curve retention",
      "Very high load capacity",
      "Stainless steel pins",
    ],
    applications: ["Maximum-load conveying", "Large containers", "Automotive assembly", "Logistics sortation"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/7/10707-large_default.jpg`,
    catalogPage: "23",
  },
  {
    id: "880TAB",
    name: "880 TAB Series",
    series: "880 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "The flagship heavy-duty sideflexing flat top chain family. Dominant in beverage and food for high-speed, high-load curve applications.",
    features: [
      "Industry-standard heavy-duty sideflexing",
      "TAB retention for curve stability",
      "Multiple materials and pin options",
      "Wide range of widths available",
    ],
    applications: ["Beverage", "Food processing", "High-speed curved conveyors", "PET lines"],
    widths: ['3.25"', '3.30"', '3.50"', '4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking", MX: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX"],
    image: `${IMG}/1/0/7/0/6/10706-large_default.jpg`,
    catalogPage: "26",
  },
  {
    id: "880M",
    name: "880 M Series",
    series: "880 M",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Sideflexing flat top chain without TAB design for standard curved conveyor applications.",
    features: [
      "Smooth sideflexing",
      '1.5" pitch',
      "Versatile curved conveying",
    ],
    applications: ["Curved conveyors", "Beverage", "General food processing"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/8/10708-large_default.jpg`,
    catalogPage: "25",
  },
  {
    id: "882M",
    name: "882 M Series",
    series: "882 M",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing chain with higher strength plate for maximum load on long curve sections.",
    features: [
      "Higher tensile strength plate",
      "Sideflexing for curved layouts",
      "Heavy-duty load rating",
      "Stainless steel pins",
    ],
    applications: ["Long curve sections", "High-load curved conveying", "Industrial applications"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "MPX"],
    image: `${IMG}/1/0/7/1/3/10713-large_default.jpg`,
    catalogPage: "30",
  },
  {
    id: "882TAB",
    name: "882 TAB Series",
    series: "882 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 body with TAB curve retention. The premium heavy-duty sideflexing chain for maximum-load curved conveying.",
    features: [
      "Maximum load capacity in class",
      "TAB retention prevents chain derailment",
      "Sideflexing for tight curves",
      "Multiple material options",
    ],
    applications: ["Maximum-load curves", "Automotive", "Heavy industrial", "Large format conveying"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/5/10715-large_default.jpg`,
    catalogPage: "33",
  },

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — SPECIAL / HIGH FRICTION
  // ═══════════════════════════════════════════════════════════
  {
    id: "1873",
    name: "1873 Series",
    series: "1873",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Large-format heavy-duty plastic chain for demanding case and carton conveying on straight sections.",
    features: [
      "Extra-wide top plate",
      "Heavy-duty straight running",
      "Multiple grip/tab variants available",
      "Stainless steel pins",
    ],
    applications: ["Case & carton conveying", "Logistics", "Distribution centers", "Heavy packaging"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/8/10718-large_default.jpg`,
    catalogPage: "36",
  },
  {
    id: "CC600",
    name: "CC 600 Series",
    series: "CC 600",
    category: "PLASTIC",
    type: "CASE",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Case conveyor chain specifically designed for cardboard box and tray conveying on high-speed distribution lines.",
    features: [
      "Optimized for case conveying",
      "High friction top options available",
      "TAB variant for curve sections",
      "Robust case-handling design",
    ],
    applications: ["Case conveying", "Distribution centers", "E-commerce", "Cardboard trays & boxes"],
    widths: ['4.50"', '6.00"', '7.50"', '10.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "GT"],
    image: `${IMG}/1/0/6/7/9/10679-large_default.jpg`,
    catalogPage: "49",
  },
  {
    id: "1701TABOP",
    name: "1701 TAB OP Series",
    series: "1701 TAB OP",
    category: "PLASTIC",
    type: "FLUSH_GRID",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Open-top (perforated / flush grid) TAB chain for applications requiring drainage, air flow, or washdown.",
    features: [
      "Open/perforated top for drainage",
      "Flush grid design",
      "TAB curve retention",
      "Easy cleaning in food applications",
    ],
    applications: ["Food processing", "Washdown lines", "Fresh produce", "Drainage required"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/3/5/10735-large_default.jpg`,
    catalogPage: "52",
  },

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — MICRO PITCH
  // ═══════════════════════════════════════════════════════════
  {
    id: "MF_SERIES",
    name: "MF Series (43–103)",
    series: "43–103 MF",
    category: "PLASTIC",
    type: "MICRO",
    pitch: '0.43"–1.0" (11–25 mm)',
    pitch_in: 0.63,
    description: "Micro-pitch flat top chain family for small product conveying, precision packaging, and tight-radius curved lines.",
    features: [
      "Ultra-small pitch for compact conveyors",
      "Very tight curve radii possible",
      "Clean, smooth top surface",
      "Suitable for small-format products",
    ],
    applications: ["Small bottles & cans", "Precision packaging", "Cosmetics", "Compact conveyor layouts"],
    widths: ['1.5"', '2.0"', '2.5"', '3.25"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/7/2/10672-large_default.jpg`,
    catalogPage: "56",
  },

  // ═══════════════════════════════════════════════════════════
  // STEEL TABLE TOP CHAINS
  // ═══════════════════════════════════════════════════════════
  {
    id: "SS820",
    name: "820 Series — Steel",
    series: "820",
    category: "STEEL",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel version of the industry-standard 820 flat top chain. Ideal for food, beverage, and washdown environments.",
    features: [
      "AISI 304 or 316 stainless steel construction",
      "Corrosion resistant",
      "FDA/food-grade suitable",
      "High-temperature operation",
    ],
    applications: ["Food processing", "Beverage (harsh washdown)", "Pharmaceutical", "Chemical environments"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS", "CS"],
    image: `${IMG}/1/0/7/4/5/10745-large_default.jpg`,
    catalogPage: "59–62",
  },
  {
    id: "SS821",
    name: "821 Series — Steel",
    series: "821",
    category: "STEEL",
    type: "STRAIGHT",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch stainless steel flat top chain for heavy case and carton conveying in harsh or washdown environments.",
    features: [
      '1.5" pitch for high loads',
      "AISI 304/316 stainless steel",
      "Corrosion and chemical resistant",
      "Food-grade suitable",
    ],
    applications: ["Case conveying — washdown", "Food processing heavy loads", "Pharmaceutical packaging"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS", "CS"],
    image: `${IMG}/1/0/7/4/6/10746-large_default.jpg`,
    catalogPage: "63–65",
  },
  {
    id: "SS880",
    name: "880 TAB Series — Steel",
    series: "880 TAB",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless steel heavy-duty sideflexing TAB chain for curved sections in high-hygiene environments.",
    features: [
      "Stainless steel heavy-duty construction",
      "TAB sideflexing for curves",
      "Washdown and CIP compatible",
      "High-load, high-hygiene applications",
    ],
    applications: ["Food & beverage washdown", "Pharmaceutical", "High-hygiene curved conveying"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/0/10750-large_default.jpg`,
    catalogPage: "70–72",
  },
  {
    id: "SS882",
    name: "882 Series — Steel",
    series: "882",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Maximum-strength stainless steel sideflexing chain for the most demanding washdown curve applications.",
    features: [
      "Maximum load stainless steel",
      "Sideflexing for curved layouts",
      "Excellent corrosion resistance",
      "CIP/COP washdown compatible",
    ],
    applications: ["Maximum-load washdown curves", "Food industry heavy duty", "Pharmaceutical"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/5/10755-large_default.jpg`,
    catalogPage: "73–76",
  },
  {
    id: "SS_HAIRPIN",
    name: "Hairpin / Bevel Chains — Steel",
    series: "Hairpin",
    category: "STEEL",
    type: "SIDEFLEX",
    pitch: '1.0" / 1.5"',
    pitch_in: 1.0,
    description: "Stainless steel hairpin and bevel-joint chain for curved and elevator conveyor sections with high hygiene requirements.",
    features: [
      "Bevel / hairpin link for extreme curves",
      "Stainless steel construction",
      "Elevator and incline capable",
      "Washdown resistant",
    ],
    applications: ["Elevator conveyors", "Extreme curve angles", "High-hygiene facilities", "Canning lines"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: 'Special — hairpin design',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/6/0/10760-large_default.jpg`,
    catalogPage: "79–104",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getProductsByCategory(categoryKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey);
}

export function getProductsByType(categoryKey, typeKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey && p.type === typeKey);
}

export function getTypesByCategory(categoryKey) {
  const types = [...new Set(CHAIN_PRODUCTS.filter(p => p.category === categoryKey).map(p => p.type))];
  return types;
}

export function getMaterialsForProduct(product) {
  return product.materials.map(mId => MATERIALS[mId]).filter(Boolean);
}