/**
 * Table Top Chain unified product data
 * Source: Movex Imperial Catalog pages 7–108 (primary) + System Plast Smart Guide (materials)
 * Product-first, brand-neutral. Brand only shown for exclusive materials.
 */

// ─── Normalized Material Library ─────────────────────────────────────────────
export const MATERIALS = {
  LF: {
    id: "LF",
    name: "Low Friction Acetal",
    category: "Plastic",
    type: "LF Acetal",
    friction: "Low (µ ≈ 0.10–0.15)",
    wearResistance: "High",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "General conveying, beverage, food packaging, dry & wet environments",
    availability: "Standard",
    brand: null,
    color: "#e0f2fe",
    badge: "Most Common",
  },
  MX: {
    id: "MX",
    name: "Performance PBT",
    category: "Plastic",
    type: "PBT (Polybutylene Terephthalate)",
    friction: "Low–Medium (µ ≈ 0.12–0.18)",
    wearResistance: "Very High",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "High-speed lines, chemical environments, elevated temperatures",
    availability: "Standard",
    brand: null,
    color: "#f0fdf4",
    badge: "High Performance",
  },
  PFX: {
    id: "PFX",
    name: "PFX Dry-Run PBT",
    category: "Plastic",
    type: "Extra Performance PBT",
    friction: "Very Low (µ ≈ 0.08–0.12)",
    wearResistance: "Excellent",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "Dry-run applications, PET bottle lines, limited lubrication environments",
    availability: "Standard",
    brand: "Movex (exclusive formulation)",
    color: "#fefce8",
    badge: "Dry-Run Optimized",
  },
  MPX: {
    id: "MPX",
    name: "Lubricated Acetal",
    category: "Plastic",
    type: "MPX Acetal",
    friction: "Very Low (µ ≈ 0.08–0.12)",
    wearResistance: "High",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "Lube-free or minimal-lube lines, accumulation conveyors",
    availability: "Standard",
    brand: null,
    color: "#fef9c3",
    badge: null,
  },
  DKM: {
    id: "DKM",
    name: "Aramid-Reinforced Acetal",
    category: "Plastic",
    type: "DKM Acetal Composite",
    friction: "Medium (µ ≈ 0.15–0.20)",
    wearResistance: "Exceptional",
    chemicalResistance: "Good",
    tempRange: "-40°F to +185°F (-40°C to +85°C)",
    applications: "Heavy-load lines, abrasive products, long conveyors requiring high tensile strength",
    availability: "On request",
    brand: null,
    color: "#fdf4ff",
    badge: "Heavy Duty",
  },
  MWX: {
    id: "MWX",
    name: "Polyamide Composite",
    category: "Plastic",
    type: "MWX PA Composite",
    friction: "Medium (µ ≈ 0.18–0.25)",
    wearResistance: "Very High",
    chemicalResistance: "Moderate",
    tempRange: "-40°F to +212°F (-40°C to +100°C)",
    applications: "Wet/hot environments, food processing with frequent washdowns",
    availability: "On request",
    brand: null,
    color: "#f0f9ff",
    badge: null,
  },
  GT: {
    id: "GT",
    name: "Grip Top (TPE Rubber Insert)",
    category: "Plastic",
    type: "Acetal + TPE Rubber (50 ShA)",
    friction: "Very High (rubber grip)",
    wearResistance: "Moderate",
    chemicalResistance: "Good",
    tempRange: "-20°F to +140°F (-30°C to +60°C)",
    applications: "Incline/decline conveying, unstable containers, grip-critical applications",
    availability: "Standard",
    brand: null,
    color: "#fff7ed",
    badge: "High Friction",
  },
  NGE: {
    id: "NGE",
    name: "NGE (Next Generation Engineering)",
    category: "Plastic",
    type: "NGE Composite (Regal Rexnord)",
    friction: "Very Low (µ ≈ 0.07–0.10)",
    wearResistance: "Outstanding — 3–5× standard acetal",
    chemicalResistance: "Excellent",
    tempRange: "-40°F to +230°F (-40°C to +110°C)",
    applications: "Extended service life, high-speed lines, reduced maintenance, dry-lube environments",
    availability: "On request",
    brand: "System Plast (exclusive)",
    color: "#ecfdf5",
    badge: "Extended Life",
  },
  SS: {
    id: "SS",
    name: "Stainless Steel",
    category: "Steel",
    type: "AISI 304 / 316 Stainless Steel",
    friction: "Low–Medium",
    wearResistance: "High",
    chemicalResistance: "Excellent",
    tempRange: "-100°F to +500°F (-73°C to +260°C)",
    applications: "Food & beverage, washdown environments, high temperatures, corrosive conditions",
    availability: "Standard",
    brand: null,
    color: "#f8fafc",
    badge: "Food Grade",
  },
  CS: {
    id: "CS",
    name: "Carbon Steel",
    category: "Steel",
    type: "Carbon Steel",
    friction: "Medium",
    wearResistance: "High",
    chemicalResistance: "Low (requires lubrication)",
    tempRange: "-40°F to +400°F (-40°C to +200°C)",
    applications: "General industrial, non-corrosive dry environments, heavy loads",
    availability: "Standard",
    brand: null,
    color: "#f1f5f9",
    badge: null,
  },
};

// ─── Product Catalog ──────────────────────────────────────────────────────────

export const CHAIN_CATEGORIES = {
  PLASTIC: "Plastic Table Top Chains",
  STEEL: "Steel Table Top Chains",
};

export const CHAIN_TYPES = {
  STRAIGHT: "Straight Running",
  SIDEFLEX: "Sideflexing",
  HEAVY: "Heavy Duty",
  LBP: "Low Back Pressure",
  HIGH_FRICTION: "High Friction",
  CASE: "Case Conveyor",
  MICRO: "Micro Pitch",
  FLUSH_GRID: "Flush Grid / Open",
};

// Image base URLs from movexii.com CDN
const IMG = "https://movexps.publifarm.com/img/p";

export const CHAIN_PRODUCTS = [

  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — STRAIGHT RUNNING (1" pitch)
  // ═══════════════════════════════════════════════════════════
  {
    id: "820",
    name: "820 Series",
    series: "820",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Industry-standard flat top chain. Improved design with 45% less open gap and 15% more contact surface.",
    features: ["45% smaller open gap", "15% increased contact surface", "Fully interchangeable with previous design", "Stainless steel pins"],
    applications: ["Beverage", "Food packaging", "General manufacturing", "Light assembly"],
    widths: ['3.25"', '3.30"', '3.50"', '4.00"', '4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "365 lbs", MX: "284 lbs", PFX: "284 lbs", MPX: "365 lbs", DKM: "365 lbs", MWX: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX", "DKM", "MWX"],
    image: `${IMG}/1/0/6/9/2/10692-large_default.jpg`,
    catalogPage: "9–11",
  },
  {
    id: "820V",
    name: "820 V Series",
    series: "820 V",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Vacuum-belt variant of the 820 with perforated top for vacuum conveying.",
    features: ["Perforated top plate for vacuum holding", "Same improved design as 820", "Stainless steel pins"],
    applications: ["Vacuum conveying", "Packaging", "Label application"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/6/9/3/10693-large_default.jpg`,
    catalogPage: "11",
  },
  {
    id: "820FG",
    name: "820 FG Series",
    series: "820 FG",
    category: "PLASTIC",
    type: "FLUSH_GRID",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Flush grid (open top) variant of the 820 for drainage and air-through applications.",
    features: ["Open/flush grid top", "Drainage and air-flow applications", "Stainless steel pins"],
    applications: ["Food processing", "Washdown", "Fresh produce", "Drainage required"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/4/10694-large_default.jpg`,
    catalogPage: "12",
  },
  {
    id: "828",
    name: "828 Series",
    series: "828",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Heavy-bodied straight-running flat top chain with higher load capacity than the 820.",
    features: ["Higher load capacity than 820", "Wide flat plate top", "Stainless steel pins"],
    applications: ["Beverage cans", "Heavier containers", "Food processing"],
    widths: ['3.25"', '3.30"'],
    maxLoad: { LF: "522 lbs", MX: "418 lbs", PFX: "418 lbs", MPX: "522 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX"],
    image: `${IMG}/1/0/6/9/8/10698-large_default.jpg`,
    catalogPage: "12",
  },
  {
    id: "831",
    name: "831 Series",
    series: "831",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Straight-running chain with raised rib profile for improved product stability.",
    features: ["Raised rib top surface", "Improved container stability", "Stainless steel pins"],
    applications: ["Unstable containers", "Cans & bottles", "Light manufacturing"],
    widths: ['3.25"', '4.50"', '7.50"'],
    maxLoad: { LF: "365 lbs", MX: "284 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/9/10699-large_default.jpg`,
    catalogPage: "13",
  },
  {
    id: "831GT",
    name: "831 GT Series",
    series: "831 GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "831 with integrated TPE rubber grip top insert for incline and grip applications.",
    features: ["TPE rubber grip insert", "Raised rib top", "Excellent grip for inclines"],
    applications: ["Incline/decline", "Unstable containers", "Grip conveying"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "365 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/0/0/10700-large_default.jpg`,
    catalogPage: "13",
  },
  {
    id: "832",
    name: "832 Series",
    series: "832",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Straight-running flat top chain with strengthened hinge area for higher tensile loads.",
    features: ["Reinforced hinge area", "Higher tensile strength", "Standard flat top surface"],
    applications: ["High tensile load lines", "Long conveyor runs", "Packaging"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/1/10701-large_default.jpg`,
    catalogPage: "14",
  },
  {
    id: "835",
    name: "835 Series",
    series: "835",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Narrow-pitch straight-running chain, compact design for tight space layouts.",
    features: ["Compact narrow profile", "Straight running", "Stainless steel pins"],
    applications: ["Space-constrained conveyors", "Pharmaceutical", "Small products"],
    widths: ['1.50"', '2.00"', '3.25"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/2/10702-large_default.jpg`,
    catalogPage: "14",
  },
  {
    id: "836",
    name: "836 Series",
    series: "836",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Extended flat-top straight chain with extra-wide plate coverage for large product footprints.",
    features: ["Extra-wide top plate", "Large product footprint support", "Stainless steel pins"],
    applications: ["Large format products", "Trays and platters", "Food packaging"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/3/10703-large_default.jpg`,
    catalogPage: "14",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — STRAIGHT RUNNING (1.5" pitch)
  // ═══════════════════════════════════════════════════════════
  {
    id: "821",
    name: "821 Series",
    series: "821",
    category: "PLASTIC",
    type: "STRAIGHT",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch flat top chain for large containers and heavy loads.",
    features: ['1.5" pitch for higher load', "Wide flat top plate", "Stainless steel pins"],
    applications: ["Case conveying", "Boxes & cartons", "Heavy packaging"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "623 lbs", MX: "495 lbs", MPX: "623 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "MPX"],
    image: `${IMG}/1/0/6/9/5/10695-large_default.jpg`,
    catalogPage: "14",
  },
  {
    id: "821GT",
    name: "821 GT Series",
    series: "821 GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "821 with integrated TPE rubber grip top. Excellent friction for inclines and unstable products.",
    features: ["TPE rubber grip insert (50 ShA)", "Excellent grip for inclines up to 30°", "Stainless steel pins"],
    applications: ["Incline/decline conveyors", "Cases & unstable products"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "623 lbs", MX: "495 lbs" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/6/10696-large_default.jpg`,
    catalogPage: "15",
  },
  {
    id: "821LBP",
    name: "821 LBP Series",
    series: "821 LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Low back pressure 1.5\" variant for accumulation lines.",
    features: ["Low back pressure design", "Roller bottom for accumulation", "Ideal for sensitive containers"],
    applications: ["Accumulation lines", "Glass bottles", "Fragile containers"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/9/7/10697-large_default.jpg`,
    catalogPage: "16",
  },
  {
    id: "821FG",
    name: "821 FG Series",
    series: "821 FG",
    category: "PLASTIC",
    type: "FLUSH_GRID",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch flush grid chain for drainage and washdown in heavy-load applications.",
    features: ["Open grid top for drainage", "Wide 1.5\" pitch", "Food processing suitable"],
    applications: ["Food processing", "Washdown", "Drainage required"],
    widths: ['7.50"', '10.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/3/6/10736-large_default.jpg`,
    catalogPage: "16",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — SIDEFLEXING (1" pitch)
  // ═══════════════════════════════════════════════════════════
  {
    id: "8257",
    name: "8257 Series",
    series: "8257",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Sideflexing flat top chain for curved conveyor sections.",
    features: ["True sideflexing", "Smooth transition through curves", "Flat top surface", "Stainless steel pins"],
    applications: ["Curved conveyors", "Beverage lines", "Space-saving layouts"],
    widths: ['3.25"', '3.30"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/5/10725-large_default.jpg`,
    catalogPage: "17",
  },
  {
    id: "8257GT",
    name: "8257 GT Series",
    series: "8257 GT",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Sideflexing with TPE rubber grip top for curved sections requiring friction.",
    features: ["Sideflexing with grip top", "TPE rubber insert (50 ShA)", "Curved layout with high friction"],
    applications: ["Curved incline sections", "Grip conveying through curves"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/6/10726-large_default.jpg`,
    catalogPage: "18",
  },
  {
    id: "8257LBP",
    name: "8257 LBP Series",
    series: "8257 LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Low back pressure sideflexing for curved accumulation lines.",
    features: ["Sideflexing + low back pressure", "Roller underside for accumulation in curves"],
    applications: ["Curved accumulation", "Glass & PET bottles through curves"],
    widths: ['3.25"', '3.50"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/7/10727-large_default.jpg`,
    catalogPage: "19",
  },
  {
    id: "8257FG",
    name: "8257 FG Series",
    series: "8257 FG",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Sideflexing flush grid chain for drainage in curved conveyor sections.",
    features: ["Sideflexing + open grid top", "Drainage in curves", "Food processing suitable"],
    applications: ["Curved food lines", "Washdown with curves", "Fresh produce"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/2/8/10728-large_default.jpg`,
    catalogPage: "19",
  },
  {
    id: "878TAB",
    name: "878 TAB Series",
    series: "878 TAB",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "TAB-design sideflexing chain for tight-radius curve retention.",
    features: ["TAB side retention design", "Sideflexing through curves", "Secure product containment"],
    applications: ["Tight-radius curves", "Beverage lines", "Can conveying"],
    widths: ['3.25"', '3.50"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/0/10700-large_default.jpg`,
    catalogPage: "20",
  },
  {
    id: "878TABGT",
    name: "878 TAB GT Series",
    series: "878 TAB GT",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "TAB sideflexing with grip-top rubber insert for gripping curved conveyors.",
    features: ["TAB retention + grip top", "TPE rubber insert", "Sideflexing through curves"],
    applications: ["Curved grip conveying", "Incline curves", "Packaging"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/0/1/10701-large_default.jpg`,
    catalogPage: "20",
  },
  {
    id: "878TABLBP",
    name: "878 TAB LBP Series",
    series: "878 TAB LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "TAB sideflexing with low back pressure rollers for accumulation on curves.",
    features: ["TAB retention + LBP rollers", "Accumulation in curves", "Gentle on fragile products"],
    applications: ["Curved accumulation", "Fragile containers through curves"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/2/10702-large_default.jpg`,
    catalogPage: "20",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — HEAVY DUTY SIDEFLEXING (879 / 880 / 882 family)
  // ═══════════════════════════════════════════════════════════
  {
    id: "879M",
    name: "879 M Series",
    series: "879 M",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing flat top chain. Large format body, high tensile strength.",
    features: ['1.5" pitch for maximum load', "Sideflexing capability", "Heavy-duty construction"],
    applications: ["Heavy load curves", "Automotive", "Industrial"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/4/10704-large_default.jpg`,
    catalogPage: "21",
  },
  {
    id: "879MGT",
    name: "879 M GT Series",
    series: "879 M GT",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing chain with TPE grip top for high-load curved incline sections.",
    features: ["Heavy-duty + grip top", "TPE rubber insert", "Sideflexing"],
    applications: ["Heavy incline curves", "Automotive", "Large containers"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/0/4/10704-large_default.jpg`,
    catalogPage: "21",
  },
  {
    id: "879MLBP",
    name: "879 M LBP Series",
    series: "879 M LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing with low back pressure for gentle accumulation on large curves.",
    features: ["Heavy-duty + LBP rollers", "Accumulation on large curves", "Sideflexing"],
    applications: ["Large container accumulation curves", "Fragile heavy products"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/4/10704-large_default.jpg`,
    catalogPage: "22",
  },
  {
    id: "879TAB",
    name: "879 TAB Series",
    series: "879 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "TAB-design heavy-duty sideflexing. Prevents derailment on tight, high-load curves.",
    features: ["TAB retention prevents derailment", '1.5" pitch heavy-duty body', "Curve-stable under high loads"],
    applications: ["High-load curved conveyors", "Automotive", "Heavy packaging"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/5/10705-large_default.jpg`,
    catalogPage: "22",
  },
  {
    id: "879TABGT",
    name: "879 TAB GT Series",
    series: "879 TAB GT",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "TAB heavy-duty sideflexing with grip top for incline curve applications.",
    features: ["TAB retention + grip top", "Heavy-duty + TPE rubber", "Sideflexing"],
    applications: ["Heavy incline curves", "Grip + curve stability"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/0/5/10705-large_default.jpg`,
    catalogPage: "22",
  },
  {
    id: "879TABLBP",
    name: "879 TAB LBP Series",
    series: "879 TAB LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "TAB heavy-duty sideflexing with LBP rollers for accumulation on high-load curves.",
    features: ["TAB + LBP rollers", "Heavy-duty accumulation curves", "Sideflexing"],
    applications: ["High-load accumulation curves", "Large containers"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/5/10705-large_default.jpg`,
    catalogPage: "22",
  },
  {
    id: "880M",
    name: "880 M Series",
    series: "880 M",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Sideflexing flat top chain without TAB for standard curved conveyor applications.",
    features: ["Smooth sideflexing", '1.5" pitch', "Versatile curved conveying"],
    applications: ["Curved conveyors", "Beverage", "General food processing"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/8/10708-large_default.jpg`,
    catalogPage: "25",
  },
  {
    id: "880MGT",
    name: "880 M GT Series",
    series: "880 M GT",
    category: "PLASTIC",
    type: "SIDEFLEX",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Sideflexing 880 M with TPE rubber grip top insert.",
    features: ["Sideflexing + grip top", "TPE rubber insert", "1.5\" pitch curves"],
    applications: ["Curved grip conveying", "Incline sideflexing"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/0/8/10708-large_default.jpg`,
    catalogPage: "25",
  },
  {
    id: "880MLBP",
    name: "880 M LBP Series",
    series: "880 M LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Sideflexing 880 M with LBP rollers for curved accumulation.",
    features: ["Sideflexing + LBP rollers", "Curved accumulation", "1.5\" pitch"],
    applications: ["Curved accumulation lines", "Fragile containers in curves"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/8/10708-large_default.jpg`,
    catalogPage: "25",
  },
  {
    id: "880TAB",
    name: "880 TAB Series",
    series: "880 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Industry flagship heavy-duty TAB sideflexing chain for high-speed, high-load curves.",
    features: ["Industry-standard heavy-duty sideflexing", "TAB retention", "Multiple materials", "Wide range of widths"],
    applications: ["Beverage", "Food processing", "High-speed curved conveyors", "PET lines"],
    widths: ['3.25"', '3.30"', '3.50"', '4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking", MX: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "PFX", "MPX"],
    image: `${IMG}/1/0/7/0/6/10706-large_default.jpg`,
    catalogPage: "26",
  },
  {
    id: "880TABGT",
    name: "880 TAB GT Series",
    series: "880 TAB GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Flagship 880 TAB with grip-top rubber for heavy-load incline curves.",
    features: ["880 TAB + grip top", "TPE rubber insert", "Heavy-duty curved inclines"],
    applications: ["Heavy incline curves", "PET and glass through curves", "Grip critical"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/6/10706-large_default.jpg`,
    catalogPage: "26",
  },
  {
    id: "880TABLBP",
    name: "880 TAB LBP Series",
    series: "880 TAB LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "880 TAB heavy-duty sideflexing with LBP rollers for accumulation on curves.",
    features: ["880 TAB + LBP rollers", "Heavy-duty curved accumulation", "Gentle on fragile containers"],
    applications: ["Heavy accumulation curves", "PET and glass accumulation"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/6/10706-large_default.jpg`,
    catalogPage: "26",
  },
  {
    id: "888TAB",
    name: "888 TAB Series",
    series: "888 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch TAB flat top chain with maximum load capacity and stable sideflexing.",
    features: ["Maximum flat-top coverage", "TAB curve retention", "Very high load capacity"],
    applications: ["Maximum-load conveying", "Large containers", "Automotive assembly"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/7/10707-large_default.jpg`,
    catalogPage: "23",
  },
  {
    id: "888TABLBP",
    name: "888 TAB LBP Series",
    series: "888 TAB LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "888 TAB with LBP rollers for maximum-load curved accumulation.",
    features: ["888 TAB + LBP rollers", "Maximum load accumulation curves"],
    applications: ["Large container accumulation", "Heavy load curved lines"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/0/7/10707-large_default.jpg`,
    catalogPage: "24",
  },
  {
    id: "882M",
    name: "882 M Series",
    series: "882 M",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Heavy-duty sideflexing chain with higher strength plate for maximum load on long curve sections.",
    features: ["Higher tensile strength plate", "Sideflexing for curved layouts", "Heavy-duty load rating"],
    applications: ["Long curve sections", "High-load curved conveying", "Industrial"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "MPX"],
    image: `${IMG}/1/0/7/1/3/10713-large_default.jpg`,
    catalogPage: "30",
  },
  {
    id: "882MGT",
    name: "882 M GT Series",
    series: "882 M GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 M with grip top rubber for heavy-load curved incline sections.",
    features: ["882 M + grip top", "TPE rubber insert", "Heavy-duty incline curves"],
    applications: ["Heavy incline curves", "Large container grip conveying"],
    widths: ['4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/1/3/10713-large_default.jpg`,
    catalogPage: "30",
  },
  {
    id: "882MLBP",
    name: "882 M LBP Series",
    series: "882 M LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 M with LBP rollers for heavy-load curved accumulation.",
    features: ["882 M + LBP rollers", "Heavy-duty curved accumulation"],
    applications: ["Heavy accumulation curves", "Long curve lines"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/3/10713-large_default.jpg`,
    catalogPage: "30",
  },
  {
    id: "882TAB",
    name: "882 TAB Series",
    series: "882 TAB",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 with TAB curve retention — premium heavy-duty sideflexing for maximum-load curved conveying.",
    features: ["Maximum load capacity in class", "TAB retention prevents derailment", "Multiple material options"],
    applications: ["Maximum-load curves", "Automotive", "Heavy industrial"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/5/10715-large_default.jpg`,
    catalogPage: "33",
  },
  {
    id: "882TABGT",
    name: "882 TAB GT Series",
    series: "882 TAB GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 TAB with grip top for maximum-load curved incline sections.",
    features: ["882 TAB + grip top", "Maximum load + grip + curve retention"],
    applications: ["Maximum-load incline curves"],
    widths: ['4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/1/5/10715-large_default.jpg`,
    catalogPage: "33",
  },
  {
    id: "882TABLBP",
    name: "882 TAB LBP Series",
    series: "882 TAB LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "882 TAB with LBP rollers for maximum-load curved accumulation.",
    features: ["882 TAB + LBP rollers", "Maximum load + curve accumulation"],
    applications: ["Maximum-load curved accumulation"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/5/10715-large_default.jpg`,
    catalogPage: "33",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — CASE CONVEYOR / HEAVY STRAIGHT
  // ═══════════════════════════════════════════════════════════
  {
    id: "1873",
    name: "1873 Series",
    series: "1873",
    category: "PLASTIC",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Large-format heavy-duty plastic chain for demanding case and carton conveying.",
    features: ["Extra-wide top plate", "Heavy-duty straight running", "Multiple variants available"],
    applications: ["Case & carton conveying", "Logistics", "Distribution centers"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/8/10718-large_default.jpg`,
    catalogPage: "36",
  },
  {
    id: "1873GT",
    name: "1873 GT Series",
    series: "1873 GT",
    category: "PLASTIC",
    type: "HIGH_FRICTION",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "1873 with grip top for incline case conveying.",
    features: ["Extra-wide plate + grip top", "TPE rubber insert", "Heavy case incline conveying"],
    applications: ["Case incline conveying", "Logistics inclines"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "40 links / 5 ft",
    materials: ["LF"],
    image: `${IMG}/1/0/7/1/8/10718-large_default.jpg`,
    catalogPage: "36",
  },
  {
    id: "1873LBP",
    name: "1873 LBP Series",
    series: "1873 LBP",
    category: "PLASTIC",
    type: "LBP",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "1873 with LBP rollers for case accumulation lines.",
    features: ["Extra-wide plate + LBP rollers", "Case accumulation", "Gentle product handling"],
    applications: ["Case accumulation", "Distribution center accumulation"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/1/8/10718-large_default.jpg`,
    catalogPage: "36",
  },
  {
    id: "CC600",
    name: "CC 600 Series",
    series: "CC 600",
    category: "PLASTIC",
    type: "CASE",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Case conveyor chain optimized for cardboard box and tray conveying on high-speed lines.",
    features: ["Optimized for case conveying", "High friction top options", "Robust case-handling design"],
    applications: ["Case conveying", "Distribution centers", "E-commerce", "Cardboard trays"],
    widths: ['4.50"', '6.00"', '7.50"', '10.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX", "GT"],
    image: `${IMG}/1/0/6/7/9/10679-large_default.jpg`,
    catalogPage: "49",
  },
  {
    id: "CC600TAB",
    name: "CC 600 TAB Series",
    series: "CC 600 TAB",
    category: "PLASTIC",
    type: "CASE",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Case conveyor chain with TAB sideflexing for curved case conveying sections.",
    features: ["TAB sideflexing + case design", "Curved case conveying", "Robust construction"],
    applications: ["Curved case conveying", "Distribution center curves"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/7/9/10679-large_default.jpg`,
    catalogPage: "49",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — FLUSH GRID / OPEN TOP
  // ═══════════════════════════════════════════════════════════
  {
    id: "1701TABOP",
    name: "1701 TAB OP Series",
    series: "1701 TAB OP",
    category: "PLASTIC",
    type: "FLUSH_GRID",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Open-top TAB chain for applications requiring drainage, air flow, or washdown.",
    features: ["Open/perforated top for drainage", "TAB curve retention", "Easy cleaning in food applications"],
    applications: ["Food processing", "Washdown lines", "Fresh produce", "Drainage required"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/3/5/10735-large_default.jpg`,
    catalogPage: "52",
  },
  {
    id: "1701OP",
    name: "1701 OP Series",
    series: "1701 OP",
    category: "PLASTIC",
    type: "FLUSH_GRID",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Straight-running open-top chain for drainage and air-through applications.",
    features: ["Open/perforated top", "Straight running", "Drainage and washdown suitable"],
    applications: ["Food processing straight lines", "Washdown", "Produce lines"],
    widths: ['3.25"', '4.50"', '6.00"', '7.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/7/3/5/10735-large_default.jpg`,
    catalogPage: "52",
  },
  // ═══════════════════════════════════════════════════════════
  // PLASTIC CHAINS — MICRO PITCH
  // ═══════════════════════════════════════════════════════════
  {
    id: "MF43",
    name: "43 MF Series",
    series: "43 MF",
    category: "PLASTIC",
    type: "MICRO",
    pitch: '0.43" (11 mm)',
    pitch_in: 0.43,
    description: "Ultra-small pitch flat top chain for compact conveyors and precision packaging.",
    features: ["11 mm pitch — smallest in range", "Very tight curve radii", "Smooth top surface"],
    applications: ["Small bottles & cans", "Cosmetics", "Compact conveyor layouts"],
    widths: ['1.50"', '2.00"', '2.50"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/7/2/10672-large_default.jpg`,
    catalogPage: "56",
  },
  {
    id: "MF63",
    name: "63 MF Series",
    series: "63 MF",
    category: "PLASTIC",
    type: "MICRO",
    pitch: '0.63" (16 mm)',
    pitch_in: 0.63,
    description: "Micro-pitch flat top chain — 16 mm pitch for small product conveying.",
    features: ["16 mm pitch", "Tight curve radii", "Suitable for small-format products"],
    applications: ["Small bottles", "Precision packaging", "Tight layouts"],
    widths: ['1.50"', '2.00"', '2.50"', '3.25"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/7/2/10672-large_default.jpg`,
    catalogPage: "56",
  },
  {
    id: "MF103",
    name: "103 MF Series",
    series: "103 MF",
    category: "PLASTIC",
    type: "MICRO",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Micro series in 1.0\" pitch for narrow-width precision conveying.",
    features: ["Standard 1.0\" pitch in narrow profile", "Compact conveyor design", "Smooth top surface"],
    applications: ["Narrow product conveying", "Precision packaging", "Pharmaceutical"],
    widths: ['1.50"', '2.00"', '2.50"', '3.25"'],
    maxLoad: { LF: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["LF", "MX"],
    image: `${IMG}/1/0/6/7/2/10672-large_default.jpg`,
    catalogPage: "57",
  },

  // ═══════════════════════════════════════════════════════════
  // STEEL TABLE TOP CHAINS — STRAIGHT RUNNING
  // ═══════════════════════════════════════════════════════════
  {
    id: "SS820",
    name: "820 Series — Steel",
    series: "820",
    category: "STEEL",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel version of the 820. Ideal for food, beverage, and washdown environments.",
    features: ["AISI 304 or 316 stainless steel", "Corrosion resistant", "FDA/food-grade suitable", "High-temp operation"],
    applications: ["Food processing", "Beverage washdown", "Pharmaceutical"],
    widths: ['3.25"', '3.50"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS", "CS"],
    image: `${IMG}/1/0/7/4/5/10745-large_default.jpg`,
    catalogPage: "59–62",
  },
  {
    id: "SS820V",
    name: "820 V Series — Steel",
    series: "820 V",
    category: "STEEL",
    type: "STRAIGHT",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel perforated vacuum flat top chain for washdown vacuum conveying.",
    features: ["Stainless steel construction", "Perforated top for vacuum", "Washdown suitable"],
    applications: ["Vacuum conveying in food environments", "Washdown packaging"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/5/10745-large_default.jpg`,
    catalogPage: "62",
  },
  {
    id: "SS820FG",
    name: "820 FG Series — Steel",
    series: "820 FG",
    category: "STEEL",
    type: "FLUSH_GRID",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel flush grid chain for drainage in food processing environments.",
    features: ["Stainless open grid top", "Drainage for food applications", "CIP/COP washdown"],
    applications: ["Food washdown lines", "Fresh produce", "Drainage required"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/6/10746-large_default.jpg`,
    catalogPage: "62",
  },
  {
    id: "SS821",
    name: "821 Series — Steel",
    series: "821",
    category: "STEEL",
    type: "STRAIGHT",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch stainless steel flat top for heavy case conveying in washdown environments.",
    features: ['1.5" pitch for high loads', "AISI 304/316 stainless steel", "Food-grade suitable"],
    applications: ["Case conveying — washdown", "Food processing heavy loads"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS", "CS"],
    image: `${IMG}/1/0/7/4/6/10746-large_default.jpg`,
    catalogPage: "63–65",
  },
  {
    id: "SS821FG",
    name: "821 FG Series — Steel",
    series: "821 FG",
    category: "STEEL",
    type: "FLUSH_GRID",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Wide-pitch stainless flush grid chain for heavy food processing drainage applications.",
    features: ["Wide pitch + stainless open grid", "Heavy-duty drainage", "Food-grade suitable"],
    applications: ["Food processing drainage", "Washdown heavy lines"],
    widths: ['7.50"', '10.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/6/10746-large_default.jpg`,
    catalogPage: "65",
  },
  // ═══════════════════════════════════════════════════════════
  // STEEL TABLE TOP CHAINS — SIDEFLEXING
  // ═══════════════════════════════════════════════════════════
  {
    id: "SS8257",
    name: "8257 Series — Steel",
    series: "8257",
    category: "STEEL",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel sideflexing flat top for curved food and beverage conveying.",
    features: ["Stainless sideflexing", "Curved conveying in washdown environments"],
    applications: ["Curved food lines", "Beverage curves washdown"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/7/10747-large_default.jpg`,
    catalogPage: "66–68",
  },
  {
    id: "SS878TAB",
    name: "878 TAB Series — Steel",
    series: "878 TAB",
    category: "STEEL",
    type: "SIDEFLEX",
    pitch: '1.0" (25.4 mm)',
    pitch_in: 1.0,
    description: "Stainless steel TAB sideflexing chain for tight-radius washdown curves.",
    features: ["Stainless TAB sideflexing", "Tight-radius curves", "Washdown compatible"],
    applications: ["Tight curved food lines", "Hygiene-critical curves", "Can conveying washdown"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '1.97"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/7/10747-large_default.jpg`,
    catalogPage: "68",
  },
  // ═══════════════════════════════════════════════════════════
  // STEEL TABLE TOP CHAINS — HEAVY DUTY SIDEFLEXING
  // ═══════════════════════════════════════════════════════════
  {
    id: "SS879M",
    name: "879 M Series — Steel",
    series: "879 M",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless steel heavy-duty sideflexing chain for high-load washdown curves.",
    features: ["Stainless heavy-duty sideflexing", "High-hygiene curved conveying", "CIP compatible"],
    applications: ["Heavy-load curves washdown", "Food & beverage industrial"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/8/10748-large_default.jpg`,
    catalogPage: "69",
  },
  {
    id: "SS879TAB",
    name: "879 TAB Series — Steel",
    series: "879 TAB",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless steel TAB heavy-duty sideflexing for demanding washdown curve applications.",
    features: ["Stainless TAB heavy-duty", "Prevents derailment in washdown curves", "CIP compatible"],
    applications: ["High-load washdown curves", "Pharmaceutical", "Food processing"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/4/8/10748-large_default.jpg`,
    catalogPage: "69",
  },
  {
    id: "SS880TAB",
    name: "880 TAB Series — Steel",
    series: "880 TAB",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless steel 880 TAB heavy-duty sideflexing for high-hygiene curved conveying.",
    features: ["Stainless steel heavy-duty", "TAB sideflexing for curves", "Washdown and CIP compatible"],
    applications: ["Food & beverage washdown", "Pharmaceutical", "High-hygiene curved conveying"],
    widths: ['3.25"', '4.50"', '6.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/0/10750-large_default.jpg`,
    catalogPage: "70–72",
  },
  {
    id: "SS882",
    name: "882 Series — Steel",
    series: "882",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Maximum-strength stainless sideflexing chain for the most demanding washdown curve applications.",
    features: ["Maximum load stainless steel", "Sideflexing for curved layouts", "CIP/COP washdown compatible"],
    applications: ["Maximum-load washdown curves", "Food industry heavy duty"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/5/10755-large_default.jpg`,
    catalogPage: "73–76",
  },
  {
    id: "SS882TAB",
    name: "882 TAB Series — Steel",
    series: "882 TAB",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless 882 TAB for maximum-load curved conveying with washdown requirements.",
    features: ["882 TAB stainless", "Maximum load + curve retention", "CIP compatible"],
    applications: ["Maximum-load washdown curves", "High-hygiene heavy duty"],
    widths: ['4.50"', '6.00"', '7.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/5/10755-large_default.jpg`,
    catalogPage: "76",
  },
  {
    id: "SS_HAIRPIN",
    name: "Hairpin / Bevel Chains — Steel",
    series: "Hairpin",
    category: "STEEL",
    type: "SIDEFLEX",
    pitch: '1.0" / 1.5"',
    pitch_in: 1.0,
    description: "Stainless steel hairpin and bevel-joint chain for curved and elevator conveyor sections.",
    features: ["Bevel/hairpin link for extreme curves", "Stainless steel construction", "Elevator and incline capable"],
    applications: ["Elevator conveyors", "Extreme curve angles", "High-hygiene facilities", "Canning lines"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: 'Special — hairpin design',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/6/0/10760-large_default.jpg`,
    catalogPage: "79–104",
  },
  {
    id: "SS_BEVEL",
    name: "Bevel Top Chains — Steel",
    series: "Bevel Top",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.0" / 1.5"',
    pitch_in: 1.0,
    description: "Stainless steel bevel-top chains for incline/decline conveying in washdown applications.",
    features: ["Bevel top for incline/decline", "Stainless steel", "High-hygiene suitable"],
    applications: ["Incline/decline food processing", "Washdown inclines", "Canning"],
    widths: ['3.25"', '4.50"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: '2.75"',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/6/0/10760-large_default.jpg`,
    catalogPage: "79–104",
  },
  {
    id: "SS1873",
    name: "1873 Series — Steel",
    series: "1873",
    category: "STEEL",
    type: "HEAVY",
    pitch: '1.5" (38.1 mm)',
    pitch_in: 1.5,
    description: "Stainless steel large-format heavy-duty chain for case conveying in washdown environments.",
    features: ["Stainless steel extra-wide plate", "Heavy-duty case conveying", "Washdown suitable"],
    applications: ["Case conveying washdown", "Food distribution washdown", "Heavy packaging"],
    widths: ['7.50"', '10.00"', '12.00"'],
    maxLoad: { SS: "To be confirmed by Uniking" },
    backflexRadius: 'To be confirmed by Uniking',
    deliveryUnit: "80 links / 10 ft",
    materials: ["SS"],
    image: `${IMG}/1/0/7/5/5/10755-large_default.jpg`,
    catalogPage: "77–78",
  },
];

// ─── Width Dimension Data ─────────────────────────────────────────────────────
// Keyed by nominal width string → dimensions (pitch 1.0" and 1.5" series)
// Source: Movex Imperial Catalog dimensional tables
export const WIDTH_DIMENSIONS = {
  // 1.0" pitch standard widths
  '1.50"': { overallWidth: '1.50"', insideWidth: '1.38"', plateHeight: '0.59"', weightLbsFt: "0.24" },
  '2.00"': { overallWidth: '2.00"', insideWidth: '1.88"', plateHeight: '0.59"', weightLbsFt: "0.30" },
  '2.50"': { overallWidth: '2.50"', insideWidth: '2.38"', plateHeight: '0.59"', weightLbsFt: "0.36" },
  '3.25"': { overallWidth: '3.25"', insideWidth: '3.13"', plateHeight: '0.63"', weightLbsFt: "0.46" },
  '3.30"': { overallWidth: '3.30"', insideWidth: '3.18"', plateHeight: '0.63"', weightLbsFt: "0.47" },
  '3.50"': { overallWidth: '3.50"', insideWidth: '3.38"', plateHeight: '0.63"', weightLbsFt: "0.50" },
  '4.00"': { overallWidth: '4.00"', insideWidth: '3.88"', plateHeight: '0.63"', weightLbsFt: "0.55" },
  '4.50"': { overallWidth: '4.50"', insideWidth: '4.38"', plateHeight: '0.63"', weightLbsFt: "0.62" },
  '6.00"': { overallWidth: '6.00"', insideWidth: '5.88"', plateHeight: '0.63"', weightLbsFt: "0.80" },
  '7.50"': { overallWidth: '7.50"', insideWidth: '7.38"', plateHeight: '0.63"', weightLbsFt: "0.98" },
  '10.00"': { overallWidth: '10.00"', insideWidth: '9.88"', plateHeight: '0.75"', weightLbsFt: "1.32" },
  '12.00"': { overallWidth: '12.00"', insideWidth: '11.88"', plateHeight: '0.75"', weightLbsFt: "1.58" },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getProductsByCategory(categoryKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey);
}

export function getProductsByType(categoryKey, typeKey) {
  return CHAIN_PRODUCTS.filter(p => p.category === categoryKey && p.type === typeKey);
}

export function getTypesByCategory(categoryKey) {
  const types = [...new Set(CHAIN_PRODUCTS.filter(p => p.category === categoryKey).map(p => p.type))];
  return types;
}

export function getMaterialsForProduct(product) {
  return product.materials.map(mId => MATERIALS[mId]).filter(Boolean);
}