/**
 * unikingBulkChains.js
 *
 * Uniking Industrial Bulk Material Handling Catalog — Normalized Chain Ingestion
 * PRIMARY SOURCE: https://unikingcanada.com/catalogs/uniking-industrial-bulk-material-catalog-industry-conveyor-chains-supplier-canada.pdf
 * DATE: 2026-05-06
 * ROLE: PRIMARY NORMALIZED BASELINE for bulk material / engineered conveying chains
 *
 * COVERS:
 *   Phase 1 — Engineered Class Chains WITH Rollers (1.654"–9" pitch)
 *   Phase 2 — Engineered Class Chains WITHOUT Rollers
 *   Phase 3 — Engineered Class Chain Attachments (normalized attachment library)
 *   Phase 4 — Welded Steel Chains (WH/WR with Uniking baseline)
 *   Phase 5 — Drag / Scraper Chain families
 *   Phase 6 — Forged Chains (drop forged rivetless)
 *   Phase 7 — Kiln Chains (specialty)
 *
 * ARCHITECTURE:
 *   UK_MERGE_REFS  — Uniking as source_ref on existing normalized chains (no new objects needed)
 *   UK_NEW_CHAINS  — New normalized chain entries defined by Uniking catalog
 *
 * CROSS-REFERENCE PRESERVED:
 *   Rexnord chain numbers → source_refs (manufacturer: "Rexnord")
 *   Link-Belt chain numbers → source_refs (manufacturer: "Link-Belt")
 *   Uniking becomes the preferred hierarchy, Rexnord/Link-Belt become source layers
 *
 * NORMALIZATION:
 *   - Rated Working Load from Uniking catalog = baseline (lbs)
 *   - Min Ultimate Strength from Uniking catalog = baseline (lbs × 10³ → converted)
 *   - If Allied-Locke or Donghua specs differ → flagged "Specification varies by manufacturer"
 */

const UK_CATALOG_URL = "https://unikingcanada.com/catalogs/uniking-industrial-bulk-material-catalog-industry-conveyor-chains-supplier-canada.pdf";

// ─── MERGE REFS — Uniking as source on existing normalized chains ──────────────
// These patch Uniking as a source_ref onto already-existing normalized entries.

export const UK_MERGE_REFS = [
  // Existing engineered chains — add Uniking baseline confirmation
  { chain_id: "SS-78",      code: "SS78",      confidence: "Confirmed", catalog_page: "9",  notes: "Uniking bulk material baseline — no rollers" },
  { chain_id: "SS-88",      code: "SS88",      confidence: "Confirmed", catalog_page: "9",  notes: "Uniking bulk material baseline — no rollers" },
  { chain_id: "SS-118",     code: "SS118",     confidence: "Confirmed", catalog_page: "9",  notes: "Uniking bulk material baseline — no rollers" },
  { chain_id: "MSR-6018",   code: "SR196",     confidence: "Confirmed", catalog_page: "4",  notes: "Uniking baseline = Rexnord SR196 / Link-Belt RS6018, 6\" pitch with rollers" },
  { chain_id: "MSR-8028",   code: "RS2800",    confidence: "Confirmed", catalog_page: "4",  notes: "Uniking baseline — 8\" pitch heavy engineered class" },
  { chain_id: "X348",       code: "X348",      confidence: "Confirmed", catalog_page: "52", notes: "Uniking forged chains section" },
  { chain_id: "X458",       code: "X458",      confidence: "Confirmed", catalog_page: "52", notes: "Uniking forged chains section" },
  { chain_id: "WH-78",      code: "WH78",      confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel baseline" },
  { chain_id: "WH-88",      code: "WH88",      confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel baseline" },
  { chain_id: "WH-106",     code: "WH106",     confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel baseline" },
  { chain_id: "WH-124",     code: "WH124",     confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel baseline" },
  { chain_id: "WH-150",     code: "WH150",     confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel baseline" },
  { chain_id: "WD-78",      code: "WD78",      confidence: "Confirmed", catalog_page: "49", notes: "Uniking drag chain attachments section" },
  { chain_id: "WD-124",     code: "WD124",     confidence: "Confirmed", catalog_page: "49", notes: "Uniking drag chain attachments section" },
  // Welded steel expansion variants
  { chain_id: "WH-82",      code: "WH82",      confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel section" },
  { chain_id: "WH-111",     code: "WH111",     confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel section" },
  { chain_id: "WH-106HD",   code: "WH106HD",   confidence: "Confirmed", catalog_page: "33", notes: "Uniking welded steel heavy duty" },
  { chain_id: "WH-106XHD",  code: "WH106XHD",  confidence: "Confirmed", catalog_page: "33", notes: "Uniking welded steel extra heavy" },
  { chain_id: "WH-110",     code: "WH110",     confidence: "Confirmed", catalog_page: "33", notes: "Uniking welded steel section" },
  { chain_id: "WH-124HD",   code: "WH124HD",   confidence: "Confirmed", catalog_page: "34", notes: "Uniking welded steel heavy duty" },
  { chain_id: "WH-132",     code: "WH132",     confidence: "Confirmed", catalog_page: "34", notes: "Uniking welded steel section" },
  { chain_id: "WH-132HD",   code: "WH132HD",   confidence: "Confirmed", catalog_page: "34", notes: "Uniking welded steel heavy duty" },
  { chain_id: "WH-150HD",   code: "WH150HD",   confidence: "Confirmed", catalog_page: "35", notes: "Uniking welded steel heavy duty" },
  { chain_id: "WH-150XHD",  code: "WH150XHD",  confidence: "Confirmed", catalog_page: "35", notes: "Uniking welded steel extra heavy" },
  { chain_id: "WH-155",     code: "WH155",     confidence: "Confirmed", catalog_page: "35", notes: "Uniking welded steel section" },
  { chain_id: "WH-159",     code: "WH159",     confidence: "Confirmed", catalog_page: "35", notes: "Uniking welded steel section" },
  { chain_id: "WH-188",     code: "WH188",     confidence: "Confirmed", catalog_page: "32", notes: "Uniking welded steel section" },
];

// ─── NEW NORMALIZED CHAINS — Uniking Baseline Definitions ─────────────────────

export const UK_NEW_CHAINS = [

  // ══════════════════════════════════════════════════════════════════
  // PHASE 1 — ENGINEERED CLASS WITH ROLLERS
  // Source: Uniking catalog p.4–8, Rexnord/Link-Belt cross-referenced
  // Uniking = primary baseline; Rexnord & Link-Belt = source_refs
  // ══════════════════════════════════════════════════════════════════

  {
    chain_id: "ENG-RR362",
    chain_family: "engineered_class",
    chain_number: "RR362",
    display_name: "RR362 Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "1.654",
    pitch_mm: "42.01",
    description: "1.654\" pitch engineered class bushed roller chain. Carburized pins, TH rollers and bushings. Rated 1,650 lb working load. Used in light bulk material conveying, aggregate, and grain applications.",
    application_tags: ["aggregate", "grain_handling", "bulk_material"],
    specs: {
      pitch_in: "1.654", pitch_mm: "42.01",
      style: "N",
      overall_pin_cotter_in: "2.03",
      sidebar_width_in: "1.00", sidebar_thickness_in: "0.13",
      sidebar_height_in: "1.13", pin_dia_in: "0.38",
      pin_properties: "CARB",
      face_width_in: "0.97", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.25", bushing_dia_in: "0.56",
      rated_working_load_lbs: "1650", min_ultimate_strength_lbs: "8000",
      weight_per_foot_lbs: "3.0", max_rpm_12t: "280",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "8000", working_load_lbs: "1650",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Uniking primary baseline. Rexnord RR362 / Link-Belt RS625 cross-reference." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "RR362", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "4", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "RR362", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS625", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1"],
    sprocket_series: "ENG-62",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: ["Attachment chains", "Extended pin"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-RR432",
    chain_family: "engineered_class",
    chain_number: "RR432",
    display_name: "RR432 Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "1.654",
    pitch_mm: "42.01",
    description: "1.654\" pitch TH-pin engineered class roller chain. Heavier construction than RR362. Rated 2,100 lb working load for light-to-medium bulk material conveying.",
    application_tags: ["aggregate", "grain_handling", "bulk_material"],
    specs: {
      pitch_in: "1.654", pitch_mm: "42.01",
      style: "N",
      overall_pin_cotter_in: "2.28",
      sidebar_width_in: "1.00", sidebar_thickness_in: "0.19",
      sidebar_height_in: "1.13", pin_dia_in: "0.44",
      pin_properties: "TH",
      face_width_in: "0.97", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.38", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2100", min_ultimate_strength_lbs: "10000",
      weight_per_foot_lbs: "3.7", max_rpm_12t: "280",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "10000", working_load_lbs: "2100",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Uniking primary baseline. Rexnord RR432 / Link-Belt RS627 cross-reference." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "RR432", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "RR432", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS627", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1"],
    sprocket_series: "ENG-62",
    materials_available: ["carbon_steel"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-81X",
    chain_family: "engineered_class",
    chain_number: "81X",
    display_name: "81X Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch 81X engineered class bushed roller chain. CARB pins, TH rollers. Rated 2,000 lb working load. Industry standard for bulk material conveyors in aggregate, mining, recycling, and grain handling.",
    application_tags: ["aggregate", "mining", "recycling", "grain_handling", "bulk_material", "heavy_industrial"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.14",
      sidebar_width_in: "1.07", sidebar_thickness_in: "0.16",
      sidebar_height_in: "1.13", pin_dia_in: "0.43",
      pin_properties: "CARB",
      face_width_in: "1.00", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.39", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2000", min_ultimate_strength_lbs: "16000",
      weight_per_foot_lbs: "2.5", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "16000", working_load_lbs: "2000",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Uniking primary baseline. Rexnord 81X / Link-Belt RS81X cross-reference. Industry-standard 2.609\" bulk conveyor chain." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "81X", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "81X", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS81X", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Allied-Locke", code: "81X", confidence: "Confirmed" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: ["81XH Heavy", "81XHH Extra Heavy", "Attachment chains"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-C1288",
    chain_family: "engineered_class",
    chain_number: "C1288",
    display_name: "C1288 Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch C1288 engineered class chain. CARB pins and bushings. Equivalent to 81X with slightly different sidebar geometry. Rated 2,000 lb working load.",
    application_tags: ["bulk_material", "aggregate", "mining"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.23",
      sidebar_width_in: "1.08", sidebar_thickness_in: "0.16",
      sidebar_height_in: "1.13", pin_dia_in: "0.41",
      pin_properties: "CARB",
      face_width_in: "1.03", roller_dia_in: "0.90",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.38", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2000", min_ultimate_strength_lbs: "16000",
      weight_per_foot_lbs: "2.5", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "16000", working_load_lbs: "2000",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord C1288 / Link-Belt SS1088. Similar rating to 81X, different geometry." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "C1288", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "C1288", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "SS1088", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-1578",
    chain_family: "engineered_class",
    chain_number: "1578",
    display_name: "1578 Engineered Class Roller Chain (K-Style)",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch 1578 K-style engineered class chain. CARB pins and bushings, extended pin design. Rated 2,200 lb working load.",
    application_tags: ["bulk_material", "aggregate", "heavy_industrial"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "K",
      overall_pin_cotter_in: "2.36",
      sidebar_width_in: "1.06", sidebar_thickness_in: "0.19",
      sidebar_height_in: "1.13", pin_dia_in: "0.41",
      pin_properties: "CARB",
      face_width_in: "1.03", roller_dia_in: "0.90",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.44", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2200", min_ultimate_strength_lbs: "17000",
      weight_per_foot_lbs: "2.6", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "17000", working_load_lbs: "2200",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord 1578 K-style. No Link-Belt equivalent listed." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "1578", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "1578", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-RR778",
    chain_family: "engineered_class",
    chain_number: "RR778",
    display_name: "RR778 Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch RR778 engineered class chain. Heavier than 81X — CARB pins, TH bushings. Rated 2,300 lb working load. Preferred for medium-heavy bulk conveying.",
    application_tags: ["bulk_material", "aggregate", "mining", "recycling"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.41",
      sidebar_width_in: "1.13", sidebar_thickness_in: "0.19",
      sidebar_height_in: "1.13", pin_dia_in: "0.44",
      pin_properties: "CARB",
      face_width_in: "1.08", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.50", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2300", min_ultimate_strength_lbs: "23000",
      weight_per_foot_lbs: "2.9", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "23000", working_load_lbs: "2300",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord RR778 / Link-Belt RS886." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "RR778", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "RR778", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS886", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-RR588",
    chain_family: "engineered_class",
    chain_number: "RR588",
    display_name: "RR588 Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch RR588 heavy engineered class roller chain. CARB pins, TH bushings. Rated 2,500 lb working load — heavier sidebar than RR778.",
    application_tags: ["bulk_material", "mining", "heavy_industrial"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.57",
      sidebar_width_in: "1.13", sidebar_thickness_in: "0.25",
      sidebar_height_in: "1.13", pin_dia_in: "0.44",
      pin_properties: "CARB",
      face_width_in: "1.08", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.63", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2500", min_ultimate_strength_lbs: "17000",
      weight_per_foot_lbs: "3.8", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "17000", working_load_lbs: "2500",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord RR588 / Link-Belt RS887." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "RR588", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "RR588", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS887", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-81XH",
    chain_family: "engineered_class",
    chain_number: "81XH",
    display_name: "81XH Heavy Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch 81XH heavy series engineered class chain. TH pins and sidebars (thicker than 81X). Rated 2,500 lb working load for heavy-duty bulk material conveying.",
    application_tags: ["bulk_material", "aggregate", "mining", "cement", "recycling"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.58",
      sidebar_width_in: "1.07", sidebar_thickness_in: "0.31",
      sidebar_height_in: "1.27", pin_dia_in: "0.43",
      pin_properties: "TH",
      face_width_in: "1.00", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.69", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2500", min_ultimate_strength_lbs: "28000",
      weight_per_foot_lbs: "4.1", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "performance", tensile_strength_lbs: "28000", working_load_lbs: "2500",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Uniking primary baseline. Rexnord 81XH / Link-Belt RS81XHN. Heavy series — thicker sidebars vs standard 81X." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "81XH", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "81XH", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS81XHN", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel"],
    options_upgrades: ["81XHH extra heavy"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-81XHH",
    chain_family: "engineered_class",
    chain_number: "81XHH",
    display_name: "81XHH Extra Heavy Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch 81XHH extra heavy engineered class chain. Heaviest sidebar in the 81X family. Rated 2,500 lb working load with maximum fatigue life. For severe-duty bulk material conveying.",
    application_tags: ["bulk_material", "aggregate", "mining", "cement", "heavy_industrial"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.76",
      sidebar_width_in: "1.07", sidebar_thickness_in: "0.31",
      sidebar_height_in: "1.27", pin_dia_in: "0.43",
      pin_properties: "TH",
      face_width_in: "1.00", roller_dia_in: "0.88",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.69", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2500", min_ultimate_strength_lbs: "28000",
      weight_per_foot_lbs: "4.6", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "28000", working_load_lbs: "2500",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord 81XHH / Link-Belt RS81XHN. Extra heavy — heaviest 81X series." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "81XHH", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4" },
      { manufacturer: "Rexnord", code: "81XHH", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS81XHN", confidence: "Confirmed", catalog_page: "4", notes: "Same LB code as 81XH — verify with manufacturer" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-270",
    chain_family: "engineered_class",
    chain_number: "270",
    display_name: "270 Heavy Duty Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch 270-class heavy duty engineered roller chain. Large 1.13\" roller diameter. Rated 3,500 lb working load — heaviest standard 2.609\" engineered class chain. Preferred for severe bulk material, mining, and aggregate applications.",
    application_tags: ["bulk_material", "mining", "aggregate", "cement", "heavy_industrial"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      style: "N",
      overall_pin_cotter_in: "2.95",
      sidebar_width_in: "1.14", sidebar_thickness_in: "0.31",
      sidebar_height_in: "1.63", pin_dia_in: "0.56",
      pin_properties: "TH",
      face_width_in: "1.09", roller_dia_in: "1.13",
      roller_style: "A", roller_properties: "TH",
      bushing_length_in: "1.77", bushing_dia_in: "0.81",
      rated_working_load_lbs: "3500", min_ultimate_strength_lbs: "40000",
      weight_per_foot_lbs: "6.9", max_rpm_12t: "145",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "40000", working_load_lbs: "3500",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Uniking primary baseline. Rexnord 270 / Link-Belt SS2004. Largest standard 2.609\" engineered chain." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "270", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "270", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "SS2004", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-270",
    materials_available: ["carbon_steel"],
    options_upgrades: ["Attachment chains", "Extended pin"],
    image_strategy: "family",
    status: "Active",
  },

  // 6" Pitch Engineered Class
  {
    chain_id: "ENG-SR196",
    chain_family: "engineered_class",
    chain_number: "SR196",
    display_name: "SR196 6\" Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch SR196 engineered class roller chain. CARB pins and bushings. 2.00\" roller face. Rated 2,600 lb working load. Used in heavy drag conveyors, aggregate, cement, and mining applications.",
    application_tags: ["bulk_material", "cement", "aggregate", "mining", "drag_conveyor"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "2.72",
      sidebar_width_in: "1.19", sidebar_thickness_in: "0.25",
      sidebar_height_in: "1.50", pin_dia_in: "0.44",
      pin_properties: "CARB",
      face_width_in: "1.09", roller_dia_in: "2.00",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.69", bushing_dia_in: "0.63",
      rated_working_load_lbs: "2600", min_ultimate_strength_lbs: "18000",
      weight_per_foot_lbs: "5.0", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "18000", working_load_lbs: "2600",
        source: "Uniking Industrial Bulk Material Catalog p.4",
        notes: "Rexnord SR196 / Link-Belt RS6018. 6\" pitch engineered class." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "SR196", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "4", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "SR196", confidence: "Confirmed", catalog_page: "4" },
      { manufacturer: "Link-Belt", code: "RS6018", confidence: "Confirmed", catalog_page: "4" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-196",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: ["White iron rollers", "Extended pin attachments"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-2126",
    chain_family: "engineered_class",
    chain_number: "2126",
    display_name: "2126 6\" Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch 2126 engineered class roller chain. Heavier construction than SR196 with larger sidebar. Rated 3,400 lb working load. Cement, aggregate, and bulk drag conveying.",
    application_tags: ["cement", "aggregate", "bulk_material", "drag_conveyor"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "2.89",
      sidebar_width_in: "1.25", sidebar_thickness_in: "0.25",
      sidebar_height_in: "1.50", pin_dia_in: "0.56",
      pin_properties: "CARB",
      face_width_in: "1.19", roller_dia_in: "2.00",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.75", bushing_dia_in: "0.81",
      rated_working_load_lbs: "3400", min_ultimate_strength_lbs: "21000",
      weight_per_foot_lbs: "5.0", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "21000", working_load_lbs: "3400",
        source: "Uniking Industrial Bulk Material Catalog p.5",
        notes: "Rexnord 2126 / Link-Belt RS1116." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "2126", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "5" },
      { manufacturer: "Rexnord", code: "2126", confidence: "Confirmed", catalog_page: "5" },
      { manufacturer: "Link-Belt", code: "RS1116", confidence: "Confirmed", catalog_page: "5" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-196",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-2190",
    chain_family: "engineered_class",
    chain_number: "2190",
    display_name: "2190 6\" Wide Roller Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch 2190 engineered class chain with 2.50\" wide roller — wider track for stable bulk material support. Rated 3,400 lb working load.",
    application_tags: ["bulk_material", "drag_conveyor", "cement", "aggregate"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "2.89",
      sidebar_width_in: "1.25", sidebar_thickness_in: "0.25",
      sidebar_height_in: "1.50", pin_dia_in: "0.56",
      pin_properties: "CARB",
      face_width_in: "1.19", roller_dia_in: "2.50",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.75", bushing_dia_in: "0.81",
      rated_working_load_lbs: "3400", min_ultimate_strength_lbs: "21000",
      weight_per_foot_lbs: "7.0", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "21000", working_load_lbs: "3400",
        source: "Uniking Industrial Bulk Material Catalog p.5",
        notes: "Rexnord 2190 / Link-Belt RS2190. Wide roller variant of 2126." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "2190", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "5" },
      { manufacturer: "Rexnord", code: "2190", confidence: "Confirmed", catalog_page: "5" },
      { manufacturer: "Link-Belt", code: "RS2190", confidence: "Confirmed", catalog_page: "5" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-197",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-SR1114",
    chain_family: "engineered_class",
    chain_number: "SR1114",
    display_name: "SR1114 6\" Heavy Duty Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch SR1114 heavy duty engineered class roller chain. Rated 4,200 lb working load. Preferred for high-capacity cement, aggregate, and bulk drag conveyors.",
    application_tags: ["cement", "aggregate", "bulk_material", "drag_conveyor", "heavy_industrial"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "3.25",
      sidebar_width_in: "1.31", sidebar_thickness_in: "0.31",
      sidebar_height_in: "1.50", pin_dia_in: "0.63",
      pin_properties: "CARB",
      face_width_in: "1.25", roller_dia_in: "2.00",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "1.94", bushing_dia_in: "0.94",
      rated_working_load_lbs: "4200", min_ultimate_strength_lbs: "23000",
      weight_per_foot_lbs: "6.3", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "performance", tensile_strength_lbs: "23000", working_load_lbs: "4200",
        source: "Uniking Industrial Bulk Material Catalog p.5",
        notes: "Uniking primary baseline. Rexnord SR1114 / Link-Belt RS1114." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "SR1114", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "5", notes: "Uniking primary baseline" },
      { manufacturer: "Rexnord", code: "SR1114", confidence: "Confirmed", catalog_page: "5" },
      { manufacturer: "Link-Belt", code: "RS1114", confidence: "Confirmed", catalog_page: "5" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-SA1", "ENG-FLIGHT"],
    sprocket_series: "ENG-196",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-2180",
    chain_family: "engineered_class",
    chain_number: "2180",
    display_name: "2180 6\" Heavy Duty Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch 2180 engineered class roller chain. Heaviest standard 6\" pitch engineered class — rated 4,500 lb working load. For maximum capacity drag and bulk conveyors.",
    application_tags: ["bulk_material", "cement", "heavy_industrial", "mining"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "3.47",
      sidebar_width_in: "1.31", sidebar_thickness_in: "0.38",
      sidebar_height_in: "1.75", pin_dia_in: "0.63",
      pin_properties: "CARB",
      face_width_in: "1.19", roller_dia_in: "2.25",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "2.06", bushing_dia_in: "0.94",
      rated_working_load_lbs: "4500", min_ultimate_strength_lbs: "35000",
      weight_per_foot_lbs: "8.7", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "35000", working_load_lbs: "4500",
        source: "Uniking Industrial Bulk Material Catalog p.5",
        notes: "Rexnord 2180. No Link-Belt equivalent listed. Heavy capacity 6\" engineered chain." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "2180", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "5" },
      { manufacturer: "Rexnord", code: "2180", confidence: "Confirmed", catalog_page: "5" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT", "ENG-SCRAPER"],
    sprocket_series: "ENG-2180",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-2183",
    chain_family: "engineered_class",
    chain_number: "2183",
    display_name: "2183 6\" Wide Roller Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch 2183 engineered class chain with 3.00\" wide roller for maximum material support width. Rated 4,600 lb working load.",
    application_tags: ["bulk_material", "cement", "drag_conveyor"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      style: "R",
      overall_pin_cotter_in: "3.50",
      sidebar_width_in: "1.31", sidebar_thickness_in: "0.31",
      sidebar_height_in: "1.50", pin_dia_in: "0.63",
      pin_properties: "CARB",
      face_width_in: "1.38", roller_dia_in: "3.00",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "2.13", bushing_dia_in: "0.89",
      rated_working_load_lbs: "4600", min_ultimate_strength_lbs: "24000",
      weight_per_foot_lbs: "10.7", max_rpm_12t: "40",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "24000", working_load_lbs: "4600",
        source: "Uniking Industrial Bulk Material Catalog p.5",
        notes: "Rexnord 2183 / Link-Belt RS951. Wide 3\" roller." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "2183", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "5" },
      { manufacturer: "Rexnord", code: "2183", confidence: "Confirmed", catalog_page: "5" },
      { manufacturer: "Link-Belt", code: "RS951", confidence: "Confirmed", catalog_page: "5" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT"],
    sprocket_series: "ENG-1131",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // 8" Pitch
  {
    chain_id: "ENG-A2800",
    chain_family: "engineered_class",
    chain_number: "A2800",
    display_name: "A2800 8\" Heavy Duty Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "8.000",
    pitch_mm: "203.20",
    description: "8\" pitch A2800 extra-heavy engineered class roller chain. CIH (Circumferentially Induction Hardened) pins. 3.50\" roller. Rated 9,800 lb working load. Heaviest bulk material conveying applications.",
    application_tags: ["bulk_material", "mining", "cement", "heavy_industrial"],
    specs: {
      pitch_in: "8.000", pitch_mm: "203.20",
      style: "R",
      overall_pin_cotter_in: "4.71",
      sidebar_width_in: "1.81", sidebar_thickness_in: "0.50",
      sidebar_height_in: "2.75", pin_dia_in: "1.00",
      pin_properties: "CIH",
      face_width_in: "1.50", roller_dia_in: "3.50",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "2.81", bushing_dia_in: "1.50",
      rated_working_load_lbs: "9800", min_ultimate_strength_lbs: "94000",
      weight_per_foot_lbs: "62.2", max_rpm_12t: "26",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "94000", working_load_lbs: "9800",
        source: "Uniking Industrial Bulk Material Catalog p.6",
        notes: "Rexnord A2800. CIH pin construction. 8\" pitch maximum load chain." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "A2800", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "6" },
      { manufacturer: "Rexnord", code: "A2800", confidence: "Confirmed", catalog_page: "6" },
    ],
    attachments_available: ["ENG-FLIGHT", "ENG-SCRAPER"],
    sprocket_series: "ENG-2800",
    materials_available: ["carbon_steel", "induction_hard"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // 9" Pitch
  {
    chain_id: "ENG-ER911",
    chain_family: "engineered_class",
    chain_number: "ER911",
    display_name: "ER911 9\" Engineered Class Roller Chain",
    standard: "ASME B29.100",
    pitch_in: "9.000",
    pitch_mm: "228.60",
    description: "9\" pitch ER911 engineered class roller chain. CARB pins, 3.00\" roller. Rated 4,650 lb working load. Heavy drag and scraper conveying in cement and aggregate.",
    application_tags: ["cement", "aggregate", "bulk_material", "drag_conveyor"],
    specs: {
      pitch_in: "9.000", pitch_mm: "228.60",
      style: "R",
      overall_pin_cotter_in: "3.45",
      sidebar_width_in: "2.00", sidebar_thickness_in: "0.31",
      sidebar_height_in: "2.00", pin_dia_in: "0.63",
      pin_properties: "CARB",
      face_width_in: "1.44", roller_dia_in: "3.00",
      roller_style: "A", roller_properties: "CARB",
      bushing_length_in: "2.13", bushing_dia_in: "0.89",
      rated_working_load_lbs: "4650", min_ultimate_strength_lbs: "33000",
      weight_per_foot_lbs: "8.5", max_rpm_12t: "22",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "33000", working_load_lbs: "4650",
        source: "Uniking Industrial Bulk Material Catalog p.7",
        notes: "Rexnord ER911 / Link-Belt RS911." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "ER911", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "7" },
      { manufacturer: "Rexnord", code: "ER911", confidence: "Confirmed", catalog_page: "7" },
      { manufacturer: "Link-Belt", code: "RS911", confidence: "Confirmed", catalog_page: "7" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT", "ENG-SCRAPER"],
    sprocket_series: "ENG-911",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: ["White iron rollers"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-ER922",
    chain_family: "engineered_class",
    chain_number: "ER922",
    display_name: "ER922 9\" Heavy Duty Engineered Class Chain",
    standard: "ASME B29.100",
    pitch_in: "9.000",
    pitch_mm: "228.60",
    description: "9\" pitch ER922 heavy duty engineered class roller chain with white iron rollers. Rated 7,200 lb working load. Maximum heavy duty bulk material drag conveying.",
    application_tags: ["bulk_material", "cement", "mining", "heavy_industrial"],
    specs: {
      pitch_in: "9.000", pitch_mm: "228.60",
      style: "R",
      overall_pin_cotter_in: "4.28",
      sidebar_width_in: "2.00", sidebar_thickness_in: "0.38",
      sidebar_height_in: "2.00", pin_dia_in: "0.75",
      pin_properties: "TH",
      face_width_in: "1.94", roller_dia_in: "3.50",
      roller_style: "A", roller_properties: "WI",
      bushing_length_in: "2.75", bushing_dia_in: "1.13",
      rated_working_load_lbs: "7200", min_ultimate_strength_lbs: "34000",
      weight_per_foot_lbs: "12.0", max_rpm_12t: "22",
    },
    performance_tiers: [
      { tier: "premium", tensile_strength_lbs: "34000", working_load_lbs: "7200",
        source: "Uniking Industrial Bulk Material Catalog p.7",
        notes: "Rexnord ER922 / Link-Belt SS927. White iron rollers for abrasive materials." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "ER922", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "7" },
      { manufacturer: "Rexnord", code: "ER922", confidence: "Confirmed", catalog_page: "7" },
      { manufacturer: "Link-Belt", code: "SS927", confidence: "Confirmed", catalog_page: "7" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT", "ENG-SCRAPER"],
    sprocket_series: "ENG-922",
    materials_available: ["carbon_steel", "white_iron_roller"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // ══════════════════════════════════════════════════════════════════
  // PHASE 2 — ENGINEERED CLASS WITHOUT ROLLERS (Bushed, no roller)
  // Source: Uniking catalog p.9–10
  // ══════════════════════════════════════════════════════════════════

  {
    chain_id: "ENG-SS1044",
    chain_family: "engineered_class",
    chain_number: "SS1044",
    display_name: "SS1044 Engineered Class Bushed Chain (No Roller)",
    standard: "ASME B29.100",
    pitch_in: "3.000",
    pitch_mm: "76.20",
    description: "3\" pitch SS1044 engineered class chain without rollers. Solid barrel bushed construction. Rides on track/guide rails. Used in drag and scraper conveyors for grain, aggregate, and bulk material.",
    application_tags: ["grain_handling", "aggregate", "bulk_material", "drag_conveyor", "scraper_conveyor"],
    specs: {
      pitch_in: "3.000", pitch_mm: "76.20",
      style: "N",
      rated_working_load_lbs: "2200", min_ultimate_strength_lbs: "18000",
      weight_per_foot_lbs: "4.2",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "18000", working_load_lbs: "2200",
        source: "Uniking Industrial Bulk Material Catalog p.9",
        notes: "Uniking primary baseline — bushed no-roller class. Link-Belt SS1044." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "SS1044", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "9", notes: "Uniking primary baseline" },
      { manufacturer: "Link-Belt", code: "SS1044", confidence: "Confirmed", catalog_page: "9" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT"],
    sprocket_series: "ENG-SS",
    materials_available: ["carbon_steel"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "ENG-SS2184",
    chain_family: "engineered_class",
    chain_number: "SS2184",
    display_name: "SS2184 Heavy Bushed Engineered Chain (No Roller)",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch SS2184 heavy bushed engineered chain without rollers. High load drag and scraper conveying applications in cement, aggregate, and mining.",
    application_tags: ["cement", "aggregate", "mining", "drag_conveyor", "bulk_material"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      rated_working_load_lbs: "4800", min_ultimate_strength_lbs: "38000",
      weight_per_foot_lbs: "10.5",
    },
    performance_tiers: [
      { tier: "performance", tensile_strength_lbs: "38000", working_load_lbs: "4800",
        source: "Uniking Industrial Bulk Material Catalog p.10",
        notes: "Uniking primary baseline — 6\" pitch bushed no-roller." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "SS2184", confidence: "Confirmed", catalog_url: UK_CATALOG_URL, catalog_page: "10", notes: "Uniking primary baseline" },
      { manufacturer: "Link-Belt", code: "SS2184", confidence: "Confirmed", catalog_page: "10" },
    ],
    attachments_available: ["ENG-A1", "ENG-K1", "ENG-FLIGHT", "ENG-SCRAPER"],
    sprocket_series: "ENG-SS",
    materials_available: ["carbon_steel"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // ══════════════════════════════════════════════════════════════════
  // PHASE 5 — DRAG / SCRAPER CONVEYOR CHAINS
  // Uniking baseline — drag chain families (bulk material)
  // ══════════════════════════════════════════════════════════════════

  {
    chain_id: "DRAG-ENG-2.609",
    chain_family: "drag_scraper",
    chain_number: "DRAG-2.609",
    display_name: "2.609\" Drag Conveyor Chain Family",
    standard: "ASME B29.100",
    pitch_in: "2.609",
    pitch_mm: "66.27",
    description: "2.609\" pitch drag and scraper conveyor chain family. Normalized entry covering 81X, 81XH, 81XHH, 270 and equivalent chains configured with flight/scraper attachments for en-masse drag conveying in bulk material handling.",
    application_tags: ["bulk_material", "grain_handling", "aggregate", "drag_conveyor", "scraper_conveyor"],
    specs: {
      pitch_in: "2.609", pitch_mm: "66.27",
      type: "Drag/scraper conveyor",
      rated_working_load_range_lbs: "2000-3500",
      common_chain_series: "81X / 81XH / 81XHH / 270",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "16000", working_load_lbs: "2000",
        source: "Uniking Industrial Bulk Material Catalog p.4 (81X baseline)" },
      { tier: "premium", tensile_strength_lbs: "40000", working_load_lbs: "3500",
        source: "Uniking Industrial Bulk Material Catalog p.4 (270 series)" },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "DRAG-2.609", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "4-11", notes: "Uniking family grouping — see individual chain entries" },
    ],
    attachments_available: ["ENG-FLIGHT", "ENG-SCRAPER", "ENG-A1", "ENG-K1"],
    sprocket_series: "ENG-78",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: ["Flight attachments", "Scraper attachments", "Extended pin"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "DRAG-ENG-6.000",
    chain_family: "drag_scraper",
    chain_number: "DRAG-6.000",
    display_name: "6\" Drag Conveyor Chain Family",
    standard: "ASME B29.100",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch drag and scraper conveyor chain family. Covers SR196, 2126, SR1114, 2180, 2183 and equivalents with flight/scraper attachments for heavy bulk material handling.",
    application_tags: ["cement", "aggregate", "mining", "bulk_material", "drag_conveyor"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      type: "Drag/scraper conveyor",
      rated_working_load_range_lbs: "2600-4600",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "18000", working_load_lbs: "2600",
        source: "Uniking Industrial Bulk Material Catalog p.5 (SR196 baseline)" },
      { tier: "premium", tensile_strength_lbs: "35000", working_load_lbs: "4600",
        source: "Uniking Industrial Bulk Material Catalog p.5 (2183 series)" },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "DRAG-6.000", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "4-11", notes: "Uniking family grouping" },
    ],
    attachments_available: ["ENG-FLIGHT", "ENG-SCRAPER", "ENG-A1", "ENG-K1"],
    sprocket_series: "ENG-196",
    materials_available: ["carbon_steel", "carburized"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // ══════════════════════════════════════════════════════════════════
  // PHASE 6 — FORGED CHAINS (p.52)
  // Uniking baseline for drop forged rivetless used in
  // overhead and power-and-free conveyor systems
  // ══════════════════════════════════════════════════════════════════

  {
    chain_id: "FORGED-DFR-FAMILY",
    chain_family: "drop_forged_rivetless",
    chain_number: "DFR-Family",
    display_name: "Drop Forged Rivetless Chain — Uniking Family",
    standard: "ASME B29.100",
    pitch_in: "3.075",
    pitch_mm: "78.11",
    description: "Drop forged rivetless chain family entry for Uniking normalized baseline. Includes X348, X458, X678, 477, 698 series. Used in overhead conveyors, power-and-free systems, and heavy industrial conveying.",
    application_tags: ["heavy_industrial", "bulk_material", "transfer_conveyor"],
    specs: {
      type: "Drop forged rivetless",
      pitch_range_in: "3.075 - 6.000",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "19500", working_load_lbs: "3900",
        source: "Uniking Industrial Bulk Material Catalog p.52" },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "DFR-Family", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "52", notes: "Uniking forged chain section — see X348, X458, X678 for individual entries" },
    ],
    attachments_available: ["DFR-DOG", "DFR-PUSHER", "DFR-TROLLEY"],
    sprocket_series: "X348",
    materials_available: ["carbon_steel", "high_temp"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  // ══════════════════════════════════════════════════════════════════
  // PHASE 7 — KILN CHAINS (p.60)
  // Specialty thermal processing chains
  // ══════════════════════════════════════════════════════════════════

  {
    chain_id: "KILN-CHAIN-3",
    chain_family: "specialty_custom",
    chain_number: "KC-3",
    display_name: "3\" Kiln Chain",
    standard: "Custom / Cement Industry",
    pitch_in: "3.000",
    pitch_mm: "76.20",
    description: "3\" pitch kiln chain for cement rotary kilns. Heat-resistant construction for high-temperature processing environments. Tumbles material and aids heat transfer in cement, lime, and aggregate kilns.",
    application_tags: ["cement", "kiln", "aggregate", "bulk_material"],
    specs: {
      pitch_in: "3.000", pitch_mm: "76.20",
      type: "Kiln chain", industry: "Cement / Kiln",
      temperature_rating: "High temperature",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "24000", working_load_lbs: "4800",
        source: "Uniking Industrial Bulk Material Catalog p.60",
        notes: "Uniking primary baseline — kiln chain." },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "KC-3", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "60", notes: "Uniking primary baseline" },
    ],
    attachments_available: [],
    sprocket_series: null,
    materials_available: ["carbon_steel", "high_temp", "heat_treated"],
    options_upgrades: ["Heat resistant alloy", "Extended wear construction"],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "KILN-CHAIN-4",
    chain_family: "specialty_custom",
    chain_number: "KC-4",
    display_name: "4\" Kiln Chain",
    standard: "Custom / Cement Industry",
    pitch_in: "4.000",
    pitch_mm: "101.60",
    description: "4\" pitch kiln chain for large-diameter rotary kilns in cement and lime manufacturing. Heavy duty heat-resistant construction.",
    application_tags: ["cement", "kiln", "bulk_material"],
    specs: {
      pitch_in: "4.000", pitch_mm: "101.60",
      type: "Kiln chain", industry: "Cement / Kiln",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "36000", working_load_lbs: "7200",
        source: "Uniking Industrial Bulk Material Catalog p.60" },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "KC-4", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "60", notes: "Uniking primary baseline" },
    ],
    attachments_available: [],
    sprocket_series: null,
    materials_available: ["carbon_steel", "high_temp"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

  {
    chain_id: "KILN-CHAIN-6",
    chain_family: "specialty_custom",
    chain_number: "KC-6",
    display_name: "6\" Kiln Chain",
    standard: "Custom / Cement Industry",
    pitch_in: "6.000",
    pitch_mm: "152.40",
    description: "6\" pitch heavy kiln chain for the largest industrial rotary kilns. Maximum heat resistance and durability for extended kiln operation.",
    application_tags: ["cement", "kiln", "bulk_material", "heavy_industrial"],
    specs: {
      pitch_in: "6.000", pitch_mm: "152.40",
      type: "Kiln chain", industry: "Cement / Kiln",
    },
    performance_tiers: [
      { tier: "standard", tensile_strength_lbs: "55000", working_load_lbs: "11000",
        source: "Uniking Industrial Bulk Material Catalog p.61" },
    ],
    source_refs: [
      { manufacturer: "Uniking", code: "KC-6", confidence: "Confirmed",
        catalog_url: UK_CATALOG_URL, catalog_page: "61", notes: "Uniking primary baseline" },
    ],
    attachments_available: [],
    sprocket_series: null,
    materials_available: ["carbon_steel", "high_temp"],
    options_upgrades: [],
    image_strategy: "family",
    status: "Active",
  },

];

export default {
  UK_MERGE_REFS,
  UK_NEW_CHAINS,
};