import { base44 } from './base44Client';

export const zohoIntelBriefing = base44.functions.zohoIntelBriefing;
export const zohoNoteWriter = base44.functions.zohoNoteWriter;
export const sendWeeklyReport = base44.functions.sendWeeklyReport;
export const syncBoulartToUniKonnect = base44.functions.syncBoulartToUniKonnect;
export const checkUniKonnect = base44.functions.checkUniKonnect;
export const weeklyPerformanceReport = base44.functions.weeklyPerformanceReport;
export const iscPerformanceReport = base44.functions.iscPerformanceReport;
export const uploadBeltImages = base44.functions.uploadBeltImages;
export const bulkUpdateCatalog = base44.functions.bulkUpdateCatalog;
export const oppProductHistory = base44.functions.oppProductHistory;
export const bulkInsertMacRelated = base44.functions.bulkInsertMacRelated;
export const pushChainRelated = base44.functions.pushChainRelated;
export const updatePinSpecs = base44.functions.updatePinSpecs;
export const upgradeAttachmentImages = base44.functions.upgradeAttachmentImages;
export const updateAttachmentImages = base44.functions.updateAttachmentImages;
export const updateAttachmentSpecs = base44.functions.updateAttachmentSpecs;
export const bulkUpdateRecords = base44.functions.bulkUpdateRecords;
export const bulkCreateRecords = base44.functions.bulkCreateRecords;
export const sendRFQEmail = base44.functions.sendRFQEmail;
export const getCatalogData = base44.functions.getCatalogData;
